### ISSUE TITLE
WSL Networking Broken in 2.0.7

### ISSUE THREAD

**Issue by fishfacemcgee** [microsoft/WSL#10709]
### Windows Version

Microsoft Windows [Version 10.0.22631.2506]

### WSL Version

2.0.7.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

1. Launch a WSL instance
    * I usually do this by opening Terminal which defaults to my Ubuntu setup, but I can also repro this by just launching wsl.exe from Powershell

### Expected Behavior

WSL Distro successfully starts

### Actual Behavior

Following error is received

```
Failed to configure network (networkingMode Nat). To disable networking, set `wsl2.networkingMode=None` in C:\Users\bjgra\.wslconfig
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0x80070424

[process exited with code 4294967295 (0xffffffff)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

Not sure how noteworthy it is but there is no .wslconfig file at the directory specified.

**Comment by fishfacemcgee** [comment]
I found https://github.com/microsoft/WSL/issues/10666 while looking through the 2.0.7 notes and it looks like I don't have Virtual Machine Platform enabled. So I'm confused as to why this _wasn't_ an issue for me prior to 2.0.7 (is the version returned by `wsl.exe --version` wrong on the Microsoft Store provided version of WSL?) and, assuming MSS versioning isn't wrong, it appears the fix in 2.0.7 does not work.

**Comment by fishfacemcgee** [comment]
I can confirm that enabling VMP fixed the issue. I'll leave this open for now in case there's additional information you'd like to me provide, but I also don't have a problem with this being marked as closed/resolved. Now that I'm able to get back into my WSL env, I've update the issue with Kernel/Distro info.

**Comment by dominicfmazza** [comment]
I am also having this same issue. Setting `wsl.networkingMode=None` or `wsl.networkingMode=mirrored`  is the only workaround.

**Comment by dominicfmazza** [comment]
Enabling VMP temporarily fixed the issue for me, it is returning after running `wsl --shutdown` and `wsl -t Ubuntu`.

**Comment by pmartincic** [comment]
@dominicfmazza, after the issue has returned, when you say the issue has returned, do you mean the VMP feature is disabled again?

**Comment by fishfacemcgee** [comment]
> /logs

@benhillis Updated with logs with both VMP disabled (where I get the error in the original Issue) and enabled just in case both may help determine why the better error didn't show.

**Comment by cal4** [comment]
Downgrading to 2.0.4 fixes it for me

**Comment by lzhprigrammer** [comment]
Yes,I have the same problem! 

Network error recv()

**Comment by bersbersbers** [comment]
Same problem after upgrading from WSL version 1.2.5.0 to 2.0.9 ("Failed to configure network (networkingMode Nat). To disable networking, set `wsl2.networkingMode=None` ..."). Fixed by installing VMP. Survives `wsl --shutdown`. Notable, and that's why I am posting here: On the first launch of `wsl` after installing VMP, I got this:

```
wsl: Failed to create virtual network with address range: '172.24.224.0/20', created new network with range: '172.18.16.0/20', The object already exists.
wsl: Failed to create network endpoint with address: '172.24.224.3', assigned new address: '172.18.31.109'
```

Just in case this helps understanding what may be going on.

**Comment by ByteEnable** [comment]
Can confirm enabling "Virtual Machine Platform" in Optional Features fixed this same issue.

**Comment by dajhorn** [comment]
Disabling the Windows Firewall triggered this bug for me.  Enabling the Windows Firewall and installing the Virtual Machine Machine Platform resolved it.

**Comment by HoracioDos** [comment]
Exact same problem here. Enabling Virtual Machine Platform fixed it.

**Comment by chanpreetdhanjal** [comment]
@fishfacemcgee please install the virtual machine platform.

**Comment by fishfacemcgee** [comment]
@chanpreetdhanjal As I stated in my follow-up comments, I did, and it fixed the issue. 

However, the current issue now is that this release note for 2.0.7:

> Add more actionable error message for when Virtual Machine Platform is not present (solves https://github.com/microsoft/WSL/issues/10666)

does not appear to be valid. My WSL instance was working just fine on the prior version of WSL, and then I ran into the error in the original issue which, as we can all see, contains zero actionable information related to the Virtual Machine Platform. I do think it's potentially noteworthy that either:

* WSL2 didn't actually require VMP prior to 2.0.7
or 
* Something in a Windows update caused VMP to be disabled, coinciding with 2.0.7 rolling out on the Microsoft Store/winget

but the fact of the matter is 2.0.7 was supposed to contain fixed behavior around VMP-related errors that otherwise appeared to be networking related and this issue is proof otherwise. If MS wants to close this issue because the reported issue of "Networking error in 2.0.7" is resolved, I won't be offended, but I think my issue and the other comments here would warrant at least this being re-categorized around the incorrect error instead.

**Comment by ByteEnable** [comment]
To back up @fishfacemcgee , I did not see this error until WSL2 was updated to 2.0.7.  I had not enabled VMP prior to this update.  After the WSL2 update I launched my distro and recieved the same networking error as posted by @fishfacemcgee .  I landed here after an Internet search forFailed to configure network (networkingMode Nat). To disable networking, set `wsl2.networkingMode=None` in C:\Users\ByteE\.wslconfig
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0x80070424

**Comment by chanpreetdhanjal** [comment]
Could you please follow the steps below and attach the diagnostic logs? https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

**Comment by fishfacemcgee** [comment]
> Could you please follow the steps below and attach the diagnostic logs? https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

@chanpreetdhanjal Can you please read the rest of the comment thread where you can see that logs were already requested and provided?

**Comment by chanpreetdhanjal** [comment]
@fishfacemcgee The link above is new WSL networking log script. Please follow the link and share when you get some time.

**Comment by fishfacemcgee** [comment]
> @fishfacemcgee The link above is new WSL networking log script. Please follow the link and share when you get some time.

@chanpreetdhanjal The link above is literally the commands I was asked to run to provide logs after I reported this issue.

**Comment by fishfacemcgee** [comment]
> @fishfacemcgee The link above is new WSL networking log script. Please follow the link and share when you get some time.

@chanpreetdhanjal And again, as I stated, this is no longer a networking issue but an error reporting issue.

**Comment by chanpreetdhanjal** [comment]
@benhillis @craigloewen-msft

**Comment by L-ingqin12** [comment]
While I set the file in `C:\Users\xx\.wslconfig` as follows, the problem was fixed:
```
[experimental]
autoMemoryReclaim=gradual  # gradual | dropcache | disabled
networkingMode=NAT         # mirrored | NAT | None 
dnsTunneling=true
firewall=true
autoProxy=true
```

**Comment by emoneal** [comment]
Enabled VMP worked for me. I had a stressful time for a few days just trying to figure out the issue. No matter what I tried worked. You are a HUGE lifesaver!

**Comment by ReneNyffenegger** [comment]
Can I somehow verify that VMP is enabled? It should be, as per UEFI setup. But I still get the same error message.

Also, some commenters recommend to "install VMP". Is this a special software? Or another terminology for enabling VT-d in UEFI?

**Comment by emoneal** [comment]
> Can I somehow verify that VMP is enabled? It should be, as per UEFI setup. But I still get the same error message.
> 
> Also, some commenters recommend to "install VMP". Is this a special software? Or another terminology for enabling VT-d in UEFI?

No, VMP stands for Virtual Machine Platform. It is part of Windows but can be enabled or disabled, which then installs or uninstalls it from your system on restart. You can verify if it is enabled by going to your start menu and searching "Windows features" and it should automatically find "Turn Windows features on or off." Scroll down until you find Virtual Machine Platform and make sure it is checked.

**Comment by ReneNyffenegger** [comment]
Thanks @moneal, checking VPM as suggested lets me run WSL again.

**Comment by moneal** [comment]
> Thanks @moneal, checking VPM as suggested lets me run WSL again.

@ReneNyffenegger lol thanks for the tag and as someone that uses WSL all the time the info was helpful but I think you wanted to thank @emoneal ;)

**Comment by AidanWelch** [comment]
I get the same issue but only after install VMWare 17, no Hyper-V

**Comment by vince-vibin** [comment]
Had the same issue, enabling "Virtual Machine Platform" in the Windows Features and then restarting fixed the issue for me.

**Comment by AidanWelch** [comment]
> Had the same issue, enabling "Virtual Machine Platform" in the Windows Features and then restarting fixed the issue for me.

Already enabled for me.  Weirdly, VMWare is installed on an external drive, WSL works when it's plugged in- but not when it's not.

**Comment by mghayour** [comment]
This worked for me (same as L-ingqin12, but firewal disabled):

```
[experimental]
autoMemoryReclaim=gradual  # gradual | dropcache | disabled
networkingMode=NAT         # mirrored | NAT | None 
dnsTunneling=true
firewall=false
autoProxy=true
```

and restart wsl using:
`wsl.exe --shutdown` and start with `wsl.exe`

**Comment by grishagin** [comment]
> This worked for me (same as L-ingqin12, but firewal disabled):
> 
> ```
> [experimental]
> autoMemoryReclaim=gradual  # gradual | dropcache | disabled
> networkingMode=NAT         # mirrored | NAT | None 
> dnsTunneling=true
> firewall=false
> autoProxy=true
> ```
> 
> and restart wsl using: `wsl.exe --shutdown` and start with `wsl.exe`

This worked for me as well, thank you.

**Comment by neemo57** [comment]
Any fix on this issue ? I have VMP enabled and have been still getting the same error. I uninstalled all my distros and reinstalled them. Turning off WSL from windows features and turning it back on seemed to do nothing either.

**Comment by ededovic** [comment]
A potential workaround is to use bridged mode and it did not require any reinstalls. 
1. created a new virtual switch using Hyper-V Manager -> Virtual Switch Manager (see below few steps)
2. made c:\users\<USER>\.wslconfig change
[wsl2]  # omit that if you already have it. 
networkingMode=bridged
vmSwitch=wsl_switch


Create New Virtual Switch: Choose the type of virtual switch you need ( 'External') and click on 'Create Virtual Switch'.
Configure the Virtual Switch:
Name your virtual switch (in my case I named it "wsl_switch" see above)
If you chose an external switch, select the network adapter (NIC) you want to use.
There will be a prompt warning about network connectivity disruption. Click 'Yes' if you agree to proceed.

**Comment by Neznakomec** [comment]
I may confirm that nothing else in my Windows system, but WSL have problems
when VPN software is enabled.
  
WSL distros simply can't reach any website, any URL
And using recommended `.wslconfig` file not helps :(

**Comment by bing-zhub** [comment]
I have enabled the VMP and the VPN was disabled.
![image](https://github.com/microsoft/WSL/assets/39323503/a2e490fd-c47d-42e2-94ef-082b2031d038)
But the issue is still there. 
``` PowerShell
PS C:\WINDOWS\system32> wsl --version
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.2538
PS C:\WINDOWS\system32> wsl
Failed to configure network (networkingMode Nat). To disable networking, set `wsl2.networkingMode=None` in C:\Users\lab\.wslconfig
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0xffffffff 
```
How can I fix this? Please help me out!

**Comment by therevoman** [comment]
Just wanted to confirm, I installed "2024-01 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5034204)" last night, and this morning my WSL showed the error mentioned above.  VMP shows as installed.  I did not try removing and re-adding it.  

I tried adding `networkingMode=NAT` in the two sections mentioned above with no success.

However,  I am using Hyper-V and have an external switch already configured.  Once I added these two settings under the `[wsl2]` section the error went away.  So glad to have "external" switching!!!
`networkingMode=bridged
vmSwitch=external`


<img width="349" alt="image" src="https://github.com/microsoft/WSL/assets/5229889/22d1dd7e-286f-4f3c-bc73-91db9be31b9c">

**Comment by ricurvelo** [comment]
> While I set the file in `C:\Users\xx\.wslconfig` as follows, the problem was fixed:
> 
> ```
> [experimental]
> autoMemoryReclaim=gradual  # gradual | dropcache | disabled
> networkingMode=NAT         # mirrored | NAT | None 
> dnsTunneling=true
> firewall=true
> autoProxy=true
> ```

Here i have this issue when i try `wsl --update` in a machine with i have no admin privilege. The update was interrupted, and the error has begin;

This aproach creating .wslconfig worked fine for me... Thank you!

**Comment by mikeshutt** [comment]
The only thing that will resolve this issue for me is to 

1. uninstall the Virtual Machine Platform
2. reboot
3. install the Virtual Machine Platform
4. reboot
 
The problem comes right back if I have to reboot for anything other reason.  Quite annoying.

**Comment by alfablac** [comment]
I was getting errors when loading up WSL, same message error asking me to load with no network, error: 0xffffffff
Turns out the problem is when an application is running on port 53 it messes with WSL
Getting to resmon on win+r then network tab, listening port sections and killing the app running on port 53 solved for me.

**Comment by brianjlacy** [comment]
I am experiencing this issue as well.

- WSL 2 was working for me prior to the 2024-03 Cumulative Update for Windows 11 Version 23H2 (KB5035853) update.
- Virtual Machine Platform is already installed.
- Windows Hypervisor Platform was NOT checked/installed; I tried installing and rebooting but the problem persists.
- I tried adding a .wslconfig file as recommended by [L-ingqin12](https://github.com/L-ingqin12) and others; problem persists.
- I am going to try uninstalling and reinstalling VMP.

**Comment by alohith** [comment]
> I am experiencing this issue as well:
> 
> ```
> > wsl
> Failed to configure network (networkingMode Nat). To disable networking, set `wsl2.networkingMode=None` in C:\Users\...\.wslconfig
> Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0xffffffff
> ```
> 
>     * WSL 2 was working for me prior to the 2024-03 Cumulative Update for Windows 11 Version 23H2 (KB5035853) update.
> 
>     * Virtual Machine Platform is already installed.
> 
>     * Windows Hypervisor Platform was NOT checked/installed; I tried installing and rebooting but the problem persists.
> 
>     * I tried adding a .wslconfig file as recommended by [L-ingqin12](https://github.com/L-ingqin12) and others; problem persists.
> 
>     * I complete uninstalled VMP, WHP, and WSL itself, rebooted, then re-installed them, updated WSL, and rebooted. The problem persists.
> 
> 
> I have no idea what to do from here.
> 
> ```
> > wsl --version
> 
> WSL version: 2.1.5.0
> Kernel version: 5.15.146.1-2
> WSLg version: 1.0.60
> MSRDC version: 1.2.5105
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows version: 10.0.22631.3296
> 
> > wsl --list --verbose
>   NAME      STATE           VERSION
> * Ubuntu    Stopped         2
> ```

I too am experiencing this. 
`Failed to configure network (networkingMode Nat). To disable networking, set 'wsl2.networkingMode=None' in C:\Users\TRaveler\.wslconfig
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/ERROR_UNHANDLED_EXCEPTION`

Thought it was linked to me trying (and failing) to set up LAN network bridge connection, but I also just did the `wsl.exe --update` command in powershell, and it was working fine/as expected before... As suggested, in the error message I created a `.wslconfig` file in the designated directory with the following:

`[experimental]
autoMemoryReclaim=gradual  # gradual | dropcache | disabled
networkingMode=none       # mirrored | NAT | None 
#dnsTunneling=false
#firewall=false
#autoProxy=true
#[wsl2]  # omit that if you already have it. 
#networkingMode=bridged
#vmSwitch=wsl_switch`

And wsl is working, but w/o networking, which kinda defeats part of the use case I have WSL for ('built-in' SSH, SFTP, rsync, rclone, etc ability and linux env), so a fix or solution soon would be greatly appreciated.

`wsl --version --verbose
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.4170`

**Comment by alohith** [comment]
> > I am experiencing this issue as well:
> > ```
> > > wsl
> > Failed to configure network (networkingMode Nat). To disable networking, set `wsl2.networkingMode=None` in C:\Users\...\.wslconfig
> > Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0xffffffff
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > * WSL 2 was working for me prior to the 2024-03 Cumulative Update for Windows 11 Version 23H2 (KB5035853) update.
> > 
> > * Virtual Machine Platform is already installed.
> > 
> > * Windows Hypervisor Platform was NOT checked/installed; I tried installing and rebooting but the problem persists.
> > 
> > * I tried adding a .wslconfig file as recommended by [L-ingqin12](https://github.com/L-ingqin12) and others; problem persists.
> > 
> > * I complete uninstalled VMP, WHP, and WSL itself, rebooted, then re-installed them, updated WSL, and rebooted. The problem persists.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have no idea what to do from here.
> > ```
> > > wsl --version
> > 
> > WSL version: 2.1.5.0
> > Kernel version: 5.15.146.1-2
> > WSLg version: 1.0.60
> > MSRDC version: 1.2.5105
> > Direct3D version: 1.611.1-81528511
> > DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> > Windows version: 10.0.22631.3296
> > 
> > > wsl --list --verbose
> >   NAME      STATE           VERSION
> > * Ubuntu    Stopped         2
> > ```
> 
> I too am experiencing this. `Failed to configure network (networkingMode Nat). To disable networking, set 'wsl2.networkingMode=None' in C:\Users\TRaveler\.wslconfig Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/ERROR_UNHANDLED_EXCEPTION`
> 
> Thought it was linked to me trying (and failing) to set up LAN network bridge connection, but I also just did the `wsl.exe --update` command in powershell, and it was working fine/as expected before... As suggested, in the error message I created a `.wslconfig` file in the designated directory with the following:
> 
> `[experimental] autoMemoryReclaim=gradual # gradual | dropcache | disabled networkingMode=none # mirrored | NAT | None #dnsTunneling=false #firewall=false #autoProxy=true #[wsl2] # omit that if you already have it. #networkingMode=bridged #vmSwitch=wsl_switch`
> 
> And wsl is working, but w/o networking, which kinda defeats part of the use case I have WSL for ('built-in' SSH, SFTP, rsync, rclone, etc ability and linux env), so a fix or solution soon would be greatly appreciated.
> 
> `wsl --version --verbose WSL version: 2.1.5.0 Kernel version: 5.15.146.1-2 WSLg version: 1.0.60 MSRDC version: 1.2.5105 Direct3D version: 1.611.1-81528511 DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.19045.4170`
[WslLogs-2024-03-25_02-03-12.zip](https://github.com/microsoft/WSL/files/14741217/WslLogs-2024-03-25_02-03-12.zip)

**Comment by alohith** [comment]
@brianjlacy did you get your situation working? if so, what steps did you take?

**Comment by ericsoderquist** [comment]
> I figured out my issue at least. If you have NordVPN client set to auto-connect when the computer starts, then you get the error when you try to start the terminal.
> 
> If you just disable your vpn before you try to start the terminal, then it starts ups without an error.

you are amazing and i love you thank you so much this has been very hard to troubleshoot but your answer did it!

**Comment by azidancorp** [comment]
I had this problem persistent even with Virtual Machine Platform was enabled.
Turns out it was something to do with the fact I installed and then uninstalled VMWare - which setup its bridging that conflicted with wsl (and also mullvad VPN)

This fixed it:
-----------
Open Registry Editor:
Press Win + R, type regedit, and press Enter.

Navigate to the Registry Key:
Go to HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{3d09c1ca-2bcc-40b7-b9bb-3f3ec143a87b} or
Go to HKEY_CLASSES_ROOT\CLSID\{3d09c1ca-2bcc-40b7-b9bb-3f3ec143a87b}.

Delete the Registry Key:
Right-click on {3d09c1ca-2bcc-40b7-b9bb-3f3ec143a87b} and select Delete.
Confirm the deletion.

Reboot Your PC:
Restart your computer to apply the changes.

Go to Network Connections:
Press Win + R, type ncpa.cpl, and press Enter.

Select Your Ethernet Adapter:
Find your Ethernet adapter, right-click on it, and select Properties.

Remove VMware Bridge Protocol:
In the Properties window, look for VMware Bridge Protocol.

Uncheck it or select it and click Uninstall.

**Comment by ttury** [comment]
In my case, this problem occurred when DHCP was disabled. Open services.msc to check the DHCP client.

**Comment by MikeS1042** [comment]
I had this same error although the error code was different at the end. Mine read 

Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0xffffffff

Turned out my DNS proxy I had installed for development was messing things up (I am using Acyrlic DNS Proxy). When I stopped this it all worked.

**Comment by euanmacinnes** [comment]
I had the same issue here after installing the 2024-03 Cumulative Update for Windows 11 Version 23H2 (KB5035853) update.

@MikeS1042 's answer prompted me to look at the Technitium DNS server I have set up for "at home DNS". Stopping Technitium, starting WSL, then restarting technitium, seemed to resolve things.

**Comment by 3265** [comment]
I have the same issue..

ailed to configure network (networkingMode Nat). To disable networking, set `wsl2.networkingMode=None` in C:\Users\xxxx\.wslconfig Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0x80041002 Press any key to continue...

**Comment by KubeDevMax** [comment]
I have this issue and none of the workarounds (I tried them all) worked.

**Comment by 3265** [comment]
@KubeDevMax I eventually rolled back to WSL1 in order to avoid the Hyper-V problem, and then it worked

https://github.com/microsoft/WSL/issues/12019

**Comment by fkpwolf** [comment]
I have this issue suddently. But since I have no change on system and VMP is always on, just restarted system and then OK.

**Comment by saeed-neorelm** [comment]
same issue here, version:
```
WSL version: 2.3.13.0
Kernel version: 6.6.36.3-1
WSLg version: 1.0.63
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26120.1843
```
and
```
$wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
```
and turning no safe mode fixes this but of course thats not really a solution, it just hides it under the rug

**Comment by jochenvw** [comment]
> I have this issue suddently. But since I have no change on system and VMP is always on, just restarted system and then OK.

+1

**Comment by akr1999** [comment]
![image](https://github.com/user-attachments/assets/86a45489-1165-4793-9e87-75ba1e55d173)

Port 53 is issue. 

- make `c:\users\<USER>\.wslconfig` (remove everything from it if exists; do keep a backup of old .wslconfig) paste this only

`[experimental]`
`networkingMode=mirrored`

Open cmd as admin

- `wsl --set-version 2` 

For a new docker installation install a distro also

- `wsl --install Ubuntu-22.04`

- `wsl --shutdown`

save and restart pc and start docker.

**Comment by ghidalgo3** [comment]
I think for me the problem was Docker Desktop. I disabled Docker Desktop on startup, restarted my machine, opened the Terminal into WSL Ubuntu 22.04 and networking worked again.

If I manually start Docker Desktop, networking still works so I believe it must be some kind of race condition between Docker Desktop and WSL.

```
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.1742
```

**Comment by rfurtad** [comment]
I had the same issue, and nothing was working, like ping from wsl to host or ping from wsl to some server outside network. So based on @akr1999 comment, I did mv /etc/wsl.conf /etc/wsl.conf.bkp. Restart and wsl and guess what? it works! It may help someone, so here are my 2 cents. Thanks @akr1999 !

**Comment by destryptor** [comment]
> I had this problem persistent even with Virtual Machine Platform was enabled. I noticed that my Mullvad VPN wouldnt connect and it said due to VMWare conflict Turns out it was something to do with the fact I installed and then uninstalled VMWare - which setup its bridging that conflicted with wsl
> 
> ## This fixed it:
> Open Registry Editor: Press Win + R, type regedit, and press Enter.
> 
> Navigate to the Registry Key: Go to HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID{3d09c1ca-2bcc-40b7-b9bb-3f3ec143a87b} or Go to HKEY_CLASSES_ROOT\CLSID{3d09c1ca-2bcc-40b7-b9bb-3f3ec143a87b}.
> 
> Delete the Registry Key: Right-click on {3d09c1ca-2bcc-40b7-b9bb-3f3ec143a87b} and select Delete. Confirm the deletion.
> 
> Reboot Your PC: Restart your computer to apply the changes.
> 
> Go to Network Connections: Press Win + R, type ncpa.cpl, and press Enter.
> 
> Select Your Ethernet Adapter: Find your Ethernet adapter, right-click on it, and select Properties.
> 
> Remove VMware Bridge Protocol: In the Properties window, look for VMware Bridge Protocol.
> 
> Uncheck it or select it and click Uninstall.

Thanks a lot @azidancorp ! I have limited knowledge in networking, and had no idea uninstalling VMWare would cause the issue.

**Comment by borjamunozf** [comment]
Reported by one developer today, started to fail after Windows update KB5045935, coincidence or not.


WSL --version 
**2.3.14.0**

![Image](https://github.com/user-attachments/assets/fe06255e-a798-48a1-8d03-8884eda6ee1e)

Restarted & rebooted machine 3 times, no success.

Virtual Machine Platform is already enabled:

![Image](https://github.com/user-attachments/assets/7b704865-7e79-4717-88f9-09199aa91d53)


Uninstall the **KB5045935** does not fix the problem:
```cmd
wusa /uninstall /kb:5045935
```

Any idea? He cannot work.

**Comment by noobie158** [comment]
If you have a vpn. turn it of.

**Comment by DaRacci** [comment]
Using a networking mode of mirrored works until you want to expose ports, so nat mode is still a requirement for myself.

Hope this can be resolved as every time i reboot my machine it fails, I have to change to mirrored, start up wsl, shutdown wsl, change back to nat, get a new IP, add new firewall rules to forward to the correct address.

This is extremely annoying to go through daily.

**Comment by clshortfuse** [comment]
Had this issue installing `wsl.2.5.1.0.x64.msi`

> Failed to create network endpoint with address: '172.19.211.174', assigned new address: '172.25.225.21'

Solved it by using Hyper-V network

```ini
networkingMode=bridged
vmSwitch=WSL_external
```

I used to have this setup weeks ago, but was disabled at the time. My guess is some lingering Hyper-V configuration prevented install. After enabling it again, it installed successfully. Then I go back into `.wslconfig` and disable the lines again.

**Comment by DaRacci** [comment]
this seems to have been fixed by a recent update, possible 24H2.

**Comment by DaRacci** [comment]
> > this seems to have been fixed by a recent update, possible 24H2.
> 
> Would you mind explaining what was fixed? I've been having issues after installing 24H2, with WSL timing out or throwing network errors. Been using mirrored network mode fine up until now, I don't know what happened again. Feels like every update of every software in my pc breaks WSL somehow at this point.

It sounds like you're saying you only had the issues after the update, I have been having them for well ever since i first setup my WSL instance well over a year ago; The network would break on any mode for me and switching it from NAT to mirrored, starting, stopping, and then switch back for it to work.

I haven't had any issues with networking for a little while now, I'm not 100% sure it was 24H2 but that more so just a guess because of how many things changed on the backend for that update, it could have also been the February Cumulative based on my time estimate.

I also made one other change to my WSL which was installing an ubunutu variant from the Microsoft Store around the same time, I've only had the issue while i had a single instance which was a NixOS image i had created myself.

I'm not 100% what fixed this but i haven't had this issue for a few weeks now and cannot be certain exactly when this was fixed as I've only noticed the fact that it wasn't happening when i saw a notification for this issue.
