### ISSUE TITLE
Linux (Penguin) Icon did not appear in File Explorer Sidebar

### ISSUE THREAD

**Issue by dorea-l** [microsoft/WSL#11026]
### Windows Version

Microsoft Windows [Version 10.0.22631.3007]

### WSL Version

WSL version: 2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

Recently installed WSL.exe after uninstalling it about a year ago.
After which, I do not see any Linux icon in the sidebar of File Explorer

### Expected Behavior

This is what I expected my File Explorer to look like after WSL installation:
![Screenshot 2024-01-15 182445](https://github.com/microsoft/WSL/assets/156664072/900c53bc-2d00-4fa4-bae1-91dbdeb86999)

### Actual Behavior

![image](https://github.com/microsoft/WSL/assets/156664072/2ce981f5-a54b-4923-b8fe-a6a6cd2476ce)

However, there is no Linux folder in my sidebar. I am able to access Ubuntu through \\wsl$\Ubuntu without issue, but I am hoping to find a way to fix this as I would like to have a Linux folder that bundles all my distribution together.

### Diagnostic Logs

![image](https://github.com/microsoft/WSL/assets/156664072/4a9d5595-7da3-4411-bf8b-45cc850fe034)

**Comment by dorea-l** [comment]
Found a way to add Linux to Navigation Pane.
https://www.tenforums.com/tutorials/127506-add-remove-linux-navigation-pane-windows-10-a.html

**Comment by dorea-l** [comment]
It only worked for a while, after restarting, the Linux folder disappeared once again.

**Comment by pmartincic** [comment]
Do you know which version you were using before when it last worked?

**Comment by dorea-l** [comment]
I was using WSL2 before uninstalling.

**Comment by dorea-l** [comment]
No response after 2 weeks.

**Comment by OneBlue** [comment]
Fixed in [2.2.1](https://github.com/microsoft/WSL/releases/tag/2.2.1)

**Comment by dorea-l** [comment]
It wasn't fixed for me, the icon doesn't appear for me at all. 
I've downloaded 2.2.1 from the repository.

**Comment by dorea-l** [comment]
@OneBlue 
It wasn't fixed for me though. I've reinstalled WSL all over again but the Icon is still not appearing.

**Comment by Minchh** [comment]
@dorea-l 
Apparently the Linux icon was hidden for me. I fixed by right-clicking on the sidebar and enabling the "show all folders" option.

**Comment by dorea-l** [comment]
Nope, didn't work for me.

**Comment by SteveSayantan** [comment]
I just upgraded to 2.2.1 but the Linux icon doesn't work as expected on Windows 10 Pro. Nothing happens when it is clicked. Please help.
