### ISSUE TITLE
Cannot use GUI apps/tools as Wayland socket doesn't exist in `XDG_RUNTIME_DIR`

### ISSUE THREAD

**Issue by mangkoran** [microsoft/WSL#11261]
### Windows Version

10.0.19044.4046

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Arch

### Other Software

- wl-clipboard 2.2.1 (shouldn't be the root cause)
- systemd 255.4-2

### Repro Steps

1. Install `wl-clipboard` -> `sudo pacman -S wl-clipboard`
2. Run `echo "foobar" | wl-copy`

### Expected Behavior

`foobar` is copied to Windows clipboard through Wayland

### Actual Behavior

```sh
❯ echo "foobar" | wl-copy
Failed to connect to a Wayland server: No such file or directory
Note: WAYLAND_DISPLAY is set to wayland-0
Note: XDG_RUNTIME_DIR is set to /run/user/1000/
Please check whether /run/user/1000//wayland-0 socket exists and is accessible.
```

### Diagnostic Logs

Not applicable

### Additional Note 

I couldn't open any GUI apps and any Wayland-related tools such as `wl-copy`.

```sh
❯ echo "foobar" | wl-copy
Failed to connect to a Wayland server: No such file or directory
Note: WAYLAND_DISPLAY is set to wayland-0
Note: XDG_RUNTIME_DIR is set to /run/user/1000/
Please check whether /run/user/1000//wayland-0 socket exists and is accessible.
```

The following are the content of `/run/user/1000/`
```sh
❯ ls -la /run/user/1000/
total 0
drwx------ 7 mangkoran mangkoran 220 Mar  7 08:38 ./
drwxr-xr-x 3 root      root       60 Mar  7 08:34 ../
srw-rw-rw- 1 mangkoran mangkoran   0 Mar  7 08:34 bus=
prw------- 1 mangkoran mangkoran   0 Mar  7 08:34 fish_universal_variables.notifier|
drwx------ 2 mangkoran mangkoran  60 Mar  7 08:34 gcr/
drwx------ 2 mangkoran mangkoran 160 Mar  7 08:34 gnupg/
drwxr-xr-x 2 mangkoran mangkoran  60 Mar  7 08:34 p11-kit/
srw-rw-rw- 1 mangkoran mangkoran   0 Mar  7 08:34 pipewire-0=
srw-rw-rw- 1 mangkoran mangkoran   0 Mar  7 08:34 pipewire-0-manager=
drwxr-xr-x 2 mangkoran mangkoran  60 Mar  7 08:34 pulse/
drwxr-xr-x 6 mangkoran mangkoran 160 Mar  7 08:34 systemd/
```

Based on that it seems `wayland-0` socket is missing in `XDG_RUNTIME_DIR`. Hmm pretty weird I think as I don't disable `guiApplications` in `.wslconfig`.

Then I found https://github.com/microsoft/wslg/issues/1187. I proceed to check `/mnt/wslg/runtime-dir/`.
```sh
❯ ls -la /mnt/wslg/runtime-dir/
total 0
drwx------ 4 mangkoran mangkoran 120 Mar  7 09:24 ./
drwxrwxrwt 8 root      root      320 Mar  7 08:34 ../
drwx------ 3 mangkoran mangkoran  60 Mar  7 08:34 dbus-1/
drwx------ 2 mangkoran mangkoran  80 Mar  7 08:34 pulse/
srwxrwxrwx 1 mangkoran mangkoran   0 Mar  7 08:34 wayland-0=
-rw-rw---- 1 mangkoran mangkoran   0 Mar  7 08:34 wayland-0.lock
```

And yep there it is. So Wayland socket is currently not in `XDG_RUNTIME_DIR`. It seems the Wayland socket was previously symlinked in `XDG_RUNTIME_DIR` as in https://github.com/microsoft/WSL/issues/10205. Then I tried to link the Wayland socket.

```sh
~
❯ ln -s /mnt/wslg/runtime-dir/wayland-0* /run/user/1000/

~
❯ echo "foobar" | wl-copy

~
❯ echo $status
0
```

Although it works as intended, I think this isn't the default behavior/a regression.

### Workaround
As a workaround, I created a simple systemd user oneshot service/unit.

```sh
❯ cat ~/.config/systemd/user/symlink-wayland-socket.service
[Unit]
Description=Symlink Wayland socket to XDG_RUNTIME_DIR

[Service]
Type=oneshot
ExecStart=/usr/bin/ln -s /mnt/wslg/runtime-dir/wayland-0      $XDG_RUNTIME_DIR
ExecStart=/usr/bin/ln -s /mnt/wslg/runtime-dir/wayland-0.lock $XDG_RUNTIME_DIR

[Install]
WantedBy=default.target
```

Enable it using the following command.

```sh
systemctl --user enable symlink-wayland-socket.service
```

> [!TIP]
> For **Ubuntu 24.04** user, please refer to additional workaround by @noopole  https://github.com/microsoft/WSL/issues/11261#issuecomment-2233443300

**Comment by dixonwille** [comment]
Can confirm with:

### Versions

```
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3155
```

```
NAME="Fedora Linux"
VERSION="39 (Container Image)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
```

### Workaround

Exactly what @mangkoran mentioned by creating a oneshot systemd service.

**Comment by stefan-oskamp** [comment]
Many thanks, @mangkoran, for the details and the service script. Had the same issue with WSL 2.1.5 and Fedora 39 and the workaround fixed it.

**Comment by xuangeyouneihan** [comment]
Here is another workaround according to [this post](https://forum.snapcraft.io/t/wsl-wslg-and-systemd-hacks/24022/4). Create `/etc/systemd/system/user-runtime-dir@.service.d/override.conf` and add:
```
[Service]
ExecStart=sh -c "ln -fs /mnt/wslg/runtime-dir/* /run/user/$UID/"
```
This will link everything in `/mnt/wslg/runtime-dir` to `/run/user/$UID`. The reason why I don't mount `/mnt/wslg/runtime-dir` at `/run/user/$UID` like what the original post does is that it will cause `user@UID.service`'s failure due to `/run/user/$UID`'s incorrect owner

**Comment by king-11** [comment]
sorry for asking this novice question but @mangkoran how do we enable this service. Thanks for the help

**Comment by mangkoran** [comment]
@king-11 It should be like below.

```
systemd --user enable symlink-wayland-socket.service
```
I will add to my top post.

PS: A quick Google search should help you faster 😉

**Comment by gergelypolonkai** [comment]
Although this issue is about Wayland, for anyone who found this becaus X apps don’t work either (like me), if you want to use X11 apps, too, you will also have to symlink `/mnt/wslg/.X11-unix/X0` to `/tmp/.X11-unix/X0`.

**Comment by arf1372** [comment]
For me, X11 apps work but Wayland doesn't.

WSL info:
```powershell
> wsl --version
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3593
```

Ubuntu info:
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble
$ uname -a
Linux MaryamGhanavati 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

and systemd is enabled.

**Comment by mangkoran** [comment]
@arf1372 You could try the symlink command first (not the systemd service) and see if solves the issue on your machine.

```
ln -s /mnt/wslg/runtime-dir/wayland-0* /run/user/1000/
```
This command is harmless as it just symlinks and not removing any files. If anything goes wrong, you could restart WSL and everything will be reverted.

**Comment by Kunal-Singh-Dadhwal** [comment]
> For me, X11 apps work but Wayland doesn't.
> 
> WSL info:
> 
> ```powershell
> > wsl --version
> WSL version: 2.1.5.0
> Kernel version: 5.15.146.1-2
> WSLg version: 1.0.60
> MSRDC version: 1.2.5105
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows version: 10.0.22631.3593
> ```
> 
> Ubuntu info:
> 
> ```shell
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 24.04 LTS
> Release:        24.04
> Codename:       noble
> $ uname -a
> Linux *** 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> and systemd is enabled.
> 
> tried:
> 
> ```shell
> $ echo "hello" | wl-copy
> Failed to connect to a Wayland server: No such file or directory
> Note: WAYLAND_DISPLAY is set to wayland-0
> Note: XDG_RUNTIME_DIR is set to /run/user/1000/
> Please check whether /run/user/1000//wayland-0 socket exists and is accessible.
> ```
> 
> As I fear the provided workaround may break my system(?) I didn't test it.

Hey bro , could you tell how you configured X11?

**Comment by tusharsnx** [comment]
Ubuntu-24.04 set these files differently than Ubuntu-22.04:

![image](https://github.com/user-attachments/assets/ee2df94d-c556-4b00-ad8b-5994dbd23aae)
![image](https://github.com/user-attachments/assets/4731c54b-1309-45c5-9160-09f842632db6)

I don't think I ever faced this issue on Ubuntu 22.04. On 24.04, I can't even run `ls` on `/mnt/wslg/runtime-dir/` without sudo, whereas 22.04 doesn't require it all.

**Comment by noopole** [comment]
> I don't think I ever faced this issue on Ubuntu 22.04. On 24.04, I can't even run `ls` on `/mnt/wslg/runtime-dir/` without sudo, whereas 22.04 doesn't require it all.

To make it work under Ubuntu 24.04 I had to set `rx` permissions on `runtime-dir`, then I could create the simlink.

```
sudo chmod +rx /mnt/wslg/runtime-dir
ln -s /mnt/wslg/runtime-dir/wayland-0* /run/user/1002/
```

(where 1002 is the current user.)

**Comment by alonbl** [comment]
WSLg bug: https://github.com/microsoft/wslg/issues/1244

**Comment by feoh** [comment]
So, this may not be a satisfying work-around for everyone, but this poblem was bowing up my Neovim session, because WAYLAND_DISPLAY was set, causing Neovim to assume that wl-copy was in play and working properly.

I added this awful bodge to my .zshrc that may help someone so I am including it here. If WSL is detected, we unset WAYLAND_DISPLAY but also add a 'wway' alias to put it back if we actually WANT to run a GUI app :)

```
# Under WSL, we KINDA have Wayland, but not really, and that blows up Neovim. Ungh. :)
# Add an alias so if we actually WANT the pseudo wayland, we can haz.

if [[ $(uname -r | grep "microsoft") ]] then
        unset WAYLAND_DISPLAY
        alias wway='export WAYLAND_DISPLAY=wayland-0'
fi
```

Yay! My neovim works again :)

**Comment by vanderzielj** [comment]
Thank you @mangkoran 

This is an issue for me on Ubuntu 24.04.1 LTS running on WSL2

```
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22631.4037
```

**Comment by shpankau** [comment]
So, this was also blowing up my copying while using Neovim (nvim) after my [X410](https://x410.dev/) trial ended:
```
$ echo abc | /usr/bin/wl-copy.orig
Failed to connect to a Wayland server: No such file or directory
Note: WAYLAND_DISPLAY is set to wayland-0
Note: XDG_RUNTIME_DIR is set to /run/user/1000/
Please check whether /run/user/1000//wayland-0 socket exists and is accessible.
```
My issue was not pasting into WSL, but copying from WSL and pasting into Windows, especially from nvim.

Unless you have disabled it, you should be able to run Windows binaries from within WSL 2. The workaround for clipboard access I have implemented is to wrapper Microsoft's bundled [c:\Windows\system32\clip.exe](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/clip) binary in a script to copy:
```
#!/bin/bash
# the pbcopy script

tee <&0 | clip.exe
exit 0
```

For pasting, I opted to wrapper PowerShell and strip the extraneous appended carriage return or null:
```
#!/bin/bash
# the pbpaste script

powershell.exe Get-Clipboard | sed 's/\r$//' | sed -z '$ s/\n$//'
exit 0
```

Put these scripts in `/usr/bin` as `/usr/bin/pbcopy` and `/usr/bin/pbpaste`. Then rename wl-copy and wl-paste and symlink the pb scripts:
```
$ sudo mv /usr/bin/wl-copy{,.orig}
$ sudo mv /usr/bin/wl-paste{,.orig}
$ sudo ln -s /usr/bin/pbcopy /usr/bin/wl-copy
$ sudo ln -s /usr/bin/pbpaste /usr/bin/wl-paste
```

If you want to test this in nvim, go into visual mode, select some text, and press `<Ctrl-R>"+y` to yank the selection to the system clipboard. Then try pasting it in a Windows app.

Yes, you could just name the scripts wl-copy and wl-paste, but I use symlinks to avoid confusing myself six months from now.

The other benefit of symlinking is being able to use the `pbcopy` and `pbpaste` commands like I would in macOS.  😄 

**NOTE:** This approach assumes you only want to copy/paste text. Unlike wl-copy/paste the MIME type is stripped/ignored.

**Comment by paolomissagia** [comment]
Thanks for reporting @mangkoran . I've got the same issue here with Fedora 40 under WSL2.

Doing the symlink command above fixed it for me for now.

**Comment by tkonsta** [comment]
For me the symlink creation as explained in the "workaround" section of the initial description in this issue, together with the permission change @noopole mentioned, did the trick. Thanks a lot for compiling that information, @mangkoran and @noopole!

However, the permission change seems to be reverted after each reboot, so I wondered if someone already has come up with a good idea about how to make this permission change permanent or at least recreate it on startup. I was thinking of just another systemd oneshot service/unit running as root, but maybe there's more elegant ways?

**Comment by codeart1st** [comment]
> For me the symlink creation as explained in the "workaround" section of the initial description in this issue, together with the permission change [@noopole](https://github.com/noopole) mentioned, did the trick. Thanks a lot for compiling that information, [@mangkoran](https://github.com/mangkoran) and [@noopole](https://github.com/noopole)!
> 
> However, the permission change seems to be reverted after each reboot, so I wondered if someone already has come up with a good idea about how to make this permission change permanent or at least recreate it on startup. I was thinking of just another systemd oneshot service/unit running as root, but maybe there's more elegant ways?

```
:~$ cat /etc/systemd/user/symlink-wayland-socket.service
[Unit]
Description=Symlink Wayland socket to XDG_RUNTIME_DIR

[Service]
Type=oneshot
ExecStart=/usr/bin/ln -s /mnt/wslg/runtime-dir/wayland-0      $XDG_RUNTIME_DIR
ExecStart=/usr/bin/ln -s /mnt/wslg/runtime-dir/wayland-0.lock $XDG_RUNTIME_DIR

[Install]
WantedBy=default.target
```

**Comment by tkonsta** [comment]
This is the same snippet, which had been already described as "workaround" in the initial description of this issue. However, I was referring to ideas about how to make the permission change permanent, which has been mentioned by @noopole above:

```
sudo chmod +rx /mnt/wslg/runtime-dir (or) chown 1002:1002 /mnt/wslg/runtime-dir
ln -s /mnt/wslg/runtime-dir/wayland-0* /run/user/1002/
```

**Comment by mangkoran** [comment]
> So, this may not be a satisfying work-around for everyone, but this poblem was bowing up my Neovim session, because WAYLAND_DISPLAY was set, causing Neovim to assume that wl-copy was in play and working properly.
> 
> I added this awful bodge to my .zshrc that may help someone so I am including it here. If WSL is detected, we unset WAYLAND_DISPLAY but also add a 'wway' alias to put it back if we actually WANT to run a GUI app :)
> 
> ```
> # Under WSL, we KINDA have Wayland, but not really, and that blows up Neovim. Ungh. :)
> # Add an alias so if we actually WANT the pseudo wayland, we can haz.
> 
> if [[ $(uname -r | grep "microsoft") ]] then
>         unset WAYLAND_DISPLAY
>         alias wway='export WAYLAND_DISPLAY=wayland-0'
> fi
> ```
> 
> Yay! My neovim works again :)

@feoh I use Neovim in WSL too and there is no need to unset `WAYLAND_DISPLAY` if you follow the workaround.

- First make sure to follow the workaround in issue description
- Set `vim.opt.clipboard = "unnamedplus"` in Neovim ([docs](https://neovim.io/doc/user/options.html#'clipboard'))
- Install `wl-clipboard`
- Reboot WSL

This way you will have functional clipboard that interop/sync with Windows clipboard (yes you can yank and paste to and from Windows clipboard). Please let me know if it works for you ^_^

**Comment by cjohansson** [comment]
For me on Ubuntu 24.04.01 LTS this script worked
```
> cat ~/.config/systemd/user/symlink-wayland-socket.service
[Unit]
Description=Symlink Wayland socket to XDG_RUNTIME_DIR

[Service]
Type=oneshot
ExecStart=ln -s /mnt/wslg/runtime-dir/wayland-0* /run/user/1000/

[Install]
WantedBy=default.target
```

I have no idea why @mangkoran script did not work, I know it worked for earlier Ubuntus under WSL

**Comment by tusharsnx** [comment]
@tkonsta 
> This is the same snippet, which had been already described as "workaround" in the initial description of this issue. However, I was referring to ideas about how to make the permission change permanent, which has been mentioned by noopole above:

The permission issue is fixed in the latest Ubuntu-24.04 https://github.com/microsoft/WSL/issues/11542 (tldr: You need to reinstall Ubuntu-24. Make sure to backup your files.)

**Comment by AlePini** [comment]
> So, this may not be a satisfying work-around for everyone, but this poblem was bowing up my Neovim session, because WAYLAND_DISPLAY was set, causing Neovim to assume that wl-copy was in play and working properly.
> 
> I added this awful bodge to my .zshrc that may help someone so I am including it here. If WSL is detected, we unset WAYLAND_DISPLAY but also add a 'wway' alias to put it back if we actually WANT to run a GUI app :)
> 
> ```
> # Under WSL, we KINDA have Wayland, but not really, and that blows up Neovim. Ungh. :)
> # Add an alias so if we actually WANT the pseudo wayland, we can haz.
> 
> if [[ $(uname -r | grep "microsoft") ]] then
>         unset WAYLAND_DISPLAY
>         alias wway='export WAYLAND_DISPLAY=wayland-0'
> fi
> ```
> 
> Yay! My neovim works again :)

@feoh This is absolutely the best way to do it imo. I love it, thanks!

**Comment by tilly63** [comment]
Many thanks, @mangkoran, for the precise description. I had the same problem with WSL 2.3.26.0 and distribution Debian 12 (Bookworm). The workaround fixed the problem.

**Comment by ajkessel** [comment]
I'm still seeing this for snap apps like Firefox, which generates the error: `[2270] Wayland Proxy [0x7f8b7ce61cd0] Error: CheckWaylandDisplay(): Failed to connect to Wayland display '/run/user/1000/snap.firefox/wayland-0' error: No such file or directory`
```
WSL version: 2.4.8.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5716
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.19045.5247
```
This command is a workaround, but shouldn't the system handle this automatically?
```
ln -s /mnt/wslg/runtime-dir/wayland-0 /run/user/1000/snap.firefox
```

**Comment by arf1372** [comment]
Hello
I'm here to report my issue has been fixed after I upgraded both WSL and Ubuntu. Now, I'm using:

```powershell
> wsl --version
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2605
```

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.10
Release:        24.10
Codename:       oracular
```

P.S.: I've used `do-release-upgrade` on my Ubuntu to upgrade.

**Comment by ajkessel** [comment]
@arf1372 do you use any graphical snaps? I'm wondering if my problem still exists for everyone or if it is particular to my setup.

**Comment by CarlosNihelton** [comment]
I looked into this topic more thoroughly with WSL 2.3.26 and WSL 2.4.8 and both meet the following description when systemd is enabled: 

- WSL creates the `/run/user` tmpfs mount point.
- WSL creates the `/run/user/<UID>` **subdirectory** and populates it with the interesting contents, such as the wayland-0 socket.
- systemd's `user-runtime-dir@<UID>.service` unit eventually kicks in and attempts to create the user runtime directory as a mount point, but it first checks whether that directory is already a mount point or not:

https://github.com/systemd/systemd/blob/main/src/login/user-runtime-dir.c#L81-L82

Here we fork. On older versions of systemd that don't contain [this commit](https://github.com/systemd/systemd/pull/31205/commits/561d8793058bba886d71f96fa157ca77cd6b5c23), the binary `/lib/systemd/systemd-user-runtime-dir` checks whether the existing `/run/user/<UID>` is a mount point and the check "suceeds" because the line below makes the `path_is_mount_point()` function return 0, what the comparison considered succesful.

https://github.com/systemd/systemd/blob/main/src/basic/mountpoint-util.c#L274-L275

Newer versions of systemd had that behaviour fixed (return 0 is not a mount point), thus instead of stopping there, the `systemd-user-runtime-dir` binary proceeds with creating `/run/user/1000` as a tmpfs mount point, effectively wiping out any previous content.

Ubuntu 22.04 is an example of the first case while Ubuntu 24.04 demonstrates the second case.

I suspect the easiest and cleanest way to solve this is by having WSL create `/run/user/<UID>` as a tmpfs mount point instead of directory.

**Comment by benhillis** [comment]
> I looked into this topic more thoroughly with WSL 2.3.26 and WSL 2.4.8 and both meet the following description when systemd is enabled:
> 
> * WSL creates the `/run/user` tmpfs mount point.
> * WSL creates the `/run/user/<UID>` **subdirectory** and populates it with the interesting contents, such as the wayland-0 socket.
> * systemd's `user-runtime-dir@<UID>.service` unit eventually kicks in and attempts to create the user runtime directory as a mount point, but it first checks whether that directory is already a mount point or not:
> 
> https://github.com/systemd/systemd/blob/main/src/login/user-runtime-dir.c#L81-L82
> 
> Here we fork. On older versions of systemd that don't contain [this commit](https://github.com/systemd/systemd/pull/31205/commits/561d8793058bba886d71f96fa157ca77cd6b5c23), the binary `/lib/systemd/systemd-user-runtime-dir` checks whether the existing `/run/user/<UID>` is a mount point and the check "suceeds" because the line below makes the `path_is_mount_point()` function return 0, what the comparison considered succesful.
> 
> https://github.com/systemd/systemd/blob/main/src/basic/mountpoint-util.c#L274-L275
> 
> Newer versions of systemd had that behaviour fixed (return 0 is not a mount point), thus instead of stopping there, the `systemd-user-runtime-dir` binary proceeds with creating `/run/user/1000` as a tmpfs mount point, effectively wiping out any previous content.
> 
> Ubuntu 22.04 is an example of the first case while Ubuntu 24.04 demonstrates the second case.
> 
> I suspect the easiest and cleanest way to solve this is by having WSL create `/run/user/<UID>` as a tmpfs mount point instead of directory.

Hey Carlos, thanks for digging in and helping here! I think you're right, I just built a private WSL that creates a tmpfs mount as /run/user/<uid> and it looks like the repo above is working. I'll clean this up and get this submitted.

Thanks to everybody for your help here.

**Comment by benhillis** [comment]
bad bot!

**Comment by ajkessel** [comment]
Is there a simple workaround to implement this tmpfs solution while we await integration into the main project? I'm currently doing this in my `.bashrc` but seems like a bad/awkward temporary solution:
```
[ -L /tmp/.X11-unix ] || ( printf 'Replacing /tmp/.X11-unix with symlink\n' && sudo rm -r /tmp/.X11-unix/ && sudo ln -s /mnt/wslg/.X11-unix /tmp )
```

**Comment by CarlosNihelton** [comment]
> Is there a simple workaround to implement this tmpfs solution while we await integration into the main project?

Attempting to create the tmpfs mount point early in boot is possible because you could create a systemd unit to run before `user-runtime-dir@1000.service`, but that may easily result in broken symlinks to the stuff in `/mnt/wslg/runtime-dir/´, so late approaches like yours are more reliable in my opinion.

**Comment by stefan-oskamp** [comment]
I had the same issue (commented earlier, above), but at the moment, I can run Wayland apps (Firefox) without a workaround.

WSL version:
```
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.22631.4602
```

I have upgraded Fedora in WSL from 40 to 41 recently.

When I open a WSL session, I see
```
$ echo $XDG_RUNTIME_DIR
/mnt/wslg/runtime-dir
```

I could not figure out where XDG_RUNTIME_DIR is set. It seems it's somehow set by WSL.

I can run Firefox even when unsetting DISPLAY, so no X involved.

Is setting XDG_RUNTME_DIR like above perhaps a simpler workaround for the ones who have problems running Wayland apps?

**Comment by segevfiner** [comment]
It seems like the issue is that WSLg wants to set `XDG_RUNTIME_DIR\ but something in the installed OS overrides it. I think `pam_systemd`. WSLg will need to incorporate adding such links/mount by itself or figure out how to override that. Otherwise wayland won't work.

**Comment by segevfiner** [comment]
I hate auto ignore issues bots! Now you are just going to get duplicates if multiple people try to resubmit this...

**Comment by mangkoran** [comment]
Hi @benhillis . Could we keep this ticket opened as long as the fix hasn't applied yet?

**Comment by schlich** [comment]
still running into this issue

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/2.5.1

**Comment by feoh** [comment]
> Fixed with https://github.com/microsoft/WSL/releases/tag/2.5.1

SO EXCITING!

I look forward to retiring my `fixwway` alias ;)

`alias fixwway='ln -s /mnt/wslg/runtime-dir/wayland-0* /run/user/1000/'`

**Comment by schlich** [comment]
I'm also still having the same issues in the new prerelease, I wonder if there are settings we can check to make sure we're getting a 'clean' config?

**Comment by marcushallett** [comment]
I'm also still having this issue. If there isn't a currently open issue, it would be nice if one could be created and exempted from closure by @microsoft-github-policy-service

**Comment by tilly63** [comment]
Did you try to disable Wayland?
In /etc/gdm3/daemon.conf

[daemon]
# Uncomment the line below to force the login screen to use Xorg
WaylandEnable=false

**Comment by boltronics** [comment]
Same issue. I just wanted `pass` to work in Debian. I ended up putting this at the end of my `.bashrc` file:
```
if [ -n "${WAYLAND_DISPLAY}" ] &&
    [ ! -h "/run/user/${UID}/${WAYLAND_DISPLAY}" ]
then
    ln -sf "/mnt/wslg/runtime-dir/${WAYLAND_DISPLAY}" "/run/user/${UID}/"
fi
```

**Comment by kidmose** [comment]
Fixed identical issue on a windows 11 machine by updating (was <2.5.1 but don't remember which).
On a another machine running windows 10, I see the same error, and it is already running  wsl 2.6.1.0. 

Applied the symlink solution and solved it.
If you happens to be running nixos inside you wsl, you can refer to this: 

``` wsl-wayland-fix.nix
# Solution taken from https://github.com/microsoft/WSL/issues/11261
# which should be solved with 2.5.1.  Confirmed to fix the error on my
# win 11 box, upgrading from something before to something after
# (2.6.1 perhaps).  But on a win 10 wsl 2.6.1 the error also occurs
# and this solved the issue.

{ config, lib, pkgs, stdenv, ... }:
{
  systemd.user.services.symlink-wayland-socket = {
    description = "Symlink Wayland socket to XDG_RUNTIME_DIR";
    wantedBy = [ "default.target" ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = [
        "/run/current-system/sw/bin/mkdir -p /run/user/1000"
        "/run/current-system/sw/bin/ln -sf /mnt/wslg/runtime-dir/wayland-0 /run/user/1000/"
        "/run/current-system/sw/bin/ln -sf /mnt/wslg/runtime-dir/wayland-0.lock /run/user/1000/"
      ];
    };
  };
}
```
