### ISSUE TITLE
MSI installer "Warning: 1946.Property [...] could not be set."

### ISSUE THREAD

**Issue by ColorfulRhino** [microsoft/WSL#11276]
### Windows Version

Microsoft Windows [Version 10.0.22631.3155]

### WSL Version

2.2.1.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 22.04

### Repro Steps

1) Download `wsl.2.2.1.0.x64.msi`, `wsl.2.1.4.0.x64.msi` or `wsl.2.1.1.0.x64.msi` from this repository's releases page.
2) Double click the installer
3) Confirm admin prompt
4) Let installer run
5) Warning appears:
![Screenshot](https://github.com/microsoft/WSL/assets/131405023/3406951e-50f4-4eea-9ba8-632679ece38f)
6) Click OK
7) Installation finishes

### Expected Behavior

No warning during install

### Actual Behavior

Warning appears during install:

![Screenshot](https://github.com/microsoft/WSL/assets/131405023/3406951e-50f4-4eea-9ba8-632679ece38f)

### Diagnostic Logs

From collected logs via `msiexec /i <path/to/msi> /L*V C:\wsllogs.txt`:
(See error where the blank lines are)

```
[...]
MSI (s) (98:0C) [23:30:51:044]: File: C:\Program Files\WSL\tr-TR\msrdc.exe.mui;	To be installed;	Won't patch;	No existing file
MSI (s) (98:0C) [23:30:51:044]: Source for file 'msrdc.exe.mui_tr_TR' is compressed
MSI (s) (98:0C) [23:30:51:045]: Executing op: FileCopy(SourceName=60wmt6ni.mui|rdclientax.dll.mui,SourceCabKey=rdclientax.dll.mui_tr_TR,DestName=rdclientax.dll.mui,Attributes=512,FileSize=143408,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=1.2.5105.0,Language=1033,InstallMode=62914560,,,,,,,)
MSI (s) (98:0C) [23:30:51:045]: File: C:\Program Files\WSL\tr-TR\rdclientax.dll.mui;	To be installed;	Won't patch;	No existing file
MSI (s) (98:0C) [23:30:51:045]: Source for file 'rdclientax.dll.mui_tr_TR' is compressed
MSI (s) (98:0C) [23:30:51:046]: Executing op: SetTargetFolder(Folder=C:\Program Files\WSL\zh-CN\)
MSI (s) (98:0C) [23:30:51:046]: Executing op: SetSourceFolder(Folder=1\PFiles64\WSL\zh-CN\)
MSI (s) (98:0C) [23:30:51:046]: Executing op: FileCopy(SourceName=hhlvgwqx.mui|msrdc.exe.mui,SourceCabKey=msrdc.exe.mui_zh_CN,DestName=msrdc.exe.mui,Attributes=512,FileSize=49184,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=1.2.5105.0,Language=1033,InstallMode=62914560,,,,,,,)
MSI (s) (98:0C) [23:30:51:046]: File: C:\Program Files\WSL\zh-CN\msrdc.exe.mui;	To be installed;	Won't patch;	No existing file
MSI (s) (98:0C) [23:30:51:047]: Source for file 'msrdc.exe.mui_zh_CN' is compressed
MSI (s) (98:0C) [23:30:51:048]: Executing op: FileCopy(SourceName=izy0lorj.mui|rdclientax.dll.mui,SourceCabKey=rdclientax.dll.mui_zh_CN,DestName=rdclientax.dll.mui,Attributes=512,FileSize=143408,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=1.2.5105.0,Language=1033,InstallMode=62914560,,,,,,,)
MSI (s) (98:0C) [23:30:51:048]: File: C:\Program Files\WSL\zh-CN\rdclientax.dll.mui;	To be installed;	Won't patch;	No existing file
MSI (s) (98:0C) [23:30:51:048]: Source for file 'rdclientax.dll.mui_zh_CN' is compressed
MSI (s) (98:0C) [23:30:51:049]: Executing op: SetTargetFolder(Folder=C:\Program Files\WSL\zh-TW\)
MSI (s) (98:0C) [23:30:51:049]: Executing op: SetSourceFolder(Folder=1\PFiles64\WSL\zh-TW\)
MSI (s) (98:0C) [23:30:51:049]: Executing op: FileCopy(SourceName=spvcbrtv.mui|msrdc.exe.mui,SourceCabKey=msrdc.exe.mui_zh_TW,DestName=msrdc.exe.mui,Attributes=512,FileSize=49184,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=1.2.5105.0,Language=1033,InstallMode=62914560,,,,,,,)
MSI (s) (98:0C) [23:30:51:049]: File: C:\Program Files\WSL\zh-TW\msrdc.exe.mui;	To be installed;	Won't patch;	No existing file
MSI (s) (98:0C) [23:30:51:049]: Source for file 'msrdc.exe.mui_zh_TW' is compressed
MSI (s) (98:0C) [23:30:51:050]: Executing op: FileCopy(SourceName=jilcuv4y.mui|rdclientax.dll.mui,SourceCabKey=rdclientax.dll.mui_zh_TW,DestName=rdclientax.dll.mui,Attributes=512,FileSize=143408,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=1.2.5105.0,Language=1033,InstallMode=62914560,,,,,,,)
MSI (s) (98:0C) [23:30:51:050]: File: C:\Program Files\WSL\zh-TW\rdclientax.dll.mui;	To be installed;	Won't patch;	No existing file
MSI (s) (98:0C) [23:30:51:050]: Source for file 'rdclientax.dll.mui_zh_TW' is compressed
MSI (s) (98:0C) [23:30:51:051]: Executing op: CacheSizeFlush(,)
MSI (s) (98:0C) [23:30:51:051]: Executing op: ActionStart(Name=CreateShortcuts,Description=Creating shortcuts Shortcut: [1],)
MSI (s) (98:0C) [23:30:51:057]: Executing op: IconCreate(Icon=wsl.ico,Data=BinaryData)
MSI (s) (98:0C) [23:30:51:058]: Executing op: SetTargetFolder(Folder=23)
MSI (s) (98:0C) [23:30:51:059]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Start Menu\Programs
MSI (s) (98:0C) [23:30:51:059]: Executing op: ShortcutCreate(Name=WSL,Feature=WSL,Component={F0C8D6BA-1502-41E7-BF72-D93DFA134730}[~]2,,Arguments=--cd ~,,Icon=wsl.ico,,,,Description=Windows Subsystem for Linux,,,,)
MSI (s) (98:0C) [23:30:51:063]: Executing op: ShortcutPropertyCreate(ShortcutName=WSL,PropertyKey=System.AppUserModel.ID,PropVariantValue=Microsoft.WSL)
MSI (s) (98:0C) [23:30:51:071]: Executing op: ShortcutPropertyCreate(ShortcutName=WSL,PropertyKey=System.AppUserModel.ToastActivatorCLSID,PropVariantValue={2B9C59C3-98F1-45C8-B87B-12AE3C7927E8})
MSI (s) (98:0C) [23:30:51:073]: Note: 1: 1946 2: System.AppUserModel.ToastActivatorCLSID 3: WSL.lnk 4: 32 
MSI (s) (98:0C) [23:30:51:073]: Note: 1: 2205 2:  3: Error 
MSI (s) (98:0C) [23:30:51:073]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1946 
MSI (c) (20:90) [23:30:51:080]: Font created.  Charset: Req=1, Ret=0, Font: Req=, Ret=Arial

MSI (c) (20:90) [23:30:51:080]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

Warning 1946.Property 'System.AppUserModel.ToastActivatorCLSID' for shortcut 'WSL.lnk' could not be set. HRESULT 32.
MSI (s) (98:0C) [23:31:00:188]: Executing op: SetTargetFolder(Folder=23)
MSI (s) (98:0C) [23:31:00:189]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Start Menu\Programs
MSI (s) (98:0C) [23:31:00:189]: Executing op: ActionStart(Name=CleanMsixState,,)
MSI (s) (98:0C) [23:31:00:190]: Executing op: CustomActionSchedule(Action=CleanMsixState,ActionType=3073,Source=BinaryData,Target=CleanMsixState,)
MSI (s) (98:D8) [23:31:00:192]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI36D5.tmp, Entrypoint: CleanMsixState
MSI (s) (98:0C) [23:31:00:198]: Executing op: ActionStart(Name=WriteRegistryValues,Description=Writing system registry values Key: [1], Name: [2], Value: [3],)
MSI (s) (98:0C) [23:31:00:198]: Executing op: ProgressTotal(Total=39,Type=1,ByteEquivalent=13200)
MSI (s) (98:0C) [23:31:00:198]: Executing op: RegOpenKey(,Key=Interface\{38541BDC-F54F-4CEB-85D0-37F0F3D2617E},,BinaryType=1,ControlRegistryReflection=0,)
MSI (s) (98:0C) [23:31:00:198]: Executing op: RegAddValue(,Value=ILxssUserSession,)
MSI (s) (98:0C) [23:31:00:198]: Disabling reflection on key: HKEY_LOCAL_MACHINE\Software\Classes\Interface\{38541BDC-F54F-4CEB-85D0-37F0F3D2617E}
MSI (s) (98:0C) [23:31:00:198]: Executing op: RegOpenKey(,Key=Interface\{38541BDC-F54F-4CEB-85D0-37F0F3D2617E}\ProxyStubClsid32,,BinaryType=1,ControlRegistryReflection=0,)
MSI (s) (98:0C) [23:31:00:198]: Executing op: RegAddValue(,Value={4EA0C6DD-E9FF-48E7-994E-13A31D10DC60},)
MSI (s) (98:0C) [23:31:00:198]: Disabling reflection on key: HKEY_LOCAL_MACHINE\Software\Classes\Interface\{38541BDC-F54F-4CEB-85D0-37F0F3D2617E}\ProxyStubClsid32
MSI (s) (98:0C) [23:31:00:198]: Executing op: RegOpenKey(,Key=CLSID\{4EA0C6DD-E9FF-48E7-994E-13A31D10DC60},,BinaryType=1,ControlRegistryReflection=0,)
MSI (s) (98:0C) [23:31:00:198]: Executing op: RegAddValue(,Value=PSFactoryBuffer,)
MSI (s) (98:0C) [23:31:00:198]: Disabling reflection on key: HKEY_LOCAL_MACHINE\Software\Classes\CLSID\{4EA0C6DD-E9FF-48E7-994E-13A31D10DC60}
MSI (s) (98:0C) [23:31:00:198]: Executing op: RegOpenKey(,Key=CLSID\{4EA0C6DD-E9FF-48E7-994E-13A31D10DC60}\InProcServer32,,BinaryType=1,ControlRegistryReflection=0,)
MSI (s) (98:0C) [23:31:00:198]: Executing op: RegAddValue(,Value=C:\Program Files\WSL\wslserviceproxystub.dll,)
[...]
```

**Comment by OneBlue** [comment]
Thank you @ColorfulRhino. Could you share the full MSI logs of a WSL installation ?

**Comment by OneBlue** [comment]
Thank you @ColorfulRhino. Let's try something: What if you delete `"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\WSL.lnk"`, and then run the installer again ? Does the warning disappear then ?

**Comment by kristibektashi** [comment]
I've seen such warnings with shortcuts appear with other MSI packages as well, and I suspect this is an issue with the Windows Installer service not being able to properly handle shortcuts in the latest updates (although I am running build 26100). If that is indeed the case, this issue should be reported to the Feedback Hub, not here.

**Comment by luxferre** [comment]
`PS C:\Users\abima> wsl --update
Проверяется наличие обновлений.
Обновление подсистема Windows для Linux до версии: 2.2.4.
Warning 1946.Property 'System.AppUserModel.ID' for shortcut 'WSL.lnk' could not be set.
Warning 1946.Property 'System.AppUserModel.ToastActivatorCLSID' for shortcut 'WSL.lnk' could not be set.`

**Comment by Mister-Click** [comment]
> ```
> PS C:\Users\abima> wsl --update
> Проверяется наличие обновлений.
> Обновление подсистема Windows для Linux до версии: 2.2.4.
> Warning 1946.Property 'System.AppUserModel.ID' for shortcut 'WSL.lnk' could not be set.
> Warning 1946.Property 'System.AppUserModel.ToastActivatorCLSID' for shortcut 'WSL.lnk' could not be set.```
> ```

I was having the same issue and updated Windows, a Windows Cumulative Update fixed it.

**Comment by avjts** [comment]
I experience similar elusive problem with different product, and I found the culprit is PowerToys.PowerLauncher.exe (a PowerToys quick launcher feature).
The additional question to @ColorfulRhino and others may be: Do you use PowerToys and have PowerToys Run feature enabled?
If yes, then you experience the issue I reported to PowerToys project: https://github.com/microsoft/PowerToys/issues/34391

**Comment by CYGG1123** [comment]
> I experience similar elusive problem with different product, and I found the culprit is PowerToys.PowerLauncher.exe (a PowerToys quick launcher feature). The additional question to @ColorfulRhino and others may be: Do you use PowerToys and have PowerToys Run feature enabled? If yes, then you experience the issue I reported to PowerToys project: [microsoft/PowerToys#34391](https://github.com/microsoft/PowerToys/issues/34391)

Truly, My PC encountered this problem after I updating the PowerToys, while many files lost their association with default application with error info like "can't find file at <Path for file>" while file is actually here.

**Comment by Stanzilla** [comment]
Also getting this error since the last ~4 updates

**Comment by luxferre** [comment]
Yes, I had the freature enabled when the issue appears.
I had not experienced the issue anymore (but afair there were no wsl update since the time). Next time I'll try update with the feature disabled, thank you.

> a PowerToys quick launcher feature

**Comment by DiskCrasher** [comment]
Still seeing this error with v2.3.26.0. And yes, I have PowerToys installed.

**Comment by gdevacc12** [comment]
DItto @DiskCrasher
```
PS>wsl --update
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.3.26.
Warning 1946.Property 'System.AppUserModel.ToastActivatorCLSID' for shortcut 'WSL.lnk' could not be set.
```

PowerToys Release v0.87.1

**Comment by trailstrider** [comment]
> DItto [@DiskCrasher](https://github.com/DiskCrasher)
> 
> ```
> PS>wsl --update
> Checking for updates.
> Updating Windows Subsystem for Linux to version: 2.3.26.
> Warning 1946.Property 'System.AppUserModel.ToastActivatorCLSID' for shortcut 'WSL.lnk' could not be set.
> ```
> 
> PowerToys Release v0.87.1

This was exactly my experience with this....  watching.

**Comment by svboyko** [comment]
```
PS> wsl --update
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.3.26.
Warning 1946.Property 'System.AppUserModel.ID' for shortcut 'WSL.lnk' could not be set.
Warning 1946.Property 'System.AppUserModel.ToastActivatorCLSID' for shortcut 'WSL.lnk' could not be set.
```
PowerToys v0.85.1

**Comment by NikosGavriilatos** [comment]
I stopped PowerToys, PowerToys Awake, Power Automate from running, and I stopped having this problem with the installation. 
PowerToys v0.80.0

**Comment by StephenHodgson** [comment]
```terminal
wsl --update
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.3.26.
Warning 1946.Property 'System.AppUserModel.ToastActivatorCLSID' for shortcut 'WSL.lnk' could not be set.
```

Unsure of what version of power toys I have installed, but I don't remember installing it to begin with.

**Comment by markeissler** [comment]
Well I have the most recent version installed (as of today): v0.88.0. Just saw this error when running `wsl --update`.

**Comment by gut5** [comment]
```
wsl --update --pre-release
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.4.10.
Warning 1946.Property 'System.AppUserModel.ToastActivatorCLSID' for shortcut 'WSL.lnk' could not be set.
```

**Comment by adifferenthero** [comment]
`>wsl --update
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.4.11.
Warning 1946.Property 'System.AppUserModel.ToastActivatorCLSID' for shortcut 'WSL.lnk' could not be set.`

Still getting the error with Powertoys v1.87.1

**Comment by Petalzu** [comment]
```
wsl --update
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.4.11.
Warning 1946.Property 'System.AppUserModel.ID' for shortcut 'WSL.lnk' could not be set.
Warning 1946.Property 'System.AppUserModel.ToastActivatorCLSID' for shortcut 'WSL.lnk' could not be set.
```
PowerToys version v0.88.0

The error does not seem to occur when the PowerToys software is closed.

**Comment by OneBlue** [comment]
Fixed by: https://github.com/microsoft/PowerToys/pull/37654

**Comment by cachius** [comment]
@OneBlue Unfortunately the issue still exists (again ?). Just encountered it with update from WSL 2.6.1 to 2.6.3 and PowerToys v0.97.2. At least the _Warning 1946.Property 'System.AppUserModel.ID'_ is gone.
```
Warning 1946.Property 'System.AppUserModel.ToastActivatorCLSID' for shortcut 'WSL.lnk' could not be set.
```
<img width="946" height="58" alt="Image" src="https://github.com/user-attachments/assets/16ddf489-8c01-478d-a6e2-fa939eb0c313" />

---

Also in https://github.com/microsoft/WSL/issues/13469 from September 2025. So the intended fix https://github.com/microsoft/PowerToys/pull/37654 from February was not enough or it has re-surfaced.

And in https://github.com/microsoft/WSL/issues/12759 it occured _without_ PowerToys installed.

**Comment by kabsolutely** [comment]
+1 without PowerToys installed.
