### ISSUE TITLE
"Cannot allocate Memory" Error Installing Xilinx PetaLinux Tools

### ISSUE THREAD

**Issue by svet-am** [Microsoft/WSL#1205]
- A brief description
  Cannot launch the installer for the Xilinx PetaLinux tools.
- Expected results
  Xilinx PetaLinux installer will run and install the PetaLinux tools
- Actual results (with terminal output if applicable)
  tony@DESKTOP-JBC25E7:~$ sudo /mnt/c/Users/Tony/Downloads/petalinux-v2016.2-final-installer.run
  sudo: unable to execute /mnt/c/Users/Tony/Downloads/petalinux-v2016.2-final-installer.run: Cannot allocate memory
- Your Windows build number
  Microsoft Windows [Version 10.0.14393]
- Steps / All commands required to reproduce the error from a brand new installation 
  Download the PetaLinux installer from Xilinx.com (http://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/embedded-design-tools/2016-2.html)

Attempt to run the installer as noted above
- Strace of the failing command
  tony@DESKTOP-JBC25E7:~$ sudo strace /mnt/c/Users/Tony/Downloads/petalinux-v2016.2-final-installer.run
  execve("/mnt/c/Users/Tony/Downloads/petalinux-v2016.2-final-installer.run", ["/mnt/c/Users/Tony/Downloads/peta"...], [/\* 14 vars */]) = -1 ENOMEM (Cannot allocate memory)
  write(2, "strace: exec: Cannot allocate me"..., 37strace: exec: Cannot allocate memory
  ) = 37
  exit_group(1)                           = ?
  +++ exited with 1 +++
- Required packages and commands to install
  Install the Ubuntu pre-requisite packages as described in Xilinx PetaLinux Reference Guide (https://www.xilinx.com/support/documentation/sw_manuals/xilinx2016_2/ug1144-petalinux-tools-reference-guide.pdf)

*Extra notes
This test machine is BIOS-based (Xeon X5690 on a SuperMicro X8DT3).  I have a Dell Latitude E6530 that is UEFI-based and all of these steps work perfectly on that machine.

I have tried increasing as well as decreasing the amount of virtual memory and it has had no effect.

**Comment by fpqc** [comment]
ENOMEM probably refers to something else failing, like a socket.  Weechat used to fail like this before datagram sockets were done.

**Comment by ghoff50** [comment]
I am having the same issue attempting the same installation.  I have upgraded to the Creators Update and have the latest supported version of Ubuntu, 16.04.2 LTS.  I got this error with 8 GB of memory in my PC and I have now upgraded to 16 GB and the same error occurs.

It appears that the problem occurs when the installer is being loaded into memory.  I performed a trace, shown below, and the error occurs during the execve call, the first kernel call that is issued.  Also listed below is a display of total and free memory, which should indicate that a large chunk of free memory, 13 GB, is available.  I tried creating a swap file.  I was successful setting up the file, registering it, but failed when I tried to enable it.  I thought that might help.


ghoff@Greg:/mnt/c/Temp$ strace -v ./petalinux-v2016.4-final-installer1.run
execve("./petalinux-v2016.4-final-installer1.run", ["./petalinux-v2016.4-final-instal"...], 
["SHELL=/bin/bash", "TERM=xterm-256color", "USER=ghoff", "NAME=Greg", "LS_COLORS=rs=0:di=01;34:ln=01;36"...,
 "HOSTTYPE=x86_64", "PATH=/usr/local/sbin:/usr/local/"..., "PWD=/mnt/c/Temp", "LANG=en_US.UTF-8", "SHLVL=1",
 "HOME=/home/ghoff", "LOGNAME=ghoff", "LESSOPEN=| /usr/bin/lesspipe %s", "LESSCLOSE=/usr/bin/lesspipe %s %"...,
 "_=/usr/bin/strace", "OLDPWD=/mnt/c"]) = -1 ENOMEM (Cannot allocate memory)
write(2, "strace: exec: Cannot allocate me"..., 37strace: exec: Cannot allocate memory
) = 37
exit_group(1)                           = ?
+++ exited with 1 +++

ghoff@Greg:/mnt/c/Temp$ free -m
              total        used        free      shared  buff/cache   available
Mem:          16299        2483       13584          17         230       13677
Swap:             0           0           0

I am willing to try any suggestions.  I realize the WSL is still in beta and that this might be a pretty strenuous test, but if the performance is OK, this would greatly simplify building Petalinux kernels.

Thanks in advance for any help!

**Comment by Blealtan** [comment]
Similar situation here. I'm installing Altera Quartus rather than Xilinx, and got the same error `ENOMEM`:

```
Blealtan@Blealtan-Desktop:/mnt/d/AOCL/AOCL-pro-17.1.0.240-linux$ ls -al ./components/QuartusProSetup-17.1.0.240-linux.run
-rwxrwxrwx 1 Blealtan Blealtan 6019021648 Oct 27 12:23 ./components/QuartusProSetup-17.1.0.240-linux.run
Blealtan@Blealtan-Desktop:/mnt/d/AOCL/AOCL-pro-17.1.0.240-linux$ strace ./components/QuartusProSetup-17.1.0.240-linux.run
execve("./components/QuartusProSetup-17.1.0.240-linux.run", ["./components/QuartusProSetup-17."...], [/* 16 vars */]) = -1 ENOMEM (Cannot allocate memory)
write(2, "strace: exec: Cannot allocate me"..., 37strace: exec: Cannot allocate memory
) = 37
exit_group(1)                           = ?
+++ exited with 1 +++
Blealtan@Blealtan-Desktop:/mnt/d/AOCL/AOCL-pro-17.1.0.240-linux$ ls -alh ./components/QuartusProSetup-17.1.0.240-linux.run
-rwxrwxrwx 1 Blealtan Blealtan 5.7G Oct 27 12:23 ./components/QuartusProSetup-17.1.0.240-linux.run
Blealtan@Blealtan-Desktop:/mnt/d/AOCL/AOCL-pro-17.1.0.240-linux$ free -m
              total        used        free      shared  buff/cache   available
Mem:          16335        3884       12220          17         230       12313
Swap:         59997           0       59997
```

As you may see I enabled a super-large swap even with sufficient physical memory configuration, but that doesn't help. May anyone have some idea?

**Comment by tara-raj** [comment]
We've fixed ENOMEM related issues recently. Please re-open this issue if you're still running into this.

**Comment by svet-am** [comment]
you say "recently."  Can you please be more precise about which release/version the ENOMEM issues were fixed in?

**Comment by benhillis** [comment]
@svet-am - I'd suggest trying out the most recently released version of Windows 10 (1803). I could try it locally but that download link is making me jump through more hoops than I'm comfortable with jumping through.

**Comment by Blealtan** [comment]
@tara-raj Still the same here.

```
blealtan@Blealtan-Desktop:/mnt/e/AOCL/AOCL-install$ strace ./components/QuartusProSetup-17.1.0.240-linux.run
execve("./components/QuartusProSetup-17.1.0.240-linux.run", ["./components/QuartusProSetup-17."...], [/* 18 vars */]) = -1 ENOMEM (Cannot allocate memory)
write(2, "strace: exec: Cannot allocate me"..., 37strace: exec: Cannot allocate memory
) = 37
exit_group(1)                           = ?
+++ exited with 1 +++
blealtan@Blealtan-Desktop:/mnt/e/AOCL/AOCL-install$ ls -alh ./components/QuartusProSetup-17.1.0.240-linux.run
-rwxrwxrwx 1 blealtan blealtan 5.7G Oct 27  2017 ./components/QuartusProSetup-17.1.0.240-linux.run
blealtan@Blealtan-Desktop:/mnt/e/AOCL/AOCL-install$ free -m
              total        used        free      shared  buff/cache   available
Mem:          16335        5878       10225          17         230       10319
Swap:         29638          40       29598
```

I‘m using Windows 10 build 17713.1000 (latest Insider Fast). Distribution of WSL is ubuntu from the Windows Store.

**Comment by svet-am** [comment]
for what it's worth, I've found that manually calling bash seems to work around this:

$ bash petalinux-v2016.2-final-installer.run
or
$ bash QuartusProSetup-17.1.0.240-linux.run

**Comment by therealkenc** [comment]
This one is suffering from lack of CLI repro steps (with the first step usually being `apt` or `wget` or `git clone`). Like @fpqc said [_in 2016_](https://github.com/Microsoft/WSL/issues/1205#issuecomment-253614656) the error observed could mean OOM or it could mean anything. The smart play here is to reboot a new issue.

**Comment by FredMurphy** [comment]
Adding bash did the trick! Thanks.
