### ISSUE TITLE
VmmemCmFirstBoot freezes Framework Laptop

### ISSUE THREAD

**Issue by Isotop7** [microsoft/WSL#12541]
### Windows Version

24H2 (26100.2894)

### WSL Version

2.3.26.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.167.4-1

### Distro Version

Debian Bookworm

### Repro Steps

- Upgrade to the latest Windows 11 release and wsl version
- Install any distro
- Reboot and login and wait for the deadlock

### Expected Behavior

After logging in, I would like to use Windows and also the WSL.

### Actual Behavior

After logging in, several VmMem processes are forked, which consume a high cpu load. The process VmmemCmFirstBoot ultimately freezes the PC. No mouse or keyboard input are possible and I have to force reboot the system by holding down the power key.

When disabling WSL or Virtualization settings in the BIOS, the system starts without any problems.

![Image](https://github.com/user-attachments/assets/b50e51e2-2731-431c-95c0-81bb1408296e)

### Diagnostic Logs

![Image](https://github.com/user-attachments/assets/ea1284c0-d27b-443e-aa08-44f66e86ecfa)

**Comment by Isotop7** [comment]
[WslLogs-2025-02-03_08-27-26.zip](https://github.com/user-attachments/files/18638703/WslLogs-2025-02-03_08-27-26.zip)

The script asked me to reproduce the issue, which I cannot do because I would have to enable WSL, which freezes my machine.

**Comment by Isotop7** [comment]
The bot is able to extract and parse zip files but not read my comment.

I‘m unable to reproduce the issue because I would need to enable VMX in EFI which would start the process VmmemCmFirstBoot after logging in. This freezes my machine INCLUDING the trace script. If you tell me how to disable that process I can generate a trace.

**Comment by Isotop7** [comment]
After switching to the prerelease, the problem is not occuring anymore (for now):

```
WSL-Version: 2.4.10.0
Kernelversion: 5.15.167.4-1
WSLg-Version: 1.0.65
MSRDC-Version: 1.2.5716
Direct3D-Version: 1.611.1-81528511
DXCore-Version: 10.0.26100.1-240331-1435.ge-release
Windows-Version: 10.0.26100.2894
```

**Comment by benhillis** [comment]
I'm not sure what vmmmemCmFirstBoot is, but it's unrelated to WSL. I would suggest filing an issue via Feedback Hub so this can get routed to the right team, feedback hub will also collect the relevant tracing information.

**Comment by Zoddo** [comment]
@gadcam do you happens to know if there has been any update to your report? When I try to open your link, it says that my account doesn't have access to these feedbacks.

**Comment by borque** [comment]
Any news on this? @gadcam ?
I run into the same problem on my Framework whenever I enable Windows Sandbox since the security update from frebruary.

**Comment by gadcam** [comment]
Hello @borque,
Microsoft people recently confirmed it is probably a `known issue` called an `integrated scheduler bug`.
So disabling `Windows Sandbox` should prevent the bug to happen.
This can be used temporarily as a workaround for people not using this feature.
I will keep you posted if there any news on this.

**Comment by kvega005** [comment]
@gadcam Is correct. This is an integrated scheduler bug that is affecting both Windows Sandbox and WSL. We are testing a fix internally. I will provide an update soon with the targeted date for shipping the fix.

**Comment by kuildor** [comment]
<img width="800" height="229" alt="Image" src="https://github.com/user-attachments/assets/17509ddc-7afb-4089-9a9c-cb7ae022f48d" />

Fixed in Insider Dev/Beta ring. Finally!

**Comment by tony-sol** [comment]
Just got recent windows updates - it' still freezes on thinkpad t14s with snapdragon x elite

UPD: kill vmmemCmFirstBoot immediately after startup, new updates came. How have 
```powershell
> Get-ComputerInfo -Property osVersion
10.0.26200

> wsl --version
WSL-Version: 2.6.1.0
Kernelversion: 6.6.87.2-1
WSLg-Version: 1.0.66
MSRDC-Version: 1.2.6353
Direct3D-Version: 1.611.1-81528511
DXCore-Version: 10.0.26100.1-240331-1435.ge-release
Windows-Version: 10.0.26100.6899
```

After rist reboot it became unresponsive again, but after a couple reboots - it works, for now

**Comment by simon-knuth** [comment]
Not seeing this anymore (26220.6780, Surface Laptop X Elite). The process still consumes a lot of resources after startup, but the system doesn't freeze and after a while it disappears.

**Comment by tempuserr** [comment]
After updating to 26100.6899 (24H2) not freezes caused by `VmmemCmFirstBoot` process anymore.

**Comment by char-46** [comment]
I'm using 26200.7309 (25H2), this problem come back.

**Comment by Trojaner** [comment]
<img width="1384" height="639" alt="Image" src="https://github.com/user-attachments/assets/3b94dc45-3889-440e-9092-99e00dfd6984" />

Can confirm its back on 26200.

**Comment by chocmake** [comment]
> Not seeing this anymore (26220.6780, Surface Laptop X Elite). The process still consumes a lot of resources after startup, but the system doesn't freeze and after a while it disappears.

On W11 Pro 24H2 26100.7462 I'm similarly not experiencing system freezes but am seeing 15-60% CPU usage from the VmmemCmFirstBoot process for up to 30 minutes after boot, on every boot, recently.

I don't have WSL installed but do have Sandbox installed, which seems to similarly be affected per the comments above about the integrated scheduler bug, though only infrequently use it (and during this month haven't been able to launch it anyway due to a [separate bug](https://github.com/microsoft/Windows-Sandbox/issues/101)).

---

Edit: in the last 2 days the issue hasn't occurred, when previously it was every boot. This coincides with when I installed an older Wacom driver. I don't see any Windows updates that occurred this past week besides an anti-virus definition update, however in the system restore list I did spot an auto snapshot that is named 'Windows Update' that is dated prior to that AV definition update and the night prior to when I installed the Wacom driver.

Edit 2: the issue returned today after boot.
