### ISSUE TITLE
Nuget fails to communicate network with NameResolutionFailure error

### ISSUE THREAD

**Issue by OlegZee** [Microsoft/WSL#1265]
- Brief description
  Popular package manager for .NET is not working in Bash.
- Expected results
  Nuget installs package requested. Or in the example below command lists available packages.
- Actual results (with terminal output if applicable)

> olegz@BIGT:~$ nuget list
> Unable to load the service index for source https://api.nuget.org/v3/index.json.
>   Error: NameResolutionFailure
- Your Windows build number
  
  > C:>ver
  > Microsoft Windows [Version 10.0.14393]
- Steps / All commands required to reproduce the error from a brand new installation 
  
  > wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  > mono nuget.exe list
- Required packages and commands to install
  
  > sudo apt-get install mono mono-complete mono-develop

**Comment by dmitriyse** [comment]
It's a Mono <--> WSL issue. I managed to get NuGet.exe work under mono 3.2.8 (shipped with ubuntu 14.04)

**Comment by OlegZee** [comment]
@dmitriyse I'm using the latest one

>  olegz@BIGT:~$ mono --version
>  Mono JIT compiler version 4.6.1 (Stable 4.6.1.5/ef43c15 Wed Oct 12 09:10:37 UTC 2016)
>  Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
>        TLS:           __thread
>        SIGSEGV:       altstack
>        Notifications: epoll
>        Architecture:  amd64
>        Disabled:      none
>        Misc:          softdebug
>        LLVM:          supported, not enabled.
>        GC:            sgen

**Comment by dmitriyse** [comment]
This problem probably solved in new WSL insider release. Root of the problem probably is IPv6 partial implementation in WSL. Internally nuget throws NameResolutionException that relates to mono (4.4.0x and grater) prefererence of IPv6 dns resolution firstly.

**Comment by denfromufa** [comment]
is there any temp fix for this? i'm on win10 build 15019, still not working.

**Comment by devlead** [comment]
Still an issue on 15058.

**Comment by denfromufa** [comment]
still issue on latest build:

![image](https://cloud.githubusercontent.com/assets/7870949/24088303/e26db18a-0cf6-11e7-9fa9-66c9059762c5.png)

I opened a nuget issue:

https://github.com/NuGet/Home/issues/4844

**Comment by Jerome2606** [comment]
What is the workaround ?

It is critical in my automatic build process.

**Comment by dmitriyse** [comment]
We needs IPv6 full implementation in WSL. Or some patch to DNS API in Mono.

**Comment by dmitriyse** [comment]
Mono should detects that IPv6 is not available and do not try to use it in DNS Api. 
Looks like MS will solving this problem yet another year.

**Comment by Jerome2606** [comment]
Ok this was working for me:

https://mackonsti.wordpress.com/2016/04/08/turn-off-ipv6-vpn-client-mac-10-10-newer/

thanks

**Comment by devlead** [comment]
Preferably I would personally see a fix or workaround in WSL as it works on native Linux and issue is with several versions of Mono. I don't rule out a fix in Mono too, but as an end user I would expect same behavior on WSL as on native Linux kernel.

**Comment by aseering** [comment]
@devlead -- if you try "ping6 ipv6.google.com" from your Linux machine, what do you get in response?  If you try the same from WSL, what do you get?

WSL deliberately differs from Linux in that it uses Windows's networking stack rather than starting its own.  This allows for useful things like having Windows and Linux applications share the same loopback interface, so you can run your webapp code in Linux on localhost and test it from a Windows browser.  Or you can securely run X11 applications over TCP, etc.

The downside is that Linux inherits Windows's IPv6-related (and other) defaults.  For example, whether IPv6 is enabled, whether Teredo is configured, etc.  All of these are things you could do on Linux; it's just a question of defaults.

So -- is this problem just due to a config difference?  Or is it a real incompatibility?

**Comment by dend** [comment]
Running into the exactly same problem with `mono 4.6.2`

**Comment by devlead** [comment]
@aseering  both WSL & standard linux gives `unknown host`, Win32 ping gives `could not find host ipv6.google.com`, which isn't surprising as I don't have any ipv6 network yet.

Diasabling IPv6 doesn't help, the local ipv6 addresses disappears from ifconfig, but nuget still fails.

**Comment by aseering** [comment]
Hm...  In that case, I'm not sure what the issue is.

Hopefully the NuGet folks will talk with the WSL folks and get this sorted out one way or another.  In the meantime, the typical way to find a smoking gun pointing at WSL misbehavior (and probably the only way for one of us end-users to assist in getting this fixed?) is to grab an `strace` of the application working successfully under Ubuntu, and an equivalent `strace` of the application failing under WSL.  The strace enumerates every system call that the application makes, and every response that Linux (or WSL) provides.  So, at some point in the trace, WSL will start providing different responses than Linux.  For example, some syscall getting information about a socket might fail under WSL rather than returning a valid response.  Once you get things down to the syscall level, that maps very clearly to WSL's implementation, so it's easy for their devs to figure out what in WSL needs to be fixed.

**Comment by denfromufa** [comment]
@aseering nuget issue got a label of "ClosedAs:External", so only WSL or Mono folks can fix this.

**Comment by jnm2** [comment]
Is this the correct issue to be following? I'm having this issue with Mono 4.8.1, Windows 10.0.15063.

**Comment by dmitriyse** [comment]
I am happy to provide some workaround.
1) Run fiddler
2) tune "allow remote computers to connect"
![image](https://cloud.githubusercontent.com/assets/10322215/25252680/109a1a48-262f-11e7-9982-361da0fe773f.png)

3) Restart fiddler
---
On WSL:
```bash
mono nuget.exe config -set http_proxy=http://[::1]:8888
```
After that you can use nuget.exe and xbuild that uses nuget.

**Comment by denfromufa** [comment]
@dmitriyse I can confirm that this is working, although I executed without mono:

```
sudo nuget config -set http_proxy=http://[::1]:8888
sudo nuget update -self
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 2.12.0.
Updating NuGet.exe to 3.5.0.
Update successful.
```

Now I can use pythonnet running with mono and cpython in WSL :)

```
python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
>>> import System
>>>
```

**Comment by alancnet** [comment]
I ran into this problem running `nuget restore` during a docker build. My solution was to change the line to `nuget restore || nuget restore || nuget restore || nuget restore || nuget restore` as multiple retries eventually installs everything.

**Comment by tara-raj** [comment]
Closing as this issue has been fixed with Mono <-> WSL. NuGet is also working on current builds. Please re-open if you hit this issue again.
