### ISSUE TITLE
After connecting to IDEA Remote Development, it crashes.

### ISSUE THREAD

**Issue by fzh075** [microsoft/WSL#12733]
### Windows Version

Microsoft Windows [版本 10.0.26100.3194]

### WSL Version

2.3.26.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Repro Steps

connect to IDEA Remote Development.

### Expected Behavior

normal operation.

### Actual Behavior

It crashes after a period of time, and operations (including wsl --shutdown) become unresponsive.

### Diagnostic Logs

[WslLogs-2025-03-24_01-52-41.zip](https://github.com/user-attachments/files/19411041/WslLogs-2025-03-24_01-52-41.zip)

**Comment by fzh075** [comment]
I think I already uploaded it?

**Comment by fzh075** [comment]
[WslLogs-2025-03-24_01-52-41.zip](https://github.com/user-attachments/files/19459156/WslLogs-2025-03-24_01-52-41.zip)

**Comment by OneBlue** [comment]
Thank you @fzh075. Unfortunately that file doesn't contain any dumps. Can you make so you run the script with "-Dump"

/dump

**Comment by fzh075** [comment]
Hi @OneBlue, thank you for your response.

**Comment by OneBlue** [comment]
Thank you @fzh075. From the dump I can see that `wslservice.exe` is stuck, apparently waiting for the VM to reply, so let's see what happening inside the VM.

Could you please:

- Reproduce the issue where WSL is stuck
- Open a debug shell via `wsl --debug-shell`
- Inside that shell, paste the content of https://github.com/microsoft/WSL/blob/master/diagnostics/dump-init-stacks.sh
- Share the output on this issue
- Also share the output of `dmesg`


So this should tell us why the vm is stuck

**Comment by fzh075** [comment]
Thank you @OneBlue .
https://drive.google.com/file/d/1QEEslTzFNi5Znww7Ri65_OgQkakrWc24/view?usp=drive_link
https://drive.google.com/file/d/1BEUu5Sc1LrwW8M_s4pTz8rCTNvl7TKKu/view?usp=drive_link

**Comment by OneBlue** [comment]
Thank you @fzh075. Looking through the linux state, nothing obvious jumps out. Let's try one more thing and if that doesn't work I'll create a script to dump the linux processes that we need.

Can you try to update to the latest version (we fixed many bugs since 2.3) via: wsl --update --pre-release, and if things get stuck again, capture another dump of wslservice.exe, along with the output of dump-init-stacks.sh ?

**Comment by fzh075** [comment]
Thank you @OneBlue .
https://drive.google.com/file/d/1yvLrFseHADI-fu6DWF1q1d_oUIxtSvIp/view?usp=drive_link
The output is not fully displayed, and some parts are truncated: https://drive.google.com/file/d/1nAyUPEGjyJesDTSVJc1gcuyHW8oYdaC2/view?usp=drive_link
https://drive.google.com/file/d/13LLGJlQNlUBhgyjzQoMyOvvcCc7-foZq/view?usp=drive_link

**Comment by fzh075** [comment]
I re-enabled the VMware Network Adapter, but it didn't solve the problem.

**Comment by fzh075** [comment]
Hello @OneBlue
