### ISSUE TITLE
CIFS version 1.0 no longer mountable

### ISSUE THREAD

**Issue by alkanen** [microsoft/WSL#13174]
### Windows Version

Microsoft Windows [Version 10.0.19045.5854]

### WSL Version

 2.5.9.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

6.6.87.2-1

### Distro Version

Ubuntu 22.04.4 LTS

### Other Software

cifs-utils 2:6.14-1ubuntu0.3 amd64

### Repro Steps

Trying to mount an old NAS with CIFS/SMB version 1.0 that worked perfectly up until a few days to a couple of weeks ago. The NAS is still mountable on my other Linux devices as well as in Windows as a network drive in the file explorer.

fstab entry:
`//<nas IP>/media     /mnt/nas   cifs  credentials=/home/<username>/.smbcredentials,iocharset=utf8,noauto,user,vers=1.0,forcegid,forceuid  0  0`

Command to run:
`mount /mnt/nas/`

### Expected Behavior

The NAS should be mounted and accessible at `/mnt/nas` as it has always been before

### Actual Behavior

Mount command output:

```
mount error(22): Invalid argument
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
```

Relevant dmesg output:

```
[168302.564357] vers=1.0 (cifs) mount not permitted when legacy dialects disabled

[168302.564798] CIFS: VFS: vers=1.0 (cifs) mount not permitted when legacy dialects disabled
```

### Diagnostic Logs

I can mount the Windows Network drive by running `sudo mount -t drvfs Z: /mnt/nas`. I can't run `ls` though because it gives the error "ls: reading directory 'nas': Invalid argument" but I *can* run `cat` on files that I know exist on the NAS if I mount it like this and I can navigate through sub directories as long as I know their names.

**Comment by 0xbadfca11** [comment]
Same as #13031, #12987 and #12983.
https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-6.1.y/arch/x86/configs/config-wsl#L3534
https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-6.6.y/arch/x86/configs/config-wsl#L7173

**Comment by alkanen** [comment]
> Same as [#13031](https://github.com/microsoft/WSL/issues/13031), [#12987](https://github.com/microsoft/WSL/issues/12987) and [#12983](https://github.com/microsoft/WSL/issues/12983). https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-6.1.y/arch/x86/configs/config-wsl#L3534 https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-6.6.y/arch/x86/configs/config-wsl#L7173

Ah, I would have never guessed they were related.

Does that mean I don't have to collect the WSL logs when I get back home, because the issue is already known?

**Comment by OneBlue** [comment]
@alkanen: This should be fixed in 2.6.0. Can you run: `wsl --update --pre-release` and see if that solves the issue ?

**Comment by alkanen** [comment]
> [@alkanen](https://github.com/alkanen): This should be fixed in 2.6.0. Can you run: `wsl --update --pre-release` and see if that solves the issue ?

I will try to remember doing it when I get back from work tonight. Thanks for the suggestion!

**Comment by alkanen** [comment]
> [@alkanen](https://github.com/alkanen): This should be fixed in 2.6.0. Can you run: `wsl --update --pre-release` and see if that solves the issue ?

I have tested now and the same issue remains with identical error messages. I have also rebooted my computer to make sure nothing old remained loaded.

I've also tried mounting with `sudo mount -t drvfs Z: /mnt/z` (where Z: is my network mount, of course) and while the mount goes through I can't list the folder contents.  I *can* access file contents on the mounted device, but only if I know the exact path to the file in question since there's no way to use `ls` to navigate. Interestingly, I *can* do e.g. `ls -l <filename>` and get the file info, it's just listing directory contents that fails.

Since the update, `wsl.exe --version` returns:

```
WSL version: 2.6.0.0
Kernel version: 6.6.87.2-1
WSLg version: 1.0.66
MSRDC version: 1.2.6228
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.19045.5965
```

**Comment by alkanen** [comment]
These logs are created after the upgrade:

[WslLogs-2025-06-24_18-26-35.zip](https://github.com/user-attachments/files/20887533/WslLogs-2025-06-24_18-26-35.zip)

**Comment by OneBlue** [comment]
Thank you @alkanen. Is there a specific reason why you need to use SMB V1, which is quote old,  here ? Does the mount succeed with ` vers=2.1` for instance ?

**Comment by alkanen** [comment]
> Thank you [@alkanen](https://github.com/alkanen). Is there a specific reason why you need to use SMB V1, which is quote old, here ? Does the mount succeed with ` vers=2.1` for instance ?

Yes, it's an old NetGear ReadyNAS Ultra that doesn't support newer than 1.0 or I would have happily used something more recent. 

Trying to mount with vers=2.1 gives this error:

```
mount error: Server abruptly closed the connection.
This can happen if the server does not support the SMB version you are trying to use.
The default SMB version recently changed from SMB1 to SMB2.1 and above. Try mounting with vers=1.0.
mount error(112): Host is down
```

I should buy something newer, but until then I'd still like to be able to access my files :)

**Comment by OneBlue** [comment]
OK thank you for the context. 

@chessturo: This seems to be caused by a kernel config change. 

In WSL 2.4.13: 

```
zcat /proc/config.gz  | grep -iF CIFS_ALLOW_INSECURE_LEGACY
CONFIG_CIFS_ALLOW_INSECURE_LEGACY=y
```

While this is unset the latest kernel:

```
zcat /proc/config.gz  | grep -iF CIFS_ALLOW_INSECURE_LEGACY
# CONFIG_CIFS_ALLOW_INSECURE_LEGACY is not set
```

**Comment by alkanen** [comment]
Yup, that looks like a likely candidate.

Is there any way for me to change the config and rebuild the kernel?  I haven't built Linux kernels since the late 1990s, and definitly not for Windows, so I have no idea how it works

**Comment by chessturo** [comment]
@alkanen it should be pretty easy if you have a working WSL instance at the moment. Just clone [the kernel repo](https://github.com/microsoft/WSL2-Linux-Kernel), make the change in `Microsoft/config-wsl` (or Microsoft/config-wsl-arm64` if you're on ARM64) and then follow the instructions to build and install the kernel. If you have problems, please feel free to ping me on this issue

**Comment by alkanen** [comment]
> [@alkanen](https://github.com/alkanen) it should be pretty easy if you have a working WSL instance at the moment. Just clone [the kernel repo](https://github.com/microsoft/WSL2-Linux-Kernel), make the change in `Microsoft/config-wsl` (or Microsoft/config-wsl-arm64` if you're on ARM64) and then follow the instructions to build and install the kernel. If you have problems, please feel free to ping me on this issue

Thanks! I really appreciate it.  Will take a stab after work tomorrow and see how it goes :)

**Comment by mfauvell** [comment]
Hi,

I can confirm the issue and the solution from @chessturo 

I have recompiled the kernel, created modules.vhdx and changed in .wsl-config the related options and it works like a charm.

Thanks.

**Comment by alkanen** [comment]
Just commenting to report that I've built the kernel now but don't have any more time to day to figure out how to actually use it. I have the instructions open, but I have spent too much time trying and failing to build the kernel before discovering that it doesn't work if you check the repo out in a directory under /mnt so I had to check it out again in my home folder and rebuild.

Will try to continue tomorrow.

**Comment by alkanen** [comment]
Okay, here we go.  @chessturo I think I have to take you up on that kind offer to assist with the installation.

I've built the kernel and modules(?) using the instructions linked.  I have a `modules.vhdx` file and a `bzImage` file for my architecture, but now I'm not sure what to do with them.  The instructions I find online seem to be outdated or in other ways not relevant for my build, because the files it says I should copy don't exist and similar problems.

I believe I'm supposed to create a `.wslconfig` file in my User directory, and add something like

```
[wsl2]
kernel=C:\\Users\\<my user>\\.wsl-kernels\\bzImage
```

to it. Is that correct?  Do I need to do something with the modules file? One set of instructions suggested mounting it and copying module files from it, but the path given didn't exist (as mentioned above), so that doesn't seem like the right thing.

If the config above is correct, I guess I should just have to do close all my open shells, run `wsl.exe --shutdown`, wait long enough for the subsystem to shut down properly and then launch again, finally confirming with `uname -r` or something that the kernel version has changed from "6.6.87.2-microsoft-standard-WSL2" that is now?

Thank you in advance

**Comment by mfauvell** [comment]
@alkanen 

You should do the same with modules.vhdx. The .wslconfig should look like this:

```
[wsl2]
kernel=C:\\Users\\{user}\\.wsl-kernels\\bzImage
kernelModules=C:\\Users\\{user}\\.wsl-kernels\\modules.vhdx
```

**Comment by alkanen** [comment]
> [@alkanen](https://github.com/alkanen)
> 
> You should do the same with modules.vhdx. The .wslconfig should look like this:
> 
> ```
> [wsl2]
> kernel=C:\\Users\\{user}\\.wsl-kernels\\bzImage
> kernelModules=C:\\Users\\{user}\\.wsl-kernels\\modules.vhdx
> ```

Thank you kindly!

**Comment by alkanen** [comment]
It worked and now I can mount my NAS again.

Thank you so much everybody!

**Comment by OneBlue** [comment]
Closing since the issue is resolved.
