### ISSUE TITLE
NixOS: wsl: Failed to start the systemd user session for 'nixos': "/usr/bin/systemctl: No such file or directory"

### ISSUE THREAD

**Issue by CSharperMantle** [microsoft/WSL#13236]
### Windows Version

Microsoft Windows [Version 10.0.26120.4520]

### WSL Version

2.6.0.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

6.6.87.2-1

### Distro Version

NixOS 25.11pre826054.1fd8bada0b61

### Other Software

N/A.

### Repro Steps

1. Install NixOS on WSL 2.6.0.0.
2. Boot the distro.

### Expected Behavior

The distro boots without error messages.

### Actual Behavior

On launching the distro, error `wsl: Failed to start the systemd user session for 'nixos'. See journalctl for more details.` occurs. The distro seems to work normally afterwards.

Currently, `init` tries to run `systemctl` to check for OS running state:

https://github.com/microsoft/WSL/blob/5f34d179550aa656155531f2b8cb6ac37f7f6f9a/src/linux/init/init.cpp#L3371-L3372

But on NixOS, there's no `/usr/bin/systemctl`. It resides in a contained directory:

```sh
$ which systemctl
/run/current-system/sw/bin/systemctl
$ ls -la /usr/bin/
total 12
drwxr-xr-x 2 root root 4096 Jul  8 08:25 .
drwxr-xr-x 4 root root 4096 Feb 24 04:56 ..
lrwxrwxrwx 1 root root   65 Jul  8 08:25 env -> /nix/store/psy9v2asypgl9ylg8cnzkixc7fv0snj0-coreutils-9.7/bin/env
$
```

### Diagnostic Logs

```log
Jul 08 08:19:43 nixos systemd[328]: Startup finished in 183ms.
Jul 08 08:19:43 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:43 nixos sudo[428]:    nixos : TTY=pts/1 ; PWD=/home/nixos ; USER=root ; COMMAND=/run/current-system/sw/bin/id -u
Jul 08 08:19:43 nixos sudo[428]: pam_unix(sudo:session): session opened for user root(uid=0) by nixos(uid=1000)
Jul 08 08:19:43 nixos sudo[428]: pam_unix(sudo:session): session closed for user root
Jul 08 08:19:44 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:44 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:44 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:44 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:45 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:45 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:45 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:45 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:46 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:46 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:46 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:46 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:47 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:47 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:47 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:47 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:48 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:48 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:48 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:49 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:49 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:49 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:49 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:50 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:50 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:50 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:50 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:51 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:51 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:51 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:51 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:52 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:52 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:52 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:53 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:53 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:53 nixos /nix/store/94lg0shvsfc845zy8gnflvpqxxiyijbz-bash-interactive-5.2p37/bin/sh: line 1: /usr/bin/systemctl: No such file or directory
Jul 08 08:19:53 nixos unknown: WSL (2 - Interop) ERROR: CreateLoginSession:2731: Timed out waiting for user session for uid=1000
```

**Full log:** [out.log](https://github.com/user-attachments/files/21117823/out.log)

[WslLogs-2025-07-08_16-32-32.zip](https://github.com/user-attachments/files/21117981/WslLogs-2025-07-08_16-32-32.zip)

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/pull/13157

**Comment by CSharperMantle** [comment]
@benhillis, would you point me to the version in which this is fixed? Is manual recompilation of `/init` needed if I wish to apply this patch?

**Comment by BrianG61UK** [comment]
Why was this closed? Problem is still present in WSL2 with Ubuntu-22.04

[WSL2.journalctl.txt](https://github.com/user-attachments/files/22442380/WSL2.journalctl.txt)
