### ISSUE TITLE
WSL pins opened directories

### ISSUE THREAD

**Issue by therealkenc** [microsoft/WSL#1529]
Pulling this out of #1492. It is possibly a dup of #1420; but I'm thinking maybe not because that issue has no lingering fds. This hits in spades with [nfs-ganesha](https://github.com/nfs-ganesha/nfs-ganesha), because the protocol is stateless and file descriptors are cached for a while before being released. Windows Explorer traipses all over thousands of files, causing lots of directory fds to remain open. This in turn causes unexpected `mv` and `rm` operations on seemingly random directories on the WSL side to fail.

This will probably also show itself when people start doing web development scenarios, because http servers have a tendency to do the same sort of fd caching.

```
// silly-rename.c
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>

int main(int argc, const char* argv[]) {
  const char msg[] = "amy's parent morton renamed to maura\n";
  int fd, ret;

  mkdir("/tmp/morton", 0777);
  fd = open("/tmp/morton/amy", O_CREAT|O_RDWR, 0666);
  ret = rename("/tmp/morton/", "/tmp/maura/");
  if (ret < 0) {
    perror("rename failed: ");
  } else {
    write(fd, msg, sizeof(msg) - 1);
  }
  close(fd);
}
```
strace on WSL:
```
mkdir("/tmp/morton", 0777)              = 0
open("/tmp/morton/amy", O_RDWR|O_CREAT, 0666) = 3
rename("/tmp/morton/", "/tmp/maura/")   = -1 EACCES (Permission denied)
```
strace on Ubuntu:
```
mkdir("/tmp/morton", 0777)              = 0
open("/tmp/morton/amy", O_RDWR|O_CREAT, 0666) = 3
rename("/tmp/morton/", "/tmp/maura/")   = 0
```

**Comment by sunilmut** [comment]
@therealkenc - Apologize for the delay here. I am sure there are other neglected issues, and I personally would like to get through them too.

Anyways, I think this stems from the NTFS limitation that prevents renaming directories which have a handle open to anything below. @SvenGroot to confirm.

**Comment by seffyroff** [comment]
Other than 'try to not open lots of files' is there any advice on avoiding this issue, given that a fix seems to be escaping us?  Is there a way to monitor and close file handles?  Is there a more suitable filesystem for hosting WSL filesystems that would avoid hitting this?  Is there a node setting we can flag to ignore these errors, given that they're apparently false positives?

**Comment by bitcrazed** [comment]
Assigned to @SvenGroot and @tara-raj to take a look, though with Xmas fast approaching, may be a couple of weeks until this gets looked into.

**Comment by therealkenc** [comment]
Tell you what you _can_ do, if you are looking for something constructive. Right now it is impossible to differentiate between `EACCES` caused by WSL failing to respect Unix filesystem semantics, versus folks who simply have their permissions wrong (`EUSERCONFUSED`). You know up in that `rename(2)` the difference, because you know whether the mode bits (what we tend to call metadata) are okay or not. In the case you can't rename because NTFS won't play ball, return a nonstandard `EBUSY` instead of `EACCES`, which will at least stick out like a sore thumb. That way reported issues triggering the known problem can be summarily duped here instead of guessing. This was asked for about a [year ago](https://github.com/Microsoft/WSL/issues/2665#issuecomment-347344501) but could have been easily buried versus rejected. Just a thought.

**Comment by eriksneff** [comment]
@seffyroff I have a recommendation. In my case, what I was trying to do was `npm install chalk` and other packages, and it was failing with the EACCES error. I was running that command from within a folder inside my WSL ubuntu 18 install's home dir. 

I realized that when I closed all programs that were looking at that folder, the error went away. I then realized that while the windows application MobaXterm was running, that error would happen. When I closed MobaXterm, the errors all stopped. HTH

**Comment by DemiMarie** [comment]
This is another motivating reason for WSL to ditch NTFS and the NT filesystem APIs, in favor of Unix-native approaches.  Probably ext4, since it has FreeBSD drivers.

**Comment by therealkenc** [comment]
With ref to #14 ([message](https://github.com/Microsoft/WSL/issues/14#issuecomment-481028594)) 

Interesting [approach](https://github.com/fuzzyTew/nodejswslfix/blob/master/interceptrename.c). This approach will work around some `EACESS` errors folks are experiencing, specifically where the open handle triggering #1529 is transient and goes away in one second or less. For other scenarios it won't work, like an editor holding a handle open, or handles being held in some cache or another for more than one second or indefinitely. Like the effort though. Working around some scenarios (especially your own) is better than it not working at all.

[Hotpatching](https://github.com/pmem/syscall_intercept) [g]libc to intercept all syscalls is a pretty big hammer though, and might seem a little excessive to some. [Not me, mind. Anything worth doing is worth overdoing.]

Another approach would be to hook higher in the food chain. Perhaps in [`libuv`](https://github.com/libuv/libuv) [here](https://github.com/libuv/libuv/blob/99440bb6734bc7edfea108f6eb6914982e9f8cf7/src/unix/fs.c#L1678).
```
$  objdump -T /usr/lib/x86_64-linux-gnu/libuv.so.1 | grep uv_fs_rename
```

Anyway, nice to see people seeking plausible mitigations.

**Comment by fuzzyTew** [comment]
In response to therealkenc's comments, I spent some time expanding on this hotpatch, now at https://github.com/fuzzyTew/wslunpindir .  When the error happens, it enumerates open filehandles from /proc, spits [some messaging](https://github.com/fuzzyTew/wslunpindir/blob/master/interceptrename.c#L94) out on /dev/tty, and waits until they are closed.  This does not find open files from Windows, only from within Linux.  Assumes the app is being run interactively.

I considered switching the hook to libuv to make things faster and lightweight, but figured time was better spent making it work in more scenarios rather than fewer.

**Comment by therealkenc** [comment]
> I spent some time expanding on this hotpatch

Noice 💯. If nothing else, it serves as a very useful [troubleshooting](https://github.com/Microsoft/WSL/issues/2665#issuecomment-481076572) tool.

> figured time was better spent making it work in more scenarios rather than fewer.

Expand your intercept-all-the-things approach [enough](https://github.com/Microsoft/WSL/issues/17#issuecomment-454376266) and you can fix the problem even for the case where the handle remains open 😉.

**Comment by Coder-256** [comment]
Is the WSL team planning to fix this? I ran into this bug today simply trying to build a `npm` project. [wslunpindir](https://github.com/fuzzyTew/wslunpindir) worked like a charm (now I use `alias npm='LD_PRELOAD=~/git/wslunpindir/interceptrename.so npm'`) but this is clearly only a workaround and does not solve the problem for all situations.

**Comment by onomatopellan** [comment]
@Coder-256 it's fixed in WSL2.

**Comment by therealkenc** [comment]
> @Coder-256 it's fixed in WSL2.

For a good swath of folk's major pain points, yes. The _underlying_ issue remains however. With minor string edits to OP:
```
// silly-rename.c
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>

int main(int argc, const char* argv[]) {
  const char msg[] = "amy's parent morton renamed to maura\n";
  int fd, ret;

  mkdir("/mnt/c/Users/there/morton", 0777);
  fd = open("/mnt/c/Users/there/morton/amy", O_CREAT|O_RDWR, 0666);
  ret = rename("/mnt/c/Users/there/morton/", "/mnt/c/Users/there/maura/");
  if (ret < 0) {
    perror("rename failed: ");
  } else {
    write(fd, msg, sizeof(msg) - 1);
  }
  close(fd);
}
```
and the strace for pedantry:
```
mkdir("/mnt/c/Users/there/morton", 0777) = -1 EEXIST (File exists)
openat(AT_FDCWD, "/mnt/c/Users/there/morton/amy", O_RDWR|O_CREAT, 0666) = 3
rename("/mnt/c/Users/there/morton/", "/mnt/c/Users/there/maura/") = -1 EACCES (Permission denied)
[...]
write(4, "rename failed: : Permission deni"..., 35) = 35
```

Which would seem academic, except that it affects everyone using WSL for WSL's raison d'être, which is interop with Windows.

**Comment by snevs** [comment]
why is `[Install Remote WSL fail with mv - permission denied #109](https://github.com/microsoft/vscode-remote-release/issues/109)` even closed? I have the same issue with mv

**Comment by HosseinAlipour** [comment]
I have the same annoying issue, is this fixed in a new version of windows?
windows version 1903 build 18362.418

**Comment by slikts** [comment]
> The problem is caused by underlying limitations in NTFS and the NT APIs you have to work with.

So it's an another facet of the same root problem as #873 and why WSL2 is being added.

> … it's fixed in WSL2.

It's not as much fixed in WSL2 as WSL2 is a fundamentally different tool with its own set of significant limitations (deriving from virtualization). Specifically, Hyper-V is not compatible with at least a couple of tools I use, and it also adds significant overhead by running Windows as a guest.

**Comment by DemiMarie** [comment]
A correct fix for WSL1 would require massive changes in the NT kernel to
accommodate WSL2.  Fixing performance as well would essentially require
reimplementing much of the Linux I/O stack.  The BSDs have code that could
be used, but it would still be a huge task.

**Comment by amanhigh** [comment]
Facing Similar Issue

```
go get -u github.com/PuerkitoBio/goquery
go: extracting github.com/PuerkitoBio/goquery v1.5.1
go get: rename /home/aman/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.5.1.tmp-274661216 /home/aman/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.5.1: permission denied
```

Permissions

```
~/go:  ls
total 0
drwxr-xr-x 1 aman aman 512 Mar 15 02:43 ..
drwxrwxrwx 1 aman aman 512 Mar 15 02:46 .
drwxrwxrwx 1 aman aman 512 Mar 15 02:46 src
drwxrwxrwx 1 aman aman 512 Mar 15 09:53 pkg
```

**Comment by clshortfuse** [comment]
I have a hypothesis that may or may not help illuminate the issue.

I have a machine that uses WSL v1 (no issues on v2). I can replicate EACCES pretty easily by trying to install a package with VSCode. I believe there's some sort of access limit or open handles.

Basically, I know VSCode is monitoring the folder I'm working in. If I install a package with VSCode is open, I'll get EACCES errors. If I close VSCode and install the packages over the Ubuntu bash, no errors. 

So, to create this issue, I believe you just have to:

* Initiate some sort of file system watcher on a folder (VSCode)
* Create and delete files within the same folder very quickly (`npm install`)

I think what's causing the EACCES issue is that VSCode isn't handling the file system changes faster than `npm` can create or delete them. That's why this only happens *sometimes* and on *some* machines. The machine I'm working on currently is REALLY slow in general and I get this errors consistently if I try it installing a package with VSCode open. WSLv2 may have fixed this issue, or it's just so much faster than WSLv1 that the it's rare for the collision to occur. The fact that the issue goes away when I close VSCode means that the handle is being kept open by the file system watcher.

I'm sure somebody smarter than I can create some sort of test script that creates and deletes a bunch of files with a watcher in the background watcher. You might find the collision. I just don't know where in WSL this issue might occur. Perhaps `inotifiy` is bugged somewhere?
