### ISSUE TITLE
set -m in SH Script fails - Cannot set tty process group (Operation not permitted)

### ISSUE THREAD

**Issue by kierangrant** [Microsoft/WSL#2051]
Build: 15063.250
**Steps:**
cat >> set-m.sh << EOF
#!/bin/sh
set -m
echo "Test" | cat
EOF
sh ./set-m.sh
**Output**
./set-m.sh: 2: ./set-m.sh: Cannot set tty process group (Operation not permitted)

Brief strace logs
from strace.txt.104:
...
setpgid(106, 105)                       = -1 EPERM (Operation not permitted)
...
from strace.txt.106:
...
setpgid(0, 105)                         = -1 EPERM (Operation not permitted)
ioctl(11, TIOCSPGRP, [105])             = -1 EPERM (Operation not permitted)
...

[**Full strace**](https://gist.github.com/kierangrant/290b4371b89bbdaa2358c81b91951fa2)

**Comment by therealkenc** [comment]
Probably related to #1210 #1653 (at least tangentially), which are both still open.

**Comment by kierangrant** [comment]
I hear that there may be a race condition in WSL that gets hit more often
now that WSL is more efficient in CU.

Interestingly, I never hit this bug before CU in this script.
But it probably is related.

On 4 May 2017 03:21, "therealkenc" <notifications@github.com> wrote:

Probably related to #1210
<https://github.com/Microsoft/BashOnWindows/issues/1210> #1653
<https://github.com/Microsoft/BashOnWindows/issues/1653> (at least
tangentially), which are both still open.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/BashOnWindows/issues/2051#issuecomment-298977642>,
or mute the thread

**Comment by ryanerwin** [comment]
I'm getting this same `"Cannot set tty process group (Operation not permitted)"`

When I run:

`echo A | hexdump -C`

Yet when I run `dash -c "echo A|hexdump -C"` it works, so I can't get an strace of it failing (in this case the error is generated in the shell before the subprocess is launched).

**Comment by Brian-Perkins** [comment]
This is related to #1063 and should be fixed in the Fall Creators Update.

**Comment by ryanerwin** [comment]
@Brian-Perkins 
I was already running the fall creators update when posting this.
At least in some circumstances, the issue is still present post creators update:

```
C:\>ver

Microsoft Windows [Version 10.0.16299.64]
```

I've been trying to replicate the error on a VM of a clean install but still haven't got a clean test case...

**Comment by BrianKrohn** [comment]
I am also seeing that this is still failing in the fall creators update.  Any command piped to awk or sed, for example, fails with "Cannot set tty process group (Operation not permitted)"

**Comment by Brian-Perkins** [comment]
There are some zombie process differences in WSL currently, where a process that has exited cannot be used as the foreground process group immediately (as opposed to Linux where it can be while it is in the zombie state). So it may be that you are running into #2786.

**Comment by therealkenc** [comment]
Since #1210 #1653 and #2786 / #3129 are all addressed, and the OP repro now works correctly with `/bin/dash` on 18291. Calling this a dupe of one of the aforementioned (pick any).
