### ISSUE TITLE
Error: 0x800703fa - Press any key to continue

### ISSUE THREAD

**Issue by tuannguyenthe** [Microsoft/WSL#2576]
When I start Bash on Ubuntu, the Bash terminal displayed:
Error: 0x800703fa
Press any key to continue...

My windows build:
Microsoft Windows [Version 10.0.17017.1000]
![image](https://user-images.githubusercontent.com/4831320/31749709-e1fcc3ec-b4a5-11e7-95b9-19a5cedcc673.png)

The only thing i did before the error was running 'jupyter notebook' and playing around with zipline. I did not update conda or apt.

**Comment by tuannguyenthe** [comment]
I restarted Windows and the problem went away. I have bash prompt now.

Can you still investigate the issue even though it went away?

**Comment by tychen5** [comment]
With the exactly the same problem on my notebook.
17025.1000

**Comment by MrSimsek** [comment]
![image](https://user-images.githubusercontent.com/10881712/34647833-fe929990-f39e-11e7-817f-391338f8aca4.png)

I am also having the exact problem.

**Comment by YihaoPeng** [comment]
I have the same issue on my notebook. I `shutdown` my Windows and power it again, and WSL displayed these error messages:
```
Installing, this may take a few minutes...
Installation Failed!
Error: 0x800703fa
Press any key to continue...
```
I have to `reboot` to let it running as normal.

**Comment by jesperll** [comment]
Just had this after updating to 1803 build 17120.1 as well. An extra reboot fixed it

**Comment by friedwm** [comment]
I have the same issue on 17133.1. Ubuntu installed in Microsoft Store. A reboot does clear the error, but everytime I open a wsl, I need a reboot again. Please fix this issue ASAP !!!
-------------- wsl says:
Installing, this may take a few minutes...
Installation Failed!
Error: 0x800703fa
Press any key to continue...

**Comment by BtheDestroyer** [comment]
Same thing as @friedwm. Happened after signing out when a program wouldn't close.

**Comment by quic0** [comment]
@friedwm's solution resolved the problem for me on build 17133.

**Comment by quic0** [comment]
@bharadwajpro Same error when running `services.msc` as Administrator.

**Comment by bharadwajpro** [comment]
@quic0 Instead of setting it to `automatic`. Just restart the service as `Administrator`.

**Comment by Rockstar04** [comment]
I'm running into the same issue. If I wait several minutes after my system boots, ubuntu starts fine.

**Comment by ngetchell** [comment]
Running as admin gets past this problem.

**Comment by jm33-m0** [comment]
after version 1803 update, wsl starts throwing `0x800703fa` error, rebooting solves the problem, but the error will still pop up on next boot

**Comment by PetterS** [comment]
Just got this after rebooting. 

	Installing, this may take a few minutes...
	Installation Failed!
	Error: 0x800703fa
	Press any key to continue...

(I have the April update)

**Comment by DarthSpock** [comment]
So I had the same issue again and restarting the LXSS service did resolve the issue.

**Comment by benhillis** [comment]
Could somebody experiencing this issue please collect and share logs so I can see what's going on?
https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by diablodale** [comment]
@benhillis attached are the detailed log files you requested.
[0x800703fa_error.zip](https://github.com/Microsoft/WSL/files/1985200/0x800703fa_error.zip)

Repro

1. Launch Ubuntu

Result
```
Installing, this may take a few minutes...
Installation Failed!
Error: 0x800703fa
Press any key to continue...
```

**Comment by derekyu56** [comment]
Just did an update (KB4103721) and the problem is gone. The service LXSS is configured as Manual. Starting Ubuntu will start the service automatically.

**Comment by mloskot** [comment]
https://github.com/Microsoft/WSL/issues/2576#issuecomment-383907890
> If I wait several minutes after my system boots, ubuntu starts fine.

I can confirm this behaviour. Despite the LxssManager service Startup Type is Manual, if I wait 3-5 minutes after booting the system, all WSL-s work: Ubuntu, Debian, Kali, even the Ubuntu 18.04.

**Comment by steevsachs** [comment]
I have this same issue, and can also confirm that KB4103721 did not resolve the problem. Starting the LxssManager service or restarting resolves the issue.

Potentially notable: I had been experiencing the issue on about 50% of boots prior to KB4103721 and then did not experience the issue until several days after KB4103721.  Could be a coincidence.

**Comment by benhillis** [comment]
@diablodale - Thanks for providing the traces. As I suspected we're getting a REG_KEY_DELETED error when trying to enumerate which distribuitons are installed.  What's mysterious is that the parent key we are querying is never deleted by our service, so I suspect something fishy is going on with some other component or perhaps even the registry.

@steevsachs - Interesting.  Let me know if you encounter this again with the update installed.  Our service is simply enumerating subkeys to determine which distributions are installed, the key in question is never deleted by us so the error is mysterious.  Seems like there may be some registry-related issue in that update that was fixed.

**Comment by steevsachs** [comment]
Thanks for the response @benhillis.  To clarify, I _have_ encountered the issue since  KB4103721.  What was notable is that, whereas before KB4103721 the issue was occurring every other boot, it seems to occur with significantly lower frequency after KB4103721.

**Comment by kyranet** [comment]
In my case, I got this after restarting Windows. I have Ubuntu 18.04

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800703fa
Error: 0x800703fa Attempt of illegal operation in a registry key that was marked for elimination.

Press any key to continue...```

**Comment by deveth0** [comment]
zupalex: same here. I also noticed, that the WSL is starting on several boots but sometimes requires a manual restart of the LxssManager (thanks for this idea!!)

**Comment by seerwright** [comment]
Reboot fixed me a well - that was scary.

**Comment by mloskot** [comment]
Folks, clearly, the reboot fix works just by a flux. It is not a fix. The LxssManager service is simply not starting, or completing startup procedure too late or starting up into an incomplete state.

Instead of spamming the ticket about "reboot fixed", simply up vote previous alike comment.

**Comment by benc-uk** [comment]
This has started happening since 1803 update, I thought my WSL was totally borked

**Comment by xtoolkit** [comment]
@kyranet how fix it?

**Comment by ozen** [comment]
@xtoolkit Please note that kyranet had a different error.

**Comment by simoncpu** [comment]
I've experienced this error twice now. Restarting LxssManager solved the problem, although I don't know why I need to restart the service in the first place.

**Comment by jomocag** [comment]
My two cents...

When trying to launch Ubuntu on my system I have seen both errors "Installation failed" and "WslRegisterDistribution failed" since last W10 big update. As @mloskot said, it have always failed when I tried to launch it just after boot&login. Today I just waited some time before trying it again and it has launched normally.

Till now I have been using a little batch file on the desktop in order to restart Lxss service (last sc command is just to confirm it is starting):
`sc stop LxssManager  `
`pause`  
`sc start LxssManager`  
`pause`  
`sc queryex LxssManager`  
`pause  `  

If you want to follow the uninstall/install path (I haven't tested it), look into [this post](https://github.com/Microsoft/WSL/issues/3054#issuecomment-377775244) at issue #3054 in order to avoid losing your files & setup.

**Comment by ioanmoldovan** [comment]
This issue only seems to happen when you shutdown with Fast startup on. It never occours after restarts, and neither after Shift+shutdown. Disabling Faststartup is for me a better fix.

**Comment by simoncpu** [comment]
I had my suspicion that something like this was causing the problem (i.e.,
other services like DNSCrypt have trouble starting on my laptop too), but I
didn't know what it's called in Windows. Googling "fast startup" now...
thanks for the tip... :)

**Comment by simoncpu** [comment]
I had the same issue too. I thought it was just normal to manually connect to OpenVPN on boot. Disabling fast startup solved a lot of other issues! Thanks, @ioanmoldovan

**Comment by benhillis** [comment]
I'll try playing around with fast startup on.

**Comment by ioanmoldovan** [comment]
Fast startup is a great idea, but it causes a lot of software/hardware
issues. Especially when dual-booting.

**Comment by benhillis** [comment]
I've identified the issue and am currently working on a fix.

**Comment by ioanmoldovan** [comment]
I’m curious, can you explain what exactly caused the issue?

By the way, why isn’t WSL open source, I mean, it’s nice to have issues page, but please, release the source code!

**Comment by benhillis** [comment]
Essentially the issue is that with fast reboot the LxssManager service is not stopped when the user's session exits and when the machine restarts some registry keys that were opened in the previous session are now invalid.

WSL is part of Windows, and Windows itself is not open source.  It would be nice if all or parts of the project could be open sourced but nothing new to report on that front.

**Comment by ioanmoldovan** [comment]
Okay, so I’ve been correct in my suspicion. I didn’t have access to this level of detail. Thank you, this explains everything.

**Comment by endiliey** [comment]
Thanks for the clarification

**Comment by benhillis** [comment]
In the meantime, I'd suggest disabling fast boot or manually restarting the LxssManager service.  Will work on getting this backported to 1803.

**Comment by ioanmoldovan** [comment]
Yes, I’ve done that a few hours ago, had a bunch of reboots, shutdowns since then, no problems anymore. I can confirm that this does work (as a workaround).

**Comment by hleach** [comment]
In my case, the service was set to manual and required startup after every reboot. I could not change the startup type in services.msc.

I had to manually set the start type of the LxssManager service to automatic via regedit.

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager
Start = 2

**Comment by Luberen** [comment]
Stopping and restarting LxssManager fixes the issue, although it's temporary solution.

**Comment by siatjiasen** [comment]
Disabling fast boot or manually restarting the LxssManager service.  Both solution work. I used the first approach. 

How to disable fast boot:
Go "Setting -> System -> Power & Sleep -> Related Settings (additional power settings) -> Choose what the power buttons do -> Change settings that are currently unavailable ->  **Unchecked** Turn on fast startup (recommended)".

If you are using dual-boot (Windows 10 + Ubuntu), it is also suggested to "unchecked" the fast startup.

Be careful -> when you update your windows 10, it will "checked" the fast startup again. 

My question Is this a final solution to Error: 0x800703fa ?

**Comment by benhillis** [comment]
This should be fixed in 17704.  If anybody that was experiencing this issue could verify I will begin the process to backport this fix to 1803.  Thanks!

**Comment by benhillis** [comment]
Thanks for confirming. I've begun the process to get the fix ported to 1803.

**Comment by iangregory** [comment]
For what it's worth, I had a similar issue which manifested with a different error code (0x800700b7). WSL couldn't find any distros. Rebooting or restarting the service didn't have any impact.

I found that the `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss` registry entry was completely empty. Using the registry export found in [this comment](https://github.com/Microsoft/WSL/issues/2986#issuecomment-375123981) as a basis, and getting the correct GUID from the distribution's `LocalCache\Local\Microsoft\Windows\Caches` folder I was able to piece together the missing registry entries, load them into the registry and restore WSL.

**Comment by feryardiant** [comment]
Just getting same issue few minutes ago after rebooting & it fixed only by **rebooting** again.

I'm using Windows 10 Home SL 1803 Build 17134.165 and everything's works just fine until I need to shut down my laptop for some reason. When I'm boot it up & open up my WSL I saw this issue. As I said I just tried to reboot it once & see is it fixed or not because I simply **don't want** to reinstall it, all my work was there & I still have a lot of to-do.

---

Also I'm not sure if it was related but I saw Device Performance & Health issue in my Windows Defender

![gambar](https://user-images.githubusercontent.com/508665/42774856-0feb8978-895d-11e8-8888-e09a34a98d8b.png)

**Comment by benhillis** [comment]
@feryardiant - This is in the servicing pipeline for 1803.  In the meantime if can disable fast boot:

https://www.intowindows.com/how-to-turn-on-or-off-fast-startup-in-windows-10/

**Comment by feryardiant** [comment]
Thanks @benhillis

**Comment by black-snow** [comment]
I usually start the wsl bash about 3-8 times and it starts working again. Seems like some service needs some time to start up for me.

**Comment by DarthSpock** [comment]
@black-snow That would be the LXSS service as mentioned several times in the thread. For some reason fast startup screws with the service even though other services are unaffected (I prefer fast startup on and haven't encountered the issue for awhile even though I did switch it back on in BIOS a couple weeks ago) Probably because I give the service time to start properly. Looking forward to a proper fix where I don't need to worry about it potentially coming up again.

**Comment by m-farah** [comment]
I Had the same problem, just restart LxssManager by following this tips:
1- Run **CMD** as administrator and restart the LxssManager status

2- Stop it by :
**sc stop LxssManager**

3- Then restart it by:
**sc start LxssManager**

**Comment by benhillis** [comment]
@DarthSpock - The issue is not that the service doesn't start. When you hit this issue, the service will be running.  The issue is that with fast boot enabled, session 0 services (like LxssManager) do not stop and some internal state (in this case an open registry key) become invalid.

**Comment by DarthSpock** [comment]
That does sound different. Thank you for the clarification.

**Comment by nanonyme** [comment]
@benhillis sorry but do you have any estimate how long time the "in the servicing pipeline" in reality means?

**Comment by benhillis** [comment]
Hopefully soon, a month or so if I had to guess. We batch fixes togerher and this bug has been approved for the next patch.

**Comment by nanonyme** [comment]
Thanks. Different projects have different ideas of release cycles so I was interested in ballpark figures.

**Comment by xtoolkit** [comment]
@benhillis 
When?
Two months later, the new version of Windows 10 was released? : |

**Comment by nanonyme** [comment]
@xtoolkit come on, this is fairly moderate impact with working workaround. Microsoft isn't going to do any panic patching just for this. If it's approved, it'll hit batch update soon

**Comment by Jose-CF** [comment]
For me the issue fixed when I started the aforementioned process. So setting it to start-up automatically fixes the issue also.

So I guess the fix for you guys is obvious. Make sure when you install an app requiring that service that the service is set to start automatically. I 10yo kid should be capable to fix it by now. Merging it in is another story :P

**Comment by benhillis** [comment]
@Josh-CF - while I appreciate your uninformed reductionism, the issue is more complicated than that.

**Comment by benc-uk** [comment]
What a spectacularly unhelpful comment

**Comment by herrvigg** [comment]
Great tip to restart LxssManager, thank you <3

This issue happens quite often :-/

**Comment by Flakesz** [comment]
Encountered the same issue, newest update but the bug prevented me from running some WSL scripts on login.
In case you don't want to manually restart the LxssManager once you log in, you can do the following:

In `C:\Users\<username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` you create a new `.bat` file (e.g. `wsl_fix.bat`) and write the command `C:\WINDOWS\system32\svchost.exe -k netsvcs -p` into it, which basically triggers the start of the LxssManager upon login.

**Comment by ioanmoldovan** [comment]
This issue is related to fast startup. I turned off fast startup and NEVER
had it since. And I use WSL a lot!

**Comment by ioanmoldovan** [comment]
Use a scheduled task if you want to avoid turning off fast startup.

**Comment by vctls** [comment]
Sorry for adding yet another comment on an already crowded issue.
I had the same issue with a manually installed Debian.
I solved it by first unregistering it with wslconfig then reinstalling it by running the exe.
```sh
wslconfig /u Debian
# unregistering stuff...
debian.exe
```

**Comment by mloskot** [comment]
https://github.com/Microsoft/WSL/issues/2576#issuecomment-388934911
> @mloskot - Do you happen to see any strange errors in the Windows event log
> around the time distros are failing to launch?

I don't see any events logged around the time I launch any of WSL distro (ie. START > Ubuntu etc.), but I see lots of logs like this one around the time of OS booting:

```
Windows detected your registry file is still in use by other applications or services. The file will be unloaded now. The applications or services that hold your registry file may not function properly afterwards. No user action is required.  

 DETAIL - 
 7 user registry handles leaked from \Registry\User\S-1-5-21-1454471165-1326574676-682003330-10609_Classes:
Process 9768 (\Device\HarddiskVolume4\Windows\System32\lxss\wslhost.exe) has opened key \REGISTRY\USER\S-1-5-21-1454471165-1326574676-682003330-10609_Classes
Process 9768 (\Device\HarddiskVolume4\Windows\System32\lxss\wslhost.exe) has opened key \REGISTRY\USER\S-1-5-21-1454471165-1326574676-682003330-10609_Classes
Process 9768 (\Device\HarddiskVolume4\Windows\System32\lxss\wslhost.exe) has opened key \REGISTRY\USER\S-1-5-21-1454471165-1326574676-682003330-10609_Classes
Process 3860 (\Device\HarddiskVolume4\Windows\System32\conhost.exe) has opened key \REGISTRY\USER\S-1-5-21-1454471165-1326574676-682003330-10609_Classes\Local Settings
Process 9768 (\Device\HarddiskVolume4\Windows\System32\lxss\wslhost.exe) has opened key \REGISTRY\USER\S-1-5-21-1454471165-1326574676-682003330-10609_Classes\Local Settings
Process 3860 (\Device\HarddiskVolume4\Windows\System32\conhost.exe) has opened key \REGISTRY\USER\S-1-5-21-1454471165-1326574676-682003330-10609_Classes\Local Settings\Software\Microsoft
Process 9768 (\Device\HarddiskVolume4\Windows\System32\lxss\wslhost.exe) has opened key \REGISTRY\USER\S-1-5-21-1454471165-1326574676-682003330-10609_Classes\Local Settings\Software\Microsoft
```

**Comment by agustinbreit** [comment]
> I Had the same problem, just restart LxssManager by following this tips:
> 1- Run **CMD** as administrator and restart the LxssManager status
> 
> 2- Stop it by :
> **sc stop LxssManager**
> 
> 3- Then restart it by:
> **sc start LxssManager**

that worked for me! thanks

**Comment by xtoolkit** [comment]
@agustinbreit 
fixed in1809!

**Comment by seahorseman** [comment]
> > I Had the same problem, just restart LxssManager by following this tips:
> > 1- Run **CMD** as administrator and restart the LxssManager status
> > 2- Stop it by :
> > **sc stop LxssManager**
> > 3- Then restart it by:
> > **sc start LxssManager**
> 
> that worked for me! thanks

Fixed! You may see access denied, just run CMD as administrator will make it work.

Thank you!

**Comment by djensen47** [comment]
I'm experiencing this in 18272 and a reboot does NOT fix it. Restarting the LxssManager does not fix it.

**Comment by djensen47** [comment]
Disabling Fast Boot also does not fix the issue. All of my work is now trapped in WSL and I have no way to work. Bugs are one thing but this is ridiculous.

**Comment by djensen47** [comment]
Thanks for the update. I went ahead an rolled back. It was a lot less painful than the last time I had to rollback so that's a plus!

**Comment by lesliepoolman** [comment]
This worked for me in OS build 17134.407
Thanks!

> 
> 
> I Had the same problem, just restart LxssManager by following this tips:
> 1- Run **CMD** as administrator and restart the LxssManager status
> 
> 2- Stop it by :
> **sc stop LxssManager**
> 
> 3- Then restart it by:
> **sc start LxssManager**

**Comment by mloskot** [comment]
Follow up to my https://github.com/Microsoft/WSL/issues/2576#issuecomment-427387182

Something happened again, after update to Windows 10 Version 1803 (OS Build 17134.441), LxssManager startup type has got set to Manual and, despite being fully privileged Administrator, I can not re-set it to Automatic:

![image](https://user-images.githubusercontent.com/80741/49820886-63adba00-fd79-11e8-9bed-c0acc78d94b1.png)

**Comment by sdjulio** [comment]
Windows 10.0.17134, Build 17134 (Pro)
Same behavior but addressed issue with Regedit.  Services.msc app would not let me change the startup type.  Instead, changed it using Regedit.exe as Admin.

Path to registry key: Computer\HKEY_LOCAL_MACHI

NE\SYSTEM\CurrentControlSet\Servic
[AutoStartLxssManager.zip](https://github.com/Microsoft/WSL/files/2693325/AutoStartLxssManager.zip)
es\LxssManager\Start
Set value to 2 (Automatic)

If you're not too paranoid you can simply import the .reg I've attached.  I understand if you're wary of using it.

**Comment by crazybytes** [comment]
Microsoft Windows [Version 10.0.17134.472]
(c) 2018 Microsoft Corporation. Alle rechten voorbehouden.

C:\Users\Gerard Wensink>bash
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
Press any key to continue...

I installed Arch Linux, and shut down my pc. On restart with bash from cmd i get this.


When i try to start Arch i get this:

Installing...
ERROR:Installation Failed!
HRESULT:0x800703fa
Press any key to continue...

I was suspecting that after seeing all kind of registering tools are in the system on every level.
Seems they first want to make you using it for free, then sabotaging everything especially through windows with its new updates, resulting in manipulating almost everything.

You can not trust Satan.

How do i get the system back?

**Comment by crazybytes** [comment]
Why should a linux shell under windows integrate with windows?
It can run in one .exe file. Managing the whole system just like it does with the powershell function.
Seems they also watch how you are pooping today.

**Comment by chiro-hiro** [comment]
I've the same issue, It will be gone if i'm restart LxssManager.

**Comment by lucastakejame** [comment]
I also failed to set LxssManager service startup to automatic via services.msc (even with admin)
BUT, I managed to set to automatic with the following command on a cmd (as admin):

> sc config LxssManager start=auto

now its set to automatic. Hope it helps =)!

**Comment by dpingk** [comment]
> I have the same issue on 17133.1. Ubuntu installed in Microsoft Store. A reboot does clear the error, but everytime I open a wsl, I need a reboot again. Please fix this issue ASAP !!!
> 
> wsl says:
> 
> ```
> Installing, this may take a few minutes...
> Installation Failed!
> Error: 0x800703fa
> Press any key to continue...
> ```
> UPDATE:
> This error has never happened before, since I fresh Installed 1803 17133.1 recently. The only different thing is I installed gcc build tool chain and nginx.
> 
> UPDATE AGAIN:
> I find a solution other than a reboot: go to `services.msc`, make sure service `LxssManager` is running, if it is running already, restart it，after turn it on I can use wsl immediately.

This helped.
I found similar problem after updating Windows BIOS firmware.

**Comment by sanjanareddy5502** [comment]
after getting a message press any key, its closing by itself

**Comment by sanjanareddy5502** [comment]
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization

**Comment by Avliis** [comment]
Hello guys! I hope you did well!

WHAT WORK FOR ME:

1- Be sure that the Lxxs Manager is auto and on COMMAND: sc config LxssManager start=auto, then restart!
3 - Check the linux subsystem for windows is on, then restart!
2 - Install the update wsl 
[wsl.2.3.24.0.x64.msi](https://github.com/microsoft/WSL/releases/download/2.3.24/wsl.2.3.24.0.x64.msi)

And you should be good!

Thank you all!
