### ISSUE TITLE
Nano display issue

### ISSUE THREAD

**Issue by trapframe** [Microsoft/WSL#27]
nano is displaying fine until you try to scroll the document, then only part of the screen is scrolling.
Sometimes when scrolling back (up) the console window is resizing itself (reducing its height)

**Comment by jernejs** [comment]
There's a similar problem with less - scrolling down works, but scrolling up only updates the top row.

**Comment by kobaltz** [comment]
I experienced this as well; had to resize the window to refresh the screen and get it looking normal (until I scroll again).

**Comment by atrauzzi** [comment]
One way to observe I think is to have a long line in the document and then try scrolling to the end of that line.

**Comment by yalcin** [comment]
similar issue have on bash command line too. words are tangling when browsing command history with up and down keys.

**Comment by zadjii-msft** [comment]
Just double checked, I think I see what's going on here and I'm working on a fix!

**Comment by floam** [comment]
`TERM=ansi` seems to work to fix this. Is it the alternate screen? https://github.com/fish-shell/fish-shell/issues/2910

**Comment by tkelman** [comment]
Another thing to test here is hitting "end" while you're already at the end of a line. This is inserting a tilde for me. Might be related?

**Comment by floam** [comment]
This is not an issue with nano, it should really be fixed up by somebody - it's an issue with the terminal emulator.

**Comment by floam** [comment]
I also see there is `TERM=interix`! How about that!

**Comment by zadjii-msft** [comment]
For the time being, yes, `TERM=ansi` would fix this, though, it's not actually a problem with the alternate screen, rather, the scrolling margin settings.

Also, the 'End' key inserting a tilde is actually unrelated, and I'm pretty sure I've got that tracked down :)

**Comment by floam** [comment]
How about "interix'?
On Tue, Apr 12, 2016 at 9:26 AM Mike Griese <notifications@github.com>
wrote:

> For the time being, yes, TERM=ansi would fix this, though, it's not
> actually a problem with the alternate screen, rather, the scrolling margin
> settings.
>
> Also, the 'End' key inserting a tilde is actually unrelated, and I'm
> pretty sure I've got that tracked down :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/BashOnWindows/issues/27#issuecomment-208991199>
>
-- 
Aaron

**Comment by bitcrazed** [comment]
@floam Interix is no longer shipped nor supported.

**Comment by floam** [comment]
The Ubuntu tarball has interix terncap. It works well for WSL/Bash today. Renders curses stuff great.  

--  
Aaron Gyes

**Comment by floam** [comment]
(And with https://github.com/floam/lxsscons, has 16 colors and isn't
infuriating with the backspace.)

-- 
Aaron Gyes

**Comment by floam** [comment]
> Interix/SFU is no longer shipped nor supported.

I am simply suggesting it as a better "lie" - especially with it no longer shipping, it will be not so destructive if someone (for example) replaces the termcap with one like I posted above. 

It would be best if it just said exactly what it is - but people will be shelling into naive remote machines, etc. and at least `interix` comes with ncurses and the degradation is rather graceful. It's a better starting point than saying xterm of all things, IMO.

**Comment by jjriv** [comment]
vim is also experiencing a similar weirdness. I am going to assume fixing this issue will also fix vim. But is a description of the bug in case it helps:

If I type 'dd' to cut a line of text, the first line disappears, not the line I am on. If I page down and page up, the text refreshes and the first line reappears. The line I cut is indeed cut.

**Comment by bitcrazed** [comment]
@jjriv Just tested on recent bits and, yes, looks like it solves your dd issue in vim.

**Comment by jjriv** [comment]
@bitcrazed Thanks! I'll be sure to check it out. Do you happen to know which build number has the fix?

**Comment by bitcrazed** [comment]
Fixed internally. Bubbling up through the build system.

**Comment by bitcrazed** [comment]
Not sure as yet. Will try to update if we find out.

**Comment by mobluse** [comment]
Browsing history with the up arrow key is still a problem in Build 14342, see example:
![arrow-up1](https://cloud.githubusercontent.com/assets/5777329/15269842/17635482-1a0c-11e6-8b64-8134b4654217.png)
![arrow-up2](https://cloud.githubusercontent.com/assets/5777329/15269843/255d6730-1a0c-11e6-90e0-b39be4a0bfe1.png)
![arrow-up3](https://cloud.githubusercontent.com/assets/5777329/15269844/2ae4180c-1a0c-11e6-8cf5-221f8ca95f75.png)
![arrow-up4](https://cloud.githubusercontent.com/assets/5777329/15269846/32db654c-1a0c-11e6-9233-c7673451fa2a.png)
![arrow-up5](https://cloud.githubusercontent.com/assets/5777329/15269847/39d6387c-1a0c-11e6-828f-6b6550b826dc.png)

**Comment by mobluse** [comment]
It is still a bug in Build 14361, because I typed in the commands in history above and used up-arrow and got similar erroneous results.

**Comment by mobluse** [comment]
The above It is still a bug in Build 14372.

**Comment by bitcrazed** [comment]
@mobluse Could you provide a step by step repro of what you're doing and what you're expecting. I don't quite follow what's up in your steps above.

**Comment by mobluse** [comment]
@bitcrazed This is still a bug in 17379. I enter all commands in the last picture except `history`. Then I do the steps from start, i.e. press up arrow and observe the result a couple of times. When I press up arrow I expect `sudo apt purge xutils`, but I get `sudo apt purge xutilsve`, i.e. the 've' comes from the previous command: `sudo apt-get autoremove`. There is probably a simpler example to reproduce this bug, but I have not found it. (I run Xming Server, but that is probably not important.)

**Comment by onomatopellan** [comment]
I also have same problem as @mobluse. I think it's easy to reproduce with a small window.
For example. in bash.exe properties change the window Width to 80 and in bash enter these commands:
`./configure --host=x86_64-w64-mingw32 --prefix=/home/onoma/mpv-winbuild-cmake/build/prefix/mingw --disable-shared --disable-frontend`
`ninja gcc winpthreads`
Just pressing up arrow 2 times and down arrow once and you will see
>  ninja gcc winpthreads6_64-w64-ming

If you press enter it just executes "ninja gcc winpthreads" so the rest It's like garbage from the previous command.

**Comment by bitcrazed** [comment]
Thanks all. I've re-created @mobluse's repro steps to exhibit the issue:

On 14385, I typed the following command sequence:
````bash
sudo apt install xterm
xterm
export DISPLAY=:0
xterm
sudo apt install xutils
xedit
sudo apt-get install x11-apps
xcalc
xedit
sudo apt purge xutils
sudo apt-get autoremove
history
````
![image](https://cloud.githubusercontent.com/assets/961950/16715195/6c0fc566-468e-11e6-82f3-d148359ae789.png)
I then typed `clear` 
Up: `clear`
Up: `history`
Up: `sudo apt-get autoremove`
Up: `sudo apt purge xutilsve`
![image](https://cloud.githubusercontent.com/assets/961950/16715210/bed1cd08-468e-11e6-9bee-8be98b874662.png)

@zadjii-msft Looks like we might have some more work to do here! Assigning to you 😜

**Comment by mobluse** [comment]
Also when you try to edit an earlier line in history it doesn't look right on the screen, but it works. 

Build 14385.

I run
`~/blockis/install.sh`
and then use up-arrow and then press Home and enter `cat ` before the command:
`cat ~/blockis/install.sh`
but it shows
`cat ockis/install.sh`

To install what is needed:
```
sudo apt update
sudo apt install git
cd
git clone https://github.com/mobluse/blockis
```

**Comment by mobluse** [comment]
I still get `sudo apt purge xutilsve` instead of `sudo apt purge xutils` in Build 14393.10 with freshly installed Bash on Ubuntu on Windows.

**Comment by Akujin** [comment]
![image](https://cloud.githubusercontent.com/assets/195216/18037115/709cdc1c-6d4a-11e6-9627-9d05fe25f539.png)
I'm still getting weirdness in 14905.

Notice that huge indent at the start. Definitely shouldn't be there.

This is nano on a remote machine via ssh.

**Comment by mstrelan** [comment]
I hadn't had any issues until updating to 14942, now nano freezes when I hit page down until I resize the window. I then can't click the Windows close button, can only exit Bash by typing exit.

**Comment by wench** [comment]
Nano in 14942 nit working probably for me either. Noticed that running nano in a screen session will get around the problem

**Comment by mstrelan** [comment]
I upgraded nano to 2.7.0 and it's fixed now. Not sure if it's related to the new .nanorc config though.

**Comment by benhillis** [comment]
@mstrelan One of our developers has a bugfix for a deadlock that I believe could explain this. He'll be checking in a fix soon and it should be in Insider builds within a few weeks.

**Comment by zadjii-msft** [comment]
We have had some issues with the TTY size recently. If `stty -a` shows the `height` as greater than the actual window's height, then that's definitely it. See #1215, because that's almost certainly related.

**Comment by Akujin** [comment]
I had to run `lxrun /uninstall /full` and `lxrun /install /y` to get this fixed. Updates and what not didn't fix it at all and I already had `TERM=ansi` set. Probably some home directory setting but I never could track it down exactly.

**Comment by mjz19910** [comment]
@Akujin Nano is not aware of the local screen size, If you change the related config values on the remote machine it should help alot. Also, check for any terminal configuration differences(stty) and ensure the remote machine is configured in the same manner.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing. If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).

**Comment by Toorero** [comment]
@bitcrazed I would be interested which issue collates to this issue on your Console because I'm still experiencing this issue on `nano` and `vim` and what not on `10.0.18363 Build 18363`.

Thanks. 😉

**Comment by zadjii-msft** [comment]
@Toorero This issue is more than 4 years old at this point. I'm sure if you're still seeing something like this, it'll have a different cause than whatever was being tracked here. I'd look for existing issues [here](https://github.com/microsoft/terminal/issues). I can't think of any existing issues that we're tracking with `vim`/`nano` that are like this, but I might be mistaken. if there's nothing that looks like what you're seeing, I'd file a new issue there.
