### ISSUE TITLE
WSL bash crashes (0x800704c8) over WSL ssh to Windows 10 OpenSSH server  

### ISSUE THREAD

**Issue by whereisaaron** [Microsoft/WSL#2842]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
`Microsoft Windows [Version 10.0.16299.192]`

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
1) Install WSL and Windows OpenSSH Server (beta)
2) start WSL bash
3) ssh to localhost
4) run WSL bash
5) Note that bash crashes

* What's wrong / what should be happening instead:

Using `bash` over `ssh` with the Windows 10 OpenSSH server, if you ssh in you get a cmd.exe shell. If you then run bash you get:
```
C:\Users\aaron>bash
Error: 0x800704c8
Press any key to continue...
```
If you run `cmd.exe` locally, and the run `bash`, no problem. It only crashes like this over ssh.
```
Microsoft Windows [Version 10.0.16299.192]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\aaron>bash
aaron@foo:/mnt/c/Users/aaron$
```

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

Not really possible? Because I can't get into bash to trace it.

**Comment by jstarks** [comment]
This is a known limitation of the current Windows release, but it is fixed in recent Windows Insider builds.

**Comment by lookingforlemons** [comment]
@jstarks Can I get a build # for this fix? I just recently upgraded to V 10.0.16299.402 and the issue is still persisting. Has the fix not made it to production yet?

**Comment by jstarks** [comment]
The fix is in the Windows 10 April 2018 update, which will be publicly available on April 30.

**Comment by whereisaaron** [comment]
Great news @jstarks, thanks again for the fix.

Four-month waits for a bug fix like this show why WSL should be unbundled from Windows 10. It should be an application download you can install separately and update weekly if you want.

Remember when we used to have to live with heinous builds of IE because it was 'part of Windows'. Why are we going back to that @jstarks?  You guys did the good work and fixed this bug months ago, why can't Microsoft let you release even a bug fix more often that 2-3 times a year?

**Comment by miltontan** [comment]
Hello, I got this identical problem when trying to launch bash on my Windows server running Windows 10 version 10.0.16299.726, which is the October 9, 2018 version. Is this known?
