### ISSUE TITLE
Unable to enable WSL - "HRESULT_FROM_WIN32(1726)" while "Installing network driver vms_pp"

### ISSUE THREAD

**Issue by cym104** [microsoft/WSL#3063]
Windows 10 ENT x64 build 17127, NICs are Killer E2400 GE & Killer Wireless 1535 WLAN.
When tring to enable WSL, the install fails after first reboot and then rolls back.

The following message is recorded in CBS.log

```
2018-03-22 20:54:37, Info                  CSI    00000121 Begin executing advanced installer phase 31 index 0 (sequence 0)
    Old component: [l:0]''
    New component: [l:0]''
    Install mode: delta
    Smart installer: true
    Installer ID: {a111f280-5923-47c0-9a68-d0bafb577901}
    Installer name: 'Network Drivers'
2018-03-22 20:54:37, Info                  CSI    00000122 Begin NetSetup servicing operation
2018-03-22 20:54:37, Info                  CSI    00000123 Begin loading the binding engine
2018-03-22 20:54:37, Info                  CSI    00000124 Finished loading the binding engine - elapsed time: 15ms
2018-03-22 20:54:37, Info                  CSI    00000125 Begin calculating changes
2018-03-22 20:54:37, Info                  CSI    00000126 Installing network driver ms_vfpext
2018-03-22 20:54:37, Info                  CSI    00000127 Installing network driver netAdapterDriver-{72FEF6B3-26F8-42AA-A41C-5B491CBB0914}
2018-03-22 20:54:37, Info                  CSI    00000128 Installing network driver vms_pp
2018-03-22 20:54:40, Info                  CSI    00000129 Error while printing exception records to this log file
2018-03-22 20:54:40, Info                  CSI    0000012a@2018/3/22:12:54:40.193 CSI Advanced installer perf trace:
CSIPERF:AIDONE;{a111f280-5923-47c0-9a68-d0bafb577901};(null);2981555us
2018-03-22 20:54:40, Info                  CSI    0000012b End executing advanced installer (sequence 0)
    Completion status: HRESULT_FROM_WIN32(1726) 
2018-03-22 20:54:40, Error      [0x01805b] CSI    0000012c (F) Failed execution of queue item Installer: Network Drivers ({a111f280-5923-47c0-9a68-d0bafb577901}) with HRESULT HRESULT_FROM_WIN32(1726).  Failure will not be ignored: A rollback will be initiated after all the operations in the installer queue are completed; installer is reliable[gle=0x80004005]
```

I'm not using 3rd party AV/firewall software(only windows defener), and there's no VPN application installed.
I tired to manually install this vms_pp driver with:
netcfg -l C:\Windows\WinSxS\amd64_dual_wvms_pp.inf_31bf3856ad364e35_10.0.17120.1_none_04bc0d690be4e471\wvms_pp.inf -c p -i vms_pp
but it simpley give me a error 0xe000022f.

I've already tried:

- made sure VT-x and VT-d enabled in BIOS
- remove any other virt soft (e.g. VMware workstation).
- remove any software that might modify network stack.
- DISM and sfc
- update driver for all NICs.
- rollback driver for all NICs to windows default.
- disable all NICs in BIOS.
- reset network from Settings app.

**Comment by Biswa96** [comment]
WSL has no relation with Hypervisor. So why do you want that?
The error:1726 is RPC_S_CALL_FAILED means remote procedure call failed.

**Comment by Biswa96** [comment]
No, nope, never.

**Comment by cym104** [comment]
@Biswa96 yes it is. both WSL and WDAG are dependent on Hyper-V.

**Comment by Biswa96** [comment]
OMG! Take a good sleep before touching PC.

**Comment by Biswa96** [comment]
Two are different things, there is no relation between them.

**Comment by cym104** [comment]
@Biswa96 Whatever. Weather WSL is related to Hyper-V or not I don't care for now. I just want to fix this 1726 error now.

**Comment by Brian-Perkins** [comment]
The confusion here is that while WSL is not dependent on Hyper-V, it is dependent on some Hyper-V networking components. This dependency was introduced in Fall Creator's Update and allows basic support for veth/vbridge devices. Recently this seems to be causing intermittent problems (see latest posts on #931) with various 3rd-party drivers installed.

**Comment by cym104** [comment]
Updated with NIC info.

**Comment by tommai78101** [comment]
@Brian-Perkins I think it's a good idea to change your title so it both displays the error message, as well as explain why (Hyper-V dependency for network components).

**Comment by gyroknight** [comment]
Has the cause of this issue been traced yet and is there a fix inbound in a future Insider build? I'm now on build 17661 and I still cannot enable WSL in Windows Features with the same errors as before.

**Comment by onomatopellan** [comment]
Build 17666 fixes some problem I had with wvms_mp driver. (Docker daemon won't run on WSL because it won't install Hyper-V Virtual Ethernet Adapter)

Maybe it also fixes this problem?

**Comment by cym104** [comment]
Sounds highly promising. Too bad it's on fast ring only.

**Comment by gyroknight** [comment]
On 17666 right now and same issue is still occurring with vms_pp.

**Comment by gyroknight** [comment]
Upgraded to 17686, still cannot install Windows Subsystem for Linux.

**Comment by gyroknight** [comment]
Issue still present on 17755.

**Comment by Biswa96** [comment]
@gyroknight Try to enable both WSL and Hyper-V feature.

**Comment by gyroknight** [comment]
@Biswa96 Same error, same issue. Tried enabling both at the same time and separately. None of them install correctly and rollback after restarting.

**Comment by gyroknight** [comment]
I can enable Windows Hypervisor Platform, but not Virtual Machine Platform, WSL, or Hyper-V, all with the same error as before. Here's the relevant excerpt from CBS.log:
`2018-09-09 03:24:38, Info                  CSI    000000ec Begin executing advanced installer phase 31 index 0 (sequence 0)
    Old component: [l:0]''
    New component: [l:0]''
    Install mode: delta
    Smart installer: true
    Installer ID: {a111f280-5923-47c0-9a68-d0bafb577901}
    Installer name: 'Network Drivers'
2018-09-09 03:24:38, Info                  CSI    000000ed Begin NetSetup servicing operation
2018-09-09 03:24:38, Info                  CSI    000000ee Begin loading the binding engine
2018-09-09 03:24:38, Info                  CSI    000000ef Finished loading the binding engine - elapsed time: 0ms
2018-09-09 03:24:38, Info                  CSI    000000f0 Begin calculating changes
2018-09-09 03:24:38, Info                  CSI    000000f1 Installing network driver ms_l2bridge
2018-09-09 03:24:38, Info                  CSI    000000f2 Installing network driver ms_vfpext
2018-09-09 03:24:38, Info                  CSI    000000f3 Installing network driver netAdapterDriver-{72FEF6B3-26F8-42AA-A41C-5B491CBB0914}
2018-09-09 03:24:38, Info                  CSI    000000f4 Installing network driver vms_pp
2018-09-09 03:24:40, Info                  CSI    000000f5 Error while printing exception records to this log file
2018-09-09 03:24:40, Info                  CSI    000000f6@2018/9/9:07:24:40.081 CSI Advanced installer perf trace:
CSIPERF:AIDONE;{a111f280-5923-47c0-9a68-d0bafb577901};(null);1540618us
2018-09-09 03:24:40, Info                  CSI    000000f7 End executing advanced installer (sequence 0)
    Completion status: HRESULT_FROM_WIN32(1726) 

2018-09-09 03:24:40, Error      [0x01805b] CSI    000000f8 (F) Failed execution of queue item Installer: Network Drivers ({a111f280-5923-47c0-9a68-d0bafb577901}) with HRESULT HRESULT_FROM_WIN32(1726).  Failure will not be ignored: A rollback will be initiated after all the operations in the installer queue are completed; installer is reliable[gle=0x80004005]
2018-09-09 03:24:40, Info                  CBS    Could not get active session for current session file logging [HRESULT = 0x80004003 - E_POINTER]
2018-09-09 03:24:40, Info                  CBS    Could not get file name for current session file logging [HRESULT = 0x80004003 - E_POINTER]
2018-09-09 03:24:40, Info                  CBS    Added C:\WINDOWS\Logs\CBS\CBS.log to WER report.
2018-09-09 03:24:40, Info                  CBS    Added C:\WINDOWS\Logs\CBS\CbsPersist_20180909054946.log to WER report.
2018-09-09 03:24:40, Info                  CBS    Not able to add pending.xml.bad to Windows Error Report. [HRESULT = 0x80070002 - ERROR_FILE_NOT_FOUND]
2018-09-09 03:24:40, Info                  CSI    000000f9 Creating NT transaction (seq 2)
2018-09-09 03:24:40, Info                  CSI    000000fa Created NT transaction (seq 2) result 0x00000000, handle @0x39c
2018-09-09 03:24:40, Info                  CSI    000000fb@2018/9/9:07:24:40.191 Beginning NT transaction commit...
2018-09-09 03:24:40, Info                  CSI    000000fc@2018/9/9:07:24:40.201 CSI perf trace:
CSIPERF:TXCOMMIT;2905`

**Comment by cym104** [comment]
Do you use TeamViewer? if so, can you try upgrading it to higher than 13.2.14327?

**Comment by cym104** [comment]
Have you tried installing some 3rd party hypervisor first?
I think it's possible that mine was fixed after install virtualbox.

**Comment by cym104** [comment]
Or maybe revert your NIC drivers to the ones that came included in windows (usually the oldest version on your system).

**Comment by gyroknight** [comment]
No luck, tried installing VirtualBox, removing VMware Workstation, removing VirtualBox, deleting all my NICs and their drivers, and still the same issue. Strangely enough, I just ran into a HYPERVISOR_ERROR BSOD, but I don't know if that's related.

**Comment by therealkenc** [comment]
This issue went stale on without a local repro. If the problem persists on Windows 20H2 aka 19042, please open a new issue following the issue template and include [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs).
