### ISSUE TITLE
wslpath -u doesn't work mounted VHDX drive or optical drive.

### ISSUE THREAD

**Issue by 0xbadfca11** [Microsoft/WSL#3246]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17677.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
C: is Hyper-V IDE Hard Drive
D: is Hyper-V IDE DVD Drive media inserted
E: is Hyper-V SCSI Hard Drive hot plugged
F: is Mounted VHDX
```sh
# mount -t drvfs E: /mnt/e
# mount -t drvfs -r D: /mnt/d
# mount -t drvfs
C: on /mnt/c type drvfs (rw,noatime,uid=0,gid=0,metadata)
F: on /mnt/f type drvfs (rw,noatime,uid=0,gid=0,metadata)
E: on /mnt/e type drvfs (rw,relatime)
D: on /mnt/d type drvfs (ro,relatime,case=off)
# wslpath 'C:\'
/mnt/c/
# wslpath 'D:\'
wslpath: D:\: No such file or directory
# wslpath 'E:\'
/mnt/e/
# wslpath 'F:\'
wslpath: F:\: Permission denied
```
* What's wrong / what should be happening instead:

```sh
# wslpath 'C:\'
/mnt/c/
# wslpath 'D:\'
/mnt/d/
# wslpath 'E:\'
/mnt/e/
# wslpath 'F:\'
/mnt/f/
```

**Comment by Voskrese** [comment]
Permission denied

**Comment by 0xbadfca11** [comment]
I'm convinced that filesystem permission is not the cause.
![image](https://user-images.githubusercontent.com/7390559/41493795-d17aaa72-7145-11e8-81fb-bae92bb0a803.png)
(F: is mounted VHDX)

**Comment by Voskrese** [comment]
FULL ACCESS for ALL - ALL

**Comment by 0xbadfca11** [comment]
Nothing changes, right?
![image](https://user-images.githubusercontent.com/7390559/41503751-bd4d258a-7216-11e8-9b0f-bc37a911c08b.png)

**Comment by Biswa96** [comment]
Your folder output seems to be weird!

**Comment by 0xbadfca11** [comment]
So, on your system did ``wslpath -u`` work on the mounted VHDX?

**Comment by Voskrese** [comment]
@0xbadfca11  да, оказывается есть проблема, но не в доступе, а видимо в путях, незаню с чем это связано не не работает опция -u для виртуального диска

> Yes, it turns out there is a problem, but not access, but apparently in the ways that it does not work with the -u option for a virtual disk

```
wslpath -u C:/
/mnt/c/
```

```
root@net:/mnt/f# wslpath -u F:/
wslpath: F:/: No such file or directory
```

```
root@net:/mnt/f# wslpath -w /mnt/f/Ubuntu
F:\Ubuntu
```

**Comment by benhillis** [comment]
I've identified the issue here and am working on a fix.

**Comment by BeErikk** [comment]
FYI I installed wsl Ubuntu 18.04 on a virtual disk in Windows 10.0.17134.137. So far I haven't noticed any issues except wslpath doesn't work on my other virtual disks. I get (with the wsl disk mounted as L:)
>$ wslpath -m /home 
>wslpath: /home: Result not representable
of course

**Comment by Brian-Perkins** [comment]
This should be fixed in Insider Build [17713](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md#build-17713)

**Comment by 0xbadfca11** [comment]
Works fine on mounted VHDX.
But still happen on optical drive.

**Comment by 0xbadfca11** [comment]
Yes. Optical drive is not mounted automatically.

**Comment by benhillis** [comment]
Ok I'll give this a try today and see what's wrong.

**Comment by heldchen** [comment]
I have this issue for a VeraCrypt (aka TrueCrypt) volume which is correctly automounted by WSL. wslpath in 17713 cannot translate windows paths pointing to it:
```
me@devbox:~$ mount | grep drvfs
C: on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,metadata,case=off)
D: on /mnt/d type drvfs (rw,noatime,uid=1000,gid=1000,metadata,case=off)
T: on /mnt/t type drvfs (rw,noatime,uid=1000,gid=1000,metadata,case=off)
me@devbox:~$ wslpath -u 'd:\'
/mnt/d/
me@devbox:~$ wslpath -u 't:\'
wslpath: t:\: No such file or directory

```
should I create a separate issue for that or is it the same problem as with the (manual mounted) optical drives?

**Comment by rodrymbo** [comment]
I have the same issue with a Veracrypt Drive. 17746 has not changed it (so far). 

I'd guess it is the same reason that `wsl` or `ubuntu1804` revert to `~` instead of the current Windows directory when the directory is on a Veracrypt drive.

If this is the same issue, it shouldn't be closed. If different, please let us know whether to create a new issue.

**Comment by leongrdic** [comment]
Same issue here with veracrypt volumes not working with `wslpath`

**Comment by 0xbadfca11** [comment]
Now, works fine on optical drive in build 18252.

> Allow path translation on volumes without a volume GUID.
> https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18252-skip-ahead

Not have a GH number, but maybe this fix.

How about VeraCrypt?

**Comment by heldchen** [comment]
yes, it works for VeraCrypt mounted volumes as well now in 18252

**Comment by Biswa96** [comment]
@therealkenc require "fixedininderbuilds" tag.
