### ISSUE TITLE
ps aux -  Ssps:display.c:66: please report this bug Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by bityob** [Microsoft/WSL#3252]
* Your Windows build number:  10.0.17134.1

* What you're doing and what's happening:  

```bash
user@mymachine:~$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   8304   104 ?        Ss   Jun04   0:01 /init ro
<...removed some rows...>
Signal 11 (SEGV) caught by ps (procps-ng version 3.3.10).
root     15472  0.0  0.0  19568  1120 ?        Ssps:display.c:66: please report this bug
Segmentation fault (core dumped)
```

* What's wrong / what should be happening instead:

`ps` output without errors

* Strace of the failing command, if applicable:  

This is the tail output of the command - `strace -v -s 256 ps aux`

```bash
stat("/etc/localtime", {st_dev=makedev(0, 2), st_ino=281474977023961, st_mode=S_IFREG|0644, st_nlink=2, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=1129, st_atime=2018/02/04-16:23:13.751519800, st_mtime=2018/05/14-12:15:13.707070500, st_ctime=2018/05/14-12:15:13.707070500}) = 0
stat("/etc/localtime", {st_dev=makedev(0, 2), st_ino=281474977023961, st_mode=S_IFREG|0644, st_nlink=2, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=1129, st_atime=2018/02/04-16:23:13.751519800, st_mtime=2018/05/14-12:15:13.707070500, st_ctime=2018/05/14-12:15:13.707070500}) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x1c} ---
write(2, "Signal 11 (SEGV) caught by ps (procps-ng version 3.3.10).\n", 58) = 58
write(1, "root     15472  0.0  0.0  19568  1120 ?        Ss", 49) = 49
write(2, "ps:", 3)                      = 3
write(2, "display.c:66: ", 14)          = 14
write(2, "please report this bug", 22)  = 22
write(2, "\n", 1)                       = 1
rt_sigaction(SIGSEGV, {SIG_DFL, [SEGV], SA_RESTORER|SA_RESTART, 0x7f78f8e254b0}, {0x403220, ~[RTMIN RT_1], SA_RESTORER, 0x7f78f8e254b0}, 8) = 0
kill(16100, SIGSEGV)                    = 0
rt_sigreturn({mask=[]} <unfinished ...>
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_USER, si_pid=16100, si_uid=1000} ---
+++ killed by SIGSEGV (core dumped) +++
```

I can send the full output to secure@microsoft.com if needed. 

It seems the same error as #1649, but I'm not sure this is the same cause. 

Thanks.

**Comment by therealkenc** [comment]
#1649 (appreciate the ref) was deemed addressed so you're correct to open a new one. Thanks.

**Comment by therealkenc** [comment]
Pretty cool fail. That's the 16th of December in the year 5,845,542,510 (it's a Tuesday) best I can tell. About six billion years from now. Seems like a bug to me. I mean, the Sun will have exhausted all it's hydrogen by then. But I don't see why WSL shouldn't still run. Seem like a bug to me.

**Comment by atsaloli** [comment]
I am getting the same segfault:

```
atsaloli@Aleksey_X1_C2G:~$ sudo su -
root@Aleksey_X1_C2G:~# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Jun19 ?        00:00:00 /init ro
root         3     1  0 Jun19 tty1     00:00:00 /init ro
atsaloli     4     3  0 Jun19 tty1     00:00:00 -bash
atsaloli    31     4  0 Jun19 tty1     00:00:01 vim 29-May-2018.txt
root        32     1  0 Jun19 tty2     00:00:00 /init ro
atsaloli    33    32  0 Jun19 tty2     00:00:02 -bash
root       111     1  0 Jun25 tty3     00:00:00 /init ro
atsaloli   112   111  0 Jun25 tty3     00:00:00 -bash
atsaloli   126   112  0 Jun25 tty3     00:00:00 vim we
Signal 11 (SEGV) caught by ps (procps-ng version 3.3.10).
root       374     1  0ps:display.c:66: please report this bug
Segmentation fault (core dumped)
root@Aleksey_X1_C2G:~#
```

**Comment by ryancdotorg** [comment]
I'm also getting this - also seems to be caused a huge time value.

This popped up after suspending my system.

**Comment by benhillis** [comment]
@jstarks and I took a look at this yesterday and determined that our boot time calculation could overflow if your machine is running for a very long time.  Essentially what happens is our instance boot time overflows, so any relative calculations based off the boot time (like process creation time) will be way off.  Working on a fix for this now.

**Comment by mrallen1** [comment]
This hits me too.

**Comment by carlpett** [comment]
Apart from kubectl mentioned in #3399, it seems to also hit ssh (as I noticed that my inexplainable ssh troubles went away when I rebooted to get kubectl working...)

**Comment by benhillis** [comment]
Your hardware clock might have a higher frequency than the one I tested the fix on. Fix is making its way to insider builds.

**Comment by atsaloli** [comment]
Wonderful, thanks for finding and fixing the issue!

**Comment by benhillis** [comment]
Should be fixed in [17728](https://github.com/MicrosoftDocs/WSL/releases/tag/17728).

**Comment by atsaloli** [comment]
👍

**Comment by LordMonoxide** [comment]
Still experiencing this issue (SSH hanging) on build 17733.  Rebooting fixes (temporarily, I'm assuming).  I had an uptime of 4 days.

**Comment by benhillis** [comment]
@LordMonoxide - Another fix is inbound, #3434.

**Comment by mbarkhau** [comment]
I came here via: https://bugs.python.org/issue33965

So others can find this more quickly, this is the error message it started with:

```Fatal Python error: _Py_InitializeMainInterpreter: can't initialize time
OverflowError: timestamp too large to convert to C _PyTime_t
```

**Comment by cdonnellytx** [comment]
I came here via: https://github.com/Microsoft/WSL/issues/3529

So others can find this more quickly, this is the error message pwsh started with:

```
FailFast:
TimeSpan overflowed because the duration is too long.
```

And this is the message ruby has been giving, which is probably related as well:

```
/usr/lib/ruby/2.5.0/timeout.rb:86: [BUG] pthread_cond_timedwait: Invalid argument (EINVAL)
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```
