### ISSUE TITLE
Can't run binaries compressed with UPX

### ISSUE THREAD

**Issue by nomisbeme** [Microsoft/WSL#330]
Build 14332:

apt install upx-ucl
upx-ucl -8 /bin/ls -o ./lscompressed
./lscompressed
bash: ./lscompressed: cannot execute binary file: Exec format error

The call to execve fails, output from strace attached.
![screen shot 2016-05-06 at 5 59 38 pm](https://cloud.githubusercontent.com/assets/7146644/15089249/7328ea2e-13b4-11e6-9775-4acffcb58bc5.png)

**Comment by Arthur2e5** [comment]
// typo in title: s=UPC=UPX=g

This is what upx'ed programs look like in objdump:
```
objdump -x -f -h -p ./bash

./bash:     file format elf64-x86-64
./bash
architecture: i386:x86-64, flags 0x00000102:
EXEC_P, D_PAGED
start address 0x0000000000471eb0

Program Header:
    LOAD off    0x0000000000000000 vaddr 0x0000000000400000 paddr 0x0000000000400000 align 2**21
         filesz 0x00000000000726c4 memsz 0x00000000000726c4 flags r-x
    LOAD off    0x0000000000102878 vaddr 0x0000000000702878 paddr 0x0000000000702878 align 2**21
         filesz 0x0000000000000000 memsz 0x0000000000000000 flags rw-

Sections:
Idx Name          Size      VMA               LMA               File off  Algn
SYMBOL TABLE:
no symbols

```

**Comment by skochinsky** [comment]
why is this labeled "feature" and not "bug"? UPXed files are proper (if a little unusual) ELFs, they should at least start without issues. There are no errors in the file format.

**Comment by skochinsky** [comment]
@benhillis  @ionescu007 (sorry Alex :)
Can someone confirm if this is caused by the absence of `NT_GNU_ABI_TAG` note (hinted by #2121)? And please retag it as a bug, not feature. Such files run fine on regular Linux.

**Comment by benhillis** [comment]
A fix for this issue has been checked in and will be available in a Windows Insider build soon.

@skochinsky - The bug versus feature tags are somewhat arbitrary, don't get too caught up on them.

**Comment by ionescu007** [comment]
Great @benhillis, now you're training people that by CC'ing me, bugs get fixed instantly.

**Comment by nomisbeme** [comment]
I can confirm that this was fixed in Build 17017. Is there a definitive source to check when the fix landed before that? I'm curious if it made the Creators Update.

**Comment by Herst** [comment]
@nomisbeme It didn't, see <https://msdn.microsoft.com/en-us/commandline/wsl/release_notes>.

**Comment by nomisbeme** [comment]
Thanks for the response Herst. I really appreciate the link to the detailed release notes.

**Comment by sunilmut** [comment]
This should be fixed in the Insider build [17017](https://msdn.microsoft.com/en-us/commandline/wsl/release-notes#build-17017).

**Comment by essbedev** [comment]
I had issues installing [PVRTexToolCLI ](https://community.imgtec.com/developers/powervr/installers/) on previous builds and it's actually been resolved from Insider build 17017. I still get the same error when I try to install the [FBX SDK](http://images.autodesk.com/adsk/files/fbx20151_fbxsdk_linux.tar.gz) . I can't figure out if it's the same problem though.

**Comment by benhillis** [comment]
@essbedev - Might be hitting the same issue as #1884.  The fix for that should be available soon.

**Comment by essbedev** [comment]
@benhillis amazing ! thanks for the quick answer

**Comment by benhillis** [comment]
@essbedev - Downloaded the binary you attached and unfortunately it's not the same thing.  Your binary is 32 bit which is not currently supported by WSL (#2468).

**Comment by sayangel** [comment]
Was also just trying to set up the FBX SDK on WSL and hit this issue. @essbedev were you able to figure out an alternative?

**Comment by therealkenc** [comment]
@sayangel  Try 17093 or better per #1884. If your scenario still fails it would be worthy of a new ticket following CONTRIBUTING.md.

**Comment by essbedev** [comment]
@sayangel, I created a topic on the Autodesk FBX forum but never got an answer... https://forums.autodesk.com/t5/fbx-forum/compatibility-with-wsl-x64/m-p/7739197/highlight/true#M9178

**Comment by therealkenc** [comment]
Ahh understood; if they only provide 32-bit binaries that's #2468 which is unrelated to "this issue" (which is about [UPX](https://upx.github.io/)). There is no work-around unfortunately (unless you work at Autodesk). There's a User Voice [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/13377507-please-enable-wsl-to-run-32-bit-elf-binaries) for what it's worth.

**Comment by eflukx** [comment]
@sunilmut This issue was closed:

> This should be fixed in the Insider build [17017](https://msdn.microsoft.com/en-us/commandline/wsl/release-notes#build-17017).

But problem seems to persist; well into the newer Win10/WSL releases. Shouldn't this be reopened ?

**Comment by bashscr** [comment]
I am having problems on WSL1 with this at the moment. upx/upx#201
