### ISSUE TITLE
roofs / -> lxfs is caseinsensitive

### ISSUE THREAD

**Issue by echtwerner** [Microsoft/WSL#3461]
If I run apt update && apt upgrade I can not install libpam-runtime... cause the dep file contains a file PAM.7.gz and a symlink pam.7.gz -> PAM.7.gz.  

```
w10:~$apt update && apt upgrade 
...
...
Errors were encountered while processing:
 /var/cache/apt/archives/libpam-runtime_1.1.8-3.2ubuntu2.1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

```
w10:~$sudo dpkg -i /var/cache/apt/archives/libpam-runtime_1.1.8-3.2ubuntu2.1_all.deb
(Reading database ... 25476 files and directories currently installed.)
Preparing to unpack .../libpam-runtime_1.1.8-3.2ubuntu2.1_all.deb ...
Unpacking libpam-runtime (1.1.8-3.2ubuntu2.1) over (1.1.8-3.2ubuntu2) ...
dpkg: error processing archive /var/cache/apt/archives/libpam-runtime_1.1.8-3.2ubuntu2.1_all.deb (--install):
 error creating symbolic link './usr/share/man/man7/pam.7.gz': File exists
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libpam-runtime_1.1.8-3.2ubuntu2.1_all.deb
```

To reproduce the bug just use
```
w10:~$touch FOO && touch foo
touch: cannot touch 'foo': Input/output error 
```

I filled in a Issue on ubuntu already. But I think it was the wrong place to fix the bug. 
https://bugs.launchpad.net/ubuntu/+source/pam/+bug/1786821
They suggested to look at https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/ but I don't know if this applys to the rootfs at all.  Since it seems to be ext4 (simulated ? ) 

```
w10:~$ cat /etc/fstab
LABEL=cloudimg-rootfs   /        ext4   defaults        0
```

**Comment by echtwerner** [comment]
Update: 
Edition: Windows 10 Pro 
Version: 1703 
Build 15063.1206

Path of lxfs:  %USERPROFILE%\AppData\lxss\


fsutil.exe does not support caseSensitive commands.

**Comment by Voskrese** [comment]
https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/

**Comment by Seriell** [comment]
I can't reproduce this problem on Windows 10 Enterprise, Version 1803. Since you're running 1703 it's likely it's already been fixed in a future update.

![image](https://user-images.githubusercontent.com/14004943/44308939-6f363900-a3b6-11e8-84ac-48a782f5b17b.png)

**Comment by therealkenc** [comment]
> Since you're running 1703 it's likely it's already been fixed in a future update.

Nah. Yes 1703 (15063) is "old", but the simple scenario posed (`touch FOO && touch foo` in LxFS) was never broken in prior releases. If that were the case, "you'd know" and this issue would have been quickly duped to a well-known bug. Something else external is going on here but the OP doesn't disclose what. The mention of `"%USERPROFILE%\AppData\lxss\"` is a tip-off though. Speculating entirely, I am going to guess this is from [mucking around](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/) with the hidden directory.

Tagging need-repro, but the constructive path is to start over with an adulterated rootfs. Upgrading to the April 2018 Update is a good idea too on its own merits, but isn't _likely_ to "fix" anything here.

**Comment by echtwerner** [comment]
I didn't mucking around with the hidden directory. :-) I just found the dir while debbuging.
I made a clean install of wsl too and the problem still exists. 
* Uninstall Ubuntu (lxrun /uninstall /full)
* Reinstall Ubuntu
* touch FOO && touch foo does not work

Since I'm normaly a macOS and Linux user I don't know if there could be some Windows related issue. 
I will Uninstall Ubuntu and dis/enable WSL to check if it  will work. Maybe I whill also move hidden dir away to make sure it is a real clean install.

**Comment by therealkenc** [comment]
You did the Right Things™ (per your Edit:), so thanks for that. 

> I didn't mucking around with the hidden directory. :-)
> after enable of WSL and new install of ubuntu "touch FOO && touch foo" works

Believe you. But _something_ to do with the filesystem got borked along the way if "`touch FOO && touch foo`" went from not working to working after a wipe and reinstall. _How_ it got borked remains a mystery.

> libpam-runtime still has Problems when calling "apt update && apt upgrade"

Alright. That reduces us to taking [these guys](https://bugs.launchpad.net/ubuntu/+source/pam/+bug/1786821) at their word. Until proven otherwise anyway. You can try Windows 10 1803 (April Update) and install Ubuntu from the store (16.04 or 18.04 won't matter). Although, again, WSL has always had a case-sensitive LxFS filesystem (contrast DrvFS). That _won't_ explain why your `touch` scenario is okay now but you still can't install `libpam-runtime`. But it will disturb enough variables (like `lxrun` and much else) that you will probably find happiness.
