### ISSUE TITLE
WSL Bash does not start in the current working directory if it is on a network drive even though the drive is already mounted in WSL

### ISSUE THREAD

**Issue by AlisterH** [microsoft/WSL#3482]
* Your Windows build number:  

10.0.17134.228

* What you're doing and what's happening:  

I am trying to start WSL bash from particular working directories.  This works as expected from local drives, but not network drives (M in this simple demonstration), in which case it starts in my Linux home directory, even though the drive is mounted in WSL.

````
C:\>bash
obfuscated@obfuscated:/mnt/c$ exit
logout

C:\>f:

F:\>bash
obfuscated@obfuscated:/mnt/f$ exit
logout

F:\>M:

M:\>bash
obfuscated@obfuscated:~$  mount
rootfs on / type lxfs (rw,noatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noatime)
C: on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000)
F: on /mnt/f type drvfs (rw,noatime,uid=1000,gid=1000)
M: on /mnt/m type drvfs (rw,relatime)
````

* What's wrong / what should be happening instead:

Bash should start from the current working directory (as long as it is accessible in WSL i.e. mounted), even if this is in a network drive.

Or is there a simple workaround I'm missing?

**Comment by rolexdev** [comment]
It's happening the same for me too, my windows version: 1803 17134.228

I need it because using wsl in my Rider development, and projects exist on a network drive (the network is actually on the host system, as running in a virtual environment).
I have spent the last 2 days trying with no avail, explorer will not start bash in the correct directory.

**Comment by vogsphar** [comment]
same for me

**Comment by flowstatedev** [comment]
This is a problem for me too. The workaround I use is to:

- Copy the wslpath [script](https://github.com/laurent22/wslpath) to the path as wslpath2. (The native wslpath won't work in this case, because it fails on non-existent paths and it thinks that mounted/network paths are non-existent in some cases.)

- Invoke bash as follows:
`bash -c "cd `wslpath2 '%CD%'` && bash"`

(The second `bash` can be replaced with the name of script file you want to run.)

It's not pretty (or portable) but it works.

**Comment by flowstatedev** [comment]
Looks like this is fixed as of Version 1903 (OS Build 18362.116).

**Comment by berwynhoyt** [comment]
> Looks like this is fixed as of Version 1903 (OS Build 18362.116).
No, this has not been fixed. I'm running WSL2 on Windows 10 Pro version 2004 (OS build 19041.264) and it isn't fixed. WSL won't load in network or subst'ed paths even if they're already mounted.

**Comment by berwynhoyt** [comment]
Here is a slight improvement to the excellent workaround by @flowstatedev.

This one is a slightly uglier one-liner but doesn't require the new wslpath script. It uses build-in tr instead. Simply place the following in bash2.cmd:

- @bash -c "cd `echo /mnt/%CD:~0,1% | tr [:upper:] [:lower:]``echo '%CD:~2%' | tr \\\\\\\\ /` && bash %*"

**Comment by vhmvdn** [comment]
The following command fixed it for me. Most of the issues are always fixed by running an update.
`sudo apt update`
