### ISSUE TITLE
mmap on wsl is ignoring RLIMIT_AS?

### ISSUE THREAD

**Issue by KiYugadgeter** [microsoft/WSL#3505]
Windows10 1803 build:17134

I tried build golang from source.
But it has failed on ubuntu 18.04 on WSL.
This error is caused by wrong mmap behavior.

    --- FAIL: TestRlimitAs (0.00s)
    syscall_linux_test.go:180: Mmap: unexpectedly suceeded after setting RLIMIT_AS

mmap of WSL seems like does not respect RESOURCE_AS limitation.

**Comment by Biswa96** [comment]
Provide your code so that someone can reproduce your issue. Also add the FULL version number. Like 17134.xy.xyz.

**Comment by KiYugadgeter** [comment]
My Version is : Windows10 1803 build:17134.228

I have put code here:
https://gist.github.com/KiYugadgeter/a26aabcadb8fffa8fbdda2c75a44cd38

**Comment by therealkenc** [comment]
Fail is [here](https://github.com/golang/sys/blob/master/unix/syscall_linux_test.go#L180). Yes, please fill out [TEMPLATE.md](https://github.com/Microsoft/WSL/blob/master/ISSUE_TEMPLATE.md) (with special attention to the last sentence of the first paragraph). Most important being an `strace` capturing the `setrlimit()` and `mmap()` bits for that part of `syscall_linux_test.go`.

But in this instance, this is essentially dupe #2526. The `strace` log is almost certainly going to show `setrlimit()` and `mmap()` succeeding because (we can reasonably assume) `RLIMIT_AS` is stubbed. So, it will boil down to stating the use case, namely identifying the "killer golang applications with widespread adoption" that a stubbed `RLIMIT_AS` is blocking.

Snippet of test golang test code at issue:

```
	// RLIMIT_AS was set to the page size, so mmap()'ing twice the page size
	// should fail. See 'man 2 getrlimit'.
	_, err = unix.Mmap(-1, 0, 2*unix.Getpagesize(), unix.PROT_NONE, unix.MAP_ANON|unix.MAP_PRIVATE)
	if err == nil {
		t.Fatal("Mmap: unexpectedly suceeded after setting RLIMIT_AS")
	}
```

**Comment by KiYugadgeter** [comment]
I
I have tried strace some times but it does not done despite I waited several hours.

**Comment by KiYugadgeter** [comment]
This bug is fixed on beta?

**Comment by gnaggnoyil** [comment]
Can confirm `setrlimit(RLIMIT_AS)` still fails silently on WSL1 environment, different with read linux environment even if the linux distribution are the same. I'm using WSL1 on Windows 10 22H2 19045.2251.

https://gist.github.com/gnaggnoyil/cda2ff5748beab3c519467eba66d80da
