### ISSUE TITLE
Default umask (permissions) is not applied

### ISSUE THREAD

**Issue by simonbuchan** [microsoft/WSL#352]
Reference: http://www.cyberciti.biz/tips/understanding-linux-unix-umask-value-usage.html

My current install has this in `/etc/profile`:

```
# The default umask is now handled by pam_umask.
# See pam_umask(8) and /etc/login.defs.
```

And, indeed `/etc/profile` has `UMASK>  >       022`, but:

```
simon@QOF:~$ umask
0000
```

The effect of this is that new files are created with 666 and dirs with 777 permissions:

```
simon@QOF:~$ touch file
simon@QOF:~$ mkdir dir
simon@QOF:~$ ll -d file dir
drwxrwxrwx 2 simon simon 0 May 12 22:54 dir/
-rw-rw-rw- 1 simon simon 0 May 12 22:54 file
```

This mostly isn't a real problem since UoW doesn't have to care about multiple users, it largely shows up as ls showing dirs with an ugly green background, but it could freak out some tools, similar to `ssh` wanting `600` on your private keys.

Simplest fix would probably be to dump a `umask 022` in `/etc/profile`, but it seems there's a bunch of stuff in that `/etc/login.defs`

Easy workaound is to add a `umask` to your `~/.bashrc`

**Comment by simonbuchan** [comment]
May be somewhat related to #167 , `/etc/profile` is supposed to be read if bash is a login shell - but even `bash.exe --login` doesn't seem to use `pam_umask`

**Comment by benhillis** [comment]
@simonbuchan Thanks for reporting this.  I think there are a couple things going on here.  I verified that when bash.exe --login is launched /bin/bash does read from /etc/profile.  I dumped my default /etc/profile and noticed a comment that:

```
# The default umask is now handled by pam_umask.
# See pam_umask(8) and /etc/login.defs.
```

When you run "bash.exe --login" that translates into "/bin/bash --login". We don't run the /bin/login binary and I'm assuming that's what normally sets up pam_umask.  Did you try adding a new umask to value to your /etc/profile?  It should work (when using bash.exe --login).

**Comment by simonbuchan** [comment]
Yep, `umask` in both `/etc/profile` and `~/.profile` run with both `bash.exe --login` and `bash -c "bash --login"`.
Interestingly, if I revert the `umask` command and do `bash.exe -c "sudo login"` then `umask` is `0002` - no idea where that is coming from!

**Comment by 0xMF** [comment]
Please ensure umask is never 0000 no matter how bash is started. 

I understand users can set umask to saner defaults in their own bashrc files but it means whatever directories and files auto-installed by scripts after WSL setup and user first bash run till the bad umask was discovered now have to be changed to sane defaults. This is exacerbated in git-based repos because git will track the change of perms to saner defaults as a (needless) change thereby status of git repo becomes dirty which simply put is both: confusing and annoying.

**Comment by simonbuchan** [comment]
@0xMF don't worry, git only tracks +x, and the .bashrc changes are mentioned as a workaround

**Comment by neurogenesis** [comment]
This also causes problems for things like dropbox, zsh (compinit/compaudit), or any tool that does basic checking for other write/read permissions.

I think supporting login will fix a lot of user issues, but likely requires implementing more subsystems which aren't available yet.

Looks like lack of vmsatat is also causing problems for tools like dropbox for linux. I only mention it here because of related file permission issues when trying to symlink across the linux/windows boundary (bad idea in general).

**Comment by zhangxj5** [comment]
Hello, It's very strange. If I run ./configure, I found that the Makefile in the dir and sub dir only has permission rw no x. So some middle product didn't output, ./configure is right, but can't do make.

It's a big problem.

**Comment by zhangxj5** [comment]
/usr/bin/m4: m4_esyscmd subprocess failed: Operation not permitted
/usr/bin/m4:configure.ac:489: cannot run command `./scripts/version.sh': Operation not permitted

**Comment by lilred** [comment]
I have put this in my `~/.profile` in the meantime:

```
# Note: Bash on Windows does not currently apply umask properly.
if [ "$(umask)" = "0000" ]; then
>   umask 022
fi
```

@benhillis: if you have time to entertain my curiosity - is there a particular reason you don't run /bin/login?

**Comment by benhillis** [comment]
@lilred - good question. Historically there have been a couple of reasons. When we first released /bin/bash worked but other shells (zsh for example) didn't work very well and we didn't want users to set their default shell to something that didn't work and get into a bad state.  There's also potential strangeness around running bash.exe and zsh being launched.

That being said, running login would actually make a lot of things simpler for us.  Currently our init daemon has to do many of the things that /bin/login normally does.  We're doing some design for the next release of Windows and I'll take a look at this and see if it would make sense to potentially switch things over now.

If you'd like to play around with using login there's a way you can use it now.

lxrun.exe /setdefaultuser root
bash.exe -c "/bin/login -f username"

**Comment by lilred** [comment]
This is fantastic, thanks for the insight. I will change my Bash shortcut to this and report back if I hit any issues.

**Comment by simonbuchan** [comment]
With `/bin/login` I do get `umask` returning `002`, which is probably "good enough" to close this, but it's still not getting the "correct" default value `022` from `/etc/login.defs` line `151`, which may be a thing.

Also it seems to start faster?!

**Comment by simonbuchan** [comment]
One thing to be aware of is it doesn't extend PATH with the windows path.

**Comment by simonbuchan** [comment]
@jackchammons Does closing this mean the default setup will now set a `umask`? `/bin/login` is not a default setup.

**Comment by jackchammons** [comment]
The current behavior is expected. We will be reevaluating where umask gets set in an future release.

**Comment by hughbe** [comment]
This is breaking unit tests for `swift-llbuild`, part of the Swift.org project:

> $ umask 22
> $ umask
>    0022
> $ mkdir foo
> $ ls -l
>  drwxrwxrwx 2 root root 0 Mar 23 16:47 foo

**Comment by nesl247** [comment]
Why was this closed? Until the umask is probably working out of the box, this issue is still ongoing.

**Comment by therealkenc** [comment]
Cleaning up issues, and this one is in a weird undead state. Jack marked it as by-design and Sunil re-opened it. It can't be both. There are three paths forward I can see here:

(1) Deem the default umask of `0000` intended behaviour by fiat and this issue can be closed.

(2) Make WSL's reimagination of `sshd` (interop) go through login like Ben [mused](https://github.com/Microsoft/WSL/issues/352#issuecomment-264217088). There is a work-around for this right now: `wsl.exe sudo /bin/login -f me`. You'll get a `umask` of `0002` by default, which is linux-behavior (if you `ssh localhost` on Real Linux you get the same umask by default).

(3) Lite version of (2), set the umask to `0002` or `0022` unilaterally in WSL `init`, and deem that intended behaviour by fiat.

This isn't really a `discussion` thread. It's either a feature request for (2) or (3), or should be closed as (1).

**Comment by simonbuchan** [comment]
There's also the umask DriveFS interop that got added recently - does that have implications here?

**Comment by therealkenc** [comment]
> There's also the umask DriveFS interop that got added recently - does that have implications here?

Not really. That improvement is about _respecting_ umask on DrvFS. Which it now will, if you set your umask to something other than `0000` and mount your DrvFS with `-o metadata`. By way of analogy, the default umask is "correct" on Real Linux, but **won't** be _respected_ on ntfs-3g or FAT32 or SMB because they don't "do" POSIX perms (notwithstanding various extensions).

**Comment by simonbuchan** [comment]
I saw that it let you set a default umask too? Maybe default that to whatever this does?

**Comment by jean** [comment]
I really can't see this being a "feature" 😟

**Comment by simonbuchan** [comment]
I'm happy with anything from https://github.com/Microsoft/WSL/issues/352#issuecomment-376021319 (well, not *happy* with by design, but I get it)

The feature would be either implementing this one thing that real `init` does in some way, or switch to using real `init` somehow.

**Comment by sjackman** [comment]
This issue is causing trouble when running the Linuxbrew/Homebrew package manager in WSL. I'd love to see the default umask set to `002`.

**Comment by 27Bslash6** [comment]
This is still a thing? Is 3 years not long enough to arrive at a conclusion to this issue?

**Comment by benhillis** [comment]
Thanks for your patience.  I'm adding a default umask of 022, with an /etc/wsl.conf setting to override it:

```
[filesystem]
umask = 02
```

**Comment by simonbuchan** [comment]
Woo! My ls will finally be cured of it's horrifying green miasma!

**Comment by radusuciu** [comment]
Had a nice surprise today when I built a static site using Hugo in WSL from `/mnt/d/` and saw that my published site had 777 permissions..

None of the workarounds mentioned here seem to have any effect. While it's possible to set `umask` to 022, everything is still created as 777 and worse, is immune to chmod!

**Comment by dgw** [comment]
@radusuciu You probably won't ever be able to `chmod` stuff in `/mnt/` drives. The permission models are completely different between Linux and Windows filesystems, so everything just appears as 777.

**Comment by therealkenc** [comment]
> You probably won't ever be able to chmod stuff in /mnt/ drives

You been able to do that since [17063](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17063) circa Christmas of 2017.

![image](https://user-images.githubusercontent.com/7049700/67610680-337cc900-f749-11e9-8d67-bf8040181ac0.png)

**Comment by dgw** [comment]
And the permissions stick? I'll have to play with that.

**Comment by therealkenc** [comment]
Ben's `login(1)` [musing](https://github.com/microsoft/WSL/issues/352#issuecomment-264217088) can fight another day a new issue/ask for `wsl.exe --login` or somesuch. This one deemed fixinbound [last June](https://github.com/microsoft/WSL/issues/352#issuecomment-506538247) with the `umask` configurable in `wsl.conf`. Applicable in both WSL1 and WSL2.

**Comment by mohd-akram** [comment]
I just updated to 1909 and this problem is still there.

**Comment by Ifiht** [comment]
![image](https://user-images.githubusercontent.com/6366639/73945715-cc54e000-4905-11ea-8460-3c5b1b7ce645.png)
Confirming that with 1909 and a fresh install of Ubuntu. 000 is still the default umask.

**Comment by Twanislas** [comment]
[This](https://github.com/Twanislas/dotfiles/blob/master/.shell/os_wsl.sh#L12) is how I workaround it in my dotfiles, if it helps anyone ;)

**Comment by therealkenc** [comment]
> I just updated to 1909 and this problem is still there.

Right; it looks like Ben's fix shipped in [18945](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18945). 18945 > 18363 (aka 1909 aha 19H2). Which is to say, it appears a number of issues that were addressed in spring/summer 2019 never made it into the November 2019 Windows 10 release. [Or, at least on best evidence.] I'll bounce the tag on this one, but to be honest I'm hoping the fine-grained fixed-in tags die this spring in favour of whatever version is cited in the issue (presupposing they're cited). Here, 18945.

**Comment by shinebayar-g** [comment]
Thanks to WSL. All my directories are 777.

**Comment by Alex6357** [comment]
It seems that pam modules are (partly) still not functioning. MOTD is not correctly shown. #1966
