### ISSUE TITLE
WSL won't start after Windows Update 18950

### ISSUE THREAD

**Issue by kodeclan** [microsoft/WSL#4371]
* Your Windows build number: Microsoft Windows [Version 10.0.18950.1000]

* What you're doing and what's happening:
- I try to start WSL2 via `wsl ~ -d DistroName`
- I get `A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`
- I shutdown WSL using `wsl --shutdown`
- I try to start the distro again using `wsl ~ -d DistroName`
- I still get `A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`
- I shutdown WSL again
- I install a fresh copy via `wsl --import DistroName2 <install-location> <rootfs.tar.gz> --version 2`
- I try to start WSL in the new install via `wsl -d DistroName2`
- Again, I get `A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

This happened after Windows Updated to 18950, (from 18945)

Also, the processes `vmwp.exe` and `vmmem` show up in the task manager and do not go away till `wsl --shutdown` is executed.

* What's wrong / what should be happening instead: WSL console should appear.

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

[wsl-logs.zip](https://github.com/microsoft/WSL/files/3462089/wsl-logs.zip)

**Comment by xtremeperf** [comment]
Same here.  My default WSL2 instance and sole WSL1 instance both work fine, but the other WSL2 instances have this problem and I haven't found a cause yet.  It doesn't seem to be related to networking config or the new .wslconfig file.  I may try rolling back to 18945.

**Comment by xtremeperf** [comment]
Alright, looks like we may have a bug in init...
here's the messages from the kernel ring buffer (using my one working WSL2 instance to check messages created when trying to launch a non-working instance):

init: (1) ERROR: UtilMkdir:1035: chmod(/bin, 40755) failed 2
init: (1) ERROR: ConfigInitializeEntry:903: Failed to create /bin 2

![Win10-18950_WSL2_UtilMkdir-failed](https://user-images.githubusercontent.com/28700174/62405800-b5ed5680-b567-11e9-90f1-997127f47a7b.jpg)

**Comment by xtremeperf** [comment]
Alright, I just figured this one out...
init fails to create "/bin" because it already exists, as a sym-link to "/usr/bin" !!!

So this issue only occurs with a rootfs that is /usr-merged... which includes Kali-linux in the Microsoft Store.  Not really sure why init is trying to create a /bin directory anyways?!?

**Comment by benhillis** [comment]
This has been fixed and will be in an Insider build soon.

**Comment by kodeclan** [comment]
Glad to know I'm not the only one having this issue. I've reverted to Windows 18945 for the time being.

**Comment by jugg3rn4ut** [comment]
Hi, any idea when the Insider build will be released please ?

**Comment by mscraigloewen** [comment]
The time from us checking in the bug fix to the change being available inside of an Insiders build can vary, and is dependent on many different factors. In general, it's around 3 to 6 weeks.

**Comment by jugg3rn4ut** [comment]
Hi @mscraigloewen, thanks for the answer. Keep up the good :)

**Comment by Chakratos** [comment]
> Glad to know I'm not the only one having this issue. I've reverted to Windows 18945 for the time being.

Could you tell me how you downgraded? Can't wait the 3-6 Weeks and would love to use WSL2 :)

**Comment by RedBeard0531** [comment]
Now that the problem has been identified, is it possible to share a workaround. This build is completely unusable with this. I've downgraded, but Windows update keeps trying to reupgrade me. I was hoping that it would get fixed in this week's patch, but since it sounds like that won't be happening, do you have any suggestions?

**Comment by buwailee** [comment]
Same here on build 18956.

**Comment by jdamian** [comment]
It is possible to convert it to wsl 1 to keep it running

**Comment by Uberck** [comment]
"This has been fixed and will be in an Insider build soon."
As of 18956.1000 which I just installed, this is still not fixed...
![edition](https://user-images.githubusercontent.com/12820409/62722655-f2440b00-b9dc-11e9-9965-07c4eba04c84.JPG)
![error](https://user-images.githubusercontent.com/12820409/62722656-f4a66500-b9dc-11e9-8b07-c05a2f19fd19.JPG)

**Comment by Biswa96** [comment]
@Uberck From the screenshot, it looks like your distribution is installed, am I right? If yes, then you can create a user by loggin in as root with `wsl.exe --distribution Ubuntu --user root` and then create the user with `useradd Uberck`. Change the distribution name as you need.

**Comment by Biswa96** [comment]
@Uberck From the screenshot, it looks like your distribution is installed, am I right? If yes, then you can create a user by loggin in as root with `wsl.exe --distribution Ubuntu --user root` and then create the user with `useradd Uberck`. Change the distribution name as you need.

**Comment by cerebrate** [comment]
I'm also getting this now on 18956.

Oh, for a functioning workaround.

**Comment by amechoul** [comment]
Hi!
Also running 18956.
For it seems that problem is only with Kali distribution.
My original kali didn't start.
Exported and imported but same issue.
Install a fresh Ubuntu and runs without problems.
Intall a fresh kali and also didn't start.

**Comment by Uberck** [comment]
Biswa yes it is installed, the only time I experience this issue is with the WSL2 Kali distribution.

**Comment by XLWZ** [comment]
I run a Arch distribution on 18956, also caught bugs
This bug is not yet fixing

**Comment by benhillis** [comment]
I would suggest rolling back to the previous build until an Insider Fast build with the fix is released.

**Comment by AjawadMahmoud** [comment]
@benhillis, For those who aren't in a hurry. When is the next build going to be available? Since this is a serious bug for many, could this be elaborated for faster release for next build, even if it's a bugfix for this WSL issue?

**Comment by y103kim** [comment]
I'm also getting this on 18956 with Arch LInux.
Only Ubuntu 18.04 is working correctly

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\illne> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Running         2
```

**Comment by Redd-2097** [comment]
Hi all, whats the latest on this, please? I have VS code insiders and win10 build 18950, both updated today, but still no action on the `code .` front

**Comment by chadrien** [comment]
Workaround that ended up working for me with arch and fedoraremix:

* convert back to wsl1: `wsl --set-version $distroname 1`
* `wsl -d $distroname -u root`
* in the distro:
  * `cd /`
  * `ls -Alh`: check if `/bin` and/or `/sbin` are symlinks to `/usr/bin`
  * remove the symlinks `rm bin sbin`
* convert to wsl2: `wsl --set-version $distroname 2`
* `wsl -d $distroname -u root -e /usr/bin/bash`
* in the distro:
  * `cd /`
  * `mv bin/wslpath usr/bin/`
  * `mv sbin/mount.drvfs usr/bin/`
  * `rmdir bin sbin`
  * `ln -s usr/bin bin`
  * `ln -s usr/bin sbin`

**Comment by kzmuhia** [comment]
Not resolved for me I am already on 18956 and get the same error using Fedoraremix

**Comment by chadrien** [comment]
Workaround that ended up working for me (used at your own risk, but no issues so far):

* start from a wsl 1 container (change version if needed with `wsl --set-version $yourdistro 1`)
* `wsl -d $yourdistro -u root`|
* from inside the distro:
  * `cd /`
  * `ls -Alh`: take a look at `bin` and `sbin`
  * if `bin` is a symlink, remove it `rm bin`. Same for `sbin`
* get out of the distro and convert it to v2 (`wsl --set-version $yourdistro 2`)
* `wsl -d $yourdistro -u root -e /usr/bin/bash`
* from inside the distro:
  * `cd /`
  * if `/bin` was a symlink:
    * `mv bin/wslpath usr/bin/`
    * `rmdir bin`
    * `mv usr/bin bin`
     * `ln -s /bin usr/bin`
  * if `/sbin` was a symlink:
    * `mv sbin/mount.drvfs usr/sbin/`
    * `rmdir sbin`
    * `mv usr/sbin sbin`
     * `ln -s /sbin usr/sbin`
* get out of the distro
* make sure it works:
  * `wsl -t $yourdistro`
  * `wsl -d $yourdistro`: hopefully this should work
  * get out of the distro and run `wsl -l -v` and make sure the version is indeed 2 for your distro
  * open `explorer.exe` and go to `\\wsl$` to make sure the network mount point is there

Hope this will be useful to others :)

**Comment by chenong** [comment]
> Workaround that ended up working for me (used at your own risk, but no issues so far):
> 
> * start from a wsl 1 container (change version if needed with `wsl --set-version $yourdistro 1`)
> * `wsl -d $yourdistro -u root`
> * from inside the distro:
>   
>   * `cd /`
>   * `ls -Alh`: take a look at `bin` and `sbin`
>   * if `bin` is a symlink, remove it: `rm bin`. Same for `sbin`
> * get out of the distro and convert it to v2 (`wsl --set-version $yourdistro 2`)
> * `wsl -d $yourdistro -u root -e /usr/bin/bash`
> * from inside the distro:
>   
>   * `cd /`
>   * if `/bin` was a symlink:
>     
>     * `mv bin/wslpath usr/bin/`
>     * `rmdir bin`
>     * `mv usr/bin bin`
>     * `ln -s /bin usr/bin`
>   * if `/sbin` was a symlink:
>     
>     * `mv sbin/mount.drvfs usr/sbin/`
>     * `rmdir sbin`
>     * `mv usr/sbin sbin`
>     * `ln -s /sbin usr/sbin`
> * get out of the distro
> * make sure it works:
>   
>   * `wsl -t $yourdistro`
>   * `wsl -d $yourdistro`: hopefully this should work
>   * get out of the distro, run `wsl -l -v` and make sure the version is indeed 2 for your distro
>   * open `explorer.exe` and go to `\\wsl$` to make sure the network mount point is there
> 
> Hope this will be useful to others :)

this work good for me，thanks

**Comment by chenong** [comment]
@chadrien thanks, this work good for me.

**Comment by citruspress** [comment]
@chadrien Thanks! Working fine for me as well.

But I believe you may have this backwards: ln -s /bin usr/bin

It's ln [OPTION]... [-T] TARGET LINK_NAME.

Or maybe it was intentional so that swapping back and forth between v1 and v2 would work? Either way on arch I had to create it as it was originally like 'ln -s usr/bin /bin' otherwise I got some error when I tried to install packages using pacman.

**Comment by chadrien** [comment]
@citruspress it was intentional. I had to make `/bin` the actual directory and `/usr/bin` the symlink, otherwise if the wsl container is shut down, then I'd get the error reported here again. The only persistent fix I found was to swap `/bin` and `/usr/bin`

**Comment by citruspress** [comment]
@chadrien I see. I haven't noticed, I assume it hasn't shut down yet. Thanks again!

**Comment by Uberck** [comment]
@chadrien - Yes the fix works, but it has left my Kali-Linux distribution stuck with root user.

The screenshot I attached is where the installation process halted, so I'm not sure if the distro ever successfully fully installed...

Mind you, I am able to launch the distribution fine using _wsl -d kali-linux_, and it appears to be running find (at least initially by running "help" 

Just wondering if this looks ok to the rest of you (distro running in root by default)

![kali-root-mode](https://user-images.githubusercontent.com/12820409/63060606-b7e8db00-bec0-11e9-8d6b-1a4b7da0aef1.JPG)

**Comment by Uberck** [comment]
Going along with my last question, I've created a new user with sudo privileges in the Kali distro, but am unable to figure out how to set the default user as my newly creater user (I don't want to be running as _root_ everyime I start the distro). How do I force WSL Kali to use a user other than root when launching with **chadrien's** fix?

**Comment by onomatopellan** [comment]
@Uberck `wsl -d kali-linux -u $username`

**Comment by craigloewen-msft** [comment]
@Uberck we are tracking the issue of changing the default user from root after importing a WSL distro here: https://github.com/microsoft/WSL/issues/3974

**Comment by Uberck** [comment]
Thanks Craig and onomatopellan

@ Onomatopellan: I've incorporated that command into the profiles.json settings file for Windows terminal at _"commandline" : "wsl.exe -d kali-linux -u myusername"_ under Kali settings, so this workaround is working nicely for now.

Craig: Thanks but I actually installed the distro from the Windows store, not the command line

**Comment by Uberck** [comment]
Suspiscions were right, its just a workaround for now...

Metasploit is brokem :(

uberck@CPPCStation:/mnt/c/Users/Chris$ msfconsole
[-] ***rting the Metasploit Framework console...\
[-] * WARNING: No database support: No database YAML file
[-] ***                     

uberck@CPPCStation:/mnt/c/Users/Chris$ sudo /usr/bin/msfdb start                                                                                                                                                                                                       System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
[+] Starting database                                                                                                                                                                                                                                                  System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

**Comment by onomatopellan** [comment]
@Uberck If you need Systemd as PID 1 there are workarounds like https://github.com/arkane-systems/genie or https://github.com/shayne/wsl2-hacks/blob/master/README.md

**Comment by Biswa96** [comment]
Just wondering, if you do want to use Kali Linux distribution for penetration testing why not just use a real Kali installation?

**Comment by craigloewen-msft** [comment]
@Uberck if you've installed it from the store you can run the command:
`kali.exe config --default-user $yourUserName` 
Just make sure to replace the $yourUserName value and you should be able to set a default user.

**Comment by Biswa96** [comment]
Same issue in 18956. Reverting back to 18945 works.

**Comment by Biswa96** [comment]
Same issue in 18956. Reverting back to 18945 works. Why WSL always crash whenever there is/was a big change in LxssManager!

**Comment by navigaid** [comment]
Still not fixed in 18963. I'm going to revert back to 18945.

**Comment by GoodbyeNJN** [comment]
@chadrien It works fine in 18963. Thanks a lot!

**Comment by XLWZ** [comment]
Still not fixed in 18965

**Comment by anaisbetts** [comment]
Is there a way to get any visibility as to what the WSL VM is doing? When errors like this happen you can't get any visibility, you just see the equivalent of "It didn't work /shrug"

**Comment by oscarbg** [comment]
seems they finally fixed on 18970, right?
someone to confirm..
thanks..

**Comment by libredot** [comment]
Finally fixed in 18970

**Comment by whoamikyo** [comment]
still not fixed for me on 18970

![](https://i.imgur.com/XwsgjsD.png)

**Comment by Biswa96** [comment]
Reinstall Windows, if possible.

**Comment by lengthmin** [comment]
Can confirm fixed in 18970.

**Comment by merkuriy** [comment]
I had version 18965.1000, and [the method](https://github.com/microsoft/WSL/issues/4371#issuecomment-521107556) suggested by @chadrien worked fine for me.
Later I will try to work without manual fixes on version 18970.

**Comment by anaisbetts** [comment]
Fixed as well for me with Arch Linux on 18970

**Comment by kodeclan** [comment]
Tested on 18970, this seems to have been fixed.

**Comment by rdcoe** [comment]
Not fixed on 18980.  I tried reverting to WSL 1 per @chadrien and the conversion completed succesfully.  However on launching:

$ wsl -d Ubuntu-18.04 -u root
mesg: ttyname failed: Inappropriate ioctl for device

**Comment by MostHated** [comment]
Hello, I am having this issue. 

![](https://i.imgur.com/jjX4Agm.png)

**Comment by onomatopellan** [comment]
@MostHated That looks like https://github.com/microsoft/WSL/issues/4105#issuecomment-531525516

**Comment by lukebakken** [comment]
I just updated to `19555.1001` and am getting this with a WSL 2 Debian 10 installation:

```
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

Prior to the update the WSL 2 environment worked fine. I have tried the suggestions in this issue to no effect.

**Comment by w9jds** [comment]
It looks like this issue is back in 19555 released today. I have opened a feedback ticket with some telemetry if you need it here: https://aka.ms/AA75u9m

Two releases ago localhost didn't work, the previous release fixed that and seemed to work just fine.

**Comment by xtremeperf** [comment]
Same here... 19555 broke WSL2.  However, I don't believe it's the same issue as before... where /usr-merged distros failed to create /bin due to existing sym-link.  Even non-/usr-merged distros fail to connect with WSL2, and therefore I haven't found a way inside to even check the kernel ring buffer messages.

**Comment by benhillis** [comment]
Yes this is a new issue, please start a new GitHub thread.
