### ISSUE TITLE
ls: cannot access '/mnt/c': Input/output error

### ISSUE THREAD

**Issue by scrossan-crown** [microsoft/WSL#4377]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt) Microsoft Windows [Version 10.0.18950.1000]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.) 
Trying to access /mnt/c/ from inside WSL 2

* What's wrong / what should be happening instead: 
Should be able to list files and dirs from /mnt/c/

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

https://gist.github.com/scrossan-crown/827948cabed828a2e040e62fc816d181

**Comment by Biswa96** [comment]
That error occurs if the hidden `wslhost.exe` process is died/killed. Just use `wsl.exe --shutdown` and restart it.

**Comment by tuananh** [comment]
> That error occurs if the hidden `wslhost.exe` process is died/killed. Just use `wsl.exe --shutdown` and restart it.

this fixes it for me

**Comment by Silic0nS0ldier** [comment]
Hit this error myself, proposed work around fixes the problem. Issue itself is recurring, no discernible pattern as of yet. I've got the Docker for Windows tech preview if that is of any relevance.

**Comment by mariusstrom** [comment]
I'm hitting this on 18956 - the pattern seems to be doing significant file I/O on the mounted NTFS+BitLockered filesystem. (for example, I've got a directory with a few thousand files on it. I can reliably repro this by grep'ing across the files)

**Comment by craigloewen-msft** [comment]
@mariusstrom can you share your reliable repro steps so we can dig into this? :)

**Comment by mariusstrom** [comment]
> @mariusstrom can you share your reliable repro steps so we can dig into this? :)

@craigloewen-msft here's what I've got. It repros not 100% of the time, but probably about 80% of the time. Not sure if all of the below is useful or red herrings, but here's all the relevant info I can think of.

I've got a OneDrive for Business folder with ~7k files in them, half JPG files and half JSON files. The OD4B is offline sync'd to a NTFS volume that is BitLocker'd (stock Surface Go setup). About half the files are sync'd locally and the other half are offline file pointers.

I'll jump into WSL2 (Ubuntu 18.04LTS) and try to do things like grep operations over the files that are sync'd locally, but even some things such as `ls -l` ops in the directory cause the operation to fail and the I/O error on anything under /mnt/c.

I'm on vacation right now, back in Redmond in a few weeks, but I'll be online periodically if there's debug info you want me to snag.

**Comment by martinothamar** [comment]
I'm using Terraform on Ubuntu WSL 2 with Windows build 18970 and this is happening all the time. Terraform is installed in Ubuntu but I have my git repos under /mnt/c so that's where I run plan/apply etc which really triggers this bug.

**Comment by benhillis** [comment]
We are working on fixing this but have had a hard time getting a local repro. If anybody has some ideas on how to trigger this please let us know.

**Comment by mariusstrom** [comment]
@benhillis when I run into a repro, mind if I ping you directly on teams when I have it going on?

**Comment by Biswa96** [comment]
> how to trigger this please let us know.

@benhillis Do you want to reproduce that error with well-known programs? I have reproduce the error by making a mistake in my program. And strace shows `EIO` with `stat(2)` and `chdir(2)`.

**Comment by dxhisboy** [comment]
> > how to trigger this please let us know.
> 
> @benhillis Do you want to reproduce that error with well-known programs? I have reproduce the error by making a mistake in my program. And strace shows `EIO` with `stat(2)` and `chdir(2)`.

Is the bug in hvpty-backend? I'm using your code and also meet Input/Output Error several times.

**Comment by Biswa96** [comment]
@dxhisboy Absolutely.

**Comment by Biswa96** [comment]
@dxhisboy Absolutely. But it's off-topic here.

**Comment by Vigasaurus** [comment]
I've been able to reproduce it pretty consistently - primarily by stopping a rather large directory operation after ~30-45 seconds (may vary based on disk speed/size). The following screenshot is after a clean restart of WSL with `wsl --shutdown` and `wsl -d Ubuntu`.

![image](https://user-images.githubusercontent.com/19434157/64485171-ab675200-d1e2-11e9-9fe6-8a47ea931bf6.png)
In this specific instance, I loaded into WSL and ran `du -h --max-depth=1` on a folder with 91 directories, and a total size of about 150GB - and after about 35 seconds of the command running I stopped it with `Ctrl+C`. 

This immediately resulted in any subsequent filesystem action on `/mnt/c` giving the Input/Output Error. I'm sure this would work with any intensive enough/long running enough command.
 I hope that helps y'all get some repro on this - and please lmk if you need anything else from me 😀

 ```Windows Version: 10.0.18963.1000```
```Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

**Comment by benhillis** [comment]
Some good news: @SvenGroot has identified the issue and is working on a fix.

**Comment by Biswa96** [comment]
Can you share any details about the issue, cause & remedy?

**Comment by Vigasaurus** [comment]
@Biswa96 see my comment above. The only solution is to `wsl --shutdown` and restart WSL.

**Comment by Biswa96** [comment]
I mean why the issue occurs and what SevenGroot found as a solution.

**Comment by benhillis** [comment]
@Biswa96 - bug in 9p server around cancellations (you could argue the bug is in the Linux 9p client but we'll fix our server implementation).

**Comment by SvenGroot** [comment]
Essentially, when an operation is interrupted by a signal (e.g. CTRL-C), the 9p client in the Linux kernel will send a "flush" message to cancel the pending request. Our server did not support cancellation, so it would return an error in response to the cancellation attempt.

It turns out the Linux client ignores the response from flush, and assumes that the request has been cancelled as soon as it receives such a response (regardless of whether it's success or error). Since we didn't actually cancel the message, we will still send the real response. When the Linux client receives this response, it thinks it's an invalid message and disconnects from the server, and will return EIO to all requests after that.

This wouldn't always happen, since if the real response came before the "flush" response, there's no issue.

One could argue that the Linux client is wrong to consider a request cancelled if the "flush" message returned an error. However, as Ben said, we'll fix this by handling "flush" correctly in our server.

Since the server is fine and it's only the client that's disconnected, you can actually recover from this without restarting WSL, by just unmounting (`sudo umount /mnt/c`) and remounting (`sudo mount C:\\ `/mnt/c`; adjust for the appropriate drive letter as needed), but you'd have to make sure that you match the right mount options too (especially the automatically added ones, such as the default owner uid and gid).

**Comment by Joe-Pena** [comment]
I've got an issue which seems from reading this seems to stem from the same the same thing.
If it's of any help, I've got Docker Technical Preview installed.

`Windows Version: 1903, OS Build: 18980.1`

`Ubuntu 18.04 WSL2`

Steps to reproduce:

1. Start with a shutdown pc. Turn it on.
2. Once signed in, open up Windows Terminal(Preview)
3. Open an Ubuntu tab.
4. Try running any windows command, such as `code` or `explorer.exe`
5. Terminal will output `command not found`

To resolve the issue:

1. Close the Ubuntu session, open a new powershell session and run the command `wsl --shutdown`
2. Open up Ubuntu again, run the command `code`, it should work as expected, by opening vscode in windows, connected to WSL2 Ubuntu.

OR

Simply restart pc. After opening up Ubuntu, `code`, `explorer.exe`, and other commands will work as usual. However, after a restart, any transparency effects (Such as the Windows Terminal's Acrylic background and the start menu color, will be shut off, with no way of turning them back on again. But I doubt this has to do with WSL itself.

**Comment by darkfader** [comment]
I got the same.
```
cd /c/Program\ Files\ \(x86\)/someprogram
grep -r status *
```
then... CTRL-C. then `ls`

**Comment by mcornella** [comment]
> you can actually recover from this without restarting WSL, by just unmounting (`sudo umount /mnt/c`) and remounting (`sudo mount C:\\ /mnt/c`)

I get this when remounting:
```
mount: /c: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
```
There is no `mount.9p` under /sbin. This is on a distro migrated from WSL1.

**Comment by zzyyzz1992** [comment]
It happens when I manipulating files in /mnt/c/...

**Comment by benhillis** [comment]
Fixed in [18995](https://blogs.windows.com/windowsexperience/2019/10/03/announcing-windows-10-insider-preview-build-18995).

**Comment by Silic0nS0ldier** [comment]
Can confirm this is now fixed for me, tested under 19001.

**Comment by CodeAunt** [comment]
> > you can actually recover from this without restarting WSL, by just unmounting (`sudo umount /mnt/c`) and remounting (`sudo mount C:\\ /mnt/c`)
> 
> I get this when remounting:
> 
> ```
> mount: /c: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
> ```
> 
> There is no `mount.9p` under /sbin. This is on a distro migrated from WSL1.
> 
> EDIT: adding `-t drvfs` to the mount command fixed it. So `sudo mount -t drvfs C:\\ /mnt/c`

fixed!!!!!! THX!!!!!!

**Comment by throwable-one** [comment]
It seems that I got it again
```
:/mnt/c$ ls
ls: cannot open directory '.': Input/output error
```
19073.1
Ubuntu 1804

**Comment by rlabrecque** [comment]
Just hit this again with:

Version	10.0.19041 Build 19041

  NAME            STATE           VERSION
* Ubuntu-18.04    Running         2


I believe it may have to do with putting windows to sleep.

**Comment by teonimesic** [comment]
Can confirm this is also happening to me from time to time in 19541 usually when running intensive I/O, such as cloning BIG git repos. I'm using Ubuntu-18.04 on WSL 2

**Comment by vranystepan** [comment]
> 
> 
> Just hit this again with:
> 
> Version 10.0.19041 Build 19041
> 
> NAME STATE VERSION
> 
>     * Ubuntu-18.04    Running         2
> 
> 
> I believe it may have to do with putting windows to sleep.

It was happening to me after each boot. I was able to apply some workaround here: disabled fast boot.

**Comment by sinapis** [comment]
Just had this issue as well:

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

4.19.84-microsoft-standard

When I tried to remount C drive, I got:
`umount: /mnt/c: target is busy.`

Worked around it with:
```
lsof | grep "/mnt/c"
killall <processes that appear in list>
```

**Comment by numeric-lee** [comment]
This was supposedly fixed 6 months ago , I encountered the same problem today.  I had luck with the following

```
    sudo umount /mnt/c
    sudo mount -t drvfs C:\\ /mnt/c
```

**Comment by rkingsbury** [comment]
> 
> 
> Just hit this again with:
> 
> Version 10.0.19041 Build 19041
> 
> NAME STATE VERSION
> 
>     * Ubuntu-18.04    Running         2
> 
> 
> I believe it may have to do with putting windows to sleep.

I'm also seeing this issue periodically, and I agree that it seems to be triggered by putting the PC to sleep. If I leave my WSL2 terminal open, sleep, and wake the computer again, I often have the input/output error.

If I then shut down the WSL2 terminal and try to restart it, the terminal will appear for a moment and then disappear. I have to manually restart the LxssManager service to get things working properly again.

**Comment by kwint** [comment]
Can confirm, just had the same issue after getting windows out of sleep

**Comment by romulobrandino** [comment]
I had the same problem, started 3 days ago, I open the WSL2 using Ubuntu, instead of opening the prompt on regular folder /mnt/c/user is opening now on root / , then when I move to cd /mnt/c/ and try a simple ls command, I got this error message ls: cannot open directory '.': Input/output error

**Comment by romulobrandino** [comment]
> 
> 
> > That error occurs if the hidden `wslhost.exe` process is died/killed. Just use `wsl.exe --shutdown` and restart it.
> 
> this fixes it for me

This helped me to fix. 

> wsl.exe --shutdown

**Comment by nyuszika7h** [comment]
This has happened twice for me on 2004 (19041.264) right after a shutdown + reboot, but I cannot consistently reproduce it. `wsl --shutdown`  fixes it.

**Comment by YannBrrd** [comment]
Same here... 👎

**Comment by kwint** [comment]
@SvenGroot @benhillis Can we reopen this issue or should we create a new one? I have this every time now after a restart

**Comment by benhillis** [comment]
@kwint - which version are you running?

**Comment by kwint** [comment]
@benhillis wsl 2 and am on a windows insiders slow ring. Will check which build version when I'm back home

**Comment by engyii** [comment]
A +1 on this issue : My wsl always starts in this error state too when i boot windows, no exception. It's consistently fixed by doing wsl.exe --shutdown. I'm using wsl 2 with Ubuntu on win 10.0.19041.264

**Comment by YannBrrd** [comment]
+1 with ubuntu 20.04 & win pro .19041.264

**Comment by rlabrecque** [comment]
@craigloewen-msft @benhillis Could we get this reopened?

Also still experiencing this, intermittently though.
Win10 Pro 10.0.19041.264 && Ubuntu 18.04

**Comment by MMDF** [comment]
I've experienced this. I restarted with updating and when apps I had open were restored, VS Code failed to communicate with WSL, found out that wslhost was down, so I shutdown WSL and it was fixed. Might be because of restarting or the update.

**Comment by AOne-T** [comment]
Also have this issue. Upgraded to Windows 2004. Enabled WSL 2 and installed clean new Ubuntu 20.04. When starting Windows Terminal it starts at Ubuntu's root folder '/'. `wsl --shutdown` helps but only until next Windows reboot. Using notebook (presumably Fast Boot enabled if it means something).

**Comment by zakeryooo** [comment]
Yeah there's still an issue here.

I have a fresh install of the latest stable Windows 10 (19041.329), installed VS code, wsl2 and docker (wsl2 engine). Every time I start Windows I have to restart WSL2 (wsl --shutdown) otherwise it's broken.

**Comment by world4jason** [comment]
same issue here
thought (wsl.exe --shutdown) works, it's still pretty annoying
win10 20161.1000 & ubuntu 20.04

**Comment by rlabrecque** [comment]
I have a different machine that's been upgraded to WIn10 2004 & WSL2, and also experiences this issue upon each boot

**Comment by phillip-elm** [comment]
I've been having a similar issue on Windows 10 v2004 and WSL2 - intermittent input/output errors when accessing the windows disk from a Docker container - except that it occurs intermittently, and `wsl --shutdown` has no apparent affect on the frequency.

I opened an issue with Docker for Windows earlier today outlining my situation, but reading this more, it seems to be more WSL specific. In any case, if anyone is interested in reading, I've gone into detail here: https://github.com/docker/for-win/issues/7552

**Comment by jainsamyak** [comment]
> I've got an issue which seems from reading this seems to stem from the same thing.
> If it's of any help, I've got Docker Technical Preview installed.
> 
> `Windows Version: 10.0.18980.1`
> 
> `Ubuntu 18.04 WSL2`
> 
> Steps to reproduce:
> 
> 1. Start with a shutdown pc. Turn it on.
> 2. Once signed in, open up Windows Terminal(Preview)
> 3. Open an Ubuntu tab.
> 4. Try running any windows command, such as `code` or `explorer.exe`
> 5. Terminal will output `command not found`
> 
> To resolve the issue:
> 
> 1. Close the Ubuntu session, open a new powershell session and run the command `wsl --shutdown`
> 2. Open up Ubuntu again, run the command `code`, it should work as expected, by opening vscode in windows, connected to WSL2 Ubuntu.
> 
> OR
> 
> Simply restart pc. After opening up Ubuntu, `code`, `explorer.exe`, and other commands will work as usual.
> 
> However, after a restart, any transparency effects (Such as the Windows Terminal's Acrylic background and the start menu color, will be shut off, with no way of turning them back on again. But I'm sure this has nothing to do with WSL.

I have the exact same problem since I installed docker desktop on Win. 2004
`wsl --shutdown` does seem to fix it though. Occurs on every reboot.
Any permanent solutions thus far?

**Comment by AOne-T** [comment]
As for me the problem still exists with 90% certainty after every reboot. I always check `cd /mnt/c` if it is accessible. If not `wsl --shutdown` and start again. 
But recenty I installed Ubuntu 18.04 LTS package from Store (alongside with default Ubuntu with this problem). And it occured that this Ubuntu 18.04 doesn't have this problem at all. It starts always in windows user folder (/mnt/c/Users/<user>).

**Comment by dpatou** [comment]
> As for me the problem still exists with 90% certainty after every reboot. I always check `cd /mnt/c` if it is accessible. If not `wsl --shutdown` and start again.
> But recenty I installed Ubuntu 18.04 LTS package from Store (alongside with default Ubuntu with this problem). And it occured that this Ubuntu 18.04 doesn't have this problem at all. It starts always in windows user folder (/mnt/c/Users/).

I've been having this issue with the same consistency (for me it's not /mnt/c it's vscode's code command that raises an IO error). I've had this issue with the same frequency on wsl Ubuntu (whatever version that is) and wsl Ubuntu 20.04.

I'm curious on 18.04 where you don't have the issue you start in windows user folder, but on the other OS (where you have issue) where do you start ? I'll try with starting on the windows mount instead of my ubuntu home to see if it removes the issue (but it's less convenient).

**Comment by AOne-T** [comment]
I also use VSCode - it's IO error when you call code from WSL is because it is inaccessible due to C: drive not mounted.
Ubuntu (20.04, default store package) where I had issue started in ~ (home dir). 
I've deleted and reinstalled that distro - it works now fine and starts us /mnt/c/Users/<user> folder as 18.04

**Comment by mcswell** [comment]
Not sure why this issue was closed; it still happens, at least it happened to me today.  Fully updated, Windows 2004 (last update was KB4571756, 'ver' in cmd.exe shows "Microsoft Windows [Version 10.0.19041.508]"), Ubuntu 20.04 version 2 (and 'uname -a' shows "Linux lobo 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
>").

I did do an 'apt upgrade' today, but it had only 4 items, and I last did this on 29 Sep. (so after aeschli marked this issue "Closed").

**Comment by kwint** [comment]
This issue has been closed since 18 okt 2019...
I did ping some maintainers before (https://github.com/microsoft/WSL/issues/4377#issuecomment-638679307). I'm not sure if this issue is on microsoft's radar. I still have the issue, but definitely less frequently than before.

**Comment by mcswell** [comment]
@kwint: oops, I saw the "update" icon next to @aeschli's post 14 days ago (around 18 Sep 2020), and assumed wrongly that they had done that.  I guess I don't understand what the "closed" icon means (some of them apparently don't even refer to this "issue", but some an issue referenced in someone's comment?).
At any rate, I had the problem today; not sure how often it happens, nor whether it's reproducible.

**Comment by kwint** [comment]
Gonna ping them again, had this issue again a few times in the last few days. 
@SvenGroot @benhillis do you guys mind opening this issue again or shall we create a new one? It is obviously still (or again) present

**Comment by phillip-elm** [comment]
Just an FYI for interested parties, I do have an open and assigned issue that is similar if not directly related (#5552) - although I've not heard back from Ben or Sven on it in a while myself. Might be worth watching in relation to this.

**Comment by Natetronn** [comment]
I'm also hitting this on 2004. Like @jainsamyak , I too have docker desktop installed. 

wsl --shutdown and wsl doesn't fix it.

**Comment by ElGusanitoPLAY** [comment]
me too, all started while trying to build a project with stack, even if a restart wsl the error comes back after doing a few things

**Comment by daniluk4000** [comment]
Same error

**Comment by wbmins** [comment]
> That error occurs if the hidden `wslhost.exe` process is died/killed. Just use `wsl.exe --shutdown` and restart it.

this fixes it for me too

**Comment by todpale** [comment]
What do we have at the moment? Uncontrolled memory increasing of Vmmem and "cannot access '/mnt/c': Input/output error". I got the last error when using WSL2's git inside PHPStorm. If you need to shutdown WSL every time when memory is out of comfort work or wslhost.exe is died, you should find a new environment to do your job. But I don't want to do this! I'm really happy that I have so powerful tool like WSL. Windows is becoming something really cool for working. But these lacks have been existed for ONE YEAR with no solution. 

I'm sorry for non-constructive speech. Just scream of soul. Problem is still here.

**Comment by AOne-T** [comment]
As for me, I reverted back and removed WSL completely. Installed VirtualBox + headless Ubuntu server. Works like a charm (VS Code with Remote SSH extension, working systemd(!), shared folders). Startup time is 5 seconds.

**Comment by Robula** [comment]
This started happening to me after I installed Docker Desktop, very annoying!

**Comment by todpale** [comment]
The simplest solution now is restarting LxssManager in services.msc.

**Comment by mreymann** [comment]
Same problem here WSL2, Ubuntu 20.04 LTS ... All fully updated ...

**Comment by wafflepie** [comment]
Disabling Fast Startup completely resolved the issue for me, though it's not a feasible solution for everyone.

**Comment by rlabrecque** [comment]
New tracking issue for this seems to be over here: https://github.com/microsoft/WSL/issues/6174

**Comment by 9jaboy** [comment]
@wafflepie  disabling Fast Startup did not work for me

**Comment by tomqwpl** [comment]
I'm getting this issue quite a lot at the moment. I'm trying to extract a large 30GB tar.gz file. I haven't managed to unpack it yet. When it fails, I get this kind of error, when everything just either returns i/o error, or segv. Clearly restarting wsl "fixes" the problem, since I'm rebooting the machine. But it doesn't fix it in the sense that I can't unpack the tar file. It's not an out of disk space issue.

**Comment by iMonZ** [comment]
I runned the docker command with sudo and not it works!

**Comment by jamieburchell** [comment]
I was able to repro this behaviour when deleting several thousand files in Windows from my Bitlockered D: drive (/mnt/d 9p mount).

**Comment by rkingsbury** [comment]
> 
> 
> I was able to repro this behaviour when deleting several thousand files in Windows from my Bitlockered D: drive (/mnt/d 9p mount).

Interesting. I always access files on a Bitlockered partition as well when I see this error.

**Comment by jamieburchell** [comment]
> > I was able to repro this behaviour when deleting several thousand files in Windows from my Bitlockered D: drive (/mnt/d 9p mount).
> 
> Interesting. I always access files on a Bitlockered partition as well when I see this error.

In my experience Windows doesn't handle thousands of files very well - either deleting them or copying them. I can get Explorer to crash/restart itself mid operation if I start off several large folder deletes. But this doesn't necessarily coincide with the /mnt being inaccessible.

**Comment by lambda-science** [comment]
Any update on this ?
Having to use powerhsell to `wsl.exe --shutdown` each time I want to open VSCode in WSL mode is exhausting

**Comment by zhengxunWu1** [comment]
Hey, I previously never had this issue but after being forced to upgrade to windows11 and then downgrade back to windows10 build 10.0.19044 since can't bear the weird behaviours of my touchpad of win11..It's really annoying anyway to fix it other than wsl.exe --shutdown? especially when i have multiple terminal running and it just happens so randomly and should be fixed.. Use Ubuntu 18.04 LTS.

**Comment by iMonZ** [comment]
> Hey, I previously never had this issue but it happens to me recently after being forced to upgrade to windows11 and then downgrade back to windows10 build 10.0.19044 since can't bear the weird behaviours of my touchpad of win11..It's still forces me to upgrade even if I have quit the insider program since win11 is extremely buggy and broken.. Do I have to do a clean installation of win10 to completely get rid of win11's legacy bugs? It's really annoying.. anyway to fix it other than wsl.exe --shutdown? especially when i have multiple terminal running and it just happens so randomly and should be fixed.. Use Ubuntu 18.04 LTS.

It would be a great idea to update your Ubuntu installation to a more recent version like 20.04 or 21.10.
But 18.04 could be too old for WSL to be supported properly since there is no demand

**Comment by jamieburchell** [comment]
I have all sorts of issues with the connection between WSL2 and Windows seemingly dying lately. Especially when doing large file operations in Explorer or using Visual Studio Code (where it hangs). This is Ubuntu 20.04.

**Comment by stloc** [comment]
before
![image](https://user-images.githubusercontent.com/4832070/144825284-884f2c42-818b-4380-84d8-f2fdc474afc7.png)

after (what ???)
![image](https://user-images.githubusercontent.com/4832070/144822338-f9ade2b6-1b6a-4c97-9935-fe50d6a14929.png)

**Comment by lambda-science** [comment]
> before ![image](https://user-images.githubusercontent.com/4832070/144825284-884f2c42-818b-4380-84d8-f2fdc474afc7.png)
> 
> after (what ???) ![image](https://user-images.githubusercontent.com/4832070/144822338-f9ade2b6-1b6a-4c97-9935-fe50d6a14929.png)

yeah you need to restart WSL2 by going to powershell, typing `wsl.exe --shutdown` and re-open WSL. This has been the case for me for more than 1.5 years now....

**Comment by stloc** [comment]
> > before ![image](https://user-images.githubusercontent.com/4832070/144825284-884f2c42-818b-4380-84d8-f2fdc474afc7.png)
> > after (what ???) ![image](https://user-images.githubusercontent.com/4832070/144822338-f9ade2b6-1b6a-4c97-9935-fe50d6a14929.png)
> 
> yeah you need to restart WSL2 by going to powershell, typing `wsl.exe --shutdown` and re-open WSL. This has been the case for me for more than 1.5 years now....

Yes I know but I try to find the cause which process break permission.

**Comment by jmtornetta** [comment]
```wsl --shutdown``` fixes for me as well

**Comment by stloc** [comment]
@jmtornetta we already know this but we want a real stable solution

**Comment by MLZC** [comment]
> That error occurs if the hidden `wslhost.exe` process is died/killed. Just use `wsl.exe --shutdown` and restart it.

work for me, now echo $PATH can output some path from windows.

**Comment by KevinJoiner** [comment]
I was experiencing this issue regularly and then noticed that I was running out of disk space which was causing WSL to crash.

**Comment by mcswell** [comment]
@KevinJoiner : out of curiosity, are you running on Linux?  I've crashed our lab's Linux system several times over the past couple years by trying to copy large files into dirs that happened to be on the same disk partition as /tmp, and I ran out of space on that partition. I'm really surprised that Linux doesn't guard against this, e.g. by reserving space for /tmp, or starting to issue console warnings when the space on some partition gets low, or s.t.  IMHO, you shouldn't be able to crash Linux by copying large files.

**Comment by KevinJoiner** [comment]
@mcswell No, I was on windows, though I have previously crashed Linux systems by copying large files. Linux usually runs into trouble when you fill-up the root partition `/`, which I am guessing is where `/tmp` lives on your system. To avoid this, it is often recommended to have `/tmp` on its own partition. If you are interested, you can read more about partition schemas [here](https://security.stackexchange.com/a/38803)

**Comment by zan73** [comment]
This is still an open issue for me.
Win 10 Version 10.0.19044.2130
Bitlocker enabled
Local Admin disabled
Attempting to perform a gradle build in Ubuntu or Kali-linux, getting build failure

└─$ ls -al /mnt
ls: cannot access '/mnt/c': Input/output error
total 8
drwxr-xr-x  4 root root 4096 Oct 24 20:29 .
drwxr-xr-x 18 root root 4096 Nov  2 11:37 ..
d?????????  ? ?    ?       ?            ? c
drwxrwxrwt  3 root root   60 Nov  2 11:37 wsl


Worked fine while I had Admin access (usually disabled by corporate profile).

**Comment by Senniral** [comment]
> That error occurs if the hidden `wslhost.exe` process is died/killed. Just use `wsl.exe --shutdown` and restart it.

Works well thank you.

**Comment by 2bam** [comment]
This worked for me `wsl.exe --shutdown`
In my case I think it has to do with the computer suspend/sleep cycle.

**Comment by sorushsaghari** [comment]
> This worked for me `wsl.exe --shutdown` In my case I think it has to do with the computer suspend/sleep cycle.

I have the same issue. after sleep or suspend my wsl is closd.

**Comment by patrickjdarrow** [comment]
`wsl.exe --shutdown` works, but the problem persists upon restart with any significant I/O (in my case saving ML models and weights using Python).

**Comment by yarrarajendra** [comment]
> > That error occurs if the hidden `wslhost.exe` process is died/killed. Just use `wsl.exe --shutdown` and restart it.
> 
> this fixes it for me

this fix worked for me thank you

**Comment by stloc** [comment]
I just came back to linux (Mint) and I think this is the best solution !

**Comment by girlpunk** [comment]
Easier solution than restarting the environment is to unmount the volume, and let it get automatically mounted again

`umount /mnt/c`

If you get a `target is busy` error, don't forget to `cd` out of any subfolder of the mount point on all sessions before unmounting.

**Comment by stoperro** [comment]
I see this issue is closed, yet I'm getting this every day (literally) on Windows 11. Is there any other issue where someone is working on it?

I also use BitLocker as someone mentioned here. The workaround with `wsl --shutdown` is not so great as I have to reopen everything and also Docker Desktop just dies...

**Comment by sydsim** [comment]
I'm also experiencing this problem. There is no particular problem right after starting WSL, but I cannot access to mounted disks(/mnt/*) after a few hours.
I cannot figure out the reason but it seems that this problem occurs sooner when I did huge Disk I/O.
and I cannot understand why so many people thumb up on "wsl --shutdown". it is not a solution.

**Comment by zynfly** [comment]
I also encountered this problem. When using rsync to synchronize files, compile projects, and so on, as long as there is a large amount of file IO, it will definitely get stuck

**Comment by sydsim** [comment]
In my case, it seems that the problem occurs when I access to the mounted disk with WSL and Windows Explorer together.
I stopped using Explorer to access the files in the disk after I got this assumption, and I never had problem until now.

**Comment by zynfly** [comment]
After changing the default mounting to SMB, this problem will not occur.

The problem should be on drvfs or 9P.

**Comment by stoperro** [comment]
@zynfly hmm, how exactly did you mount the disk to avoid the issue?

**Comment by Kumen** [comment]
> After changing the default mounting to SMB, this problem will not occur.
> 
> The problem should be on drvfs or 9P.

providing a solution would be great. Please share your secrets with us :)

**Comment by zynfly** [comment]
1. mk the local folder shared
2. edit the fstab in wsl to mount this folder 
`//DEVICE_NAME/shared_folder /mnt/shared_folder cifs username=xxxx,password=xxxx,iocharset=utf8,sec=ntlm 0 0`
the fstab should be like this, I can't remember clearly.
I configured it on the previous computer, but it broke down and I can't remember the details clearly.

@stoperro @Kumen

**Comment by narbhar** [comment]
I encounter a similar kind of issue where the any filesystem related command hangs forever. For example `ls` command hangs forever. I work in a scenario where I have some algorithm running WSL but relies on data being generated and dumped on Windows drive. I noticed during frequent polling of disk from python or when a process on windows is busy writing to the disk at the same time I encounter this issue. It is errorless. Python doesn't throw an error when it can't retrieve info from commands such as `os.listdir`. Interrupt commands also don't work when drives aren't accessible anymore. The only solution for me is to restart the entire WSL environement

**Comment by tplunket** [comment]
I've got this issue where my drive is disconnected even in Windows Explorer; is that the same as folks are seeing or different?

I actually move WSL to my D: drive at some point in the past and it's mostly fine but every once in a while the drive disappears, all of my bash terminals in Ubuntu (20.04.6) (the default one that I get with `wsl.exe`, not sure what it actually is) get in a state since "the system" is effectively gone and even killing the terminal with ^D hangs. Even trying to open Explorer from the taskbar hangs for a while, it eventually opens and this drive is missing. Reboot to recover although I'll try just restarting WSL to see if Windows can recover on its own?

I have opened up the PC and reseated the drive; I suppose something could be flaking there but it does only seem to happen when I'm "doing a lot," e.g. I've got VSCode open and I'm searching through files etc., and if I'm just doing terminal things and using Vim for editing it doesn't seem to happen.

**Comment by IYATT-yx** [comment]
I have discovered a factor that triggers an "Input/output error". After using a portable hard drive on my computer, when I tried to eject it, it prompted me that it was occupied. I used PowerToys and found that it was dllhost, so I turned off dllhost so that the portable hard drive could be ejected. But immediately, the drive letter mounted under/mnt cannot be accessed in WSL. I repeated the operation and it was indeed triggered by turning off dllhost.

**Comment by al-vincent** [comment]
In case it helps others at all - the solution described here https://superuser.com/a/1747876 worked for me:
> In WSL, Use
> `sudo mount -t drvfs DRIVE: /mnt/DRIVE`
> E.g.
> `sudo mount -t drvfs D: /mnt/d`

**Comment by allwelldotdev** [comment]
How can this issue be closed when the problem still persists even in 2025?! Makes no sense. I shouldn't have updated my Windows11 to the new version (version 24H2), in the previous version I did not encounter this problem neither did I know about it. Now, its unbearable. Occuring everytime I open WSL and use it for more than 3-4 hours. The only solution is running `wsl --shutdown` in Powershell, but it's not a good solution because why should I tear down my entire container setup, start up again, only to experience the same problem 3-4 hours later. Starting to see why developers flock to Mac from Windows because Windows bad experience coupled with poor software is just unbearable. I'm pissed right now. 😡

**Comment by craigloewen-msft** [comment]
@allwelldotdev  could you please open a new issue for the error you're seeing? And could you please include WSL logs in it? That would allow us to determine what could be going on! Thank you!

**Comment by allwelldotdev** [comment]
Noted. Done.
[https://github.com/microsoft/WSL/issues/12824](https://github.com/microsoft/WSL/issues/12824)
