### ISSUE TITLE
Can't start WSL1 or 2 instances since 18970 - Remote Procedure Call Failed

### ISSUE THREAD

**Issue by jbaribeault** [microsoft/WSL#4474]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.18970.1005

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Can't start existing WSL - new WSL shows same error upon trying to create a new user - regardless of DISTRO.
```
C:\Users\jbari>wsl --list
Windows Subsystem for Linux Distributions:
Ubuntu-18.04 (Default)
Ubuntu1804_v1

C:\>wsl
The remote procedure call failed.

C:\>wsl -d Ubuntu1804_v1 -u root
The remote procedure call failed.

C:\>bash
The remote procedure call failed.
```

* What's wrong / what should be happening instead:

Should start up! Been using my v1 (because I had vmware workstation installed) since WSL was a thing. 

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

Can't do an strace if I can't get into the distro :)

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

All 3 logs stay empty :(

Reverting to an earlier build worked - but the update happened again overnight since I forgot to pause. Now it won't back down again :( So now I can't use WSL at all.

I've tried removing everything, removing the feature, adding it back in, and even removed VMWare workstation and ALL VPNs except my Fortinet client (need that one right now) so that WSL can do v2 if it wants - Hyper-V machines can run fine with full network, so no issues there.

Event logs show:
```
Faulting application name: svchost.exe_LxssManager, version: 10.0.18970.1001, time stamp: 0x992e0685
Faulting module name: ucrtbase.dll, version: 10.0.18970.1001, time stamp: 0xafa25d02
Exception code: 0xc0000409
Fault offset: 0x00000000000714ae
Faulting process id: 0x5fc8
Faulting application start time: 0x01d564e01a2d28c7
Faulting application path: C:\WINDOWS\system32\svchost.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 2494190c-fadc-4d38-ae5c-59b3df5f838c
Faulting package full name: 
Faulting package-relative application ID: 


```
each time the WSL or BASH command is run......so there is a crash with svchost.
sfc /scannow is clean
dism check also clean.

really stuck here - help!?! I really _**need**_ WSL back :)

**Comment by benhillis** [comment]
Are there any Windows Error Reporting Service dumps?

**Comment by jbaribeault** [comment]
Hmm - where would I find that?

**Comment by jbaribeault** [comment]
![image](https://user-images.githubusercontent.com/2313591/64454130-6ab6ee00-d0a7-11e9-8335-a4e3c53fe118.png)

New ones are also being deployed as v1 - I just tried Kali for example.
>wsl -l -v
  NAME             STATE           VERSION
* Ubuntu-18.04     Stopped         1
  kali-linux       Running         1
  Ubuntu1804_v1    Stopped         1

**Comment by jbaribeault** [comment]
```
wsl --set-version kali-linux 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The RPC server is unavailable

Same event: 
Faulting application name: svchost.exe_LxssManager, version: 10.0.18970.1001, time stamp: 0x992e0685
Faulting module name: ucrtbase.dll, version: 10.0.18970.1001, time stamp: 0xafa25d02
Exception code: 0xc0000409
Fault offset: 0x00000000000714ae
Faulting process id: 0x63a4
Faulting application start time: 0x01d564eecc3ed605
Faulting application path: C:\WINDOWS\system32\svchost.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: b637da50-5cd0-4670-af4d-6bb066b52317
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by benhillis** [comment]
This may work: https://www.gfi.com/support/products/How-to-collect-user-mode-crash-dumps-with-Windows-Error-Reporting

**Comment by jbaribeault** [comment]
Sure i'll add svchost.exe to the regkeys and try and capture....hang on

**Comment by jbaribeault** [comment]
Can't get a crashdump to save my life with the regkeys set....

**Comment by benhillis** [comment]
I did some digging and found where Waston crashes end up.  I'm looking at some dumps now.  Thanks!

**Comment by jbaribeault** [comment]
Awesome - let me know if you need anything else....I'll be watching this closely!

**Comment by jbaribeault** [comment]
Confirmed problem still there in 18975 :(

**Comment by benhillis** [comment]
I have resolved this issue, it is due to some bad assumptions about network state. Best course of action is to revert to the previous build if you are experiencing this issue.  Fix is on the way.

**Comment by jbaribeault** [comment]
As stated before I can't back out anymore and 18980 didn't fix. If there is a complex method to fix please post it! Or - if it isn't possible to fix short of a nuke from orbit, I'll find time to do just that on my laptop.

**Comment by transmitterdan** [comment]
@benhillis 

Would be nice to get an estimate of when this fix will go live.  I got a big update the other day from MSFT but did not include fix for this issue.

E:\>ver

Microsoft Windows [Version 10.0.18980.1]

E:\>wsl
The remote procedure call failed.

This is really a problem since I can't revert the Window update without basically nuking all the machines I have.

**Comment by benhillis** [comment]
@transmitterdan - Hard to give an exact date, but I hope next week.

**Comment by pbolduc** [comment]
Last few days my WSL is broken too

```
Faulting application name: svchost.exe_LxssManager, version: 10.0.18362.1, time stamp: 0x32d6c210
Faulting module name: lxssmanager.dll, version: 10.0.18362.239, time stamp: 0x00e72cfc
Exception code: 0xc0000005
Fault offset: 0x000000000004a7c6
Faulting process id: 0xb10
Faulting application start time: 0x01d570249b42bc47
Faulting application path: C:\WINDOWS\system32\svchost.exe
Faulting module path: c:\windows\system32\lxss\lxssmanager.dll
Report Id: 46c28135-8dee-4bc9-9bfa-2a90aede5529
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by neoadventist** [comment]
Would love some insight as to the exact issue here. Its a black box for me. Thank you to whoever is working on fixing this!

**Comment by benhillis** [comment]
Essentially a fast fail coming safe buffer copy library and a variable length struct. The code was fine but the library was being overprotective. Fix is inbound.

**Comment by nandhanandy92** [comment]
Those who facing this issue can you guys able to open hyper-v manager i think hyper-v is not working in the backgroud

**Comment by nandhanandy92** [comment]
Can able to run Hyper-v but no luck in running wsl2 
same RPC server not available error :(

**Comment by benhillis** [comment]
Fixed in [18995](https://blogs.windows.com/windowsexperience/2019/10/03/announcing-windows-10-insider-preview-build-18995).

**Comment by transmitterdan** [comment]
@benhillis 
The fix is partially effective.  Now WSL will run which is great.  But DNS is broken. The "dreaded" Temporary failure in name resolution. error is back.

It seems that the symlink /etc/resolv.conf-->../run/systemd/resolve/stub-resolv.conf is no longer appropriate. Deleted the symlink and created manually /etc/resolv.conf with single line:

nameserver 8.8.8.8

line and DNS works again.

**Comment by mmcgirr** [comment]
I'd like to chime in on this issue as well.  

Same failure mode as O.P.  
Attempt to start WSL, receive "The remote procedure call failed".  Same error in windows logs regarding svchost_LxssManager.

Cannot manually set LxssManager to start - will fail right out.

Full text of failure: 
Faulting application name: svchost.exe_LxssManager, version: 10.0.19030.1, time stamp: 0x7f0c4c00
Faulting module name: ntdll.dll, version: 10.0.19030.1, time stamp: 0x71167529
Exception code: 0xc0000008
Fault offset: 0x000000000009e8ca
Faulting process id: 0x396c
Faulting application start time: 0x01d5a4bdd8bc5dd8
Faulting application path: C:\WINDOWS\system32\svchost.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 00591644-bb36-46ac-9df0-237bdc83e757
Faulting package full name: 
Faulting package-relative application ID: 

Windows build version: Microsoft Windows [Version 10.0.19030.1]

WSL was working fine until this latest update on my system.

**Comment by Project-Magenta** [comment]
same as @mmcgirr 
```
Faulting application name: svchost.exe_LxssManager, version: 10.0.19541.1000, time stamp: 0x05c40bb9
Faulting module name: ntdll.dll, version: 10.0.19541.1000, time stamp: 0xb9629030
Exception code: 0xc0000008
Fault offset: 0x00000000000a21da
Faulting process ID: 0xa74
Faulting application start time: 0x01d63a1530709753
Faulting application path: C:\WINDOWS\system32\svchost.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: 027100fc-e0e1-426e-a8e1-5bfb0d16fbd4
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by benhillis** [comment]
@Project-Magenta - Sounds like a different bug, could you please open a new issue?

**Comment by evertonpussi1985** [comment]
hi my wsl is broken 
Microsoft Windows [Version 10.0.19042.508]

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800706be
Error: 0x800706be The remote procedure call failed.

Press any key to continue...

I m try to uninstall linux wsl and reinstall. 
try start e stop wuauserv and crpto..... not works

**Comment by Kansuler** [comment]
> hi my wsl is broken
> Microsoft Windows [Version 10.0.19042.508]
> 
> Installing, this may take a few minutes...
> WslRegisterDistribution failed with error: 0x800706be
> Error: 0x800706be The remote procedure call failed.
> 
> Press any key to continue...
> 
> I m try to uninstall linux wsl and reinstall.
> try start e stop wuauserv and crpto..... not works

I also got problem with this after an update 2020-09-10. I uninstalled update KB4571756 and it started working for me again.

**Comment by pekrr1e** [comment]
> > hi my wsl is broken
> > Microsoft Windows [Version 10.0.19042.508]
> > Installing, this may take a few minutes...
> > WslRegisterDistribution failed with error: 0x800706be
> > Error: 0x800706be The remote procedure call failed.
> > Press any key to continue...
> > I m try to uninstall linux wsl and reinstall.
> > try start e stop wuauserv and crpto..... not works
> 
> I also got problem with this after an update 2020-09-10. I uninstalled update KB4571756 and it started working for me again.

It seems that KB4571756  mixed up with Windows 10 Insider Preview 20211.1000 (rs_prerelease)...
I cannot find the way to uninstall KB4571756. Do you have any tips to do that? With standalone KB4571756 installation file?

**Comment by Kansuler** [comment]
> > > hi my wsl is broken
> > > Microsoft Windows [Version 10.0.19042.508]
> > > Installing, this may take a few minutes...
> > > WslRegisterDistribution failed with error: 0x800706be
> > > Error: 0x800706be The remote procedure call failed.
> > > Press any key to continue...
> > > I m try to uninstall linux wsl and reinstall.
> > > try start e stop wuauserv and crpto..... not works
> > 
> > 
> > I also got problem with this after an update 2020-09-10. I uninstalled update KB4571756 and it started working for me again.
> 
> It seems that KB4571756 mixed up with Windows 10 Insider Preview 20211.1000 (rs_prerelease)...
> I cannot find the way to uninstall KB4571756. Do you have any tips to do that? With standalone KB4571756 installation file?

I went into Windows Update -> View update history -> uninstall updates and then select the KB4571756 and uninstall it. Hope it helps. I'm not running Windows Insider Preview. Version 10.0.19041 Build 19041

**Comment by umittaylan** [comment]
> > > > hi my wsl is broken
> > > > Microsoft Windows [Version 10.0.19042.508]
> > > > Installing, this may take a few minutes...
> > > > WslRegisterDistribution failed with error: 0x800706be
> > > > Error: 0x800706be The remote procedure call failed.
> > > > Press any key to continue...
> > > > I m try to uninstall linux wsl and reinstall.
> > > > try start e stop wuauserv and crpto..... not works
> > > 
> > > 
> > > I also got problem with this after an update 2020-09-10. I uninstalled update KB4571756 and it started working for me again.
> > 
> > 
> > It seems that KB4571756 mixed up with Windows 10 Insider Preview 20211.1000 (rs_prerelease)...
> > I cannot find the way to uninstall KB4571756. Do you have any tips to do that? With standalone KB4571756 installation file?
> 
> I went into Windows Update -> View update history -> uninstall updates and then select the KB4571756 and uninstall it. Hope it helps. I'm not running Windows Insider Preview. Version 10.0.19041 Build 19041

Same problem with you guys, but i can't find KB4571756 update to uninstall.

**Comment by pekrr1e** [comment]
> > > > > hi my wsl is broken
> > > > > Microsoft Windows [Version 10.0.19042.508]
> > > > > Installing, this may take a few minutes...
> > > > > WslRegisterDistribution failed with error: 0x800706be
> > > > > Error: 0x800706be The remote procedure call failed.
> > > > > Press any key to continue...
> > > > > I m try to uninstall linux wsl and reinstall.
> > > > > try start e stop wuauserv and crpto..... not works
> > > > 
> > > > 
> > > > I also got problem with this after an update 2020-09-10. I uninstalled update KB4571756 and it started working for me again.
> > > 
> > > 
> > > It seems that KB4571756 mixed up with Windows 10 Insider Preview 20211.1000 (rs_prerelease)...
> > > I cannot find the way to uninstall KB4571756. Do you have any tips to do that? With standalone KB4571756 installation file?
> > 
> > 
> > I went into Windows Update -> View update history -> uninstall updates and then select the KB4571756 and uninstall it. Hope it helps. I'm not running Windows Insider Preview. Version 10.0.19041 Build 19041
> 
> Same problem with you guys, but i can't find KB4571756 update to uninstall.

Maybe we need rollback to previous version? or just wait for another update~

**Comment by Kansuler** [comment]
Follow this solution, it worked for me after i installed the update:

https://github.com/microsoft/WSL/issues/5880#issuecomment-691367294

**Comment by umittaylan** [comment]
> > > > > > hi my wsl is broken
> > > > > > Microsoft Windows [Version 10.0.19042.508]
> > > > > > Installing, this may take a few minutes...
> > > > > > WslRegisterDistribution failed with error: 0x800706be
> > > > > > Error: 0x800706be The remote procedure call failed.
> > > > > > Press any key to continue...
> > > > > > I m try to uninstall linux wsl and reinstall.
> > > > > > try start e stop wuauserv and crpto..... not works
> > > > > 
> > > > > 
> > > > > I also got problem with this after an update 2020-09-10. I uninstalled update KB4571756 and it started working for me again.
> > > > 
> > > > 
> > > > It seems that KB4571756 mixed up with Windows 10 Insider Preview 20211.1000 (rs_prerelease)...
> > > > I cannot find the way to uninstall KB4571756. Do you have any tips to do that? With standalone KB4571756 installation file?
> > > 
> > > 
> > > I went into Windows Update -> View update history -> uninstall updates and then select the KB4571756 and uninstall it. Hope it helps. I'm not running Windows Insider Preview. Version 10.0.19041 Build 19041
> > 
> > Same problem with you guys, but i can't find KB4571756 update to uninstall.
> 
> Maybe we need rollback to previous version? or just wait for another update~

Oh, BTW, I'm running 20211 on Insider.

**Comment by pekrr1e** [comment]
> Follow this solution, it worked for me after i installed the update:
> 
> [#5880 (comment)](https://github.com/microsoft/WSL/issues/5880#issuecomment-691367294)

It's another issue. Element Missing~re-register dll.

**Comment by antonymarion** [comment]
> > > > > > > hi my wsl is broken
> > > > > > > Microsoft Windows [Version 10.0.19042.508]
> > > > > > > Installing, this may take a few minutes...
> > > > > > > WslRegisterDistribution failed with error: 0x800706be
> > > > > > > Error: 0x800706be The remote procedure call failed.
> > > > > > > Press any key to continue...
> > > > > > > I m try to uninstall linux wsl and reinstall.
> > > > > > > try start e stop wuauserv and crpto..... not works
> > > > > > 
> > > > > > 
> > > > > > I also got problem with this after an update 2020-09-10. I uninstalled update KB4571756 and it started working for me again.
> > > > > 
> > > > > 
> > > > > It seems that KB4571756 mixed up with Windows 10 Insider Preview 20211.1000 (rs_prerelease)...
> > > > > I cannot find the way to uninstall KB4571756. Do you have any tips to do that? With standalone KB4571756 installation file?
> > > > 
> > > > 
> > > > I went into Windows Update -> View update history -> uninstall updates and then select the KB4571756 and uninstall it. Hope it helps. I'm not running Windows Insider Preview. Version 10.0.19041 Build 19041
> > > 
> > > 
> > > Same problem with you guys, but i can't find KB4571756 update to uninstall.
> > 
> > 
> > Maybe we need rollback to previous version? or just wait for another update~
> 
> Oh, BTW, I'm running 20211 on Insider.

Same issue on insider 20221

**Comment by chengyi818** [comment]
After I update to 10.0.19041.208,My wsl cannot start with error message: The remote RPC server was cancelled. 

I try to uninstall KB4571756,and install KB4577063, but still not work.

At last,I revert to previous build and pause windows update.now wsl can work.

**Comment by rishabh-zibo** [comment]
Try to see if lxssmanager is running and if not then try to manually turn it on and change the service to start automatically. If it says access denied then run the following command in an elevated cmd promt: 

sc config LxssManager start=auto

This fixed the issue for me.
