### ISSUE TITLE
Starting WSL in drives other than C:\ opens wsl in /home/user

### ISSUE THREAD

**Issue by kwint** [microsoft/WSL#4714]
* Your Windows build number:  10.0.17763.316

* What you're doing and what's happening:  
Open powershell (or cmd) via explorer in specific folder (let's say `C:\Users\kwint\documents`)
execute: `wsl`
wsl opens in the same folder (pwd returns: `/mnt/c/Users/kwint/documents`)
Open powershell (or cmd) via explorer in a specific folder on an other drive than C (lets say `Q:\code`)
execute `wsl`
wsl opens in `~` folder (pwd returns `/home/kwint`)

![image](https://user-images.githubusercontent.com/7907280/69636277-89010a00-1056-11ea-8fc3-c67904379534.png)

* What's wrong / what should be happening instead:
wsl should always open/start in the some folder as where I executed it

If this is fixed in an newer build number please let me know, then I have some extra pressure to get my system administrator to do some work :/

**Comment by craigloewen-msft** [comment]
Tested this on Windows version 19013 and it's fixed here!

![image](https://user-images.githubusercontent.com/42221804/69748577-84dbf780-10fd-11ea-8420-9d9c98c69ac6.png)

I don't have access to a VM right now to test an earlier version, but I can around next week. Please @ me if no one else on this thread checks on an earlier version before then. :)

**Comment by kwint** [comment]
Got my system administrator to enable updates, but problem still exists on windows 10.0.18363.476. But since this works on the next insider build I think I'll just have to wait
