### ISSUE TITLE
Unable to Remove or Modify /usr/bin/ssh-agent After Windows Defender Found a Trojan

### ISSUE THREAD

**Issue by RyanDraves** [microsoft/WSL#4794]
* Your Windows build number:  Microsoft Windows [Version 10.0.18362.535]

* What you're doing and what's happening: 
I received a notification from Windows Defender that it had discovered a Trojan in `\\wsl$\Ubuntu\usr\bin\ssh-agent` and would like me to take action and restart my computer. I accepted. Upon restarting, `openssh-client` was no longer installed, and continued to not be recognized after attempting `sudo apt-get install openssh-client`, which returned results of the package already being recognized. After uninstalling and reinstalling `openssh-client`, the reinstall failed part way through, bringing me to my current problem.

When I attempt `sudo apt-get remove openssh-client` I get:
![image](https://user-images.githubusercontent.com/19778373/71707809-9aa6a180-2dba-11ea-90c3-c1837a2d9cee.png)

When I attempt `eval 'ssh-agent'` (after a successful `sudo chmod 755 /usr/bin/ssh-agent` or `777`) I get `-bash: /usr/bin/ssh-agent: cannot execute binary file: Exec format error`.

When I attempt `sudo rm /usr/bin/ssh-agent`, I get a `permission denied`.

The fun part: when I run Windows File Explorer as Administrator, I get:
![image](https://user-images.githubusercontent.com/19778373/71707878-28828c80-2dbb-11ea-887b-e6494795c467.png)

And lastly, when I run Powershell as Administrator and run `rm ssh-agent`, I get:
![image](https://user-images.githubusercontent.com/19778373/71707925-80b98e80-2dbb-11ea-8ca1-b608c04afcfe.png)

* What's wrong / what should be happening instead:
The permissions to the half-installed file `/usr/bin/ssh-agent` are incorrect, and not modifiable by even the Windows administrator. I would expect a WSL sudoer to be able to modify/remove the file, as well as execute it as normal.

* Strace of the failing command, if applicable:  [Here's sudo rm /usr/bin/ssh-agent](https://gist.github.com/RyanDraves/4645b8f940b80ae9323ae38d20ad9d31)

**Comment by Majsvaffla** [comment]
I had the same experience some minutes ago. The ssh-agent works for me after first removing the broken installation and then installing it again. 

I would suspect that there isn't really a Trojan in the ssh-agent binary but who knows 😄

**Comment by Diaolou** [comment]
As of this morning, I've got this issue too.

This might not be the best place for this post but this is the only thread that appeared for me when Googling this issue today.

Removing the file and reinstalling the whole `openssh-client` package it leads to it being immediately re-quarantined.

However, it's being identified as a Win32 virus in an ELF file, which makes no sense.

Setting an exception for the alleged trojan, `Trojan:Win32/Softcnapp`, and then reinstalling with `sudo apt install openssh-client --reinstall` works for now.

Hopefully the false positive will be fixed soon.

**Comment by gstorhaug** [comment]
Looks like this have been fixed in the latest "Protection updates" (Security intelligence version: 1.307.1639.0) - at least I am not having the problem anymore.

(I have also uninstalled openssh-client, manually removed /usr/bin/ssh-agent, and reinstalled openssh-client.  This may also be part of why it is working now).

**Comment by RyanDraves** [comment]
> As of this morning, I've got this issue too.
> 
> This might not be the best place for this post but this is the only thread that appeared for me when Googling this issue today.
> 
> Removing the file and reinstalling the whole `openssh-client` package it leads to it being immediately re-quarantined.
> 
> However, it's being identified as a Win32 virus in an ELF file, which makes no sense.
> 
> Setting an exception for the alleged trojan, `Trojan:Win32/Softcnapp`, and then reinstalling with `sudo apt install openssh-client --reinstall` works for now.
> 
> Hopefully the false positive will be fixed soon.
> 
> EDIT: Have submitted to Microsoft to re-test.
> EDIT2: https://www.virustotal.com/gui/file/c8475e6c3823b461940b48f2d1214dc9b04a3dfe90c13f21a117d533b86798d5
> EDIT3: Microsoft confirmed false positive.

Thank you for the feedback. I still have issues with my "quarantined" (I guess that's what's causing the issue?) `/usr/bin/ssh-agent`, as well a follow up.

For the file, I'm not sure how to add the `Trojan:Win32/Softcnapp` exception. I tried adding an exception to Windows Security, but all I found was "Add a File" which I added the wslpath to `/usr/bin/ssh-agent`. But, after that, `sudo apt-get install /usr/bin/ssh-agent --reinstall` produced a similar permission error. Do you have any way I or anyone else that ended up locking themselves out of this file could fix that?

Also, for the follow up, what would have been the best way to report this problem? I'm really only familiar with these Github Issues because... uh... debugging, so I didn't know where else to report the issue. Thanks in advance.

**Comment by RyanDraves** [comment]
Update, for anyone else still experience similar issues where the file became quarantined:
In `Windows Security` -> `Virus and Threat Protection` -> `Protection History`, you can see the recently detected "Trojan". I spammed the `Restore` and `Remove` buttons until it went away. After restarting, the rule applied and I regained access to delete `/usr/bin/ssh-agent`, and the reinstall worked fine.

As an added layer of please-don't-happen-again, `Windows Security` -> `Virus and Threat Protection` -> `Manage Settings` -> `Add or Remove Exclusions` will allow you to stop the file from being scanned again. The path Windows will recognize is `\\wsl$\Ubuntu\usr\bin\ssh-agent`.

One last followup that does concern WSL is that I thought it strange `sudo chmod` allowed me to gain read/write/execute permissions on the file, albeit the quarantine stopped me from removing or moving the file outright. I was able to edit it in nano and make it empty. On the Windows side, however, I didn't have and couldn't obtain read/write/execute permissions even as an Administrator. Thought that was odd.

**Comment by Diaolou** [comment]
@RyanDraves Glad you got it sorted. The actual issue (false positive) was best reported at https://www.microsoft.com/en-us/wdsi/filesubmission - they replied very quickly and updated their database. I'm not sure there was ever an issue with WSL itself, really.

**Comment by craigloewen-msft** [comment]
Since the false positive has been reported, and the original problem has been fixed I'll mark this issue as closed! Please feel free to reopen it if you are still experiencing the issue, or create a new one that references this one. Thanks!
