### ISSUE TITLE
WSL Debian installation and Legacy console mode

### ISSUE THREAD

**Issue by rei-vilo** [microsoft/WSL#5001]
**Configuration**

* Your Windows build number:   10.0.18363.720

**What you're doing and what's happening:**  

I'm following the procedure [Windows Subsystem for Linux Installation Guide for Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

* Launch PowerShell with Legacy console on
* Run `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
* Open Windows Store
* Download Debian
* Launch Debian

**What's wrong / what should be happening instead:**

+ Installation starts
+ I'm prompted for a user name
+ I'm typing the username in
+ Same as #319, the console requires to turn Legacy console off
   
I've tried each of the possibilities listed below:

+ Option 1
  + Turn Legacy console off 
  + Type in the user name
  + Same error message is promtped

+ Option 2
  + Turn Legacy console off 
  + Reboot as mentionned in the Properties  panel
  + Launch Debian
  + The screen is empty.

+ Option 3
  + Turn Legacy console off 
  + Close the console
  + Launch Debian
  + The screen is empty.

How to solve this issue? Please clarify the installation procedure. Thank you.

**Comment by DHowett-MSFT** [comment]
This is a bug in the Console. After you turn off legacy console mode, please go to the “terminal” tab and turn off the “use separate foreground”, “use separate background” and the cursor color options. This is fixed in the next version of Windows.

**Comment by rei-vilo** [comment]
Unfortunately, turning off the “use separate foreground”, “use separate background” and the cursor colour options has no effect. Still the same error message. Moreover, opening the Terminal pane show them checked again.

How to force the installation of WSL Debian?

**Comment by DHowett-MSFT** [comment]
They will be reset to on and the colors set to black whenever you have the legacy console turned on. You should not be using the legacy console option. It is intended for legacy application compatibility.

**Comment by rei-vilo** [comment]
The legacy console mode is turned off.

**Comment by rei-vilo** [comment]
I closed the Debian console and opened it again.

Surprise, Debian shows off with default user `root`!

> root@myPC:~# uname -a
> 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 GNU/Linux

**Comment by WSLUser** [comment]
> Surprise, Debian shows off with default user root!

That is no longer a Console issue but a WSL issue which I solved in https://github.com/WhitewaterFoundry/Pengwin/issues/595 with the help of crramirez.

**Comment by rei-vilo** [comment]
Is WSL ready for prime-time?

**Comment by DHowett-MSFT** [comment]
The distribution's setup application aborting in a weird state when you close it has no bearing on whether WSL is ready for prime-time.

**Comment by DHowett-MSFT** [comment]
(These applications are owned by the distribution.)
