### ISSUE TITLE
Can not use --set-version command to switch to wsl2. Error: 0xffffffff

### ISSUE THREAD

**Issue by fdavidg** [microsoft/WSL#5193]
Windows Version 10.0.19041.208

Below are the command I used:

C:\Users\user>wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2

C:\Users\user>wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Error: 0xffffffff

C:\Users\user>wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         1
  kali-linux      Stopped         1

C:\Users\user>ver

Microsoft Windows [Version 10.0.19041.208]

**Comment by rescenic** [comment]
In Windows Feature, have you enable:
Hyper-V, Virtual Machine Platform, and Windows Hypervisor Platform?

**Comment by fdavidg** [comment]
Yes, all three are enabled and yes I have the appropriate settings enables
in the BIOS, also.

FrankD Gunseor

**Comment by DimDroll** [comment]
It happened to me as well. Even if you succeed in running the command you would have to wait a lot for conversation to take place.

It's faster just to re-install Distribution. Uninstall it from "Apps & Features" and install then through MS Store. You will lose the content of the VM though.

**Comment by wzzyj** [comment]
For some reason you need to make sure no servcie/app is currently using some common ports. 

I my case, I find `AdGuardHome` caused this issue as it will use port 53.

**Comment by mchubby** [comment]
If you have no use for Hyper-V (no intent to run VMs), possible workaround is to remove the hyper-v feature and restart.
HV is not mentioned in the instructions (https://docs.microsoft.com/en-us/windows/wsl/install-win10) and AFAICT it's not a dependency for WSL2.

**Comment by jk7ss** [comment]
Ran into the same issue

> Error: 0xffffffff

Hyper-V is still required according to this FAQ: 
https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#does-wsl-2-use-hyper-v-will-it-be-available-on-windows-10-home

**Comment by allanregistos** [comment]
Fixed by right-clicking the wsl_update_x64.msi kernel and select uninstall, then install the kernel package again.
Credits to:
https://github.com/microsoft/WSL/issues/5651#issuecomment-663959276

**Comment by 7xt** [comment]
Still not fixed, I've already follow you all guide guys.

perhaps there is a problem on virtualization in bios, I can't find virtualization option on my bios settings.

need help.

**Comment by mchubby** [comment]
What is your motherboard and CPU models?

In powershell, execute `(GWMI Win32_Processor).VirtualizationFirmwareEnabled`
should be True

**Comment by jpmolla** [comment]
Nothing worked to me apart [this solution on Reddit](https://www.reddit.com/r/bashonubuntuonwindows/comments/d98c91/how_to_diagnose_error_0xffffffff/):

- Find out if a process listens on port 53 by doing `netstat -a -o -n`
- If you find something, kill it by its PID: `kill <PID>`
- Try again `wsl --set-version <VM_NAME> 2`

That worked for me. Hope it will help!

**Comment by tunmyse** [comment]
> * Find out if a process listens on port 53 by doing `netstat -a -o -n`
> * If you find something, kill it by its PID: `kill <PID>`

This solved it for me!

**Comment by iFlyinq** [comment]
> Nothing worked to me apart [this solution on Reddit](https://www.reddit.com/r/bashonubuntuonwindows/comments/d98c91/how_to_diagnose_error_0xffffffff/):
> 
> * Find out if a process listens on port 53 by doing `netstat -a -o -n`
> * If you find something, kill it by its PID: `kill <PID>`
> * Try again `wsl --set-version <VM_NAME> 2`
> 
> That worked for me. Hope it will help!

Thanks! It worked 😘🎉

**Comment by prakomkumham** [comment]
> * netstat -a -o -n

Thanks! worked for me 💋

**Comment by tousif786** [comment]
Thanks, @wzzyj, and a special thanks to @jpmolla for a detailed answer.

**Comment by epenflow** [comment]
> 

this worked out for me, thanks dude!
