### ISSUE TITLE
Error occured mounting a file system on startup. No Channels available

### ISSUE THREAD

**Issue by Lagicrus** [microsoft/WSL#5254]
* Your Windows build number:  Microsoft Windows [Version 10.0.19628.1]

* What you're doing and what's happening: 
Typing in start bar "WSL" to trigger opening app
(same happens via terminal)
`An error occurred mounting one of your file systems. Please run 'dmesg' for more details.` is then printed at the top of the console

* What's wrong / what should be happening instead:
WSL should load fine
It instead errors

* Strace of the failing command, if applicable:  
Message log from 'dmesg' as instructed
https://starb.in/PHJEUz.txt

**Comment by evan-kinney** [comment]
@Lagicrus sudo apt update && sudo apt upgrade followed by wsl --shutdown and then starting wsl again resolved the issue for me.

**Comment by Lagicrus** [comment]
> @Lagicrus sudo apt update && sudo apt upgrade followed by wsl --shutdown and then starting wsl again resolved the issue for me.

Hey thanks for the idea, sadly that doesn't seem to have worked :/ 
https://starb.in/mPpLlz.txt for the packages changed, maybe you had something else change or was just a coincidence. 
Ran `wsl --shutdown` in PowerShell and then loaded WSL back up and same error message.
Maybe its a Windows build issue? Currently on `10.0.19635.1` and still persists.

**Comment by evan-kinney** [comment]
> > @Lagicrus sudo apt update && sudo apt upgrade followed by wsl --shutdown and then starting wsl again resolved the issue for me.
> 
> Hey thanks for the idea, sadly that doesn't seem to have worked :/
> https://starb.in/mPpLlz.txt for the packages changed, maybe you had something else change or was just a coincidence.
> Ran `wsl --shutdown` in PowerShell and then loaded WSL back up and same error message.
> Maybe its a Windows build issue? Currently on `10.0.19635.1` and still persists.

I'm on build `19635.1` too. This build was the first that I noticed the error.

**Comment by benhillis** [comment]
Fixed in [19640](https://blogs.windows.com/windowsexperience/2020/06/03/announcing-windows-10-insider-preview-build-19640/)

**Comment by Lagicrus** [comment]
> Fixed in [19640](https://blogs.windows.com/windowsexperience/2020/06/03/announcing-windows-10-insider-preview-build-19640/)

I have since updated to 19645 (after testing on 19640) and I still get an error :/
This time WSL2 wanted a Kernal Update 
![image](https://user-images.githubusercontent.com/24227350/84556362-1584c880-ad1a-11ea-8d90-539315c44a90.png) which was done, only to reveal the same issue

As versions have changed, thought I might as well paste the new logs https://starb.in/AXhASV.yaml

Any other ideas? Not being able to mnt stuff is frustrating at this point

**Comment by rescenic** [comment]
[**@Lagicrus**](https://github.com/Lagicrus) commented on [Jun 13, 2020, 8:05 AM GMT+7](https://github.com/microsoft/WSL/issues/5254#issuecomment-643546116 "2020-06-13T01:05:48Z - Replied by Github Reply Comments"):
> > Fixed in [19640](https://blogs.windows.com/windowsexperience/2020/06/03/announcing-windows-10-insider-preview-build-19640/)
> 
> I have since updated to 19645 (after testing on 19640) and I still get an error :/  
> This time WSL2 wanted a Kernal Update  
> [![image](https://user-images.githubusercontent.com/24227350/84556362-1584c880-ad1a-11ea-8d90-539315c44a90.png)](https://user-images.githubusercontent.com/24227350/84556362-1584c880-ad1a-11ea-8d90-539315c44a90.png) which was done, only to reveal the same issue
> 
> As versions have changed, thought I might as well paste the new logs [https://starb.in/AXhASV.yaml](https://starb.in/AXhASV.yaml)
> 
> Any other ideas? Not being able to mnt stuff is frustrating at this point


There are several steps which I am using to solve this problem:
0. cmd: wsl --shutdown
1. Turn off fast startup in power option.
2. cmd as admin:
netsh winsock reset
netsh int ip reset all
netsh winhttp reset proxy
ipconfig /flushdns
Windows Search > Network Reset
CCleaner > Remove all temporary data
3. Make .wslconfig in user's Windows home folder
[wsl2]
memory=2GB
processors=2
localhostForwarding=true
swap=2GB
swapFile=
4. Restart your computer

**Comment by inthevortex** [comment]
Has any solution come for this yet? I am on OS build 19645.1 and still having the issue.

**Comment by inthevortex** [comment]
> 
> 
> [**@Lagicrus**](https://github.com/Lagicrus) commented on [Jun 13, 2020, 8:05 AM GMT+7](https://github.com/microsoft/WSL/issues/5254#issuecomment-643546116):
> 
> > > Fixed in [19640](https://blogs.windows.com/windowsexperience/2020/06/03/announcing-windows-10-insider-preview-build-19640/)
> > 
> > 
> > I have since updated to 19645 (after testing on 19640) and I still get an error :/
> > This time WSL2 wanted a Kernal Update
> > ![image](https://user-images.githubusercontent.com/24227350/84556362-1584c880-ad1a-11ea-8d90-539315c44a90.png) which was done, only to reveal the same issue
> > As versions have changed, thought I might as well paste the new logs https://starb.in/AXhASV.yaml
> > Any other ideas? Not being able to mnt stuff is frustrating at this point
> 
> There are several steps which I am using to solve this problem:
> 0. cmd: `wsl --shutdown`
> 
>     1. Turn off fast startup in power option.
> 
>     2. cmd as admin:
> 
> 
> ```
> netsh winsock reset
> netsh int ip reset all
> netsh winhttp reset proxy
> ipconfig /flushdns
> ```
> 
> Windows Search > Network Reset
> CCleaner > Remove all temporary data
> 
>     1. Make .wslconfig in user's Windows home folder
> 
> 
> ```
> [wsl2]
> memory=2GB
> processors=2
> localhostForwarding=true
> swap=2GB
> swapFile=
> ```
> 
>     1. Restart your computer

Did not work for me

**Comment by therealkenc** [comment]
/fixed [19640](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-19640) amorphous "Stability improvements for virtio-9p". 

For ongoing _not_ "`An error occurred mounting one of your file systems. Please run 'dmesg' for more details`" [OP](https://github.com/microsoft/WSL/issues/5254#issue-623564087) fail, LZ otherwise-open #5014.
