### ISSUE TITLE
Interop Issue: unable to find interpreter for launching Windows .exe files using Interop

### ISSUE THREAD

**Issue by grogzoid** [microsoft/WSL#5466]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.19613.1005] 
Your Distribution version: Release:        18.04
Whether the issue is on WSL 2 and/or WSL 1:Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```

# Steps to reproduce

1. Attempt to run Windows .exe that are in my WSL path:
~$ which code
/mnt/c/Users/gfinn/AppData/Local/Programs/Microsoft VS Code/bin/code

~$ code
run-detectors: unable to find an interpreter for /mnt/c/Users/gfinn/AppData/Local/Programs/Microsoft VS Code/Code.exe

#  Expected behavior

Windows executable would launch

# Actual behavior

Error message shown above:
run-detectors: unable to find an interpreter for /mnt/c/Users/gfinn/AppData/Local/Programs/Microsoft VS Code/Code.exe

**Comment by grogzoid** [comment]
Maybe the contents of /proc/sys/fs/binfmt_misc/WSLInterop are relevant:

~$ cat /proc/sys/fs/binfmt_misc/WSLInterop
enabled
interpreter /tools/init
flags: F
offset 0
magic 4d5a

/tools/init does not exist
instead, init is in /
trying a cheap hack of creating /tools and symlinking to /init , or copying /init to /tools did not help.

**Comment by grogzoid** [comment]
This started after a Visual Studio Code upgrade.

**Comment by therealkenc** [comment]
> /tools/init does not exist

That `interpreter /tools/init` is normal and correct, just nonobvious because of mount namespaces. It was a good avenue of attack though, so props for that.

>This started after a Visual Studio Code upgrade.

Does `notepad.exe` launch, or do you get the same `unable to find an interpreter` error message? If `notepad.exe` fails too, it isn't the VS Code upgrade, it just felt like that.

No guesses for you off the cuff. If it really is just `code` then do a purge and reinstall of VS Code. If `notepad.exe` doesn't work either, this gets more curious.

**Comment by grogzoid** [comment]
Univeral problem, with the interop interpreter. cmd.exe, notepad.exe do not work, same error message. So, right, nothing to do with code.

**Comment by grogzoid** [comment]
Might have uncovered something:
$ mount | grep binfmt_misc
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=31,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=1307)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)

**Comment by therealkenc** [comment]
> systemd-1 on /proc/sys/fs/binfmt_misc type autofs

WSL isn't going to inject anything `systemd` related, anywhere. You probably have critically missing steps in the repro. To test that hypothesis, install a clean 20.04 (only because you're on 18.04 not for the upgrade), see if notepad.exe works.

**Comment by patrick330602** [comment]
I also have the similar issue starting today, I am unable to run any windows related executables.
I am using Linux 4.19.121-microsoft-WSL2-standard, Windows 10 20150.1000
Close docker for Windows(WSL2 backend) actually helps me, so it is possibly a docker related issue

**Comment by therealkenc** [comment]
>  so it is possibly a docker related issue

That data point helps a lot. Can you do the same `mount | grep binfmt_misc` as grogzoid did above and see if you have the mysterious `systemd-1` in there also.

**Comment by grogzoid** [comment]
I've realized my issue is probably a self-inflicted wound from adding a
hack to get system working a few weeks ago. Should I close this?

**Comment by therealkenc** [comment]
@grogzoid If you are good on a clean install yes close. 

@patrick330602 If you think you've got a "possibly docker related issue" open that up under a different cover. Try to narrow it down as much as you can first though. I run Windows docker with the WSL backend (as do thousands) and haven't encountered a "`run-detectors: unable to find an interpreter: `" error, but that doesn't mean there isn't something going on in your specific scenario.

**Comment by benhillis** [comment]
Having two instances of the binfmt_misc filesystem mounted is going to cause issues.  I would try to determine where the second one is coming from.

**Comment by jdknox** [comment]
I just wanted to mention I had this same problem, and none of the troubleshooting steps from above added any clues on how to solve.  But I had recently `apt install`ed some things and went through those to see what I could see.  Turns out `nuget` added some `libmono` stuff that broke my `interop`ability.   As soon as I removed that package, everything starting working again.

But I would add, the error message is a bit cryptic out-of-context.  Maybe it should mention something about WSL for those of us who are plain, old uninitiated mortals?

**Comment by doggy8088** [comment]
@jdknox I can't fix this problem by executing the following command:

```sh
sudo update-binfmts --disable cli
```

**Comment by autoferrit** [comment]
I am on a relatively fresh copy of ubuntu 20.04 in wsl2. I noticed it having this issue last night. I do not that I never installed docker inside the wsl environment, and enabled the wsl feature in docker for windows. When running some of the above commands I get these outputs:

```bash
❯ mount | grep binfmt_misc
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
```
libmono
```bash
❯ apt search libmono | grep -i installed

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libmono-btls-interface4.0-cil/focal,now 6.8.0.105+dfsg-2 amd64 [installed,automatic]
libmono-corlib4.5-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
libmono-i18n-west4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
libmono-i18n4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
libmono-security4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
libmono-system-configuration4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
libmono-system-core4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
libmono-system-numerics4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
libmono-system-security4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
libmono-system-xml4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
libmono-system4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
```
I know I have been able to run say vscode through wsl before and worked fine. I discoverd the issue when trying to run it again and got the same error
```bash
❯ code-insiders .
run-detectors: unable to find an interpreter for /mnt/c/Users/shawn/AppData/Local/Programs/Microsoft VS Code Insiders/Code - Insiders.exe
```
If I run command in https://github.com/microsoft/WSL/issues/5466#issuecomment-695155716
```bash
sudo update-binfmts --disable cli
```
will that disable running the windows applications from the wsl cli?

**Comment by daler-rahimov** [comment]
restarting wsl with power shell > `wsl --shutdown` helped.

**Comment by ali-khawaja** [comment]
> restarting wsl with power shell > `wsl --shutdown` helped.

thank you!

**Comment by snero** [comment]
https://github.com/microsoft/WSL/issues/5466#issuecomment-741607590

This worked 100% for me. 

> 
> 
> restarting wsl with power shell > `wsl --shutdown` helped.

**Comment by patchu** [comment]
> @jdknox I can fix this problem by executing the following command:
> 
> ```shell
> sudo update-binfmts --disable cli
> ```

This totally worked for me!

**Comment by mdegans** [comment]
> I am on a relatively fresh copy of ubuntu 20.04 in wsl2. I noticed it having this issue last night. I do not that I never installed docker inside the wsl environment, and enabled the wsl feature in docker for windows. When running some of the above commands I get these outputs:
> 
> ```shell
> ❯ mount | grep binfmt_misc
> binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
> ```
> 
> libmono
> 
> ```shell
> ❯ apt search libmono | grep -i installed
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> libmono-btls-interface4.0-cil/focal,now 6.8.0.105+dfsg-2 amd64 [installed,automatic]
> libmono-corlib4.5-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
> libmono-i18n-west4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
> libmono-i18n4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
> libmono-security4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
> libmono-system-configuration4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
> libmono-system-core4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
> libmono-system-numerics4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
> libmono-system-security4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
> libmono-system-xml4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
> libmono-system4.0-cil/focal,now 6.8.0.105+dfsg-2 all [installed,automatic]
> ```
> 
> I know I have been able to run say vscode through wsl before and worked fine. I discoverd the issue when trying to run it again and got the same error
> 
> ```shell
> ❯ code-insiders .
> run-detectors: unable to find an interpreter for /mnt/c/Users/shawn/AppData/Local/Programs/Microsoft VS Code Insiders/Code - Insiders.exe
> ```
> 
> If I run command in [#5466 (comment)](https://github.com/microsoft/WSL/issues/5466#issuecomment-695155716)
> 
> ```shell
> sudo update-binfmts --disable cli
> ```
> 
> will that disable running the windows applications from the wsl cli?
> 
> **EDIT**: I tried the above command anyways, and it fixed the issue for me.

This fixed it for me after a libmono install. I installed `glade` which installed half of the Ubuntu repos in return. Happened to see libmono scroll by. Thanks for spotting that!

**Comment by konsbe** [comment]
> > so it is possibly a docker related issue
> 
> That data point helps a lot. Can you post the output of `mount | grep binfmt_misc` as grogzoid did above and see if you have the mysterious `systemd-1` and/or duplicate `binfmt_misc` entries.

I have the same issue without using docker, seems like dublicate files. am just trying to run manually vs code wis Ubuntu 20.04
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)

**Comment by pierrejoye** [comment]
I confirm Mono breaks it somehow. I just installed it and it broke my config.

**Comment by zzxyz** [comment]
`man update-binfmts` is helpful in answering the question about what `sudo update-binfmts --disable cli` will do.  `update-binfmts --display cli` -- It's the mono-runtime cli.

**Comment by orinwalker** [comment]
This also worked for me
>restarting wsl with power shell > wsl --shutdown helped.

**Comment by ruizach** [comment]
> restarting wsl with power shell > `wsl --shutdown` helped.

This also worked for me

**Comment by cschladetsch** [comment]
Yeah no idea why, but starting a PoweShell and then restarting a WSL shell allowed me back access to git lfs etc.

**Comment by aarzaary** [comment]
Thanks
`update-binfmts --disable cli`
Solved my problem 😁

**Comment by sadglamor** [comment]
### It should be caused by the conflict with systemd.
Please check the file `/etc/wsl.conf` and see if the `systemd = true` flag was added under `[boot]` settings as shown below. If so, please switch it to false.

![Snipaste_2023-01-12_11-45-09](https://user-images.githubusercontent.com/109228238/211971706-ec936287-0ba0-4d3b-a0c8-e03f5b0c160d.png)


For more info, please refer to [https://learn.microsoft.com/en-us/windows/wsl/wsl-config#per-distribution-configuration-options-with-wslconf](url)

**Comment by codebymikey** [comment]
Uninstalling the `mono-runtime` package via `sudo apt remove mono-runtime` also resolves the issue.

See https://github.com/microsoft/WSL/issues/9257#issuecomment-1352443162

**Comment by Renatochaz** [comment]
> @jdknox I can fix this problem by executing the following command:
> 
> ```shell
> sudo update-binfmts --disable cli
> ```

For future info: After installing "mono-complete" on my WSL2, for dotnet programming in vscode, i had this same issue, and this command fixed it.

**Comment by takekazuomi** [comment]
Thanks
> update-binfmts --disable cli

Solved my problem.

**Comment by pasqual-artif** [comment]
solves the Problem just temporary... after windows reboot the Problem occurs again

**Comment by fabio-s-franco** [comment]
Permanently solved by uninstalling mono-runtime.

**Comment by nam20485** [comment]
So, any of:

1. `sudo update-binfmts --disable cli`_*_
1. `sudo apt remove mono-runtime` https://github.com/microsoft/WSL/issues/9257#issuecomment-1352443162
1. changing `systemd=true` to `false` in `/etc/wsl.conf` [(source)](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#per-distribution-configuration-options-with-wslconf)

resolve the issue apparently (while 1.*
.96 is temporary and only persists until the next restart of WSL). The common cause seems to be the (indirect) install of `mono-runtime` package.

Personally disabling `systemd` is not an option given that I just spent a lot of time & effort getting SSH to auto-start in WSL...

Is anyone aware of the actual root cause? (Or was that already covered above?)

_Thanks everyone for the solutions._

**Comment by nam20485** [comment]
Unless I am missing something this issue should not be closed. It was closed because the OP sovled his instance of the issue but it is clearly still happening for more than a few people.

**Comment by jimklimov** [comment]
To re-apply the fix after WSL reboots, I've added this bit among many other hacks into my `~/.profile` :
````
# https://github.com/microsoft/WSL/issues/5466
python.exe --version >/dev/null 2>&1 \
|| sudo update-binfmts --disable cli
````

So it tries to run whatever Windows exe that is supposed to exit quickly and successfully, and if it fails - applies the fix from this thread. Should only happen once per WSL boot and subsequent log-in (which is also parsed when Docker Desktop starts and causes WSL to start).

**Comment by nerffan1** [comment]
Thank You to everyone! I just ran into this issue all of a sudden despite using WSL2 without this issue for the longest time. Besides using Visual Studio Community, I cannot think of what might have caused this....

**Comment by condrove10** [comment]
I ran into this issue after installing `lens` (for Kubernetes GUI management) via WSL, after removing it the issue stopped. Hope this might help someone.
