### ISSUE TITLE
WSL2 init process only mounts /usr/lib/wsl/* for first-started distro

### ISSUE THREAD

**Issue by diddledan** [microsoft/WSL#5506]
# Environment

```none
Windows build number: 10.0.20152.0
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

1. Run `wsl --shutdown` to clear any active WSL2 sessions
1. Start a WSL2 distro
1. Start a different WSL2 distro
1. The first distro has the paths `/usr/lib/wsl/*`  mounted (good)
1. The second distro does not have the paths `/usr/lib/wsl/*` mounted (bad)

#  Expected behavior

The paths at `/usr/lib/wsl/*` should correctly mount for all distros regardless of start/boot order.

# Actual behavior

Only the first-started distro has the DXGI library paths mounted. For example, when running Docker Desktop (with WSL2 backend) you cannot use the DXGI Machine Learning AI libraries in any distro because the `/usr/lib/wsl/*` paths are only mounted for the Docker distro because it was the first one started on bootup/login to Windows.

**Comment by therealkenc** [comment]
Confirmed here:

![image](https://user-images.githubusercontent.com/7049700/86047216-6aeff380-ba03-11ea-9948-464ca51e041b.png)


The dmesg looks like:

![image](https://user-images.githubusercontent.com/7049700/86047292-8a871c00-ba03-11ea-920f-5d52f4d5396f.png)

**Comment by onomatopellan** [comment]
I think this can be considered has fixed in insider builds.

**Comment by jeffsilverm** [comment]
I am still having this issue:
```
$ dmesg -H -T -P
[Fri Aug  5 15:52:51 2022]  Microsoft 4.4.0-19041.1237-Microsoft 4.4.35
[Fri Aug  5 15:52:51 2022] <3>init: (1) ERROR: ConfigInitializeCommon:665: Failed to mount /usr/lib/wsl/drive
[Fri Aug  5 15:52:51 2022] : 19
[Fri Aug  5 15:52:51 2022] <3>init: (1) ERROR: ConfigInitializeCommon:665: Failed to mount /usr/lib/wsl/lib
[Fri Aug  5 15:52:51 2022] 19
chq-jeffsi@CHQ-JEFFSI-LX:~$ uptime
 17:46:45 up  1:53,  0 users,  load average: 0.52, 0.58, 0.59
chq-jeffsi@CHQ-JEFFSI-LX:~$
```
The mount command looks like:
```
QQQQQQ@QQQQQQQQQ:~$ uptime
 17:46:45 up  1:53,  0 users,  load average: 0.52, 0.58, 0.59
qqqq@@@@@@@:~$ sudo mount -t cifs //10.x.xx.xxx/mis_YYYY_YYYY\$ /mnt/q/  -o "username=QQQQ"
Password for //10.x.xx.xxx/mis_YYYY_YYYY\$:
mount error: cifs filesystem not supported by the system
mount error(19): No such device
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
$
```

**Comment by onomatopellan** [comment]
>Microsoft 4.4.0-19041.1237-Microsoft 4.4.35

@jeffsilverm Your distro is WSL1. Try in a WSL2 distro and it should mount '/usr/lib/wsl/'.
