### ISSUE TITLE
libcuda.so.1 is not a symbolic link 

### ISSUE THREAD

**Issue by sirredbeard** [microsoft/WSL#5548]
This is cross-post of Ubuntu bug 1886532 which is pending investigation.

On Windows 10 build 20161 WSL2 running sudo apt upgrade results in warning:

"libcuda.so.1 is not a symbolic link"

It appears to be a result of a postinst hook in libc-bin.

![Annotation 2020-07-06 115104](https://user-images.githubusercontent.com/33820650/86613230-46ee5e00-bf7f-11ea-9222-3fb1a7f53e41.png)

https://bugs.launchpad.net/ubuntuwsl/+bug/1886532

**Comment by therealkenc** [comment]
Yeah, copies not symlinks. 

![image](https://user-images.githubusercontent.com/7049700/86639280-83c15180-bf8d-11ea-9355-7e7e5c67e5e8.png)

**Comment by BlackCoffee163** [comment]
Is there a solution for this? My `/usr/lib/wsl/lib` looks exactly like this. Where do I need symlinks and from where to where?

**Comment by therealkenc** [comment]
It's in `%SYSTEMROOT%\System32\lxss\lib`. It might be possible to make it a symlink in that folder, though I haven't tried and mucking your `System32` is not recommended for lots of good reasons. You could also probably make the warning go away by mount binding a symlink over the file on the WSL side. Haven't tried that either.

Thus far the warning hasn't proved blocking in any way. It isn't even that clear (to me) why `ldconfig` feels inclined to point it out, because there isn't anything technically "wrong" with the file not being a symlink, except for violating a convention. Absent some heretofore unstated blocking use-case, the smart play ("solution") is to ignore the warning.

**Comment by Axolotl163** [comment]
What would cause problems with symlinking from system32. Like I know generally altering system32 is bad, but would symlinks cause problems?

**Comment by wanfuse123** [comment]
Directory of C:\Windows\System32\lxss\lib

09/18/2020  03:53 PM    <DIR>          .
08/30/2020  09:51 AM           124,664 libcuda.so
09/12/2020  08:44 AM           832,936 libd3d12.so
09/12/2020  08:44 AM         5,073,944 libd3d12core.so
09/12/2020  08:44 AM        25,069,816 libdirectml.so
09/12/2020  08:44 AM           878,768 libdxcore.so
08/30/2020  09:51 AM        40,496,936 libnvwgf2umx.so
               6 File(s)     72,477,064 bytes
               1 Dir(s)  643,723,309,056 bytes free

C:\Windows\System32\lxss\lib>mklink libcuda.so.1 libcuda.so
symbolic link created for libcuda.so.1 <<===>> libcuda.so

**Comment by wanfuse123** [comment]
simlynk generates new error

sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
Failed to initialize NVML: Unknown Error

**Comment by wanfuse123** [comment]
docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -privileged -gpu -benchmark
Run "nbody -benchmark [-numbodies=<numBodies>]" to measure performance.
        -fullscreen       (run n-body simulation in fullscreen mode)
        -fp64             (use double precision floating point values for simulation)
        -hostmem          (stores simulation data in host memory)
        -benchmark        (run benchmark to measure performance)
        -numbodies=<N>    (number of bodies (>= 1) to run in simulation)
        -device=<d>       (where d=0,1,2.... for the CUDA device to use)
        -numdevices=<i>   (where i=(number of CUDA devices > 0) to use for simulation)
        -compare          (compares simulation results running once on the default GPU and once on the CPU)
        -cpu              (run n-body simulation on the CPU)
        -tipsy=<file.bin> (load a tipsy model file for simulation)

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.

Error: only 0 Devices available, 1 requested.  Exiting.



NOTE: the -privileged switch changes the error from above

**Comment by PeerXu** [comment]
```
$ sudo docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -privileged -gpu -benchmark
CUDA error at bodysystemcuda_impl.h:159 code=46(cudaErrorDevicesUnavailable) "cudaEventCreate(&m_deviceData[0].event)" 
Run "nbody -benchmark [-numbodies=<numBodies>]" to measure performance.
	-fullscreen       (run n-body simulation in fullscreen mode)
	-fp64             (use double precision floating point values for simulation)
	-hostmem          (stores simulation data in host memory)
	-benchmark        (run benchmark to measure performance) 
	-numbodies=<N>    (number of bodies (>= 1) to run in simulation) 
	-device=<d>       (where d=0,1,2.... for the CUDA device to use)
	-numdevices=<i>   (where i=(number of CUDA devices > 0) to use for simulation)
	-compare          (compares simulation results running once on the default GPU and once on the CPU)
	-cpu              (run n-body simulation on the CPU)
	-tipsy=<file.bin> (load a tipsy model file for simulation)

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.

> Windowed mode
> Simulation data stored in video memory
> Single precision floating point simulation
> 1 Devices used for simulation
GPU Device 0: "GeForce GTX 1080" with compute capability 6.1

> Compute 6.1 CUDA device: [GeForce GTX 1080]
```

**Comment by wanfuse123** [comment]
What happens if tou ad
 -- compair after benchmark ? Forget it if one or two dashes

**Comment by Shohou** [comment]
/usr/lib/wsl/lib is included through /etc/ld.so.conf.d. You will find a file there with instructions how to prevent its generation. You have to delete that file and create /etc/wsl.conf with the fillowing lines:
```
[automount]
ldconfig = false
```

**Comment by thierryherrmann** [comment]
Same problem here using Win 10 build 20257.1 both with ubuntu 18.04 and ubuntu 20.04 (kernel 4.19.128).
Problem shows up either through `sudo apt-get install -y nvidia-docker2` or `sudo apt-get install -y cuda-toolkit-11-0`, two steps mentioned in the official [NVidia CUDA-wsl procedure](https://docs.nvidia.com/cuda/wsl-user-guide/index.html).
Must have worked at some point but something must have been broken

**Comment by ligewu** [comment]
1. disable automount in /etc/wsl.conf
> [automount]
> ldconfig = false

2. copy /usr/lib/wsl/lib to /usr/lib/wsl2/lib (in wsl, writable)

3. edit /etc/ld.so.conf.d/ld.wsl.conf
> /usr/lib/wsl/lib --> **/usr/lib/wsl2/lib** (new location)

4. rm /usr/lib/wsl2/lib/libcuda.so.* and sudo ldconfig

works for CUDA in WSL, but "Segmentation fault" in DirectML

**Comment by sryio** [comment]
There is another solution works for me :

* Open cmd as Administrator and cd into C:\Windows\System32\lxss\lib
* Delete libcuda.so and libcuda.so.1 (You can also do this in Windows Explorer as well)
* Run ```wsl -e /bin/bash``` in cmd and you should already in ```/mnt/c/Windows/System32/lxss/lib```, now you have rights to create symlink:
```bash
    ln -s libcuda.so.1.1 libcuda.so.1
    ln -s libcuda.so.1.1 libcuda.so
```

Done.

**Comment by EvanThomasKaduthanam** [comment]
I am new to this, and I din't get what you sould do in the solution u all said works...

I deleted libcuda.so and libcuda.so.1 using File Explorer, now I am having trouble figuring out the next part, thank you in advance!

**Comment by LanceMcCarthy** [comment]
> I am new to this, and I din't get what you sould do in the solution u all said works...
> 
> I deleted libcuda.so and libcuda.so.1 using File Explorer, now I am having trouble figuring out the next part, thank you in advance!

Here are the exact steps:

![image](https://user-images.githubusercontent.com/3520532/141310163-22f10bdf-af81-4420-9e20-5da2550c5532.png)

**Comment by SuperSandro2000** [comment]
> * /mnt/c/Windows/System32/lxss/lib

Works on my machine.

Why isn't this not fixed by WSL already?

**Comment by SofiaXu** [comment]
1. Run CMD in Windows(as Administrator)
2. `cd %SYSTEMROOT%\System32\lxss\lib`
3. `del libcuda.so`
4. `mklink libcuda.so libcuda.so.1`
5. Run wsl
6. `sudo ldconfig`
7. done
libcuda.so, libcuda.so.1 and libcuda.so.1.1 are same file because they have same hash.

**Comment by Purpzie** [comment]
This also happens in Arch whenever you use pacman. It seems like this isn't limited to Ubuntu. (Note: I used `wsl --import` with Arch's official bootstrap, not the hacky ArchWSL)

![image](https://user-images.githubusercontent.com/25022704/156613695-f49b1bcd-c7cb-4978-acf7-51cfc09dd6b8.png)
![image](https://user-images.githubusercontent.com/25022704/156613759-f1a17c05-fb95-49d1-80b5-b7535afbeef4.png)

**Comment by CaffreyXu** [comment]
> symbolic link

Thanks！

**Comment by petemoore** [comment]
Can this issue be given the "bug" label?
Are there any plans for a fix?
Thanks.

**Comment by NotTheDr01ds** [comment]
Primarily for Windows 11 users (since it relies the `[boot].command` option in `/etc/wsl.conf`) -- A slight improvement to the [excellent suggestion](https://github.com/microsoft/WSL/issues/5548#issuecomment-990521993) by @wswind.  This approach builds on that one, but doesn't require any change to `/etc/ld.so.conf.d/ld.wsl.conf`:

One time configuration:

```
sudo mount --bind /usr/lib/wsl/lib /usr/lib/wsl/lib2 -o X-mount.mkdir
sudo umount /usr/lib/wsl/lib
sudo ln -s /usr/lib/wsl/lib2/* /usr/lib/wsl/lib
```

Then add the following to `/etc/wsl.conf`:

```
[boot]
command = sleep 10 ; mount --bind /usr/lib/wsl/lib /usr/lib/wsl/lib2 -o X-mount.mkdir ; umount /usr/lib/wsl/lib
```

That:

* Bind mounts the `../wsl/lib` to `../wsl/lib2` (essentially creates a copy of the mount)
* Unmounts the original `/usr/lib/wsl/lib`
* Creates the symlinks so that they live in the directory ldconfig expects

* On subsequent boots, the symlinks will already exist in the filesystem, but the `/init` generated automount will be "hiding" them (and they'd be broken symlinks anyway until the location they are pointing to is mounted).  Mounting the bind-mount and unmounting the `init`-generated one (via `/etc/wsl.conf`) will cause them to show up and be valid.

It's also possible to get this running on Windows 10 using a `wsl.exe -u root mount ...` command-line somewhere in your shell startup.  If anyone wants help with that, let me know.

**Comment by nchj** [comment]
After two years of discussion
Microsoft still has not marked this as a bug
nor has it provided an official solution
But this problem affects everyone who uses GPU in WSL2
It Really Sucks

**Comment by cinderbdt** [comment]
[This](https://github.com/microsoft/WSL/issues/5663#issuecomment-1068499676) worked well for me.

**Comment by hsmiranda** [comment]
> There is another solution works for me :
> 
> * Open cmd as Administrator and cd into C:\Windows\System32\lxss\lib
> * Delete libcuda.so and libcuda.so.1 (You can also do this in Windows Explorer as well)
> * Run `wsl -e /bin/bash` in cmd and you should already in `/mnt/c/Windows/System32/lxss/lib`, now you have permission to create symlink:
> 
> ```shell
>     ln -s libcuda.so.1.1 libcuda.so.1
>     ln -s libcuda.so.1.1 libcuda.so
> ```
> 
> Done.

Works for me, thanks

**Comment by mattjwarren** [comment]
This happens on apt-get upgrade / update for me clear on what the  and I see there ar solutions here - but I am not clear on what speicifc issues result from encountering the `/sbin/ldconfig.real: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link` error?

**Comment by whaaaley** [comment]
> 

Thank you so much for this! I was trying to install imagemagick but ran into this error.

**Comment by whaaaley** [comment]
> I don't want to delete anything under `System32` Make symbolic links in another folder like `/usr/lib/wsl/lib2` would fix this in wsl.
> 
> 1. add `ldconfig = false` to /etc/wsl.conf
> 
> ```shell
> echo -e "[automount]\nldconfig = false" | sudo tee -a /etc/wsl.conf
> ```
> 
> 2. make the symbolic link and use it
> 
> ```shell
> sudo mkdir /usr/lib/wsl/lib2
> sudo ln -s /usr/lib/wsl/lib/* /usr/lib/wsl/lib2
> echo /usr/lib/wsl/lib2 | sudo tee /etc/ld.so.conf.d/ld.wsl.conf
> ```

Thank you so much for this! I was trying to install imagemagick but ran into this error.

**Comment by JasonTan94** [comment]
If you're using WSL2
> 1. Run CMD in Windows (as Administrator)
```
C:
cd \Windows\System32\lxss\lib
del libcuda.so
del libcuda.so.1
mklink libcuda.so libcuda.so.1.1
mklink libcuda.so.1 libcuda.so.1.1
```
> 2. Open WSL bash
```
wsl -e /bin/bash
sudo ldconfig
```

Thanks to @sryio, saves me a ton of time!

**Comment by phillip-elm** [comment]
The steps above worked for me, but I needed to run `wsl --shutdown` before `sudo ldconfig` would work:

```bash
# in cmd as admin
cd C:\Windows\System32\lxss\lib
del libcuda.so
del libcuda.so.1
wsl -e /bin/bash
# in WSL
ln -s libcuda.so.1.1 libcuda.so.1
ln -s libcuda.so.1.1 libcuda.so
exit
# back in CMD
wsl --shutdown
wsl -e /bin/bash
# in restarted WSL
sudo ldconfig
```

_Note: Do this at your own risk. Credit goes to the folks above who figured this out._

**Comment by FlorentDardenne** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. Tous droits réservés.

Testez le nouveau système multiplateforme PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> cd C:\Windows\System32\lxss\lib
PS C:\Windows\System32\lxss\lib> del libcuda.so
PS C:\Windows\System32\lxss\lib> del libcuda.so.1
PS C:\Windows\System32\lxss\lib> wsl -e /bin/bash
florent@DESKTOP-JOMCKBV:/mnt/c/Windows/System32/lxss/lib$ ln -s libcuda.so.1.1 libcuda.so.1
florent@DESKTOP-JOMCKBV:/mnt/c/Windows/System32/lxss/lib$ ln -s libcuda.so.1.1 libcuda.so
florent@DESKTOP-JOMCKBV:/mnt/c/Windows/System32/lxss/lib$ exit
exit
PS C:\Windows\System32\lxss\lib> wsl --shutdown
PS C:\Windows\System32\lxss\lib> wsl -e /bin/bash
florent@DESKTOP-JOMCKBV:/mnt/c/Windows/System32/lxss/lib$ sudo ldconfig
[sudo] password for florent:
ldconfig: Can't link /usr/lib/wsl/lib/libnvoptix_loader.so.1 to libnvoptix.so.1
florent@DESKTOP-JOMCKBV:/mnt/c/Windows/System32/lxss/lib$

I followed the step and still an error (i've no idea what's it means)
> phillip-elm

**Comment by Amarok24** [comment]
> 

I guess your error would be thrown without even touching the libcuda files since it has to do with libnvoptix, have you tried `sudo ldconfig` before?
I just tried the solution by phillip-elm https://github.com/microsoft/WSL/issues/5548#issuecomment-1366418464 and it works for me.

**Comment by Dutra-Apex** [comment]
> If you're using WSL2
> 
> > 1. Run CMD in Windows (as Administrator)
> 
> ```
> C:
> cd \Windows\System32\lxss\lib
> del libcuda.so
> del libcuda.so.1
> mklink libcuda.so libcuda.so.1.1
> mklink libcuda.so.1 libcuda.so.1.1
> ```
> 
> > 2. Open WSL bash
> 
> ```
> wsl -e /bin/bash
> sudo ldconfig
> ```
> 
> Thanks to @sryio, saves me a ton of time!

This solution worked for me, but I had to reinstall CUDA for WSL. After following the instructions here (https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_local) I was able to get to work.

**Comment by julianxhokaxhiu** [comment]
> I don't want to delete anything under `System32` Make symbolic links in another folder like `/usr/lib/wsl/lib2` would fix this in wsl.
> 
> 1. add `ldconfig = false` to /etc/wsl.conf
> 
> ```shell
> echo -e "[automount]\nldconfig = false" | sudo tee -a /etc/wsl.conf
> ```
> 
> 2. make the symbolic link and use it
> 
> ```shell
> sudo mkdir /usr/lib/wsl/lib2
> sudo ln -s /usr/lib/wsl/lib/* /usr/lib/wsl/lib2
> echo /usr/lib/wsl/lib2 | sudo tee /etc/ld.so.conf.d/ld.wsl.conf
> ```

This should be flagged as the real workaround until an official fix is provided. @craigloewen-msft is it possible to have a bit of attention on this one? Should be trivial to be fixed. Thank you

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I've also been seeing this issue for quite some time.  I'm running a custom WSL2 image initially generated from what was then the latest upstream Gentoo 'stage3' tarball as of some time on February 26<sup>th</sup>, 2022 using the instructions from [here](https://developer.moe/gentoo-on-wsl-2) and [the relevant Gentoo Wiki page](https://wiki.gentoo.org/wiki/Gentoo_in_WSL).  I've kept both the default, main Gentoo ebuild repository and another ebuild repository I added later synced and kept my packages up to date by re-'`emerge`'ing them as needed, alongside other package administration/maintenance.  This all started back on some version of 64-bit Intel Windows 10 Pro 21H2&thinsp;—&thinsp;I think that's what must've come with my system, IIRC?&thinsp;—, but I've obviously run several Windows OS and Microsoft Store app updates since then and am currently now on:  

 - 64-bit Intel Windows 11 Pro 22H2, build 22621.1928
 - Windows Feature Experience Pack v1000.22644.1000.0

This has all worked rather well, for the most part.  I'm not going to mess with my System32 folder or any other Windows OS folders/files, obviously, or any WSL2 filesystem mappings.  I'll just wait for an official fix to land.

**Comment by DeForestDiamond** [comment]
I had just fixed this and then started installing docker as soon as I ran the command `$ sudo apt-get install -y docker-ce docker-ce-cli containerd.io` it came back. 

Hope this helps to find the cause. Also, thank you everyone for your fantastic help!

**Comment by avysk** [comment]
Just mentioning: this issue was opened more than 3 years ago...

**Comment by ackalker** [comment]
If no-one at Microsoft gets @mentioned, I don't think much will happen, as this issue has most likely sunk to the bottom of the pile.

**Comment by d3vv** [comment]
```
 wsl -v
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.2416
```

```
# ldconfig
ldconfig: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link

```

Is there any progress here?

**Comment by wizpresso-steve-cy-fan** [comment]
I believe there is a bigger problem on Nvidia side. If I do a soft symlink libcuda.so.1.1 to libcuda.so.1 and libcuda.so respectively in `/mnt/c/Windows/System32/lxss/lib`, `docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody` would fail to launch. I do a hard link for now but I'm not sure if that's viable

**Comment by mosullivan93** [comment]
I have an alternative fix that is applicable to certain WSL installations and doesn't involve deleting anything in System32.

If your WSL is in `C:\Program Files\WSL` (as opposed to `C:\Program Files\WindowsApps\MicrosoftCorporation.blahblahblah`), then you can take advantage of the way WSL overlays its packaged libraries atop the system's libraries and fix the problem without needing to modify the files under `C:\Windows\System32\lxss\lib`.

You can check where `wslservice.exe` is by running: `wmic service where name="wslservice" get pathname`

You can create the links that `ldconfig` wants yourself in `C:\Program Files\WSL\lib` and they'll override the problematic files in your user distributions, and, importantly, the WSLg/System distribution. From an elevated CMD prompt run:
```cmd
mklink "C:\Program Files\WSL\lib\libcuda.so.1" libcuda.so.1.1
mklink "C:\Program Files\WSL\lib\libnvoptix_loader.so.1" libnvoptix.so.1
```

**Comment by avysk** [comment]
Hello, anyone from Microsoft here? The bug is laughably old.

**Comment by vinberg88** [comment]
Paste in Console

`ln -s libcuda.so.1.1 libcuda.so.1
ln -s libcuda.so.1.1 libcuda.so
echo -e "[automount]\nldconfig = false" | sudo tee -a /etc/wsl.conf
sudo mkdir /usr/lib/wsl/lib2
sudo ln -s /usr/lib/wsl/lib/* /usr/lib/wsl/lib2
echo /usr/lib/wsl/lib2 | sudo tee /etc/ld.so.conf.d/ld.wsl.conf`

**Comment by alanlivio** [comment]
Rephrasing @nchj: "After ~~two~~ three years of discussion Microsoft still has not marked this as a bug
nor has it provided an official solution"

**Comment by kizmat** [comment]
> I don't want to delete anything under `System32` Make symbolic links in another folder like `/usr/lib/wsl/lib2` would fix this in wsl.
> 
> 1. add `ldconfig = false` to /etc/wsl.conf
> 
> ```shell
> echo -e "[automount]\nldconfig = false" | sudo tee -a /etc/wsl.conf
> ```
> 
> 2. make the symbolic link and use it
> 
> ```shell
> sudo mkdir /usr/lib/wsl/lib2
> sudo ln -s /usr/lib/wsl/lib/* /usr/lib/wsl/lib2
> echo /usr/lib/wsl/lib2 | sudo tee /etc/ld.so.conf.d/ld.wsl.conf
> ```

This seemed to have solved it for me. 
Thank you.

**Comment by wswind** [comment]
> @wswind [#5548 (comment)](https://github.com/microsoft/WSL/issues/5548#issuecomment-990521993) -Thanks!
> 
> > I don't want to delete anything under `System32` Make symbolic links in another folder like `/usr/lib/wsl/lib2` would fix this in wsl.
> > 
> > 1. add `ldconfig = false` to /etc/wsl.conf
> > 
> > ```shell
> > echo -e "[automount]\nldconfig = false" | sudo tee -a /etc/wsl.conf
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. make the symbolic link and use it
> > 
> > ```shell
> > sudo mkdir /usr/lib/wsl/lib2
> > sudo ln -s /usr/lib/wsl/lib/* /usr/lib/wsl/lib2
> > echo /usr/lib/wsl/lib2 | sudo tee /etc/ld.so.conf.d/ld.wsl.conf
> > ```
> 
> This seemed to have solved it for me. Thank you.

Haha, it's my pleasure. I switched to a laptop without nvidia graphics card and haven't seen the problem since then.

I'm impressed that this issue have been fixed for years. 😂

**Comment by alanlivio** [comment]
Hi all. I still have this problem. Is there no official solution from the WSL team?

**Comment by imaspol** [comment]
Hi all, I've just run into the same bug when installing nvidia drivers into wsl:
`sudo apt-get install -y cuda-drivers`
The message I've got:
`/sbin/ldconfig.real: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link`
Hope my message will wake up the issue...

**Comment by matbee-eth** [comment]
You may have to rebuild your nvidia docker containers for them to see the updated symlinks

**Comment by infish155** [comment]
What would happen if I just ignore it? I dont dare to do anything without official solusion.

**Comment by NotTheDr01ds** [comment]
@infish155 Per the thread above, nothing seems to actually be broken by the error.  Ignoring it is just fine - That's what most others are doing in the meantime :-)

**Comment by BraveDrXuTF** [comment]
> > There is another solution works for me :
> > 
> > * Open cmd as Administrator and cd into C:\Windows\System32\lxss\lib
> > * Delete libcuda.so and libcuda.so.1 (You can also do this in Windows Explorer as well)
> > * Run `wsl -e /bin/bash` in cmd and you should already in `/mnt/c/Windows/System32/lxss/lib`, now you have permission to create symlink:
> > 
> > ```shell
> >     ln -s libcuda.so.1.1 libcuda.so.1
> >     ln -s libcuda.so.1.1 libcuda.so
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Done.
> 
> “failed to create symbolic link 'libcuda.so.1': Permission denied”, what should I do sir

fixed with cmd admin, but another problem arises: CUDA backend failed to initialize: FAILED_PRECONDITION: No visible GPU devices.

**Comment by rodgermoore** [comment]
> Hi all, I've just run into the same bug when installing nvidia drivers into wsl: `sudo apt-get install -y cuda-drivers` The message I've got: `/sbin/ldconfig.real: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link` Hope my message will wake up the issue...

**Once a Windows NVIDIA GPU driver is installed on the system, CUDA becomes available within WSL 2. The CUDA driver installed on Windows host will be stubbed inside the WSL 2 as libcuda.so, therefore users must not install any NVIDIA GPU Linux driver within WSL 2.**

[Source](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#cuda-support-for-wsl-2)

**Comment by BHare1985** [comment]
Running into this myself with both Ubuntu and Debian from the Microsoft Store.

This solved it when run inside the linux terminal:

```
cd /usr/lib/wsl/lib
sudo rm libcuda.so libcuda.so.1
sudo ln -s libcuda.so.1.1 libcuda.so.1
sudo ln -s libcuda.so.1 libcuda.so
sudo ldconfig
```

**Comment by RyanbowZ** [comment]
remember to execute sudo ldconfig after softlink in the directory of /usr/lib/wsl/lib, rather than C:\Windows\System32\lxss\lib
Otherwise your NVidia GPU Driver might fail!

**Comment by ackalker** [comment]
From what I've found, it seems to me that Microsoft has an (undocumented?)
practice of not using any symbolic links in software that they provide with
Windows.

Although the NTFS file system is perfectly capable of creating symbolic
links, it requires enabling Developer Mode as well as ensuring some
additional setting in that category is enabled for non-Administrator users
to be able to do so.

Op za 15 feb 2025 17:56 schreef Lukas Satin ***@***.***>:

**Comment by hfliuyiming** [comment]
This approach will remain effective even after restarting WSL.

```bash
sudo mkdir /usr/lib/wsl/libsym
sudo ln -s /usr/lib/wsl/lib/* /usr/lib/wsl/libsym
sudo cp /etc/wsl.conf ./wsl.conf
cat << EOF >> ./wsl.conf
[automount]
ldconfig = false
EOF
sudo mv ./wsl.conf /etc/wsl.conf
sudo sed -i 's@^/usr/lib/wsl/lib$@/usr/lib/wsl/libsym@' '/etc/ld.so.conf.d/ld.wsl.conf'
```

**Comment by avysk** [comment]
Yes, exactly, it had no activity for the last year, and I do not see how it is a problem of reporter.
