### ISSUE TITLE
Enabling Virtual Machine Platform results in a black screen

### ISSUE THREAD

**Issue by loafylemon** [microsoft/WSL#5617]
# Environment

```none
Windows build number: 10.0.19041 Build 19041
Your Distribution version: N/A
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

1. Install clean version of Windows.
2. Turn on **Windows Subsystem For Linux** in Windows Features.
3. Restart computer. (Optional)
4. Turn on **Virtual Machine Platform** in Windows Features.
5. Restart computer.
6. Results in a black screen.

#  Expected behavior

System should boot up and proceed with installation of WSL-2.

# Actual behavior

System restarts but gets stuck in an infinite black screen after manufacturer's logo. Key combinations (i.e. CTRL+ALT+DEL) do not work, mouse pointer is not shown.

Hard reset with a power button is required, but the issue persists. Using a restoration point made prior to enabling Virtual Machine Platform restores system functionality and allows it to boot normally.

# Additional information

Related Bios Settings:
```none
SVM Mode: Enabled
UMA Frame Buffer: Auto (128M)
```

Device information:
```none
ASUS FX505DY
CPU: AMD Ryzen 5 3550H w/ Radeon Vega 8 
RAM: 2x16 GB @ 2400 MHz
dGPU: Radeon RX560 X
Storage: 256GB NVMe SSD + 1TB HDD
Hyper-V: Fully supported
```

**Comment by therealkenc** [comment]
You'll probably get better feedback in the [microsoft community](https://answers.microsoft.com/en-us/) and [elsewhere](https://www.google.com/search?rlz=1C1CHBF_enCA895CA895&biw=1588&bih=1119&sxsrf=ALeKk009JohqOt-GP9bCsIGHMPoXAUMJBQ%3A1595267903711&ei=P9sVX4z_KrC-0PEPyriyuAU&q=windows+won%27t+boot+hypervisor+platform+sandbox+black+screen&oq=windows+won%27t+boot+hypervisor+platform+sandbox+black+screen&gs_lcp=CgZwc3ktYWIQAzoFCCEQoAE6BwghEAoQoAFQtR9Y5DFg3DNoAXAAeACAAWaIAakJkgEEMTIuMpgBAKABAaoBB2d3cy13aXrAAQE&sclient=psy-ab&ved=0ahUKEwjMmuOFtNzqAhUwHzQIHUqcDFcQ4dUDCAw&uact=5) than here. Can hold open for community suggestions tho. Usually answer is various degrees of "fiddle BIOS harder" or "contact your motherboard manufacturer for assistance".

**Comment by Madac1** [comment]
I have the exact same problem on ASUS TUF FX505DT. 
When trying to install WSL 2, and SVM (virtualization) is enabled, the pc just can't boot and stays in a black screen on startup.

Here is my specs:
CPU: Ryzen 5 3550H
RAM: 2x8GB 2400Hz
GPU: Nvidia GTX 1650
Storage: SSD 256GB nvme

**Comment by PranavH54** [comment]
> I have the exact same problem on ASUS TUF FX505DT. When trying to install WSL 2, and SVM (virtualization) is enabled, the pc just can't boot and stays in a black screen on startup.
> 
> Here is my specs: CPU: Ryzen 5 3550H RAM: 2x8GB 2400Hz GPU: Nvidia GTX 1650 Storage: SSD 256GB nvme

Did you find any workaround? I had to set my UMA buffer size to Auto and it takes about 2 GB of my RAM. I have the exact same laptop as yours.

**Comment by nermineslimane** [comment]
I have the exact same problem did anyone find any solution, UMA buffer size is set to auto in my BIOS settings .
Here are my OS and laptop specs and whenever i activate the feature "Virtual Machine Platform" for WSL2 it results in a freeze my PC goes black and won't start

- OS Name	Microsoft Windows 11 Home Single Language
- Version	10.0.22000 Build 22000
- OS Manufacturer	Microsoft Corporation
- System Manufacturer	ASUSTeK COMPUTER INC.
- System Model	TUF Gaming FX505DD_TUF505DD
- System Type	x64-based PC
- Processor	AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx, 2100 Mhz, 4 Core(s), 8 Logical Processor(s)
- BIOS Version/Date	American Megatrends Inc. FX505DD.317, 3/11/2021
- BIOS Mode	UEFI

**Comment by BearToCode** [comment]
I had a similar issue with the PC not booting up after enabling WSL. After resetting BIOS to default settings it worked just fine. In my case it was due to the RAM frequency being set too high, even though it should have been supported. I'm not sure if it is your same issue but I hope this can help.

**Comment by anirudh09041** [comment]
> I have the exact same problem on ASUS TUF FX505DT. 
> When trying to install WSL 2, and SVM (virtualization) is enabled, the pc just can't boot and stays in a black screen on startup.
> 
> Here is my specs:
> CPU: Ryzen 5 3550H
> RAM: 2x8GB 2400Hz
> GPU: Nvidia GTX 1650
> Storage: SSD 256GB nvme

I am also facing the same problem.
Did you find any solution?

**Comment by raoshaab** [comment]
# Solution 
After enabling the features such as WSL or HyperV, you restart, and if the screen goes black after the restart, you just have to follow a minor fix. 
**Works on Asus TUF laptop.**

Its a UMA buffer issues that is mostly common on AMD CPU

1. Enter the BIOS Menu
2. In Advanced you may see a UMA Buffer size option. Set it to **Auto**, if Auto is not available just don't set it to 128 , 256, or 512.
**UMA = Auto** 
3. Save the changes and restart.
Now you may see the fix working.

**Comment by loafylemon** [comment]
The system still won't boot, even though the UMA buffer setting was already set to Auto, as I explained in my initial post.
Since the problem has persisted for three years, it is safe to assume that ASUS' FX505 devices are the only party responsible for it.

I switched to another computer where the problem does not exist. I think I have no other choice but to close this issue as stale/unresolved.

**Comment by ker2x** [comment]
> I have the exact same problem on ASUS TUF FX505DT. When trying to install WSL 2, and SVM (virtualization) is enabled, the pc just can't boot and stays in a black screen on startup.
> 
> Here is my specs: CPU: Ryzen 5 3550H RAM: 2x8GB 2400Hz GPU: Nvidia GTX 1650 Storage: SSD 256GB nvme

Setting UMA Buffer to Auto in bios on the same hardware (FX505DT) fixed it.

**Comment by FoxWithBoot** [comment]
> # Решение
> После включения таких функций, как WSL или HyperV, вы перезагружаетесь, и если после перезагрузки экран становится черным, вам просто нужно выполнить небольшое исправление. **Работает на ноутбуке Asus TUF.**
> 
> Это проблемы с буфером UMA, которые чаще всего встречаются на процессоре AMD
> 
> 1. Войдите в меню BIOS
> 2. В расширенном вы можете увидеть параметр размера буфера UMA. Установите для него значение **Auto**, если параметр Auto недоступен, просто не устанавливайте его на 128, 256 или 512.
>    **UMA = Auto**
> 3. Сохраните изменения и перезапустите.Теперь вы можете увидеть, что исправление работает.

Thanks a lot. For me this solution worked (ASUS TUF Gaming AMD Windows 10).

**Comment by Daasin** [comment]
Same problem on Steamdeck, UMA buffer is set to 1G by default and there is no 'auto' option (although it's meant to automatically shift as needed) 
 
I've tried setting it to 4G but no luck

**Comment by arkni8** [comment]
Man, there has to be some problem with Windows as well. I had Virtual Machine turned on to run Windows Subsystem on Android. It was working fine and I was blissful for the longest time. About a year now. But then suddenly something happened, I presume an imminent Windows update ***shaking fist*** and now this exact thing seeems to be happening to me too.

For a whole day, I thought that I had fried my iGPU somehow (which would be baffling considering the CPU thats attached to the GPU is running a-okay) but thankfully I had a linux OS installed prior to Windows 11 which opened right up without any problem.

Much fiddling and reinstalling Windows ( I know :/ ), this is where I have ended up after I singled out that this feature is causing the problem.

**Comment by arkni8** [comment]
Update - Thanks to this thread. Setting the UMA Buffer to Auto fixed the problem!

I will post an follow up in case something else goes wrong but most likely it won't? Fingers crossed. I think this is the only viable fix for the problem.

If UMA Buffer doesn't work for you, you might need to live with software rendering on CPU while the Virtual Machine is enabled.

**Comment by Daasin** [comment]
But how does one get Android to work In Windows if this blocks it?

**Comment by amkhrjee** [comment]
> > I have the exact same problem on ASUS TUF FX505DT. When trying to install WSL 2, and SVM (virtualization) is enabled, the pc just can't boot and stays in a black screen on startup.
> > 
> > Here is my specs: CPU: Ryzen 5 3550H RAM: 2x8GB 2400Hz GPU: Nvidia GTX 1650 Storage: SSD 256GB nvme
> 
> Setting UMA Buffer to Auto in bios on the same hardware (FX505DT) fixed it.

This solved it for me on an FX505DY.

**Comment by amkhrjee** [comment]
I have a FX505DY and this used to work fine when I had the pre-installed 8 GB memory. After upgrading the memory to 16 gigs this problem occurred. Setting the UMA Buffer to Auto solved it for me.

**Comment by OniMock** [comment]
This worked for me, but I would like to keep a buffer size for my gpu above 4gb since I only have the integrated graphics card. Would anyone have a solution?

**Comment by Gadzrux** [comment]
I have ASUS TUF gaming fx705dt and I face the same problem I think this is something to do with the TUF gaming models particularly 505 and 705 series (I maybe wrong)

**Comment by AlexAlkhatib** [comment]
Hello my friends.
I have asus tuf gaming fx505 and I am facing the same problem, the screen stops getting black only when I disable VM Technology in BIOS but with that set up, I am not able to use Docker and Virtual Machines anymore on my PC, I need a solution please

**Comment by ker2x** [comment]
> Hello my friends. I have asus tuf gaming fx505 and I am facing the same problem, the screen stops getting black only when I disable SVM in BIOS but with that set up, I am unable to use Docker and Virtual Machines anymore on my PC, I need a solution please

@AlexAlkhatib : The solution has been posted in the comments above.

- Enter the BIOS Menu
- In Advanced you may see a UMA Buffer size option. Set it to Auto, if Auto is not available just don't set it to 128 , 256, or 512.
UMA = Auto
- Save the changes and restart.

Now you may see the fix working.

**Comment by AlexAlkhatib** [comment]
@ker2x
Thanks, your solution works for the moment.

**Comment by Asagher** [comment]
> # Solution 
> After enabling the features such as WSL or HyperV, you restart, and if the screen goes black after the restart, you just have to follow a minor fix. 
> **Works on Asus TUF laptop.**
> 
> Its a UMA buffer issues that is mostly common on AMD CPU
> 
> 1. Enter the BIOS Menu
> 2. In Advanced you may see a UMA Buffer size option. Set it to **Auto**, if Auto is not available just don't set it to 128 , 256, or 512.
> **UMA = Auto** 
> 3. Save the changes and restart.
> Now you may see the fix working.

Thanx its solved in asus tuf gaming fx505dd

**Comment by AlexAlkhatib** [comment]
Hi @Asagher !
I am still getting the same problem, my PC just went down, the solution you gave works from time to time but does not solve the problem permenantly.
Though I desinstalled WSL and desabled Hyper V.
Thanks for trying to help me, I appreciate your response.
