### ISSUE TITLE
Exit code 0xFFFFFFFF at WSL2 distro startup

### ISSUE THREAD

**Issue by timkoers** [microsoft/WSL#6042]
# Environment

```
Windows build number: 10.0.19041.0
Your Distribution version: 20.04 LTS
Whether the issue is on WSL 2: yes
```

# Steps to reproduce

Booting up a distro

**WSL logs**: 

https://aka.ms/AA9vgt2

#  Expected behavior

WSL2 to bootup my distro

# Actual behavior
 
WSL2 is not booting up, my guess that it is something network related since there is no WSL vEthernet adapter created.

**Comment by licanhua** [comment]
Add @benhillis 
The error is in hvsocket:116, and error code is 0x8007273F( An address incompatible with the requested protocol was used.)

**Comment by craigloewen-msft** [comment]
It seems like this error is related to this bug: https://github.com/microsoft/WSL/issues/4364 which is fixed in the latest insiders builds and has been backported. 

Could you let me know the exact output of running the command `ver` in CMD? 

And could you try checking for updates and installing any necessary ones and running WSL again?

**Comment by timkoers** [comment]
> 
> 
> Add @benhillis
> The error is in hvsocket:116, and error code is 0x8007273F( An address incompatible with the requested protocol was used.)

Well my error code is 4294967295, which equals 0xFFFFFFFF



> 
> 
> It seems like this error is related to this bug: #4364 which is fixed in the latest insiders builds and has been backported.
> 
> Could you let me know the exact output of running the command `ver` in CMD?
> 
> And could you try checking for updates and installing any necessary ones and running WSL again?

Microsoft Windows [Version 10.0.19041.546]

It just started installing KB4577063 and after a reboot I still get the exit code 
```
[process exited with code 4294967295]
```

**Comment by benhillis** [comment]
@craigloewen-msft - Do you know which KB has this fix?

**Comment by craigloewen-msft** [comment]
[KB 4577063](https://support.microsoft.com/en-us/help/4577063/windows-10-update-kb4577063) should have the fix for this problem, it's curious you're still seeing this error.

**Comment by bplasmeijer** [comment]
@craigloewen-msft not ok, help required, cannot use wsl.

Package Identity : Package_for_KB4577266~31bf3856ad364e35~amd64~~19041.504.1.2
State : Installed
Release Type : Security Update
Install Time : 9-9-2020 09:18

**Comment by timkoers** [comment]
> 
> 
> [KB 4577063](https://support.microsoft.com/en-us/help/4577063/windows-10-update-kb4577063) should have the fix for this problem, it's curious you're still seeing this error.

I've created a new feedback item containing this error with the new update applied. https://aka.ms/AA9ymri

**Comment by royvou** [comment]
@bplasmeijer could you check/try the following as workaround?
- Is Internet connection sharing enabled?
- Can you delete all hyperv adapters, reboot and let them refreshand try again.
- Are you using any custom VPN client?

When I have/had issues, one of those usually was related.

**Comment by bplasmeijer** [comment]
> @bplasmeijer could you check/try the following as workaround?
> 
> * Is Internet connection sharing enabled?
> * Can you delete all hyperv adapters, reboot and let them refreshand try again.
> * Are you using any custom VPN client?
> 
> When I have/had issues, one of those usually was related.

We run GlobalProject from Palo Alto Networks, and Get-VMNetworkAdapter: ```You do not have the required permission to complete this task. Contact the administrator of the authorization policy for the computer 'XYZ'.```

cc: @craigloewen-msft

**Comment by craigloewen-msft** [comment]
@bplasmeijer can you file a Feedback Hub issue with logs for this and add a link here as a comment?

Instructions on how to do that can be found [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs).

**Comment by bplasmeijer** [comment]
> @bplasmeijer can you file a Feedback Hub issue with logs for this and add a link here as a comment?
> 
> Instructions on how to do that can be found [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs).

Hi @craigloewen-msft see [Feedback Hub issue](https://aka.ms/AA9z1uu)
Thanks in advance
Bart

**Comment by bplasmeijer** [comment]
> > @bplasmeijer can you file a Feedback Hub issue with logs for this and add a link here as a comment?
> > Instructions on how to do that can be found [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs).
> 
> Hi @craigloewen-msft see [Feedback Hub issue](https://aka.ms/AA9z1uu)
> Thanks in advance
> Bart

Hi @craigloewen-msft

After update [October 13, 2020—KB4579311 (OS Build 19041.572)](https://support.microsoft.com/en-us/help/4579311/windows-10-update-kb4579311) my **WSL** is back 🔥

Update (October 1, 2020—KB4577063 (OS Build 19041.546) Preview)[October 1, 2020—KB4577063 (OS Build 19041.546) Preview] **NOT OK**

**Comment by fragrantforest** [comment]
Sorry , I'm chinese , my English is poor , so I will use Chinese to show you my solution.

1、打开设备管理器
2、检查Microsoft Hyper-V 虚拟化基础结构驱动程序 是否被禁用了。如果未启动，把它启动，问题解决。
![3I3GIGQFMV 7IBJMITI@XLC](https://user-images.githubusercontent.com/20220546/104706169-bb3b6280-5755-11eb-842b-6b0e809fdb52.png)

我之前由于要用VMvare，所以禁用了一些Hyper-V相关的一些东西，后来忘记全部恢复回来，所以遇到 wsl2已退出进程代码为4294967295 这个问题。
