### ISSUE TITLE
randomly disappearing x-windows

### ISSUE THREAD

**Issue by matteoguglielmi** [microsoft/WSL#6963]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.985]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020

### Distro Version

Ubuntu 20.04

### Other Software

Package: terminator                      
Version: 1.91-4ubuntu1
State: installed
Automatically installed: no
Priority: optional
Section: universe/misc
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Uncompressed Size: 2,149 k
Depends: python3-cairo, python3-configobj, python3-dbus, python3-gi, python3-gi-cairo, python3-psutil, gir1.2-glib-2.0, gir1.2-gtk-3.0, gir1.2-pango-1.0, gir1.2-vte-2.91, dbus-x11,
         python3:any
Recommends: gir1.2-keybinder-3.0, gir1.2-notify-0.7, xdg-utils
Provides: x-terminal-emulator
Description: multiple GNOME terminals in one window
 Terminator is a little project to produce an efficient way of filling a large area of screen space with terminals.

 The user can have multiple terminals in one window and use key bindings to switch between them. See the manpage for details.
Homepage: https://gnometerminator.blogspot.com/p/introduction.html

### Repro Steps

The most successful way to reproduce the problem is to install a x-server (I'm using Xming 7.7.0.66) and then run terminator.

When the terminator window pops up, just avoid moving the mouse or use the keyboard for about 40/60 minutes (in other words just leave your pc alone for about one hour).

Doing so, the first thing you will notice (most of the times) when moving the mouse again after so much time is that the terminator window will suddenly/immediately disappear from your desktop.

Please note that the terminator window will eventually disappear anyway, even if you keep using windows instead of leaving it alone for such a long time (this happens to me every single day from 1 to 3 times).

Usually, what happens after the terminator/wsl2 crash is that it's not possible to start terminator again (WSL2 must be restarted).

BTW, the same issue occurs when using xterm and/or rxvt (I'm only using WSL2 via those x-terminals, I'm not running any other graphical tool).

### Expected Behavior

terminator window does not randomly disappear

### Actual Behavior

terminator window randomly disappears

### Diagnostic Logs

When terminator cannot be started anymore, this is the log it generates:

$> terminator

Traceback (most recent call last):
  File "/usr/bin/terminator", line 86, in <module>
    dbus_service = ipc.DBusService()
  File "/usr/share/terminator/terminatorlib/ipc.py", line 43, in __init__
    self.prepare_attributes()
  File "/usr/share/terminator/terminatorlib/ipc.py", line 50, in prepare_attributes
    bus = dbus.SessionBus()
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-haXh54TBMQ: Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/terminator", line 107, in <module>
    ipc.new_window_cmdline(optionslist)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 193, in _exec
    bus = dbus.SessionBus()
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-haXh54TBMQ: Connection refused

**Comment by therealkenc** [comment]
> BTW, the same issue occurs when using xterm 

Might be #5339. Try the [work-around](https://github.com/microsoft/WSL/issues/5339#issuecomment-771030005) over there and see if it helps. Destined for de-facto fixed with [WSLg](https://github.com/microsoft/wslg) if not.

**Comment by matteoguglielmi** [comment]
Thank you for the reply!

I'm testing the suggested work-around (so far so good), will post my findings in few days from now.

**Comment by matteoguglielmi** [comment]
After the latest windows patches, the issue is back and the proposed work-around is no longer working.
