### ISSUE TITLE
After latest Windows update I can't run WSL version 2 and Docker is not launching on Windows 10 Enterprise for Virtual Desktop

### ISSUE THREAD

**Issue by cfl-agaidulean** [microsoft/WSL#7332]
### Windows Build Number

Microsoft Windows [Version 10.0.19042.1165]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu-20.04

### Other Software

Docker version 20.10.8, build 3967b7d
Docker Desktop Version 3.6.0.67351

### Repro Steps

Well, I have no exact reproducible steps, the nature of the problem is that after updating to
![image](https://user-images.githubusercontent.com/84081771/130152452-c04daf06-d9d2-44ec-9fbc-8d0f4964203d.png)
![image](https://user-images.githubusercontent.com/84081771/130152509-80fd4a04-75db-4947-a1bb-88fe0e616ef5.png)
![image](https://user-images.githubusercontent.com/84081771/130152536-550fb09e-c83f-47bd-a282-0c5f9fb2177d.png)

I can't change the default/or distribution version to WSL 2.

When I run  `wsl --set-version Ubuntu-20.04 2` I get a fallback to --help.

Running after this

```
wsl --status
Default Distribution: Ubuntu-20.04
Default Version: 1

Windows Subsystem for Linux was last updated on 8/19/2021
WSL automatic updates are on.

Kernel version: 5.10.16
```

```
wsl --list --verbose
  NAME            STATE           VERSION
* Ubuntu-20.04    Stopped         1
```

### Expected Behavior

WSL will change the distro to version 2

### Actual Behavior

![image](https://user-images.githubusercontent.com/84081771/130152645-e32f4127-52dc-4175-a18f-eb6fb2abe12c.png)

**Comment by cfl-agaidulean** [comment]
If someone can assist me on this, as it is blocking me pretty hard on the job and my own investigations around the issue didn't result in success

**Comment by benhillis** [comment]
@cfl-agaidulean - can you share the whole help text?  What SKU of Windows are you running?

**Comment by cfl-agaidulean** [comment]
Whole output after using the command
```
 wsl --set-version Ubuntu-20.04 2
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --distribution, -d <Distro>
        Run the specified distribution.

    --user, -u <UserName>
        Run as the specified user.

Arguments for managing Windows Subsystem for Linux:

    --help
        Display usage information.

    --install [Options]
        Install additional Windows Subsystem for Linux distributions.
        For a list of valid distributions, use 'wsl --list --online'.

        Options:
            --distribution, -d [Argument]
                Downloads and installs a distribution by name.

                Arguments:
                    A valid distribution name (not case sensitive).

                Examples:
                    wsl --install -d Ubuntu
                    wsl --install --distribution Debian

    --set-default-version <Version>
        Changes the default install version for new distributions.

    --shutdown
        Immediately terminates all running distributions and the WSL 2
        lightweight utility virtual machine.

    --status
        Show the status of Windows Subsystem for Linux.

    --update [Options]
        If no options are specified, the WSL 2 kernel will be updated
        to the latest version.

        Options:
            --rollback
                Revert to the previous version of the WSL 2 kernel.

Arguments for managing distributions in Windows Subsystem for Linux:

    --export <Distro> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import <Distro> <InstallLocation> <FileName> [Options]
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

        Options:
            --version <Version>
                Specifies the version to use for the new distribution.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are
                currently being installed or uninstalled.

            --running
                List only distributions that are currently running.

            --quiet, -q
                Only show distribution names.

            --verbose, -v
                Show detailed information about all distributions.

            --online, -o
                Displays a list of available distributions for install with 'wsl --install'.

    --set-default, -s <Distro>
        Sets the distribution as the default.

    --set-version <Distro> <Version>
        Changes the version of the specified distribution.

    --terminate, -t <Distro>
        Terminates the specified distribution.

    --unregister <Distro>
        Unregisters the distribution and deletes the root filesystem.
```


Windows Details:

Edition	Windows 10 Enterprise for Virtual Desktops
Version	20H2
Installed on	‎5/‎11/‎2021
OS build	19042.1165

**Comment by benhillis** [comment]
Very Strange...

/logs

**Comment by cfl-agaidulean** [comment]
```
 wpr -start wsl.wprp -filemode

        The system cannot find the file specified.

        Error code: 0x80070002
```

Even though the file is there.

Also noticed I don't have `C:\Users\<my_name>\.wslconfig`

**Comment by cfl-agaidulean** [comment]
I can't send screenshots unfortunately, due to company policy

**Comment by cfl-agaidulean** [comment]
Can we just check in what logical branch condition causes wsl to fallback to --help when entering --set-version?

**Comment by benhillis** [comment]
That's why I'm asking, that shouldn't be possible.

**Comment by licanhua** [comment]
I'm using the same Windows version, and didn't see this error. Can you run `C:\Windows\System32\wsl.exe --set-version Ubuntu-20.04 2`.
If it doesn't work, you have to provide [logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs)

**Comment by cfl-agaidulean** [comment]
![image](https://user-images.githubusercontent.com/84081771/130201899-89aacb58-fe9e-4687-a4c5-fec6f3440969.png)

It's the same issue.

I created an issue in Feedback Hub with the same name as this Github issue name

**Comment by MMulaosmanovic** [comment]
I had the same issue with KB5005189 on Windows 11 this morning, after uninstalling the update I was able to open WSL again.

**Comment by cfl-agaidulean** [comment]
I am on Win 10 and I don't have this update, from what category is this update
![image](https://user-images.githubusercontent.com/84081771/130246883-b6e61183-ef47-4c51-b378-7dea8a60fe07.png)

**Comment by MMulaosmanovic** [comment]
It was under Quality Updates, installed a few hours ago and after the install I couldnt get Docker Desktop or WSL to start. The update is Windows 11 specific so it will not show up on your Windows 10 instance.

**Comment by cfl-agaidulean** [comment]
OH MY GOD YESSS! Thanks @MMulaosmanovic so much! I was not sure what exact update to uninstall so I removed both KB5005033 and KB4562830. But I believe it was **_KB5005033_** who caused the issue. 

I'll still keep this ticket open for Microsoft to come with a hotfix after that update so my win will be latest version.

![image](https://user-images.githubusercontent.com/84081771/130251537-4b8cc746-4c5b-4c88-931f-2958be490751.png)

**Comment by yyhmsg** [comment]
Not a detailed response, however, fwiw I had the same errors/issues - it could no longer see the default ubuntu even though it was listed it as there - ubuntu wouldn't run and docker would fail.  I added a distro (wsl --install) and in docker unchecked "use default distro" and manually told it to use whatever ones I wanted.  Restarted and all works fine (including the pre-existing ubuntu install). 

It seems like the windows update might lose a pointer of some kind to the default Ubuntu distro and installing another distro possibly? resets whatever it is that keeps track of the distros and allows them to run.

**Comment by licanhua** [comment]
@benhillis  Is "Edition Windows 10 Enterprise for Virtual Desktops" a Windows server?  @cfl-agaidulean is using this version. And  in our code, if it's Windows Server, we will print help message.

@MMulaosmanovic Are you using Windows Server?

**Comment by cfl-agaidulean** [comment]
Any news on this? It seems after each VDI restart the updates are automatically re-applied, at least I know the issue now and easily uninstall them right away but still, annoying.

**Comment by DanielMcAssey** [comment]
Any updates to this? Cant run WSL2 on Server 2022.

**Comment by janegilring** [comment]
Same issue here - uninstalling the KB5005033 update resolved the issue temporarily. Looking forward to a permanent resolution.

**Comment by yyhmsg** [comment]
I don't know if this is relevant or will help others, but I had all the same issues as above - I simply stopped and started wsl2 then installed a new (happened to be different) distro, rebooted, after that everything worked as before with the old and the new distro - and haven't had a problem since (never uninstalled the latest updates).   It seemed, that somehow installing another distro rewired some of the broken internals and made all well again, but YMMW....

**Comment by cfl-agaidulean** [comment]
@yyhmsg Check currently running wsl version, I bet it's v1

**Comment by yyhmsg** [comment]
@cfl-agaidulean no, it's version 2 with all the latest windows updates installed...
wsl -l -v
   NAME                          STATE       VERSION
* Ubuntu-20.04               Running     2
 openSUSE-42               Running     2
 docker-desktop-data     Running     2
 docker-desktop             Running     2

**Comment by cfl-agaidulean** [comment]
@benhillis Hi, is there any progress with fixing this issue? Our developers have a huge problem this, WSL v1 is slow as a temporary measure, and some guys can't uninstall the updates mentioned above.

Please, is there any way we can speed up fixing this stuff?

**Comment by fbordalo** [comment]
I worked around the issue by removing `"proxyHttpMode": false` line from the configuration file. I'm using Windows 10 home edition with the latest security patch. I do not have the security patches noted in the thread, but still had the following issue.

Log error message:
`[09:29:38.296][GoBackendProcess  ][Error  ] msg="while parsing JSON from <...\\AppData\\Roaming\\Docker\\settings.json: json: cannot unmarshal bool into Go struct field Content.proxyHttpMode of type string"`

**Comment by cfl-agaidulean** [comment]
Hey Microsoft please do something with **_KB5005565_**, its heavily impacting our development services, we can't work with WSL 1

Can we get at least an estimation on when it will be fixed? 

Thank you!

**Comment by janegilring** [comment]
@craigloewen-msft Do you know whether the issue is isolated to Windows 10, or also applicable to Windows 11?

**Comment by cfl-agaidulean** [comment]
Thanks for the update. Time to switch to MacOS 💢

**Comment by daniel-anova** [comment]
> I can confirm that uninstalling KB5005565 gets it working again.

Removed the update and was still unable to do `wsl --set-default-version 2`. Did you perform any aditional set after removing the update?

**Comment by mihail-golban** [comment]
> > I can confirm that uninstalling KB5005565 gets it working again.
> 
> Removed the update and was still unable to do `wsl --set-default-version 2`. Did you perform any aditional set after removing the update?
> 
> Edition Windows 10 Enterprise for Virtual Desktops
> Version 21H1
> Installed on ‎6/‎25/‎2021
> OS build 19043.1165

It worked for me!

What steps did I perform:
1. Uninstall KB5005565 update
2. I went into the Windows settings under Apps > Apps and Features and uninstalled Ubuntu
![image](https://user-images.githubusercontent.com/91265279/134740833-be3e774d-3a9f-4e58-a182-7b283331edbd.png)

3. [Download](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi) the Linux kernel update package. [Read more](https://docs.microsoft.com/en-gb/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package)
4. Run the update package downloaded in the previous step. (Double-click to run - you will be prompted for elevated permissions, select ‘yes’ to approve this installation.)
5. Set WSL2 as my default version `wsl --set-default-version 2`
6. Install Ubuntu from Microsoft Store or if it not available you can manually install it using this [link](https://aka.ms/wslubuntu2004).
7. Open up Powershell and run: `wsl -l -v`
![image](https://user-images.githubusercontent.com/91265279/134741844-aa01f23f-3b1d-41be-8d68-bd2b6b1e1d30.png)

Now Docker is launching without any errors.🚀

**Comment by mihailgolban** [comment]
> > I can confirm that uninstalling KB5005565 gets it working again.
> 
> Removed the update and was still unable to do `wsl --set-default-version 2`. Did you perform any aditional set after removing the update?
> 
> Edition Windows 10 Enterprise for Virtual Desktops
> Version 21H1
> Installed on ‎6/‎25/‎2021
> OS build 19043.1165

It worked for me!

What steps did I perform:
1. Uninstall KB5005565 update
2. I went into the Windows settings under Apps > Apps and Features and uninstalled Ubuntu
![image](https://user-images.githubusercontent.com/91265279/134740833-be3e774d-3a9f-4e58-a182-7b283331edbd.png)

3. [Download](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi) the Linux kernel update package. [Read more](https://docs.microsoft.com/en-gb/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package)
4. Run the update package downloaded in the previous step. (Double-click to run - you will be prompted for elevated permissions, select 'yes' to approve this installation.)
5. Set WSL2 as my default version `wsl --set-default-version 2`
6. Install Ubuntu from Microsoft Store or if it not available you can manually install it using this [link](https://aka.ms/wslubuntu2004).
7. Open up Powershell and run: `wsl -l -v`
![image](https://user-images.githubusercontent.com/91265279/134741844-aa01f23f-3b1d-41be-8d68-bd2b6b1e1d30.png)

Now Docker is launching without any errors.🚀

**Comment by mihailgolban** [comment]
> Any news on this? It seems after each VDI restart the updates are automatically re-applied, at least I know the issue now and easily uninstall them right away but still, annoying.

I fixed that by disabling Windows Update service.
![image](https://user-images.githubusercontent.com/32766966/134915499-8ad6da41-16e6-431d-a608-5d9fabb2428c.png)

**Comment by jasonycw** [comment]
> @jasonycw I think the bug may lie in the updates KB5005611, KB5005539. You should uninstall them as well. It might help.

Tried uninstall all those update and it's still not working

Windows even auto install KB5005565 for me during other uninstallation which fail to uninstall :(
![image](https://user-images.githubusercontent.com/4518597/136343143-56c90624-e5d5-465d-b98c-758641c016fa.png)

**Comment by daniel-anova** [comment]
For those that just want docker and can't get WSL2 to work another option is to ignore the docker error until getting settings and disable the WSL2 based engine. This allows to use the older Hyper-V based docker.

**Comment by cfl-agaidulean** [comment]
@craigloewen-msft - do you recall when this change is going out? Was it yesterday?

**Comment by christopherdoyle** [comment]
I was also experiencing this issue on WVD w/ 21H1, but the latest updates seem to have resolved it.

**Comment by cfl-agaidulean** [comment]
Can someone from Microsoft give an official answer around this?

**Comment by rafagsiqueira** [comment]
I am not from Microsoft, but I can confirm that together with the last update, there was also an update to WSL. This seems to have solved the problem.

**Comment by clst** [comment]
It is however not fixed on Server 2022 with the latest updates :(

**Comment by DesktopECHO** [comment]
> It is however not fixed on Server 2022 with the latest updates :( #7666


WSL2 Deosn't run on Windows Server, never did.

**Comment by clst** [comment]
Ah I see. That it worked fine previously was not by design it seems. That should have been communicated better.

This is confusing:  
https://docs.microsoft.com/en-us/windows/wsl/install-on-server  and  
https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server

The FAQ states "desktop" however: https://docs.microsoft.com/en-us/windows/wsl/faq#does-wsl-2-use-hyper-v--will-it-be-available-on-windows-10-home-

**Comment by craigloewen-msft** [comment]
I can help add some clarity here:

Currently, WSL 2 is supported in Windows Virtual Desktop (WVD). Please make sure you take the latest security update (Specifically this November patch Tuesday update) and you will have access to WSL 2 distros. 

WSL 2 is currently supported on [Windows Server versions 2004 and 20H2](https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info).

**Comment by craigloewen-msft** [comment]
The fix is available in [KB5007186](https://support.microsoft.com/en-us/topic/november-9-2021-kb5007186-os-builds-19041-1348-19042-1348-and-19043-1348-033ee59c-e9b7-4eaf-8ee7-b3512bb1a0aa)

**Comment by ecoonradt** [comment]
@craigloewen-msft I am still experiencing this exact same issue on a Windows 11 Enterprise VM running in Azure.  The hotfix referenced above cannot be installed because the OS version is different.  Can this be fixed in Windows 11 as well?

![image](https://user-images.githubusercontent.com/5040738/167451113-5c32316b-a533-43d1-be47-6c2be22362aa.png)

![image](https://user-images.githubusercontent.com/5040738/167451308-0af27d87-3fa6-479f-8a73-6e0052b5a443.png)

**Comment by craigloewen-msft** [comment]
You are on Windows Server 2022, where WSL 2 distros are not currently supported. Please use WIndows server 20H2 until then, we are investigating adding WSL 2 support to Windows Server 2022.

**Comment by rchristman89** [comment]
Is this still an issue on Windows 11 Enterprise multi-session 21H2 (OS Build 22000.978)? I am getting the same issue trying to set the default version to 2.
![image](https://user-images.githubusercontent.com/8922086/191350797-b94cdf57-4a6f-4cb5-9699-fe3ca5317e9f.png)

**Comment by ecoonradt** [comment]
Yeah, that's the exact same thing I still get.  I think @craigloewen-msft misunderstood my comment from earlier this year.  I am not running Windows Server 2022, it's a Windows 11 Enterprise multi-session VM, running in Azure in my case.

**Comment by craigloewen-msft** [comment]
Hey folks if you're running Windows 11 build 22000 on a multi-session VM, then we are aware of a problem where WSL 2 distros aren't accessible. We have a backport in the works to fix this. If you'd like to get immediate access please install the Store version of WSL at: https://aka.ms/wslstorepage

**Comment by ecoonradt** [comment]
Thanks for the update!  With that new Store version of WSL I was able to successfully set the default version to 2.  I was not able to update existing ditstros to v2, but I was able to uninstall and re-install them successfully.  Thanks again!

**Comment by rchristman89** [comment]
@ecoonradt I deployed Win11 22h2 and did not run into the issue if that helps also.
