### ISSUE TITLE
WSL1 STOP Error in Windows 11 / Server 2022 (MEMORY_MANAGEMENT)

### ISSUE THREAD

**Issue by DesktopECHO** [microsoft/WSL#7480]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.194]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

4.4.0-22000-Microsoft

### Distro Version

Kali Rolling / Ubuntu 20.04

### Repro Steps

Windows 11 BugCheck occurs when running Kali-xRDP or Ubuntu 20.04 session over RDP.  
Other users report this is happening in WSL1 console:
- **EXAMPLE**: Install rust using rustup as follows: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` 
- System will BSOD before installation completes.

Can also confirm this issue **does not occur** under Windows 10.

### Expected Behavior

BugCheck-free computing

### Actual Behavior

BugChecks in WSL1

Not just me seeing this:

https://github.com/DesktopECHO/kWSL/issues/11
https://twitter.com/xssfox/status/1434311282824417280

### Diagnostic Logs

[WinDBG-seamonkey.txt](https://github.com/microsoft/WSL/files/7261505/WinDBG-seamonkey.txt)
[WinDBG-spotify.txt](https://github.com/microsoft/WSL/files/7261506/WinDBG-spotify.txt)
[WinDBG-WebKitWebProcess.txt](https://github.com/microsoft/WSL/files/7261507/WinDBG-WebKitWebProcess.txt)

**Comment by Biswa96** [comment]
How to set it up in WSL1 environment?

**Comment by DesktopECHO** [comment]
Install [Kali-xRDP](https://github.com/DesktopECHO/kali-xrdp) and watch some YouTube video in Seamonkey.  It will hapenn in minutes or hours.

**Comment by TheSkorm** [comment]
I hit this running ffmpeg, but not in a repeatable fashion

**Comment by DesktopECHO** [comment]
> I hit this running ffmpeg, but not in a repeatable fashion

Thanks for that info.  I’ve also had trouble repeating this issue as well, but eventually I would hit it.  When you were running ffmpeg, were you using it to view video, or convert a file?  If it was video, were you running Xorg or xRDP at the time?

**Comment by TheSkorm** [comment]
Only to convert. I didn't have any xorg or rdp running

**Comment by DesktopECHO** [comment]
I managed to capture the BSOD in action:

https://user-images.githubusercontent.com/33142753/135947782-40a6db88-d6ee-4ba6-8fd8-e3610b575955.mp4

**Comment by crramirez** [comment]
Hello,

I had the same issue yesterday with a completely unrelated action. I was doing a `dnf update` in Oracle Linux and crashed with the **MEMORY MANAGEMENT** Stop code.

In WSL1 in Windows 11 Release Preview

Regards,
Carlos

**Comment by andirady** [comment]
I'm also having the same problem for Debian on Windows 11 version 10.0.22000 Build 22000
For my case, most crashes are caused by java runtime created by the jlink tool.

**Comment by DesktopECHO** [comment]
> Thanks for reporting, we have identified the fix and are working on getting a change out to Insiders.

I heard that a fix went out to Windows 11 Insiders last month, can anyone confirm if this is the case?

**Comment by Erisa** [comment]
I can confirm that for me ar least this was the case. The latest dev build has no signs of this crash after an extended period of testing. The same machine on 22000 crashes constantly when performing some WSL 1 tasks (Notably compiling Rust/Go applications and doing an apt update)

**Comment by DesktopECHO** [comment]
Thanks for that information!  If it’s not too much trouble can you advise what version Windows you’re running?

**Comment by BigTear** [comment]
> I hit this running ffmpeg, but not in a repeatable fashion 

today  i met it too when i run ffmpeg in wsl ubuntu shell，and before i met it when run pip to uninstall packages...

unpredictable bug annoying me today.

**Comment by crramirez** [comment]
Lastest weeks I have experienced other similar issues. I don't see the blue screen but the PC freezes. And it is always related to WSL1, when I put every distro in WSL2 it stops happening. 

But I have a friend with Windows 11 without this problem at all. Maybe it only happens with AMD CPUs? Someone with Intel?

**Comment by kykc** [comment]
@crramirez yes, my case with `rustup` happened on Intel 10900k

**Comment by raspiduino** [comment]
> I managed to capture the BSOD in action:
> 
>  BSOD.mp4

I got exactly the same thing! On Windows 11 build 22000.556 (stable channel) and also use Kali Linux from the store, also crash when open Firefox in it!

**Comment by raspiduino** [comment]
> Lastest weeks I have experienced other similar issues. I don't see the blue screen but the PC freezes. And it is always related to WSL1, when I put every distro in WSL2 it stops happening.
> 
> But I have a friend with Windows 11 without this problem at all. Maybe it only happens with AMD CPUs? Someone with Intel?

Mine crashed when opening Firefox on WSL on `Dual-Core T4300`

**Comment by zakirmshaikh** [comment]
I got similar issue when i tried to install just aws cli on my wsl ubuntu on windows 11. in 5 second it goes in to Memory_Management_crash

**Comment by crramirez** [comment]
Hello @benhillis 

Do you have any news about this? In my case, I need to make tests in WSL1 to check for regressions and the only way to do them is by using a Windows 10 virtual machine.

Regards,
Carlos

**Comment by matthewlloyd** [comment]
Still reproducible on Windows 11 build 22000.593 after the KB5011563 update, WSL1, AMD system.

**Comment by Erisa** [comment]
As best as I can tell, the issue is fixed in Insider Beta and Dev builds (Build 22581.200 being the latest in both),

The issue is only present on retail/stable/release preview versions right now.

**Comment by mguinhos** [comment]
Also having this problem with Kivy + buildozer + p4a

**Comment by kwaegel** [comment]
No idea when the fix will eventually hit the stable channel, but it's still broken in build 22000.652 (KB5012643).

I use WSL at my day job, and having it randomly crash and take down the entire system is _incredibly_ frustrating right now.

**Comment by Erisa** [comment]
> No idea when the fix will eventually hit the stable channel, but it's still broken in build 22000.652 (KB5012643).
> 
> I use WSL at my day job, and having it randomly crash and take down the entire system is _incredibly_ frustrating right now.

The fix is included as part of the (Currently Beta Channel) preview for what we assume is the next feature update (22H2),  so unfortunatelly unless someone pays attention and backports it to current versions, you will have to wait until that feature update in the latter half of this year or enroll in Insider Beta Channel.

**Comment by kwaegel** [comment]
Unfortunate. I might try to switch over to WSL2 until this is fixed, but WSL2 has it's own problems with [abysmal shared filesystem performance](https://github.com/microsoft/WSL/issues/4197).

My entire rationale for using WSL1 (and WSL in general) is shared development of a common code base, and right now both subsystem versions have significant problems doing that. 😞

**Comment by pratik-chakravorty** [comment]
Is there an ETA on when the fix will be live for stable / release builds? This is really frustrating.

**Comment by DesktopECHO** [comment]
This issue has been resolved in the Windows 11 22H2 Release Preview.

**Comment by matthewlloyd** [comment]
I can confirm this is fixed in today's Windows 11 22H2 public release. Thank you so much!

**Comment by harahauk** [comment]
I just starting getting this on the first dnf update on AlmaLinux in WSL1. BSOD in latest stable build of WIN11 enterprise with memory management as stop code. Tried reinstall of AlmaLinux and it happens again on the dnf update that includes a kernel upgrade.

I first installed the upgrade neccesary for wsl2, but then set wsl1 as default cause i dont want VMWare running on Windows Hypervisor.

**Comment by DesktopECHO** [comment]
> latest stable build of WIN11

What version exactly?

**Comment by harahauk** [comment]
> > latest stable build of WIN11
> 
> What version exactly?

Edition	Windows 11 Enterprise
Version	21H2
Installed on	‎10/‎5/‎2022
OS build	22000.1042
Experience	Windows Feature Experience Pack 1000.22000.1042.0

Features enabled:
Windows subsystem for linux
Virtual machine platform

Additional info of relevance:
I followed the instruction from VMWare here:
hxxps://kb[.]vmware[.]com/s/article/2146361
Maybe this setup is not supported?

No hyper-v support enabled.
Clean install from two days ago, fully updated windows and drivers on a new Lenovo Laptop (Ideapad 5).
I installed a kernel upgrade pack for wsl2, but I am using WSL 1 as default and in this particular distro. I dont expect WSL2 to work as I have disabled hyper-V.

Reliability monitor reports:
The computer has rebooted from a bugcheck.  The bugcheck was: 0x0000001a (0x0000000000042001, 0xffffcd0ee2715d10, 0x0000000000000000, 0x0000000000000000). A dump was saved in: C:\Windows\MEMORY.DMP. Report Id: 57e1eeb6-78f7-4904-8fec-b5a105d5d4a8.

**Comment by Erisa** [comment]
If we ignore insiders for a moment and talk about stable:

This crash occurs on all patched releases of Windows 11 version 21H2 so far, on all build numbers starting 22000.

it was never fixed in a patch to 21H2, but was fixed for the next feature update 22H2 (externally called Windows 11 2022 Update) with build numbers starting from 22621.
22H2 is considered generally available but is part of a rollout and on Enterprise you getting it may depend on other factors.

Unfortunately the only way to fix this crash currently is to upgrade to Windows 11 version 22H2/"2022 Update". I'm not aware of any other fixes or workarounds in the history of this issue.

**Comment by harahauk** [comment]
> If we ignore insiders for a moment and talk about stable:
> [snip]

Thank you for this insight, I will fins a way to patch up my Windows version.

**Comment by DesktopECHO** [comment]
This issuse persists in Windows Server 2022 

BSOD Installing Rust: 
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

Running latest update KB5021249 (Dec 2022)
`Microsoft Windows [Version 10.0.20348.1366]`

**Comment by kdschlosser** [comment]
Just came across this running doxygen.  All windows 11 updates are installed. WSL2 Ubuntu 20.04. 

took an eon for the bsod to complete the crash dump. I am going to see if it does the same thing again after it finishes rebooting.

**Comment by DesktopECHO** [comment]
> Just came across this running doxygen. All windows 11 updates are installed. WSL2 Ubuntu 20.04.
> 
> took an eon for the bsod to complete the crash dump. I am going to see if it does the same thing again after it finishes rebooting.

Highly unlikely this is the same bug, or you’re still on Win 11 21H2.

Issue was confirmed to be fixed in Win11 22H2 but apparently the fix did not land in Server 2022.

**Comment by kdschlosser** [comment]
you are correct. I believe that one of the 32GM sticks of ran went south in my computer. It is no longer showing the correct amount of memory. It is ECC ram too. I have to run some tests to confirm it because I don't actually know when the RAM disappeared from the computer.

**Comment by DesktopECHO** [comment]
Hello @benhillis and @craigloewen-msft
Any idea when this fix will end up in Server 2022?

**Comment by seth586** [comment]
Same problem persists Windows Server 2022, os build `20348.1487`
