### ISSUE TITLE
Arrow Keys Not Working in Visual Studio Code Integrated Terminal

### ISSUE THREAD

**Issue by shavvn** [Microsoft/WSL#770]
Windows Build: 1607.

How to reproduce:

1.Follow the guideline of [VS Code document](https://code.visualstudio.com/docs/editor/integrated-terminal), add bash on windows to integrated terminal in VS Code settings file:

```
"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe"
```

2.Run VS Code (from Windows), open the terminal, type some commands, the arrow keys don't work. (cannot recall last command or move the cursor for editing)

I searched the previous issues and there seemed to be a few other cases, not sure if it's related though, so I just thought I might as well post it here.

**Comment by fpqc** [comment]
Same thing happens with conemu unless you run with certain special console flags.

**Comment by iz0eyj** [comment]
I add that Code won't start using the graphic environment Linux side (XFCE):
[1632:0805/080354:FATAL:render_sandbox_host_linux.cc(40)] Check failed: 0 == shutdown(renderer_socket_, SHUT_RD). shutdown: Argomento non valido (Invalid argument in english).
#0 0x000001befd1e <unknown>
#1 0x000001c05bab <unknown>
#2 0x000001c0616d <unknown>
#3 0x0000025d7752 <unknown>
#4 0x0000023c3f62 <unknown>
#5 0x0000023cac44 <unknown>
#6 0x0000023c35b6 <unknown>
#7 0x00000112c261 <unknown>
#8 0x00000112af50 <unknown>
#9 0x00000307d7ec main
#10 0x7f2a71f51f45 __libc_start_main
#11 0x00000053dee9 <unknown>

**Comment by fpqc** [comment]
I bet the next edition of vs code will have substantial integration with WSL (the way it has ssh remote integration now)

**Comment by wizzard0** [comment]
I believe this is the same issue as #111

**Comment by fpqc** [comment]
@wizzard0 yep, that's the ConEMU thing.

**Comment by NitroAMD** [comment]
This should work now in Version January 2017 (version 1.9): "Windows support
The library used to communicate with the terminal process on Windows has been upgraded which fixes many of the problems the terminal had on Windows such as arrow keys not functioning and the prompt line going out of sync. A special thanks to Ryan Prichard for his winpty library and for assisting with the upgrade."

**Comment by RangerGH** [comment]
I'm running 1.13 and they still do not work on Windows 7.  Am I missing something or did they regress.  If I use the integrated terminal nothing happens when I press the up or down arrow keys so no command recall.

**Comment by fpqc** [comment]
@RangerGH uhhhhhh you can't run WSL on Windows 7.

**Comment by RangerGH** [comment]
I have no idea what WSL is but I'm using VSCode on Windows with the integrated terminal and based on the title thought this the correct bug report.  I missed the reference to bash.

**Comment by therealkenc** [comment]
Duping #111.
