### ISSUE TITLE
After WSL is turned on, the windows11 taskbar and task manager are constantly refreshed.

### ISSUE THREAD

**Issue by cherrol** [microsoft/WSL#8166]
### Version

Microsoft Windows 21H2 OS 22000.588

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

Docker version 20.10.13, build a224086
docker-compose version 1.29.2, build 5becea4c
Node v16.13.2 (inside ubuntu)

### Repro Steps

After starting wsl for a while

### Expected Behavior

N/A

### Actual Behavior

N/A

**Comment by BigTear** [comment]
I also encountered a similar situation.

Whenever I start WSL2 Ubuntu through the Windows Terminal for the first time after win11 restarted, the wt window flickers uncontrollably.

At this time, the input method (Microsoft Pinyin) in my taskbar shows that it is switching between Chinese and English input states constantly - automately(it seems like constantly pressing Shift). I can't input normally in wt. When I use the mouse to focus on the window of other Windows applications, that window will also flicker, and the input method is constantly switching by itself.

In this case, I can only wait or just press any keys on the keyboard and hope that it can return to normal by itself, sometimes it returns to normal, sometimes I can only use the mouse to force close wt to return to normal and when the next time I use wt When I start wsl2-Ubuntu, it will still automatically shift like crazy, and it will take a while to return to normal.

wsl2 can be used normally after returning to normal.

Here's some info from my PC:
Win11: Version 21H2 (OS build 22000.556)
Input method: Microsoft Pinyin (system built-in)

WSLs:
WSL1 (normal, no errors): Alpine v3.15
Kernel: Linux Tc 4.4.0-22000-Microsoft #1-Microsoft Fri Jun 04 16:28:00 PST 2021 x86_64 Linux

WSL2 (crazy): Ubuntu 20.04
Kernel: Linux Tc 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

I can also provide more information if needed.

**Comment by benhillis** [comment]
I'm not able to reproduce this. Are there any interesting events in the event log?

**Comment by cherrol** [comment]
> 我无法重现这一点。事件日志中是否有任何有趣的事件？

What logs should I provide? wsl or windows?

**Comment by MitchTalmadge** [comment]
Hey there. We've noticed this problem over at https://github.com/docker/for-win/issues/12532. It seems that copying an image with an alpha channel into the clipboard will start the flickering. Copying anything else, like text, into the clipboard will stop the flickering.

![demo](https://user-images.githubusercontent.com/8848080/163771774-b52f9847-d98d-4ba5-b974-ea1d7d62fa17.gif)

We initially thought Docker Desktop was causing this issue, but it seems to be related more closely to WSL.

**Comment by cherrol** [comment]
> Hey there. We've noticed this problem over at [docker/for-win#12532](https://github.com/docker/for-win/issues/12532). It seems that copying an image with an alpha channel into the clipboard will start the flickering. Copying anything else, like text, into the clipboard will stop the flickering.
> 
> ![demo](https://user-images.githubusercontent.com/8848080/163771774-b52f9847-d98d-4ba5-b974-ea1d7d62fa17.gif)
> 
> We initially thought Docker Desktop was causing this issue, but it seems to be related more closely to WSL.

I tried this operation, as described and expected.

**Comment by capi** [comment]
Someone in the Docker issue pointed out that the developers over at Greenshot tracked it down to some specific image format being present on the clipboard.
https://github.com/greenshot/greenshot/issues/348

**Comment by cherrol** [comment]
> Someone in the Docker issue pointed out that the developers over at Greenshot tracked it down to some specific image format being present on the clipboard. [greenshot/greenshot#348](https://github.com/greenshot/greenshot/issues/348)
![video](https://user-images.githubusercontent.com/30708661/164197378-4392fa5d-6db6-45ad-a5c8-8e9cacaa20e4.gif)

My operation process is like this.

**Comment by MitchTalmadge** [comment]
Still happening. I'll provide logs soon

**Comment by wischi-chr** [comment]
Could someone reopen this ticket or should we create a new one?

**Comment by MitchTalmadge** [comment]
Here are logs from when the problem is **not** happening at all, as a control group:
[WslLogs-2022-05-31_22-53-41.zip](https://github.com/microsoft/WSL/files/8811173/WslLogs-2022-05-31_22-53-41.zip)

Here are logs containing the following sequence of events:
1. Started with the problem not happening
2. Used greenshot to capture a region of my screen, marked it up, and copied it to my clipboard (to reproduce the problem)
3. The problem begins happening
4. I let the problem run for ~10-15 seconds
5. I save the logs with the problem still happening.

[WslLogs-2022-05-31_22-54-02.zip](https://github.com/microsoft/WSL/files/8811185/WslLogs-2022-05-31_22-54-02.zip)

**Comment by cherrol** [comment]
I can't reopen this issue, i think we need to create a new one.

**Comment by cherrol** [comment]
[WslLogs-2022-06-06_16-06-55.zip](https://github.com/microsoft/WSL/files/8842875/WslLogs-2022-06-06_16-06-55.zip)

This is the problem logs.

**Comment by cherrol** [comment]
Looks like wslg has fixed this.[fix clipboard crash #39](https://github.com/microsoft/weston-mirror/pull/39)

**Comment by MitchTalmadge** [comment]
@cherrol Thanks for finding this. I'll test out the new version and see if it fixes it for me too

**Comment by cherrol** [comment]
The problem was solved after I updated windows and wsl.

**Comment by OneBlue** [comment]
Thanks for the followup @MitchTalmadge .

I was looking at the logs you shared earlier, and I could see weston crashing, which explains the symptoms you were describing.

Glad to hear updating fixed it !

**Comment by MRFU510N88** [comment]
This is still not fixed for me. similar issue, using photoshop or any editor, copy image with an alpha channel to clipboard. 

If I shutdown WSL flickering stops. If I then restart WSL flickering returns. If i hit windows key+v and clear the clipboard. issue goes away. I have also noticed when this 'flickering' starts remote desktop connection is the uppermost utilized in task manager, and goes away as soon as it stops. very strange behaviour.

**Comment by MitchTalmadge** [comment]
> This is still not fixed for me. similar issue, using photoshop or any editor, copy image with an alpha channel to clipboard. 
> 
> If I shutdown WSL flickering stops. If I then restart WSL flickering returns. If i hit windows key+v and clear the clipboard. issue goes away. I have also noticed when this 'flickering' starts remote desktop connection is the uppermost utilized in task manager, and goes away as soon as it stops. very strange behaviour.

Can you please share the output of `wsl --version`

**Comment by didyouexpectthat** [comment]
I'm running into this issue since Windows 11. Never noticed it with Windows 10. Windows 11 21H2. It drastically impacts game performance; my game which renders 360 fps will drop down to double-digit FPS during flicker/refreshes. 
It doesn't happen immediately after starting wsl. I notice my CPU usage increases when the refreshing occurs. I run `wsl.exe --shutdown` and the flickering stops. 
I do use Greenshot and copy images to the clipboard as pngs.  I just tested it and it immediately triggered it. I went to Windows + X and deleted the picture, and it did resolve stop refreshing, which is better than killing wsl.

**Comment by wangziling** [comment]
Hmmm... Still get this problem.

I'm using the windows terminal to use the wsl conveniently.
When some (any) WSL subsystem runs, it may cause the flickering with high odds.

After WSL subsystem stopped, the flickering will stop latter.

I saw that here exists a process named **mstsc.exe** (Microsoft terminal services client) when WSL subsystem runs. Does this program cause this  flickring issue?

Kernel version: 5.10.102.1
Win11 professional edition 10.0.22000.1042

**Comment by mattiusclay** [comment]
Also still getting this, same versions as above!

**Comment by hero3616** [comment]
I am having the same issue. WSL --update didn't help (already latest). I'm on Win 11. Snipping Tool doesn't cause the problem but GreenShot does. Any solution?

**Comment by it-podshivalov** [comment]
I have the same problem.

PS C:\Windows\System32> wsl --version
WSL: 1.0.3.0
Core: 5.15.79.1
WSLg: 1.0.47
MSRDC: 1.2.3575
Direct3D: 1.606.4
DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows: 10.0.22000.1335

**Comment by OneBlue** [comment]
@it-podshivalov: Can you please capture logs ?  and share them here 

/logs

**Comment by dilith2009github** [comment]
> I'm not able to reproduce this. Are there any interesting events in the event log?

it happend to me in windows 10 after i put the computer to sleep and turn it on again when ever i move my mouse it flickers it usually resolves after i restart my computer but now im sick of restrarting every time i out

**Comment by Euynac** [comment]
I also faced the same problem…

**Comment by dilith2009github** [comment]
did you fix or is there any new ways to fix it, please reply

**Comment by Eshchock1** [comment]
> > I'm not able to reproduce this. Are there any interesting events in the event log?
> 
> it happend to me in windows 10 after i put the computer to sleep and turn it on again when ever i move my mouse it flickers it usually resolves after i restart my computer but now im sick of restrarting every time i out

Facing the EXACT same issue, really frustrating no I idea whats going wrong

**Comment by ckdgkwkd27** [comment]
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2506

I also have same problem. what should I do?
Does WSLg 1.0.51 has Same Issue?

**Comment by rabbidave** [comment]
still happening
