### ISSUE TITLE
WSL2 date incorrect after waking from sleep

### ISSUE THREAD

**Issue by q3769** [microsoft/WSL#8204]
### Version

Microsoft Windows [Version 10.0.22581.100]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Release:        20.04

### Repro Steps

1. Leave the Windows system untouched until it goes to sleep.
2. Wait for a while, say an hour.
3. Wake up the computer, and type "date" in WSL 2 shell

### Expected Behavior

WSL 2 date should be the same as Windows date.

### Actual Behavior

WSL 2 date is way behind and slower than the Windows date.

**Comment by mcollier** [comment]
I'm noticing the same thing.  For me, WSL2 time was in sync with the Windows time until I updated to use the Windows Store version of WSL.  Now, whenever my PC resumes from sleep, the WSL2 time is minutes to hours behind.  

To "fix", I will `wsl --terminate` and then restart WSL.

Default Distribution: Ubuntu-20.04
Default Version: 2
WSL version: 0.56.2.0
Kernel version: 5.10.102.1
WSLg version: 1.0.30
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22581.100

**Comment by q3769** [comment]
Yes, this is a regression bug after I updated to the latest Win11 beta push. I also found an earlier bug of the same nature https://github.com/microsoft/WSL/issues/5324

**Comment by longfield-tech** [comment]
Same for me (Ubuntu 20.04)

WSL version: 0.56.2.0
Kernel version: 5.10.102.1
WSLg version: 1.0.30
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22581.200

**Comment by ionutvilie** [comment]
same error; for me, this is not related system going to sleep, the clock is desynchronizing even if my terminal is in the background. 
```
PS C:\Users\xxxxx> date ; wsl date
12 April, 2022 09:17:54
Mon Apr 11 21:13:21 EEST 2022

PS C:\Users\ionut> wsl -v
WSL version: 0.58.0.0
Kernel version: 5.10.102.1
WSLg version: 1.0.32
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22593.1
```

**Comment by dboreham** [comment]
Also seeing this here on ARM64 with the latest Win11 insiders beta build and latest WSL2 kernel:

```
PS C:\Users\david> systeminfo /fo csv | ConvertFrom-Csv | select OS*, System*, Hotfix* | Format-List


OS Name             : Microsoft Windows 11 Pro
OS Version          : 10.0.22598 N/A Build 22598
OS Manufacturer     : Microsoft Corporation
OS Configuration    : Standalone Workstation
OS Build Type       : Multiprocessor Free
System Boot Time    : 4/17/2022, 9:27:16 AM
System Manufacturer : Microsoft Corporation
System Model        : Surface Pro X
System Type         : ARM64-based PC
System Directory    : C:\WINDOWS\system32
System Locale       : en-us;English (United States)
Hotfix(s)           : 3 Hotfix(s) Installed.,[01]: KB5007297,[02]: KB5014100,[03]: KB5014104



PS C:\Users\david> wsl uname -a
Linux cambridge1 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
PS C:\Users\david> date

Sunday, April 17, 2022 9:13:56 PM


PS C:\Users\david> wsl date
Sun Apr 17 12:06:40 MDT 2022
PS C:\Users\david>
```

Somewhat more annoying is that the usual workaround `hwclock -s` no longer appears to work:

```
PS C:\Users\david> wsl -u root hwclock -s
hwclock: Cannot access the Hardware Clock via any known method.
hwclock: Use the --verbose option to see the details of our search for an access method.
PS C:\Users\david>
```

**Comment by dylanwa** [comment]
This is a really annoying issue!  

It blocks any application you're developing with Auth function; you'll get this error message: 
"The ID token is not yet valid. Make sure your computer's time and time zone are both correct."

```
> wsl uname -r
5.10.102.1-microsoft-standard-WSL2
```

wsl datetime is totally out of sync with System datetime
```
>  Get-Date; wsl date

Monday, April 25, 2022 10:53:11 PM
Mon Apr 25 22:37:05 PDT 2022
```

**Comment by dylanwa** [comment]
Found a workaround, set up a Windows scheduled task to update Ubuntu datetime when machine wake up from sleep.
https://github.com/microsoft/WSL/issues/4149

**Comment by RobCannon** [comment]
It looks like this is fixed in release https://github.com/microsoft/WSL/releases/tag/0.65.1!

**Comment by kforeverisback** [comment]
Created a function which I can call at my convenience:
```bash
update_clock () {
        echo '[ROOT] Updating clock (sudo hwclock --hctosys)'
        sudo hwclock -s
        sudo ntpdate time.windows.com
}
```

Since, `hwclock -s` no longer works consistently, I've `ntpdate time.windows.com`, that works as of today.

**Comment by Cosss7** [comment]
https://github.com/microsoft/WSL/issues/7719

Same like this, but still bad utill now.

**Comment by heaths** [comment]
`sntp time.windows.com` didn't work while my machine was in this state - soon after updating to the Windows Store version via `wsl --upgrade`. I ended up having to shutdown WSL and restart it.

**Comment by heaths** [comment]
Not sure if it helps, but I hadn't experienced this problem for a while after the original bug was fixed (back when `sudo hwclock -s` worked) until I upgraded from the MSI-installed WSL2 kernel to the Store-installed package per the prompt I was getting when logging into my distro.

**Comment by Annih** [comment]
@heaths what version do you have exactly?

I upgraded recently both Windows and my WSL but I still get out of sync clock when restoring my session from sleep/hibernate.

My versions:
```WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.521
```

**Comment by tsteven4** [comment]
I still loose clock sync with
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.608

**Comment by heaths** [comment]
> @heaths what version do you have exactly?

```
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.521
```

**Comment by tsteven4** [comment]
I'm still losing sync, now with:

WSL version: 0.70.0.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.674

**Comment by ternst-micado** [comment]
Same issue here, date and time out of sync after sleep.

WSL version: 0.70.0.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.674

**Comment by sabaronett** [comment]
Same.

WSL version: 0.70.0.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.674

**Comment by pacanukeha** [comment]
Same
`wsl -v
WSL version: 0.70.0.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.675`

**Comment by cubeleo** [comment]
This is a constant friction when trying to develop inside WSL2.  Running make, clock skew warnings clog the build output.

**Comment by tage64** [comment]
I agreee, it sucks.

I get all sorts of strange errors due to the clock being incorrect. Sometimes the clipboard hangs, sometimes I can't connect to internet, and sometimes `hwclock -s` rewinds the clock even further.

Imagine you could do the same thing with the physical REAL time. Rewind the time and rewrite history!

**Comment by nwsparks** [comment]
with systemd now available i've installed ntp as a workaround and just restart the service after sleep. still annoying though.

**Comment by haroldiedema** [comment]
`sudo hwclock -s` no longer works after updating. The latest kernel patch only seemed to fix it when the WSL machine initially boots, but as soon as the host machine comes back from sleep, the time is skewed again. Using `hwclock -s` used to fix this, but this also no longer works.

In practice, the patch made things (much) worse...

**Comment by derkoe** [comment]
Same here with 1.0.0.0

```
WSL-Version: 1.0.0.0
Kernelversion: 5.15.74.2
WSLg-Version: 1.0.47
MSRDC-Version: 1.2.3575
Direct3D-Version: 1.606.4
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version: 10.0.22621.819
```

**Comment by wpwoodjr** [comment]
I worked around this by configuring the `systemd-timesyncd` service:
```
sudo apt install systemd-timesyncd
sudo systemctl edit systemd-timesyncd
sudo systemctl start systemd-timesyncd
```
When editing, add the two lines beginning with `[Unit]`, as shown below:
![image](https://user-images.githubusercontent.com/6633152/205764109-a6710872-292d-4567-ad65-3ef341244c61.png)

**Comment by RobCannon** [comment]
That seems to work for me!  I automated the configuration in our setup script with this:

```
# Fix time sync issues in WSL
# https://github.com/microsoft/WSL/issues/8204#issuecomment-1338334154
sudo mkdir -p /etc/systemd/system/systemd-timesyncd.service.d
sudo tee /etc/systemd/system/systemd-timesyncd.service.d/override.conf > /dev/null <<'EOF'
[Unit]
ConditionVirtualization=
EOF
sudo systemctl start systemd-timesyncd
```

**Comment by heaths** [comment]
What are the downsides to running systemd? While I used linux almost exclusively many, many years ago, that predates systemd and all I've seen around the net is hate but haven't really seen why.

**Comment by zyition** [comment]
> `sudo hwclock -s` no longer works after updating. The latest kernel patch only seemed to fix it when the WSL machine initially boots, but as soon as the host machine comes back from sleep, the time is skewed again. Using `hwclock -s` used to fix this, but this also no longer works.
> 
> In practice, the patch made things (much) worse...

@haroldiedema  You can check whether the file `/etc/adjtime` exists or not. I met same issue like you, but after I delete the file `/etc/adjtime`, 
command `hwclock -s` works again. Hope that helps

**Comment by haroldiedema** [comment]
@zyition That file doesn't exist for me. I solved it by running a script from windows every time my machine comes back from sleep/standby to synchronize the WSL clock again. Although very hacky, it works for fresh boots and standby.

**Comment by GenericallyNamed** [comment]
I don't have much to add other than that I am experiencing the same issue as well. 

It's persisted for months, and I can attest that it seems to be related to possibly using sleep mode or similar state rather than shutting down my computer. I use a Surface so normally when done using my machine I normally just close the keyboard cover or press the sleep button. Presumably whenever the computer is put to sleep at some point WSL goes into some state/hibernation that causes the clock to go out of sync, right now it's more than 12 hours behind, which as far as time is concerned, is really frustrating.

One thing in particular I take issue with is that it also affects time and date on files. I use vscode with the WSL remote feature and find that all of the files I create, including things like compiled binaries, have the incorrect time on them. It also extends to using Git! New commits and pushes I make to GitHub also have the incorrect date, making new updates on my repository look as if they are from hours ago.

WSL 2
Kernel version: 5.10.16
Ubuntu version: 20.04.3 LTS
Windows 11 22H2 OS Build 22623.1020

**Comment by makersite-dkeil** [comment]
I also face this issue but I haven't found a reliable trigger for it. It may or may not be triggered by sleep/resume with WSL running but even a WSL shutdown and restart of the VM does not fix it afterwards.

You can sync you clock all day long but if it's the same issue as it is for me, then it won't get you very far, because for me the clock drifts at almost 80k ppm:

```
# chronyc tracking
Reference ID    : B97DBE3A (prod-ntp-5.ntp4.ps5.canonical.com)
Stratum         : 3
Ref time (UTC)  : Wed Dec 14 10:14:02 2022
System time     : 3.982856989 seconds fast of NTP time
Last offset     : -4.546419621 seconds
RMS offset      : 4.450622082 seconds
Frequency       : 74443.312 ppm fast
Residual freq   : -79802.383 ppm
Skew            : 14688.409 ppm
Root delay      : 0.034386788 seconds
Root dispersion : 4.902681828 seconds
Update interval : 63.8 seconds
Leap status     : Normal
```

```
wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.819
```

**Comment by wpwoodjr** [comment]
> You can sync you clock all day long but if it's the same issue as it is for me, then it won't get you very far, because for me the clock drifts at almost 80k ppm:

That frequency increase is chronyc trying to sync you up by increasing the frequency of the clock.  Don't use chronyc as it takes too long.  Use ntp or systemd-timesyncd as above.

**Comment by makersite-dkeil** [comment]
> That frequency increase is chronyc trying to sync you up by increasing the frequency of the clock. Don't use chronyc as it takes too long. Use ntp or systemd-timesyncd as above.

no it's not... from the manpage: *The ‘frequency’ is the rate by which the system’s clock would be wrong if chronyd was not correcting it.*

fyi: chrony is a much better ntp client than the "traditional" ntp client and even systemd-timesyncd

**Comment by wpwoodjr** [comment]
> no it's not... from the manpage: _The ‘frequency’ is the rate by which the system’s clock would be wrong if chronyd was not correcting it._

The frequency is modified by chronyc to perform the sync up.   I tried to use chronyc when I discovered the issue, but it takes a looong time to sync when the time is off by so much.  Use one of the other options and you will be back in business.

**Comment by makersite-dkeil** [comment]
> The frequency is modified by chronyc to perform the sync up. I tried to use chronyc when I discovered the issue, but it takes a looong time to sync when the time is off by so much. Use one of the other options and you will be back in business.
that's how other ntp clients do it as well.. what you're referring to is burst setting the clock once on service startup, which chrony does, too ... or others don't either, depending on configuration.

regardless, the frequency measures how much too fast or too slow the clock is running and at 80k ppm, even syncing every second, will leave you with a clock that's about 40ms off on average.

I appreciate that you had better luck doing something else, but this doesn't necessarily apply universally ... rest assured, I'm confident I know what I'm doing on the Linux side of things and around keeping accurate clocks in particular... 

at any rate, this is an off-topic discussion that only adds noise to this ticket... the matter of the fact is that sometimes, my WSL clock is going so wrong that it'll go wrong by about 80m per second. that's a severe bug and not reasonably fixable with any sort of syncing whatsoever (a good clock will be accurate to single digit ppm or less - even in a VM... this one is 5 orders of magnitude off of that) - the workarounds aren't good enough at all. this needs fixing.

I've yet to find a way to reliably reproduce it, sadly

**Comment by wpwoodjr** [comment]
> rest assured, I'm confident I know what I'm doing on the Linux side of things and around keeping accurate clocks in particular...

Maybe too confident to listen to others' experience?

I'm talking about stepping, not bursting.  For some reason chronyc stepping doesn't work on wsl, so chronyc tries to catch up using only the small frequency shift.  You can see this for yourself if you try the [makestep](https://chrony.tuxfamily.org/doc/3.5/chronyc.html#:~:text=Not%20synchronised.-,makestep,-makestep%20threshold%20limit) command with no parameters.

> **makestep**
> Normally chronyd will cause the system to gradually correct any time offset, by slowing down or speeding up the clock as required. In certain situations, the system clock might be so far adrift that this slewing process would take a very long time to correct the system clock.
> 
> The makestep command can be used in this situation. There are two forms of the command. The first form has no parameters. It tells chronyd to cancel any remaining correction that was being slewed and jump the system clock by the equivalent amount, making it correct immediately.

**Comment by makersite-dkeil** [comment]
> Maybe too confident to listen to others' experience?

Have you considered that different workloads require different clock precision and that some people actually do research and try workarounds before they take their issue to a bug tracker?

> I'm talking about stepping, not bursting. For some reason chronyc stepping doesn't work on wsl, so chronyc tries to catch up using only the small frequency shift. You can see this for yourself if you try the [makestep](https://chrony.tuxfamily.org/doc/3.5/chronyc.html#:~:text=Not%20synchronised.-,makestep,-makestep%20threshold%20limit) command with no parameters.

Yes, by default chrony does not make unreasonably large or unreasonably numerous steps to bring the clock in sync... in it's default config on ubuntu 22.04 it'll step for any clock being more than 1s out of sync but only for the first 3 updates. There's good reasons to prefer skewing the clock into correctness over stepping it.

again... I was talking about a skew of _80,000 parts per million_... even with stepping the clock _every second_, it'd still be off by about 40ms on average without skewing. If that's good enough for your application then more power to you - to me this is a considerable issue.

**Comment by wpwoodjr** [comment]
> this issue is still a bug
Once again, that frequency of 80,000 ppm is due to chrony trying to skew the clock back to the correct time.  Once chrony gets the clock in sync, the frequency will go back to a more reasonable value.

You can test this by stepping the clock manually to the correct time (within a second or so) using the `date` command, then let chrony finish skewing the clock to the (more or less) exact time.  The frequency should settle to a much more reasonable value.

**Comment by makersite-dkeil** [comment]
ok, so here's what I did:

```
~$ sudo systemctl stop chrony
~$ # in Windows, manually trigger a time sync
~$ sudo hwclock -s
~$ sudo systemctl start chrony
~$ # wait a few seconds for chrony to start talking to NTP servers
~$ chronyc tracking
Reference ID    : B97DBE3A (prod-ntp-5.ntp1.ps5.canonical.com)
Stratum         : 3
Ref time (UTC)  : Thu Dec 15 08:57:36 2022
System time     : 0.000000703 seconds slow of NTP time
Last offset     : +0.005346779 seconds
RMS offset      : 0.005346779 seconds
Frequency       : 29948.346 ppm slow
Residual freq   : -11104.643 ppm
Skew            : 2013.957 ppm
Root delay      : 0.043662440 seconds
Root dispersion : 0.634110272 seconds
Update interval : 0.6 seconds
Leap status     : Normal
```

I also came up with this, which idk how meaningfull it is, but there you go:
```
~$ while true ; do date +%S.%N ; sleep 1; done
37.657882577
38.661192891
39.665028530
40.667721855
41.671233246
42.676070889
43.678523570
44.682264484
45.685863034
46.689582035
47.693886220
48.697604929
49.700895714
50.703951778
51.707737129
52.712032999
53.716718919
54.721564093
55.726611469
```
In a perfect world the nanoseconds part would stay virtually identical over iterations... now, I realize that scheduling plays a role as well and maybe sleep isn't using a high resolution timer either, but when I run this on my home server, it'll only deviate by about 1ms per iteration, whereas here you can see it's much more.

**Comment by Se7enSquared** [comment]
I am also experiencing this issue. It's very frustrating and makes it hard to use WSL at all. I have to sync the clock before doing anything.

**Comment by Se7enSquared** [comment]
@makersite-dkeil

Not sure if this workaround could help you, but I've just followed [this guide](https://www.howtogeek.com/746532/how-to-launch-cron-automatically-in-wsl-on-windows-10-and-11/) to auto-start wsl and cron. 

Then I ran `sudo crontab -e` and added these two jobs (probably don't need both but I'm just trying to get this to work so I can do my job!)

```
*/5 * * * * ntpdate time.windows.com
*/1 * * * * hwclock -s
```

I have not tested this yet, but will report back

**Comment by wpwoodjr** [comment]
> In a perfect world the nanoseconds part would stay virtually identical over iterations...

Looks like you have an positive drift of about 3.8 msecs/iteration, but that can be due to the overhead of the while loop, other processes running, etc.

**Comment by wpwoodjr** [comment]
> Not sure if this workaround could help you, but I've just followed [this guide](https://www.howtogeek.com/746532/how-to-launch-cron-automatically-in-wsl-on-windows-10-and-11/) to auto-start wsl and cron.

This might work better for you: https://github.com/microsoft/WSL/issues/8204#issuecomment-1338334154

A bonus, with `systemd`, `cron` is started automatically.

**Comment by woloss** [comment]
> This might work better for you: [#8204 (comment)](https://github.com/microsoft/WSL/issues/8204#issuecomment-1338334154)
> 
> A bonus, with `systemd`, `cron` is started automatically.
Thanks, so far works flawless unlike my tries with `ntp` and `hwlock` , second one still gave big skew.

I guess they should revive this issue #5324.

**Comment by mars2nico** [comment]
Has issue been something patched? -- `hwclock -s` seems to work correctly.

```shell-session
$ date && powershell.exe -Command "Get-Date"
Fri Jan 20 07:23:22 JST 2023

2023年1月20日 7:23:22
$ date && sudo hwclock --hctosys && date
Fri Jan 20 07:24:50 JST 2023
Fri Jan 20 07:25:02 JST 2023

$ date && powershell.exe -Command "Get-Date"
Fri Jan 20 07:25:43 JST 2023

2023年1月20日 7:25:44
```

```shell-session
> wsl --version
WSL バージョン: 1.0.3.0
カーネル バージョン: 5.15.79.1
WSLg バージョン: 1.0.47
MSRDC バージョン: 1.2.3575
Direct3D バージョン: 1.606.4
DXCore バージョン: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windowsバージョン: 10.0.22621.1105
```

**Comment by thantos** [comment]
Not for me with the same version.

```sh
> wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1105
```

```sh
> date
Fri Jan 20 00:42:58 CST 2023
> sudo hwclock --hctosys && date
Fri Jan 20 00:38:31 CST 2023
> sudo ntpdate pool.ntp.org
20 Jan 00:41:27 ntpdate[26461]: 198.211.103.209 rate limit response from server.
20 Jan 10:09:29 ntpdate[26461]: step time server 198.137.202.56 offset 34080.331714 sec
> date
Fri Jan 20 10:09:30 CST 2023
```

`hwclock` seems to work if the clock was already fixed with `ntpdate`.

**Comment by laertis** [comment]
Still experiencing the same issue with `WSL version: 1.0.3.0` although intermittently 

```
λ wsl.exe --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1105
```

* `hwclock -s` never worked for me
* `ntpdate pool.ntp.org` worked but only until restart or another wsl instance or sth else, not sure

I have not identified yet what's cause the intermittent skew in my case but I just did a `wsl --shutdown` in the admin command prompt and when I started wsl again through the windows terminal the date was still correct. I'll come back after a few days of testing with more info

**Comment by SimonLafrikh** [comment]
Facing the same issue recently with this version
```
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1105
```

**Comment by MrDanielCadeau** [comment]
Same Issue here: windows 11 and WSL2 with Ubuntu 22.04

Will see if is enough for me to put a command execution on WSL boot using [/etc/wsl.conf file](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconf).

```shell
ntpdate time.windows.com
```
But is not a good workaround if you need to keep your computer ON.
Thanks for this issue post.

**Comment by jmonoenko** [comment]
I've experienced this issue the past two days when logging in to my work pc.

```
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1105
```

Running the following distro

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

Fixed by running `sudo ntpdate time.windows.com`.

I have added `sudo ntpdate time.windows.com` to my `.bashrc`  and added the following to `visudo` under `# Cmnd alias specification`: `{userName} ALL=(ALL) NOPASSWD:/home/{userName}/.bashrc ntpdate time.windows.com` so the clock is synced on a reboot.

**Comment by DevilYanYan** [comment]
I have been experiencing the issue since like October 2022, it's crazy there's no permanent fix for this yet, 

`sudo hwclock -s`

It still works, but it isn't very pleasant to have to do it constantly, I noticed this the first time when trying to apt update inside a container during the building of the image, and took to forever to figure out this was the issue.

**Comment by stevemandl** [comment]
`sudo hwclock -s` usd to work for me, but a few weeks ago it stopped working. Now I have to open powershell and do a `wsl --shutdown` and then restart it to get the clock back in sync. It would be really nice if this could be fixed. 

Windows 11 WSL 1.0.3.0

**Comment by michaelarnauts** [comment]
You can also install ntpdate and do a ntpdate time.windows.com anytime you resume from standby.

**Comment by heaths** [comment]
> You can also install ntpdate and do a ntpdate time.windows.com anytime you resume from standby.

@michaelarnauts as a triggered event? How is that configured, or does the daemon - if running (well, resuming to a run state) - do that automatically?

**Comment by wpwoodjr** [comment]
> I worked around this by configuring the `systemd-timesyncd` service under `systemd`. Note, this approach seems to modify the time in the parent WSL VM, as such it corrects the time in all WSL distro instances, so probably you only want to implement this in one instance.
> 
> First you have to [enable ](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/#set-the-systemd-flag-set-in-your-wsl-distro-settings)`systemd` for this to work:
> 
> **Set the systemd flag set in your WSL distro settings** You will need to edit the [wsl.conf](https://docs.microsoft.com/windows/wsl/wsl-config#wslconf) file to ensure systemd starts up on boot.
> 
> Add these lines to the `/etc/wsl.conf` (note you will need to run your editor with sudo privileges, e.g: `sudo nano /etc/wsl.conf`):
> 
> ```
> [boot]
> systemd=true
> ```
> 
> And close out of the nano editor using CTRL+O to save and CTRL+X to exit. Now close your WSL distro windows and run `wsl.exe --shutdown` from PowerShell, then restart your WSL instance. Upon launch you should have `systemd` running.
> 
> Now install `systemd-timesyncd`:
> 
> ```
> sudo apt install systemd-timesyncd
> sudo systemctl edit systemd-timesyncd
> ```
> 
> In the second step, when editing, add the two lines beginning with `[Unit]`, as shown below: ![image](https://user-images.githubusercontent.com/6633152/205764109-a6710872-292d-4567-ad65-3ef341244c61.png)
> 
> Now start it:
> 
> ```
> sudo systemctl start systemd-timesyncd
> ```
> 
> Check status with:
> 
> ```
> timedatectl status
> timedatectl timesync-status
> ```

Guys have you tried the above?  Works for me.

**Comment by heaths** [comment]
> Guys have you tried the above? Works for me.

I can't seem to find them now, but I've read there are drawbacks to running systemd on WSL2...though I'm happy to be corrected. There are certainly advantages. IIRC, how the machine sleeps is changed.

**Comment by michaelarnauts** [comment]
> > You can also install ntpdate and do a ntpdate time.windows.com anytime you resume from standby.
> 
> @michaelarnauts as a triggered event? How is that configured, or does the daemon - if running (well, resuming to a run state) - do that automatically?

No, I just run it manually when my docker builds start failing due to apt-get not working, or when I notice my commits are made in the past 😄

**Comment by zzJZzz** [comment]
I first caught this error when I saw my git commits had my most recent changes but was 4 days behind!
 Kernel: 5.15.79.1
 Windows version	10.0.22621 Build 22621
 
 So far `sudo hwclock -s` still works. Had to do it twice so far, 1 last week and 1 today.

**Comment by amykapernick** [comment]
This fix worked for me - https://github.com/microsoft/WSL/issues/8204#issuecomment-1338334154

Even if there are drawbacks, the project I'm working on at the moment means I'm having to restart WSL several times a day, it's worth it

**Comment by amykapernick** [comment]
It also happens when the computer isn't sleeping as well, I turned off sleep and it still happened. Often I'd have to resync the main Windows clock as well, despite it being setup to auto do everything

**Comment by jdblischak** [comment]
I've been fixing this by regularly shutting down WSL, which is super inconvenient. I finally tried the `sudo hwclock -s` trick. This reset the clock, but unfortunately it is still an hour behind, which I don't think anyone has reported above yet.

```
# wsl
$ date
Tue Feb  7 10:04:24 EST 2023
$ sudo hwclock -s
$ date
Tue Feb  7 12:56:11 EST 2023
$ sudo hwclock -s
$ date
Tue Feb  7 12:56:29 EST 2023

# powershell
> date

Tuesday, February 7, 2023 1:59:09 PM

> wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1105
```

**Comment by samikrc** [comment]
For me, just switching on systemd took care of it, since the service `systemd-timesyncd` is switched on my default with systemd. You can check that by running `systemctl list-unit-files --type=service`, as mentioned in the MS page (https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl)

**Comment by wpwoodjr** [comment]
I'm led to believe by the documentation that the default for timesyncd is not to run it in a virtualized environment, so you need to update the config with `sudo systemctl edit systemd-timesyncd` to:

```
[Unit]
ConditionVirtualization=
```

**Comment by tsteven4** [comment]
> I'm led to believe by the documentation that the default for timesyncd is not to run it in a virtualized environment, so you need to update the config with `sudo systemctl edit systemd-timesyncd` to:
> 
> ```
> [Unit]
> ConditionVirtualization=
> ```

Or, as decribed https://github.com/microsoft/WSL/issues/8204#issuecomment-1339506778, add a /etc/systemd/system/systemd-timesyncd.service.d/override.conf file.

**Comment by dboreham** [comment]
Shouldn't a hypervisor present correct hw clock time to its host VMs, without need to resort to running userspace time sync daemons therein?

**Comment by tokenosopher** [comment]
> > I worked around this by configuring the `systemd-timesyncd` service under `systemd`. Note, this approach seems to modify the time in the parent WSL VM, as such it corrects the time in all WSL distro instances, so probably you only want to implement this in one instance.
> > First you have to [enable ](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/#set-the-systemd-flag-set-in-your-wsl-distro-settings)`systemd` for this to work:
> > **Set the systemd flag set in your WSL distro settings** You will need to edit the [wsl.conf](https://docs.microsoft.com/windows/wsl/wsl-config#wslconf) file to ensure systemd starts up on boot.
> > Add these lines to the `/etc/wsl.conf` (note you will need to run your editor with sudo privileges, e.g: `sudo nano /etc/wsl.conf`):
> > ```
> > [boot]
> > systemd=true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And close out of the nano editor using CTRL+O to save and CTRL+X to exit. Now close your WSL distro windows and run `wsl.exe --shutdown` from PowerShell, then restart your WSL instance. Upon launch you should have `systemd` running.
> > Now install `systemd-timesyncd`:
> > ```
> > sudo apt install systemd-timesyncd
> > sudo systemctl edit systemd-timesyncd
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the second step, when editing, add the two lines beginning with `[Unit]`, as shown below: ![image](https://user-images.githubusercontent.com/6633152/205764109-a6710872-292d-4567-ad65-3ef341244c61.png)
> > Now start it:
> > ```
> > sudo systemctl start systemd-timesyncd
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Check status with:
> > ```
> > timedatectl status
> > timedatectl timesync-status
> > ```
> 
> Guys have you tried the above? Works for me.

Trying now. Thanks for the walkthrough. Will let you know how I fare.

**Comment by imdouyu** [comment]
Windows version: 22H2, build: 22621.1265, WSL2    
Still need manually update time by run ` sudo hwclock -s`.

**Comment by fabricioandreis** [comment]
I found a workaround via the Windows Task Scheduler that does not depend upon `systemd`, but uses a Windows system event for the Kernel-Power that specifies when the system is exiting Modern Standby (Event ID: `507`).

Create task in the Windows Task Scheduler:
- Trigger:
  - Begin the task: `On an event`
  - Log: `System`
  - Source: `Kernel-Power`
  - Event ID: `507`
- Action:
  - Program: `C:\WINDOWS\system32\wsl.exe`
  - Add arguments: `sudo hwclock -s`
   
![image](https://user-images.githubusercontent.com/2251524/221428518-8af97407-c279-4135-88b9-e5bc659627c2.png)

**Comment by chainblockHelper** [comment]
@fabricioandreis wasn't able to get this to work. Perhaps a system reboot is needed?

**Comment by fabricioandreis** [comment]
@chainblockHelper, I did not reboot the system to make it work.

My strategy was to put my computer to sleep and wake it up multiple times, and then monitor `Windows Logs` > `System` events to find one that always appeared. The one with the ID 507 consistently showed up. Maybe the ID in other versions of Windows is different.

I'm running Windows 11 Pro:
```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎12/‎05/‎2022
OS build	22623.1325
Experience	Windows Feature Experience Pack 1000.22639.1000.0
```

Did your computer trigger the task? Did you set it up with all options that I mentioned?

**Comment by chainblockHelper** [comment]
@fabricioandreis Thanks for the insights.

I did let the PC go to sleep both manually and organically (overnight). Didn't trigger.  I know `hwclock` requires sudo privileges.  But my logs show it didn't even trigger (and then fail).

My windows Build: 
```
Edition	Windows 11 Home
Version	22H2
OS build	22621.1265
Experience	Windows Feature Experience Pack 1000.22638.1000.0
```

**Comment by fabricioandreis** [comment]
@chainblockHelper, I think the best approach is to split the problem into 2 parts:

1. If it did not trigger, then it's because the Task Scheduler could not find an event with that ID. Did you manage to find an event with that ID in the Event Viewer app? Maybe there is another one with the same meaning but different ID.

2. You could test if the windows command successfully updates the distro instance clock by just opening a regular PowerShell or Command Prompt window, executing `C:\WINDOWS\system32\wsl.exe sudo hwclock -s` and then checking the date in the WSL distro. 
Another possible command could be to force it to update via Network Time Protocol (NTP) with `C:\WINDOWS\system32\wsl.exe sudo ntpdate pool.ntp.org`. 
I should also mention that the `sudo` command works fine for me because my WSL distros do not have a user password set, so it skips authentication.

**Comment by gaia** [comment]
@fabricioandreis @chainblockHelper: scheduled tasks would be a great workaround, but don't bother with for now. there is another bug preventing them from working. I discovered this after spending quite a bit of time trying to get a simple action (`whoami`) to trigger under simple conditions (timed) and it didn't work.

https://github.com/microsoft/WSL/issues/9231

Now could someone tell me please if `systemd-timesyncd` is currently working? Sir @wpwoodjr? Cause I've resorted to putting it on .bashrc for now. Clunky, I know.

**Comment by samikrc** [comment]
@gaia : Definitely working great for me! I run lot of vscode-based python dev, and have not had any problem after setting this up.

**Comment by wpwoodjr** [comment]
Sure, yes @gaia, the `systemd` method works fine.

**Comment by atomlin** [comment]
It somehow started working on my machine, however I have two guys on my team experiencing this daily, is there anyone from Microsoft working on this? The issue still shows unassigned.

**Comment by matthewnourse** [comment]
I wrote a little daemon to work around the problem, I hope you find it helpful.
https://github.com/matthewnourse/polite-hwclock-hctosys

**Comment by wpwoodjr** [comment]
I haven't seen the systemd issues mentioned in your blog post.  systemd-timesyncd working great over here.

**Comment by dimo414** [comment]
Echoing what [juhap saw](https://github.com/microsoft/WSL/issues/5324#issuecomment-1475287750) in #5324, I'm seeing significant skew that isn't corrected by `hwclock -s` within just a few hours of running `wsl --shutdown`:

```
PS > date; wsl date; wsl sudo hwclock

Thursday, March 23, 2023 2:29:47 PM
Thu Mar 23 13:15:51 PDT 2023
2023-03-23 13:15:46.897899-07:00
```

**Comment by MichaelHipp** [comment]
This problem is widespread and ongoing. And the effects can be pretty serious.

**Comment by xirixiz** [comment]
Yep, same issue for a while. Solved in in ~/.basrc
```
(nohup sudo service ntp restart &) &> /dev/null
```

Also added the following with `sudo visudo`
```
# Cmnd alias specification
Cmnd_Alias CNTLM_CMDS = /usr/sbin/service ntp restart
```

To allow ntp to be restarted without requiring the sudo password.

Fixes it, but still, every session I open ntp is restarted in the background. Hurts my mind.

**Comment by gojimmypi** [comment]
a club I did not expect to be a member of:

```
PS C:\Users\gojimmypi> date ; wsl date

Thursday, March 30, 2023 11:36:49 PM
Thu Mar 30 20:15:27 CEST 2023


PS C:\Users\gojimmypi> wsl -v
WSL version: 1.1.6.0
Kernel version: 5.15.90.1
WSLg version: 1.0.50
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1413
```

I'm using the [solution above](https://github.com/microsoft/WSL/issues/8204#issuecomment-1231813357):

```
sudo apt-get install ntpdate

sudo hwclock -s
sudo ntpdate time.windows.com
```

Note that `sudo hwclock -s` alone gets close, but still off by more than 10 minutes:

```
PS C:\Users\gojimmypi> date ; wsl date

Thursday, March 30, 2023 11:48:01 PM
Thu Mar 30 23:36:13 CEST 2023
```

So the real key for accurate WSL time is the `ntpdate`:

```
sudo ntpdate time.windows.com
```

**Comment by githubMichaelYang** [comment]
how can we get better attraction on this? 
<img width="456" alt="image" src="https://user-images.githubusercontent.com/3575931/229210166-8cff121e-683b-4519-98c9-fbfa69d3e431.png">

**Comment by dremsol** [comment]
I noticed the following
```
❯ systemctl status systemd-timesyncd
○ systemd-timesyncd.service - Network Time Synchronization
     Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
  Condition: start condition failed at Tue 2023-04-04 21:05:56 CEST; 12s ago
             └─ ConditionVirtualization=!container was not met
       Docs: man:systemd-timesyncd.service(8)

Apr 02 08:32:49 EAGLE systemd[1]: Condition check resulted in Network Time Synchronization being skipped.
Apr 04 21:05:56 EAGLE systemd[1]: Condition check resulted in Network Time Synchronization being skipped.
```

**Comment by sabbour** [comment]
This is a really painful experience. `wsl --shutdown` throws my off balance as I need to relaunch the WSL windows again and I lose context.

**Comment by shivshanks** [comment]
I think I have a way of reliably reproducing this if anyone from the Microsoft Linux kernel team is watching this thread. 

The key seems to be running WSL2 inside Windows itself running in a Hyper-V VM. Running directly on a Windows host doesn't have the problem. In my problematic case, it's WSL2 running in a Windows 10 VM inside a Windows 11 host. WSL2 kernel and windows are all updated to the latest. Perhaps something is getting lost in the VM inside an VM scenario? 

When I get some time, I will try to reproduce this on another machine with this VM inside a VM scenario.

Feel free to contact me if any traces/logs are needed.

**Comment by wpwoodjr** [comment]
> I think I have a way of reliably reproducing this if anyone from the Microsoft Linux kernel team is watching this thread.
> 
> The key seems to be running WSL2 inside Windows itself running in a Hyper-V VM. Running directly on a Windows host doesn't have the problem. In my problematic case, it's WSL2 running in a Windows 10 VM inside a Windows 11 host. WSL2 kernel and windows are all updated to the latest. Perhaps something is getting lost in the VM inside an VM scenario?
> 
> When I get some time, I will try to reproduce this on another machine with this VM inside a VM scenario.
> 
> Feel free to contact me if any traces/logs are needed.

I had this issue under Windows 11 on a laptop.  For a solution see https://github.com/microsoft/WSL/issues/8204#issuecomment-1338334154

**Comment by captainfalcon23** [comment]
I am having this issue since moving to Windows 11. Using a fresh install of Win 11, WSL, Oracle Linux 7.9. Every time the host sleeps, the time skews out. Here's an example:
```
[XXX ~]$ date
Thu Apr 13 18:51:23 AEST 2023
[XXX ~]$ sudo ntpdate time.windows.com
[sudo] password for XXX:
14 Apr 09:15:15 ntpdate[3858]: step time server 52.148.114.188 offset 51816.353629 sec
[XXX ~]$ date
Fri Apr 14 09:16:53 AEST 2023
```

And right now, can't implement Chrony or anything similar to https://github.com/microsoft/WSL/issues/8204#issuecomment-1338334154 due to https://github.com/microsoft/WSL/issues/9961 :( :( :(

**Comment by craigloewen-msft** [comment]
/dupe #10006

We're migrating all clock skew issues to a megathread so we can keep the top comment up to date with any updates and work arounds. Thank you for filing this!

**Comment by rebroad** [comment]
I'm having this issue also.

C:\Users\rebroad>wsl -v
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1555

**Comment by edyu** [comment]
I use the following to fix the problem now:
<pre>
sudo apt install chrony
sudo systemctl restart chrony.service
</pre>
You do need to install systemd by adding the following lines to `/etc/wsl.conf` and restart wsl with `wsl --shutdown` before al this:
<pre>
[boot]
systemd=true
</pre>

**Comment by leonaAtkins** [comment]
I have this problem.
I've resorted to adding a cron job to update the system clock every hour.

**Comment by taufderl-anvil** [comment]
Why is this issue closed, I still have this problem every day
```
> wsl -v
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2134
```

**Comment by dboreham** [comment]
> Why is this issue closed, I still have this problem every day

It was closed, and a new bug opened, because people kept posting workarounds here (the problem itself needs to be fixed, not worked around). See: https://github.com/microsoft/WSL/issues/8204#issuecomment-1517948969

**Comment by troy-mac** [comment]
dboreham,  then let's get on it Microsoft!!!  This is insane, over a year people have been complaining
and the problem still exists, pretty unacceptable if you ask me.
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2134

**Comment by daglees** [comment]
I'm also experiencing this.

```sh
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2283
```

**Comment by lackovic** [comment]
> Now start it:
> 
> ```
> sudo systemctl start systemd-timesyncd
> ```

Do we need to start it manually every time we open WSL?


> Check status with:
> 
> ```
> timedatectl status
> timedatectl timesync-status
> ```

What's the expected result of these commands? When I run them they give me a bunch of information but it's unclear if they have any effect:

```
$ timedatectl status
               Local time: Wed 2023-09-27 17:57:39 EEST
           Universal time: Wed 2023-09-27 14:57:39 UTC
                 RTC time: Wed 2023-09-27 14:57:37
                Time zone: Europe/Tallinn (EEST, +0300)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

$ timedatectl timesync-status
       Server: 185.125.190.58 (ntp.ubuntu.com)
Poll interval: 32s (min: 32s; max 34min 8s)
         Leap: normal
      Version: 4
      Stratum: 2
    Reference: 5617C31E
    Precision: 1us (-25)
Root distance: 4.172ms (max: 5s)
       Offset: +366.242ms
        Delay: 33.236ms
       Jitter: 507.117ms
 Packet count: 3
    Frequency: -33.471ppm
``` 

`timesync-status` says there is an offset but it's always the same if I run the command multiple consecutive times. When I ran after a few minutes it gives a different offset and it never say if it actually adjusted the time to the correct one.

**Comment by simonerlandsen** [comment]
> ```
> [boot]
> systemd=true
> ```

> ```

this breaks opening vscode from wsl with `code .`

https://github.com/WhitewaterFoundry/Pengwin/issues/635

**Comment by wpwoodjr** [comment]
@simonerlandsen I'm not seeing that in Ubuntu:
![image](https://github.com/microsoft/WSL/assets/6633152/edb0abc2-c753-4038-ad18-6883ff89b90f)

**Comment by wpwoodjr** [comment]
@lackovic 
> Do we need to start it manually every time we open WSL?
> 
No

> What's the expected result of these commands? When I run them they give me a bunch of information but it's unclear if they have any effect:

Just to be sure everything is running.  Looks good in your case.  Just check the WSL time once in awhile to verify its correct.

**Comment by simonerlandsen** [comment]
> @simonerlandsen I'm not seeing that in Ubuntu

Okay, I guess it's not universal, but others has the same issue as me with it, so fair warning

**Comment by russd2357** [comment]
az login fails because time is incorrect. Here's what I did to try and fix it, but was unsuccessful. Normally hwclock -s will remedy the situation, but every now and then it looks like WSL gets stuck and I have to reboot to fix it. Personally, I don't think this issue should be closed.

![error](https://github.com/microsoft/WSL/assets/3382689/7247c513-7a41-446a-bddd-d98628decb8b)

**Comment by pmartincic** [comment]
It's closed because it's marked as a duplicate. I'm locking this thread.
