### ISSUE TITLE
wsl --import hangs

### ISSUE THREAD

**Issue by yshui** [microsoft/WSL#8714]
### Version

10.0.22000.856

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

N/A

### Repro Steps

Run `wsl --import` on a large tarball. (Mine was ~25G)

### Expected Behavior

Import completes successfully.

### Actual Behavior

`wsl` hangs indefinitely. 

I monitored the disk usage and the size of the VM disk image. After a while, the disk usage drops to ~0 and the disk image size stops increasing. I ran import several times, and the final disk image size varied between 4G ~ 19G.

**Comment by yshui** [comment]
I had to create an new distro and unpack the tarball on top of the rootfs manually. The tarball unpacked just fine, so it couldn't be a corrupted tarball.

**Comment by nicholasio** [comment]
I'm having the same issue. I'm trying to move the install location to a different disk.

**Comment by LeeEdgoose** [comment]
Having a similar issue

Windows 10 21H2 multisession instance in Azure VDI. 

run wsl --import Ubuntu *install location* *tar location* --version 2

Vmem in task manager starts to ramp up and the ext4.vhdx starts to increase in size and then both stall. wsl becomes unresponsive at this point and wsl --shutdown just hangs. vmem still shows up in processes, no memory usage fluctuation. Have to fully shutdown the Azure VM which takes ages to deallocate due to the lock up.

Currently using FSLogix Profile containers but have experienced this issue with and without FSLogix utilisation.

I have had the import job complete several times but it seems to be pot luck as to whether it stalls and locks up or not

**Comment by JHNP727** [comment]
seeing the same issue, attached logs
[WslLogs-2022-08-17_12-27-22.zip](https://github.com/microsoft/WSL/files/9358862/WslLogs-2022-08-17_12-27-22.zip)

**Comment by qiyuey** [comment]
[WslLogs-2022-08-20_00-55-52.zip](https://github.com/microsoft/WSL/files/9383980/WslLogs-2022-08-20_00-55-52.zip)

**Comment by nanasess** [comment]
[WslLogs-2022-08-20_11-04-33.zip](https://github.com/microsoft/WSL/files/9386042/WslLogs-2022-08-20_11-04-33.zip)

**Comment by jaykrell** [comment]
I have had wsl --import running about 4 days.
I am running a recent rsprerelease arm64 build.

**Comment by nanasess** [comment]
After downgrading to WSL 0.56.1, we fixed it with reference to the comments below.
https://github.com/microsoft/WSL/issues/4735#issuecomment-1039886803

**Comment by uniartisan** [comment]
[WslLogs-2022-08-23_17-02-45.zip](https://github.com/microsoft/WSL/files/9401048/WslLogs-2022-08-23_17-02-45.zip)
Same problem.
```
 wsl --version
WSL 版本： 0.65.3.0
内核版本： 5.15.57.1
WSLg 版本： 1.0.41
MSRDC 版本： 1.2.3213
Direct3D 版本： 1.601.0
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22000.856
```

**Comment by nicholasio** [comment]
Has this been fixed? not sure if it should be closed.

**Comment by gbiagini** [comment]
I'm currently having this problem on 2 machines.

About to test on a third. Import invariably hangs, albeit at different points in the process.

**Comment by yshui** [comment]
Hello? Many people has replied with their logs, can someone reopen this please? @owenschupp

**Comment by owenschupp** [comment]
Reopening issue; thank you all for providing logs!

**Comment by w93163red** [comment]
I also have this issue.


[WslLogs-2022-08-31_14-28-01.zip](https://github.com/microsoft/WSL/files/9464373/WslLogs-2022-08-31_14-28-01.zip)

**Comment by w93163red** [comment]
After downgrading to the official version (removing WSL for preview in MS Store and reinstalling from turn-on features), I can successfully import the tar file

**Comment by kovan** [comment]
If you are running Windows 11 Insiders program and you opt out of it and reset Windows to the standard version, you can sucessfully do the import.

**Comment by xcgspring** [comment]
Encounter this issue too

**Comment by ishepherd** [comment]
[WslLogs-2022-10-03_11-04-33.zip](https://github.com/microsoft/WSL/files/9693937/WslLogs-2022-10-03_11-04-33.zip)

@owenschupp this problem has been dormant for awhile, can you please find someone to assign to? [I will also email Insider Support per this instruction](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#7-additional-information)

**Comment by davidritter** [comment]
I am also seeing this issue importing from an old machine to a new one. Happy to contribute any additional log files but it seems like there is an abundance of diagnostic information already available. 
I'm using the latest GA version of `wsl 0.66.2.0`

**Comment by asifmohtesham** [comment]
I am facing the same issue as well.

> I see the same symptoms. `wsl.exe --import` hangs indefinitely. It seems to be unpacking the disk image and the unpack just stops at some random point and never makes further progress.
> 
> [WslLogs-2022-10-03_11-04-33.zip](https://github.com/microsoft/WSL/files/9693937/WslLogs-2022-10-03_11-04-33.zip)
> 
> @owenschupp this problem has been dormant for awhile, can you please find someone to assign to? [I will also email Insider Support per this instruction](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#7-additional-information)

**Comment by black-snow** [comment]
Same, super annoying. Also docker stopped working. Will try to get an older WSL version.

**Comment by kerenkxs2** [comment]
Also experiencing the same problem.

**Comment by BobbyWibowo** [comment]
I can also confirm that my ~26GB tar finally imported successfully after uninstalling WSL "Preview"

I just did `wsl --update` afterwards to re-install the "Preview" updates

**Comment by black-snow** [comment]
@BobbyWibowo what updates? Am I missing out on something? ;)

**Comment by ishepherd** [comment]
Uninstalling the [WSL preview app](https://aka.ms/wslstorepage) (ms-windows-store://pdp/?productid=9P9TQF7MRM4R) did not help me.

No surprise as the versions output by `wsl.exe -v` were exactly the same, whether I'd installed from the store, or from `wsl.exe --install --web-download`.

However I am fixed anyway :tada::

I was following the detailed instructions from @murrahjm https://murrahjm.github.io/Exporting-WSL-data/ but I think WSL has evolved since those were written.

[What I ended up doing was `wsl.exe --import` into a completely bare directory following these instructions.](https://stackoverflow.com/a/65161328) It created the vhdx, only, in that bare directory and registered the new distro properly.

Shout out to @craigloewen-msft - Would be great to have a canonical article on how to migrate a WSL distro between machines?

**Comment by AnonHax0r** [comment]
So I found this issue, I am having it as well on Windows 11 2H2 fully updated. My solution? Reboot the PC and open NO apps you do not need (browser is fine). Navigate in file explorer to where you are SAVING the imported instance. Start the import process you should see the vhdx form in the folder you navigated to. If you have access to the old machine, you will want to look at the vhdx file and get the size and keep that as a rough target, but you are going to patiently watch the task manager and that file grow, if you see disk usage stop or the file stop growing for more than 15 seconds restart the import and repeat this until it works. I had a 12.5gb tarball, took me about 10 tries and it finally imported and is working! Hope this helps until a fix is applied.

**Comment by ematt70** [comment]
Same issue.  Logs attached.
[WslLogs-2022-10-19_09-10-56.zip](https://github.com/microsoft/WSL/files/9821205/WslLogs-2022-10-19_09-10-56.zip)

**Comment by soup501** [comment]
> So I found this issue, I am having it as well on Windows 11 2H2 fully updated. My solution? Reboot the PC and open NO apps you do not need (browser is fine). Navigate in file explorer to where you are SAVING the imported instance. Start the import process you should see the vhdx form in the folder you navigated to. If you have access to the old machine, you will want to look at the vhdx file and get the size and keep that as a rough target, but you are going to patiently watch the task manager and that file grow, if you see disk usage stop or the file stop growing for more than 15 seconds restart the import and repeat this until it works. I had a 12.5gb tarball, took me about 10 tries and it finally imported and is working! Hope this helps until a fix is applied.

this works for me - exported an Ubuntu instance yesterday for a new CPU install, went to import and it got stuck ~7 times before it succeeded.

I did like you said and monitored the size of the folder as it was going through the import and ctrl-c'ing it whenever it stopped increasing. Looks like it's a recent bug as I did a similar thing a few months ago and it worked with no issues.

**Comment by Jason0-0** [comment]
now the wsl will warn you to update the kernel or you can't import the tarball. However, when you update it by using `wsl --update` it will install the wsl preview by default, which make the importing fail. 
The solutiont  to this problem is downning the upgrade pack from the wsl github site:[https://learn.microsoft.com/zh-cn/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package](url)

**Comment by AndreaLanfranchi** [comment]
```
Versione WSL: 0.70.0.0
Versione kernel: 5.15.68.1
Versione WSLg: 1.0.45
Versione MSRDC: 1.2.3575
Versione Direct3D: 1.606.4
Versione DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
versione Windows: 10.0.22621.674
```

So I have the very same issue and [this post](https://github.com/microsoft/WSL/issues/8714#issuecomment-1279286156) helped me solve the problem : worth to mention though I **also had to disable AV real time protection**.

**Comment by movusae** [comment]
same to me. I had tried more than 10 times
![image](https://user-images.githubusercontent.com/114342753/198825913-b970cf17-4229-413c-8caf-b2cec8c23285.png)

**Comment by fscheuMoba** [comment]
I have the same problem with my 110 GB tar that I exported with a very old WSL version (that had a version number like 10.0.XX). Tried many times to import (20+), but the import got stuck on every try at a random size of the vhdx file (most of the time something between 0.5 GB and 15 GB). 
For me there was no other option than installing fresh Ubuntu and manually copy my files from the tar to the newly installed distribution.

My current WSL versions:
```
WSL-Version: 0.70.4.0
Kernelversion: 5.15.68.1
WSLg-Version: 1.0.45
MSRDC-Version: 1.2.3575
Direct3D-Version: 1.606.4
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version: 10.0.22000.1098
```

**Comment by asifmohtesham** [comment]
> I have the same problem with my 110 GB tar that I exported with a very old WSL version (that had a version number like 10.0.XX). Tried many times to import (20+), but the import got stuck on every try at a random size of the vhdx file (most of the time something between 0.5 GB and 15 GB). For me there was no other option than installing fresh Ubuntu and manually copy my files from the tar to the newly installed distribution.
> 
> My current WSL versions:
> 
> ```
> WSL-Version: 0.70.4.0
> Kernelversion: 5.15.68.1
> WSLg-Version: 1.0.45
> MSRDC-Version: 1.2.3575
> Direct3D-Version: 1.606.4
> DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows Version: 10.0.22000.1098
> ```

I was able to reach up to 40 GB, but then it hung. My tar file is 46 GB.

**Comment by protango** [comment]
I had to import a 160GB tarball and it just wasn't working. I fixed it by uninstalling WSL via control panel, and then re-installing WSL 2 using the manual installation method here: https://learn.microsoft.com/en-us/windows/wsl/install-manual.

After that it was able to import my 160GB tar backup fine 😁.

**Comment by Fanduzi** [comment]
same issue

**Comment by manjoc** [comment]
resolved it only using super admin in power shell

**Comment by jhzsyang** [comment]
Thanks @protango ! Resolved it by deleting WSL preview and manually installing WSL 2 when importing a 30 GB tar file.

> I had to import a 160GB tarball and it just wasn't working. I fixed it by uninstalling WSL via control panel, and then re-installing WSL 2 using the manual installation method here: https://learn.microsoft.com/en-us/windows/wsl/install-manual.
> 
> After that it was able to import my 160GB tar backup fine 😁.

**Comment by smallcrustation** [comment]
Having the same problem. Originally installed WSL2 manually. Also Tried preview.

**Comment by keai4le** [comment]
Windows11 preview beta channel latest
I just uninstall the WSL preview and then wsl --set-version/wsl --import work fine(the ext4.vhdx size increase normally so far)

**Comment by khanhnt93** [comment]
open setting -> Apps -> Installed apps -> find wsl preview -> uninstall.
Try wsl --import again, it's normally after that

**Comment by Jan1torEarl** [comment]
Same issue here with 6GB tar backup. After several failed attempts of cancelling and re-starting, uninstalling WSL preview and then following "manual" steps from https://learn.microsoft.com/en-us/windows/wsl/install-manual worked!

Should note I started on the WSL version that ships with Windows 11 as I upgraded with a complete format on a new computer.

Now I can get back to work. Very helpful thread, big thanks to everyone.

**Comment by mattschlosser** [comment]
Uninstalling WSL preview did the trick for me.

**Comment by ngurajeka** [comment]
Encounter the same issue today, was trying to import ~150GB backup file.
After uninstalling the WSL Preview, the import process working properly.

**Comment by kwaegel** [comment]
Same issue, same fix via uninstalling the WSL Preview.

**Comment by osorionicolas** [comment]
Seems to be fixed on the latest release 0.78.0 (pre-release) and do not see the hang issue anymore.

**Comment by widoz** [comment]
I've had the same problem yesterday and fixed it by uninstalling WSL Preview.
@osorionicolas are you talking about the Preview version?

**Comment by osorionicolas** [comment]
@widoz Yes, I'm using the Preview version

**Comment by widoz** [comment]
@osorionicolas But isn't the [0.70.8](https://github.com/microsoft/WSL/releases/tag/0.70.8) the latest one? I do not read anything about import fixes 🤔 .

**Comment by osorionicolas** [comment]
Idk, I was with this same error and after update to that version it worked with a file of ~60GB

**Comment by Skaggio** [comment]
I fixed the issue on my side by using the "wsl --update" command: the "WSL version" reported in the output of the "wsl --version" command increased from "0.70.4" to "1.0.0.0" after the update and then I imported a 56GB tar at first attempt (whereas the import had always failed with the previous version).
HIH!

**Comment by ishepherd** [comment]
[Tweet from @craigloewen-msft regarding this issue](https://twitter.com/craigaloewen/status/1592985437093494784):

> Can you try build 1.0.0 and see if it fixes you? There was a potential fix for this there.

**Comment by c01o** [comment]
Sadly I'm still having the issue for 180GB image on wsl 1.0.1.0

**Comment by DaneDuPlooy** [comment]
Same problem

WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.963

tar is ~165GB, ext4.vhdx doesn't get past about max 6GB before "hanging".

Windows 11, I haven't tried the uninstall / manual re-install yet (no WSL "Preview" under apps).

**Comment by ThisIsRuddy** [comment]
I stumbled on a way to get around this using LxRunOffline, please see steps below

Hope this helps some people :)

```
//install chocolatey (PowerShell)
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

choco install lxrunoffline

//Add to PATH env
C:\tools\lxrunoffline

//import wsl image (-n name / -d install directory / -f tar file)
LxRunOffline install -n Ubuntu-Default -d C:\wsl -f C:\Ubuntu.tar
```

**Comment by syjcnss** [comment]
Same problem

WSL 版本： 1.2.0.0
内核版本： 5.15.90.1
WSLg 版本： 1.0.51
MSRDC 版本： 1.2.3770
Direct3D 版本： 1.608.2-61064218
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows 版本： 10.0.22621.1555

**Comment by a1393323447** [comment]
I have the same issue. I found a helpful tool: [LxRunOffline](https://github.com/DDoSolitary/LxRunOffline).

**Comment by garyo** [comment]
I'm seeing the same issue, trying to import Rocky Linux 8.
```
PS C:\Users\garyo> wsl --update
Checking for updates.
The most recent version of Windows Subsystem for Linux is already installed.
PS C:\Users\garyo> wsl --version
WSL version: 2.0.6.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.22635.2552
```
Uninstalled the preview, didn't seem to make any difference.

**Comment by azizp128** [comment]
Move the tarball file to another SSD/HDD first, then import it to your machine. It worked for me.

**Comment by ckagerer** [comment]
Yesterday we also had the problem here with a tarball approx. 180 GB in size.
The high memory consumption of “Vmmem” was noticeable.
So I assigned more RAM and swap in the .wslconfig and then it worked. The memory consumption of Vmmmem then increased to >25GB during the import.

Here is my .wslconfig:

```ini
[wsl2]
# Limits VM memory to use no more than x, this can be set as whole numbers using GB or MB.
memory=64GB

# Sets amount of swap storage space to x, default is 25% of available RAM
swap=64GB

# Sets swapfile path location, default is %USERPROFILE%\AppData\Local\Temp\swap.vhdx
swapfile=D:\\wsl_swap.vhdx
```

Maybe it will help someone else.

By the way, the tip about importing from another drive didn't work for us.

**Comment by epiciskandar** [comment]
> Yesterday we also had the problem here with a tarball approx. 180 GB in size. The high memory consumption of “Vmmem” was noticeable. So I assigned more RAM and swap in the .wslconfig and then it worked. The memory consumption of Vmmmem then increased to >25GB during the import.
> 
> Here is my .wslconfig:
> 
> [wsl2]
> # Limits VM memory to use no more than x, this can be set as whole numbers using GB or MB.
> memory=64GB
> 
> # Sets amount of swap storage space to x, default is 25% of available RAM
> swap=64GB
> 
> # Sets swapfile path location, default is %USERPROFILE%\AppData\Local\Temp\swap.vhdx
> swapfile=D:\\wsl_swap.vhdx
> Maybe it will help someone else.
> 
> By the way, the tip about importing from another drive didn't work for us.

This helped me, also I restarted the machine to ends hanging wsl process.
