### ISSUE TITLE
`systemd status` fails output on Ubuntu

### ISSUE THREAD

**Issue by elsaco** [microsoft/WSL#8879]
### Version

10.0.22621.521

### WSL Version

- [ ] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.62.1

### Distro Version

Ubuntu 22.10

### Repro Steps

install Ubuntu (Preview), store id 9P7BDVKVNXZ6. This version has systemd already enabled.

### Expected Behavior

`systemctl status` command to work

### Actual Behavior

```
toor@XPS:~$ systemctl status
Failed to dump process list for 'XPS', ignoring: Input/output error
● XPS
    State: degraded
    Units: 318 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 1 units
    Since: Sat 2022-09-24 08:43:15 PDT; 14min ago
  systemd: 251.4-1ubuntu6
  Tainted: cgroupsv1
   CGroup: /

```

It doesn't work on ArchLinux also:

```
[toor@XPS ~]$ systemctl status
Failed to dump process list for 'XPS', ignoring: Input/output error
● XPS
    State: running
    Units: 243 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 0 units
    Since: Sat 2022-09-24 08:51:04 PDT; 14s ago
  systemd: 251.4-1-arch
  Tainted: cgroupsv1
   CGroup: /

```

Both WSL instances run `systemd-251.4`, so this could be a `systemd` issue. It works okay on Ubuntu 22.04 and `systemd-249.11`.

**Comment by cerebrate** [comment]
Yeah, this one's been happening since systemd 250 shipped, under all the systemd hacks and now under the official support.

**Comment by Skepfyr** [comment]
I've done some investigating:
This regression was introduced by systemd/systemd@038cae098b6d85ad9fb06594d36f49915d32f000, which comes from this PR systemd/systemd#21172. It's possible this is related to systemd/systemd#22089 but I'm not sure as it's slightly different symptoms and isn't fixed on main. That commit was a change to `systemctl status` to use the systemd dbus instead of "directly via cgroupfs" (I'm not sure what that means). I can replicate this bug by calling the dbus directly with `busctl call -- org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager GetUnitProcesses 's' '-.slice'`. Some code diving suggests that the cause of the IO error is that systemd is not expecting to see zero PIDs in `/sys/fs/cgroup/unified/cgroup.procs`, which I have a bunch of, I believe they're there because systemd is in a PID namespace but not in a new cgroup.

I see 3 possible places the bug might be:
1. That `systemctl status` code: it possibly shouldn't be making that dbus call in that way, however, I'm skeptical as that API sounds sensible from its name.
2. The systemd dbus handler for that method: [systemd/systemd:src/core/dbus-unit.c:1310](https://github.com/systemd/systemd/blob/e56074a2121d2db7964321156fe522232b16034d/src/core/dbus-unit.c#L1310), specifically this line that generates the IO error [systemd/systemd:src/basic/cgroup-util.c](https://github.com/systemd/systemd/blob/main/src/basic/cgroup-util.c#L83), that generates an error because of the previously mentioned zeros in `/sys/fs/cgroup/unified/cgroup.procs`.
3. The WSL handling of cgroups: it's possible that systemd shouldn't observe zeros in its root cgroup. The [systemd container interface](https://systemd.io/CONTAINER_INTERFACE/) suggests that systemd should be running in a new cgroup, but I don't know if that is required.

**Comment by cerebrate** [comment]
I think it is 3; that's the same root cause @nullpo-head figured out for the problem when it was reported under _distrod_ (https://github.com/nullpo-head/wsl-distrod/issues/31#issuecomment-1079726209) . Of course, with systemd now running as pid 1 without a hack, the fix'll need to be in WSL proper.

**Comment by cerebrate** [comment]
Still an issue on 0.68.2, FWIW.

**Comment by BtbN** [comment]
I've applied the following workaround to my systemd on WSL, and it makes the output looks like (I think) it's supposed to look:

```
diff -Naur systemd-stable-251.8.orig/src/core/dbus-unit.c systemd-stable-251.8/src/core/dbus-unit.c
--- systemd-stable-251.8.orig/src/core/dbus-unit.c      2022-12-13 23:27:56.133926327 +0100
+++ systemd-stable-251.8/src/core/dbus-unit.c   2022-12-13 23:39:03.772622555 +0100
@@ -1288,6 +1288,8 @@
                  * “cgroup.procs” in a threaded domain cgroup contains the PIDs of all processes in
                  * the subtree and is not readable in the subtree proper. */
                 r = cg_read_pid(f, &pid);
+                if (r == -EIO)
+                        continue;
                 if (IN_SET(r, 0, -EOPNOTSUPP))
                         break;
                 if (r < 0)
```

It's most likely not a proper fix or a good idea to do, but it gets stuff working for me in the meantime.

**Comment by chutzimir** [comment]
> I've applied the following workaround to my systemd on WSL, and it makes the output look like (I think) it's supposed to look:
> 
> ```
> diff -Naur systemd-stable-251.8.orig/src/core/dbus-unit.c systemd-stable-251.8/src/core/dbus-unit.c
> --- systemd-stable-251.8.orig/src/core/dbus-unit.c      2022-12-13 23:27:56.133926327 +0100
> +++ systemd-stable-251.8/src/core/dbus-unit.c   2022-12-13 23:39:03.772622555 +0100
> @@ -1288,6 +1288,8 @@
>                   * “cgroup.procs” in a threaded domain cgroup contains the PIDs of all processes in
>                   * the subtree and is not readable in the subtree proper. */
>                  r = cg_read_pid(f, &pid);
> +                if (r == -EIO)
> +                        continue;
>                  if (IN_SET(r, 0, -EOPNOTSUPP))
>                          break;
>                  if (r < 0)
> ```
> 
> It's most likely not a proper fix or a good idea to do, but it gets stuff working for me in the meantime.

Thanks. I also rebuilt the `systemd-250-12.el9_1` SRPM on Rocky 9.1 with a patch similar to what you showed above. It will do the trick until it gets fixed somewhere.

This is on

```
> wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.1335
```

**Comment by allenatdecisiv** [comment]
This is also happening on Fedora 36:
```
❯ sudo systemctl status
Failed to dump process list for 'fedoraremix', ignoring: Input/output error
● fedoraremix
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Mon 2023-01-30 13:33:55 EST; 2min 58s ago
   CGroup: /
```

systemd version:
```
❯ sudo systemctl --version
systemd 250 (v250.9-1.fc36)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

WSL version:
```
❯ wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2546
```

**Comment by mokeyish** [comment]
This is also happening on Kali-linux

**Comment by MorphBonehunter** [comment]
I guess this issue will get more attention over time with more distos update systemd to >= 250. At the moment it seems that the only [supported distro](https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-6---install-your-linux-distribution-of-choice) with such an systemd version is Kali (but I did not verify this).

**Comment by allenatdecisiv** [comment]
@MorphBonehunter,

The patch provided by @BtbN does work for me on Fedora 36 using the technique described by @chutzimir.
```
❯ sudo systemctl status
● fedoraremix
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Wed 2023-03-01 15:11:12 EST; 5min ago
   CGroup: /
           ├─   2 /init
           ├─   5 plan9 --control-socket 6 --log-level 4 --server-fd 7 --pipe-fd 9 --log-truncate
           ├─ 243 /init
           ├─ 255 /bin/sh /usr/lib/bottle-imp/wait-forever.sh
           ├─ 257 sleep 1h
           ├─ 456 /init
           ├─ 457 /init
           ├─ 458 machinectl -E WT_SESSION=20dace65-44b2-4ed6-9001-7429bf8779d5 -E WT_PROFILE_ID={d8637476-55e3-42dd-ab39-3f25bc643>
           ├─init.scope
           │ └─ 1 /sbin/init
           ├─system. Slice
```

```
❯ systemctl --version
systemd 250 (v250.10-2.1.fc36)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

```
❯ wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2673
```

**Comment by elsaco** [comment]
Using different systemd versions `systemctl status` works sometimes.

openSUSE Tumbleweed with systemd 252.5, not working:

```
elsaco@eleven:~> systemctl status
Failed to dump process list for 'eleven', ignoring: Input/output error
● eleven
    State: running
    Units: 289 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 0 units
    Since: Wed 2023-03-01 12:13:31 PST; 21min ago
  systemd: 252.5+suse.46.gd87834a334
  Tainted: cgroupsv1
   CGroup: /
```

Ubuntu 22.04 with systemd 249.11, working:

```
elsaco@eleven:~$ systemctl status --no-pager
● eleven
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Wed 2023-03-01 12:35:34 PST; 22s ago
   CGroup: /
           ├─docker
           │ └─efdf49cbafdcccda6b8ce5077932766b38a74d0d41af44dbe4fe4d36f50a28d6
           ├─user.slice
           │ └─user-1000.slice
           │   ├─user@1000.service
           │   │ └─init.scope
           │   └─session-c1.scope
           ├─init.scope
           └─system.slice
---cut---
```

Both distros run on:

```
WSL version: 1.1.3.0
Kernel version: 5.15.90.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1344
```

**Comment by SuperSandro2000** [comment]
> I've applied the following workaround to my systemd on WSL, and it makes the output look like (I think) it's supposed to look:
> 
> ```
> diff -Naur systemd-stable-251.8.orig/src/core/dbus-unit.c systemd-stable-251.8/src/core/dbus-unit.c
> --- systemd-stable-251.8.orig/src/core/dbus-unit.c      2022-12-13 23:27:56.133926327 +0100
> +++ systemd-stable-251.8/src/core/dbus-unit.c   2022-12-13 23:39:03.772622555 +0100
> @@ -1288,6 +1288,8 @@
>                   * “cgroup.procs” in a threaded domain cgroup contains the PIDs of all processes in
>                   * the subtree and is not readable in the subtree proper. */
>                  r = cg_read_pid(f, &pid);
> +                if (r == -EIO)
> +                        continue;
>                  if (IN_SET(r, 0, -EOPNOTSUPP))
>                          break;
>                  if (r < 0)
> ```
> 
> It's most likely not a proper fix or a good idea to do, but it gets stuff working for me in the meantime.

Works and was dead easy to get into NixOS:

```nix
nixpkgs.overlays = [
  (final: prev: with final; {
    systemd-wsl = final.systemd.overrideAttrs ({ patches, ... }: {
      patches = patches ++ [
        ./systemd-systemctl-status-wsl.patch
      ];
    });
  })
];

systemd.package = pkgs.systemd-wsl;
```

**Comment by CarlosNihelton** [comment]
Still an issue to date.

```
Versão do WSL: 1.2.0.0
Versão do kernel: 5.15.90.1
Versão do WSLg: 1.0.51
Versão do MSRDC: 1.2.3770
Versão do Direct3D: 1.608.2-61064218
Versão do DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Versão do Windows: 10.0.25336.1010
```

Also tested with pre-release 1.2.4. Both using cgroups v2. Of the Ubuntu apps, that situation still only affects the Ubuntu-Preview for now, but eventually other releases will be at systemd version 2.50 or later, so that will be a problem.

A suitable fix seems to be to create and assign a cgroup and a [cgroup namespace](https://docs.kernel.org/admin-guide/cgroup-v2.html#namespace) to every distro instance. Handling the cgroup2 mount point properly before starting systemd, it should then see that as its root cgroup. There will be no PID 0's inside the `cgroup.procs` file, because it will be populated only by the PIDs of the child processes of systemd. Also, care must be taken to ensure the 'login" shell also goes to the that cgroup (and namespaces).

For the sake of demonstration, if instead of enabling systemd through the proper settings in `wsl.conf` we use the hack described below, then we get `systemctl status` behaving correctly, with the downside of the root cgroup being displayed not as `/`.


> An extension to an older hack script to start systemd in its own namespace and cgroup.

```bash
#!/bin/sh
set -eu

# Ensure that we don't clean up /tmp setup by the Microsoft init process.
mkdir -p /run/tmpfiles.d
ln -s /dev/null /run/tmpfiles.d/tmp.conf

umount /proc/sys/fs/binfmt_misc

# Create the distro cgroup
mkdir -p /sys/fs/cgroup/distros/ubuntu-preview

# Start systemd in its own namespace. Notice the `-C` for cgroup
env -i /usr/bin/unshare -Cm --fork --mount-proc --pid --propagation unchanged -- sh -c '
echo $PPID > /sys/fs/cgroup/distros/ubuntu-preview/cgroup.procs && exec /lib/systemd/systemd --unit=multi-user.target
' &
```

DISCLAIMER: By no means the above is a solution. It has many drawbacks, such as not showing the systemd root cgroup as `/` as well as requiring more hacks to run processes (such as a shell) under the systemd namespaces.

Configuring the boot command parameter to run that script and starting a shell under systemd namespaces allows us to see the following `systemctl` output.

> /etc/wsl.conf

```ini
[boot]
command=<absolute path of the script>
```

```
carlos@Zero01:~$ systemctl status
● Zero01
    State: running
    Units: 312 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 0 units
    Since: Wed 2023-04-19 15:18:12 -03; 5s ago
  systemd: 252.5-2ubuntu3
   CGroup: /distros/ubuntu-preview
           ├─init.scope
           │ └─1 /lib/systemd/systemd --unit=multi-user.target
           └─system.slice
             ├─console-getty.service
             │ └─125 /sbin/agetty -o "-p -- \\u" --noclear --keep-baud - 115200,38400,9600 vt220
             ├─cron.service
             │ └─111 /usr/sbin/cron -f -P
             ├─dbus.service
             │ └─112 @dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
             ├─rsyslog.service
             │ └─124 /usr/sbin/rsyslogd -n -iNONE
             ├─snap-core22-607.mount
             │ └─62 snapfuse /var/lib/snapd/snaps/core22_607.snap /snap/core22/607 -o ro,nodev,allow_other,suid
             ├─snap-snapd-18596.mount
             │ └─63 snapfuse /var/lib/snapd/snaps/snapd_18596.snap /snap/snapd/18596 -o ro,nodev,allow_other,suid
             ├─snap-snapd-18933.mount
             │ └─65 snapfuse /var/lib/snapd/snaps/snapd_18933.snap /snap/snapd/18933 -o ro,nodev,allow_other,suid
             ├─snap-subiquity-4692.mount
             │ └─64 snapfuse /var/lib/snapd/snaps/subiquity_4692.snap /snap/subiquity/4692 -o ro,nodev,allow_other,suid
             ├─snap-subiquity-4714.mount
             │ └─61 snapfuse /var/lib/snapd/snaps/subiquity_4714.snap /snap/subiquity/4714 -o ro,nodev,allow_other,suid
             ├─snap.subiquity.subiquity-server.service
             │ ├─117 /bin/sh /snap/subiquity/4714/usr/bin/subiquity-server
             │ └─186 /snap/subiquity/4714/usr/bin/python3.10 -m subiquity.cmd.server
             ├─snapd.service
             │ └─119 /usr/lib/snapd/snapd
```

**Comment by xiaoyang-sde** [comment]
This issue is reproducible on WSL-based Arch Linux with `systemd 254 (254.5-1-arch)`.

```console
$ sudo SYSTEMD_LOG_LEVEL=7 SYSTEMD_PAGER= systemctl status
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/systemd/private...
Bus n/a: changing state OPENING → AUTHENTICATING
Bus n/a: changing state AUTHENTICATING → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.DBus.Properties member=GetAll cookie=1 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a  cookie=1 reply_cookie=1 signature=a{sv} error-name=n/a error-message=n/a
● MSI-B660M
    State: running
    Units: 252 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 0 units
    Since: Thu 2023-11-09 11:18:50 PST; 25min ago
  systemd: 254.5-1-arch
  Tainted: cgroupsv1
   CGroup: /
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=GetUnitProcesses cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=error sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a  cookie=2 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.IOError error-message=Input/output error
Failed to dump process list for 'MSI-B660M', ignoring: Input/output error
Bus n/a: changing state RUNNING → CLOSED
```

**Comment by Splarv** [comment]
The same with debian
C:\Users\splar>wsl --version
Версия WSL: 2.0.9.0
Версия ядра: 5.15.133.1-1
Версия WSLg: 1.0.59
Версия MSRDC: 1.2.4677
Версия Direct3D: 1.611.1-81528511
Версия DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Версия Windows: 10.0.19045.3803

root@dog:~# dpkg -s systemd
Package: systemd
Status: install ok installed
Priority: important
Section: admin
Installed-Size: 9647
Maintainer: Debian systemd Maintainers <pkg-systemd-maintainers@lists.alioth.debian.org>
Architecture: amd64
Multi-Arch: foreign
Version: 252.19-1~deb12u1

root@dog:~# systemctl status
Failed to dump process list for 'dog', ignoring: Input/output error
● dog
    State: running
    Units: 300 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 0 units
    Since: Thu 2023-12-14 23:36:50 MSK; 17min ago
  systemd: 252.19-1~deb12u1
  Tainted: cgroupsv1
   CGroup: /

**Comment by Tatsh** [comment]
Gentoo.

```
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3693
```

```
# uname -a
Linux WX-5CG3342PM9 6.7.0-gentoo-microsoft-standard-WSL2 #3 SMP Mon Jan  8 14:07:42 EST 2024 x86_64 12th Gen Intel(R) Core(TM) i7-1265U GenuineIntel GNU/Linux
# systemctl status
Failed to dump process list for '...', ignoring: Input/output error
● WX-5CG3342PM9
    State: running
    Units: 258 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 0 units
    Since: Mon 2024-01-08 14:58:00 EST; 56s ago
  systemd: 255
  Tainted: cgroupsv1
   CGroup: /
```

**Comment by Tatsh** [comment]
Updated patch for v255:

```diff
diff --git a/src/core/dbus-unit.c b/src/core/dbus-unit.c
index 1a037b7..f0550e8 100644
--- a/src/core/dbus-unit.c
+++ b/src/core/dbus-unit.c
@@ -1300,6 +1300,8 @@ static int append_cgroup(sd_bus_message *reply, const char *p, Set *pids) {
                  * readable in the subtree proper. */

                 r = cg_read_pidref(f, &pidref);
+                if (r == -EIO)
+                        continue;
                 if (IN_SET(r, 0, -EOPNOTSUPP))
                         break;
                 if (r < 0)
```

**Comment by storm2lele** [comment]
> Updated patch for v255:
> 
> ```diff
> diff --git a/src/core/dbus-unit.c b/src/core/dbus-unit.c
> index 1a037b7..f0550e8 100644
> --- a/src/core/dbus-unit.c
> +++ b/src/core/dbus-unit.c
> @@ -1300,6 +1300,8 @@ static int append_cgroup(sd_bus_message *reply, const char *p, Set *pids) {
>                   * readable in the subtree proper. */
> 
>                  r = cg_read_pidref(f, &pidref);
> +                if (r == -EIO)
> +                        continue;
>                  if (IN_SET(r, 0, -EOPNOTSUPP))
>                          break;
>                  if (r < 0)
> ```

How to update the systemd code on arch?

systemd version: systemd 255.4-2

**Comment by trallnag** [comment]
Also seeing this on Windows 11 in a **Debian Bookworm** distro.

```txt
> wsl --version
WSL-Version: 2.1.5.0
Kernelversion: 5.15.146.1-2
WSLg-Version: 1.0.60
MSRDC-Version: 1.2.5105
Direct3D-Version: 1.611.1-81528511
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows-Version: 10.0.22631.3447
```

```txt
> systemctl --version
systemd 252 (252.22-1~deb12u1)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

In **Ubuntu** it is working fine.

**Comment by trallnag** [comment]
> I guess this issue will get more attention over time with more distos update systemd to >= 250. At the moment it seems that the only [supported distro](https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-6---install-your-linux-distribution-of-choice) with such an systemd version is Kali (but I did not verify this).

@MorphBonehunter, yep. Ubuntu 24 is around the corner and it uses systemd 255

**Comment by Stanzilla** [comment]
Yes, do **not** update to Ubuntu 24.04, I made that mistake yesterday.

https://twitter.com/stanzillaz/status/1783274242995290244

**Comment by yveshield** [comment]
This issue is reproducible on WSL-based Arch Linux with systemd 253.5-1ubuntu6.1.
`$ sudo PAGER= SYSTEMD_LOG_LEVEL=debug systemctl status
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/systemd/private...
Bus n/a: changing state OPENING → AUTHENTICATING
Bus n/a: changing state AUTHENTICATING → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.DBus.Properties member=GetAll cookie=1 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a  cookie=1 reply_cookie=1 signature=a{sv} error-name=n/a error-message=n/a
● wsl
    State: degraded
    Units: 368 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 2 units
    Since: Wed 2024-05-01 14:33:38 CST; 2h 21min ago
  systemd: 253.5-1ubuntu6.1
  Tainted: cgroupsv1
   CGroup: /
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=GetUnitProcesses cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=error sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a  cookie=2 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.IOError error-message=Input/output error
Failed to dump process list for 'wsl', ignoring: Input/output error
Bus n/a: changing state RUNNING → CLOSED`

**Comment by BtbN** [comment]
This is fixed in the latest systemd stable version of 255, so someone just has to get Ubuntu to update.

**Comment by themasch** [comment]
> This is fixed in the latest systemd stable version of 255, so someone just has to get Ubuntu to update.

I am still seeing the same error message on 255 (fedora 40): 

```
[root@WSLHOST ~]# systemctl --version
systemd 255 (255.4-1.fc40)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

[root@WSLHOST ~]# PAGER= SYSTEMD_LOG_LEVEL=debug systemctl status
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/systemd/private...
Bus n/a: changing state OPENING → AUTHENTICATING
Bus n/a: changing state AUTHENTICATING → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.DBus.Properties member=GetAll cookie=1 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a  cookie=1 reply_cookie=1 signature=a{sv} error-name=n/a error-message=n/a
● WSLHOST
    State: degraded
    Units: 149 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 2 units
    Since: Wed 2024-05-29 11:56:38 CEST; 53s ago
  systemd: 255.4-1.fc40
   CGroup: /
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=GetUnitProcesses cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=error sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a  cookie=2 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.IOError error-message=Input/output error
Failed to dump process list for 'WSLHOST', ignoring: Input/output error
Bus n/a: changing state RUNNING → CLOSED
```

Is there something else I'm doing wrong?

**Comment by themasch** [comment]
@MorphBonehunter got it, thank you! I misunderstood @BtbN an thought every 255 version fixed the problem, didnt notice that it was fixed in a minor release. Thanks!

**Comment by SuzukiHonoka** [comment]
same issue here

**Comment by julianxhokaxhiu** [comment]
Seems to work fine also here on Arch.

CMD output:
```bash
❯ wsl --version
Versione WSL: 2.2.4.0
Versione kernel: 5.15.153.1-2
Versione WSLg: 1.0.61
Versione MSRDC: 1.2.5326
Versione Direct3D: 1.611.1-81528511
Versione DXCore: 10.0.26091.1-240325-1447.ge-release
Versione di Windows: 10.0.22631.3880
```

zsh output:
```bash
❯ systemctl status
● ASUS-ROG-LAPTOP
    State: running
    Units: 302 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 0 units
    Since: Wed 2024-07-10 20:23:28 CEST; 2min 5s ago
  systemd: 256.2-1-arch
  Tainted: cgroupsv1
   CGroup: /
   #[...]   
```

Thanks!

**Comment by Stanzilla** [comment]
> ```shell
> systemctl status
> ```

I'm on systemd 255 (255.4-1ubuntu8.2) and it looks like it is still broken, 

```
❯ systemctl status
Failed to connect to bus: No such file or directory
```

**Comment by Stanzilla** [comment]
I've been informed on [Twitter](https://x.com/cerebrate/status/1814006500060213377) that the fix should be in **255.7**

**Comment by 0Styless** [comment]
@Stanzilla On Ubuntu 24.04:

```bash
$ sudo systemctl --version                                                                                                                                                                                                 1.5m  Mon 21:33
systemd 256 (256-1ubuntu1)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT +LIBARCHIVE
```

Still doesn't work.

**Comment by Stanzilla** [comment]
> @Stanzilla On Ubuntu 24.04:
> 
> ```shell
> $ sudo systemctl --version                                                                                                                                                                                                 1.5m  Mon 21:33
> systemd 256 (256-1ubuntu1)
> +PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT +LIBARCHIVE
> ```
> 
> Still doesn't work.

Yikes. I hope we get some better news soon. Should we open a bug at Ubuntu? @craigloewen-msft?

**Comment by bpkroth** [comment]
> > @Stanzilla On Ubuntu 24.04:
> > ```shell
> > $ sudo systemctl --version                                                                                                                                                                                                 1.5m  Mon 21:33
> > systemd 256 (256-1ubuntu1)
> > +PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT +LIBARCHIVE
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Still doesn't work.
> 
> Yikes. I hope we get some better news soon. Should we open a bug at Ubuntu? @craigloewen-msft @benhillis?

Could check or re-open this one:
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/2067922

**Comment by trallnag** [comment]
It now works for me

```
> systemctl status
● metro
    State: running
    Units: 403 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 0 units
    Since: Sat 2024-07-20 22:53:46 CEST; 1 day 23h ago
  systemd: 255.4-1ubuntu8.2
  Tainted: cgroupsv1
   CGroup: /
           ├─init.scope
           │ ├─     1 /sbin/init
           │ ├─     2 /init
           │ ├─     8 plan9 --control-socket 6 --log-level 4 --server-fd 7 --pipe-fd 9 --log-truncate
           │ ├─   558 /init
...
```

```
> wsl --version
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22631.3880
```

```
> systemctl version
systemd 255 (255.4-1ubuntu8.2)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

**Comment by BtbN** [comment]
You need to do a daemon-reexec or just plain wsl restart after installing the update.

**Comment by Stanzilla** [comment]
> You need to do a daemon-reexec or just plain wsl restart after installing the update.

I did that several times actually

**Comment by Stanzilla** [comment]
> It now works for me
> 
> ```
> > systemctl status
> ● metro
>     State: running
>     Units: 403 loaded (incl. loaded aliases)
>      Jobs: 0 queued
>    Failed: 0 units
>     Since: Sat 2024-07-20 22:53:46 CEST; 1 day 23h ago
>   systemd: 255.4-1ubuntu8.2
>   Tainted: cgroupsv1
>    CGroup: /
>            ├─init.scope
>            │ ├─     1 /sbin/init
>            │ ├─     2 /init
>            │ ├─     8 plan9 --control-socket 6 --log-level 4 --server-fd 7 --pipe-fd 9 --log-truncate
>            │ ├─   558 /init
> ...
> ```
> 
> ```
> > wsl --version
> WSL version: 2.2.4.0
> Kernel version: 5.15.153.1-2
> WSLg version: 1.0.61
> MSRDC version: 1.2.5326
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.26091.1-240325-1447.ge-release
> Windows version: 10.0.22631.3880
> ```
> 
> ```
> > systemctl version
> systemd 255 (255.4-1ubuntu8.2)
> +PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
> ```

is that a fresh install or something before 24.04 that you upgraded?

**Comment by trallnag** [comment]
Installed the distribution 2024-04-29, grabbed the image for 24.04 directly from Ubuntu. Back then it was not yet available in the Microsoft Store
