### ISSUE TITLE
Cannot disable Interop via /etc/wsl.conf -- 0.68.2 regression (probably introduced in 0.67.6)

### ISSUE THREAD

**Issue by NotTheDr01ds** [microsoft/WSL#8932]
### Version

Microsoft Windows [Version 10.0.22000.978]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.62.1

### Distro Version

Ubuntu 22.04 (also tested with Tumbleweed)

### Repro Steps

1. Disable Interop by creating/editing `/etc/wsl.conf`:

    ```
    [interop]
    enabled=false
    ```

1. Exit the distribution.
1. `wsl --terminate <distro>` or `wsl --shutdown` (tested with both)
2. Restart the distribution
5. Run `powershell.exe`
6. Exit PowerShell
3. Run `notepad.exe`

### Expected Behavior

```
<3>WSL (22) ERROR: UtilAcceptVsock:247: accept4 failed 110
```

Or similar, with an exit status of 1.  This is the behavior I have confirmed on 0.66.2, at least.  On releases before the new error model (0.64.0), I believe it fails silently with an exit status of 1.  This is the behavior I saw on Windows 10.

### Actual Behavior

* PowerShell runs as it would if Interop was enabled (as a console app).

* Notepad runs, but runs in a window behind Windows Terminal (when interop is enabled, it automatically comes to the foreground).

---

Note that enabling or disabling Systemd does not have any effect on Interop.

---

Setting:

```
[interop]
enabled=false
appendWindowsPath=false
```

Removes the Windows path, but Interop still works.  The above output was obtained by:

```
/mnt/c/Windows/System32/clip.exe < /etc/wsl.conf
```

Which should have failed.

**Comment by blami** [comment]
I have exactly opposite problem (perhaps related so that's why I report it here) - cannot __enable__ interop. Before upgrading to 0.68.2 it worked fine but after update I am unable to start any Windows process from within WSL2. Shell gives me following error:

``` shell
~ $ which powershell.exe
/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
~ $ powershell.exe
zsh: exec format error: powershell.exe
```

**Comment by ezxpro** [comment]
@blami maybe try this tip from the [official wsl docs](https://learn.microsoft.com/en-us/windows/wsl/filesystems#share-environment-variables-between-windows-and-wsl):
```
echo 0 > /proc/sys/fs/binfmt_misc/WSLInterop
```
The `/proc/sys/fs/binfmt_misc/WSLInterop` file in question doesn't have a single `0` in it. It has an interop flag that can be either `enabled` or `disabled`. Using the command above with `echo 1` sets it to `enabled`, and vice-versa.

It didn't work here, though. WSL path is utterly broken, it works fine until you upgrade packages once, then it becomes a shitshow.

**Comment by benhillis** [comment]
Good catch, looks like this was regressed when we added the ability to launch Windows executables from processes launched by systemd or boot.init. This behavior would be broken if you have systemd enabled or not. I will fix.

**Comment by benhillis** [comment]
Fixed with https://github.com/microsoft/WSL/releases/tag/0.70.4.

**Comment by mataha** [comment]
This is not fixed - still can't disable interop even with `wsl.conf` set up properly on WSL2:

```console
$ ls /proc/sys/fs/binfmt_misc
WSLInterop  WSLInterop-late  register  status

$ cat /proc/sys/fs/binfmt_misc/WSLInterop
enabled
interpreter /init
flags: PF
offset 0
magic 4d5a

$ cat /proc/sys/fs/binfmt_misc/WSLInterop-late
enabled
interpreter /init
flags: P
offset 0
magic 4d5a

$ cat /etc/wsl.conf
[automount]
enabled = true

[boot]
systemd = true

[interop]
enabled = false
appendWindowsPath = false

[network]
generateResolvConf = false

$ which make
/home/user/cosmocc/bin/make

$ make --version
<3>WSL (15239) ERROR: UtilAcceptVsock:250: accept4 failed 110
```

Where `make` is an [Actually Portable Executable](https://justine.lol/ape.html) downloaded from [here](https://cosmo.zip/pub/cosmos/bin/make). Diagnostic data follows:

```dosbatch
> wsl -v
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.4651

> wsl uname -a
Linux desktop 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mataha** [comment]
For what it's worth, this problem persists even after updating to 2.2.4.

**Comment by thohnb** [comment]
> ### Version
> 
> Microsoft Windows [Version 10.0.22000.978]
> ### WSL Version
> 
>     * [x]  WSL 2
> 
>     * [ ]  WSL 1
> 
> 
> ### Kernel Version
> 
> 5.15.62.1
> ### Distro Version
> 
> Ubuntu 22.04 (also tested with Tumbleweed)
> ### Other Software
> 
> _No response_
> ### Repro Steps
> 
>     1. Disable Interop by creating/editing `/etc/wsl.conf`:
>        ```
>        [interop]
>        enabled=false
>        ```
> 
>     2. Exit the distribution.
> 
>     3. `wsl --terminate <distro>` or `wsl --shutdown` (tested with both)
> 
>     4. Restart the distribution
> 
>     5. Run `powershell.exe`
> 
>     6. Exit PowerShell
> 
>     7. Run `notepad.exe`
> 
> 
> ### Expected Behavior
> 
> ```
> <3>WSL (22) ERROR: UtilAcceptVsock:247: accept4 failed 110
> ```
> 
> Or similar, with an exit status of 1. This is the behavior I have confirmed on 0.66.2, at least. On releases before the new error model (0.64.0), I believe it fails silently with an exit status of 1. This is the behavior I saw on Windows 10.
> ### Actual Behavior
> 
>     * PowerShell runs as it would if Interop was enabled (as a console app).
> 
>     * Notepad runs, but runs in a window behind Windows Terminal (when interop is enabled, it automatically comes to the foreground).
> 
> 
> Note that enabling or disabling Systemd does not have any effect on Interop.
> 
> Setting:
> 
> ```
> [interop]
> enabled=false
> appendWindowsPath=false
> ```
> 
> Removes the Windows path, but Interop still works. The above output was obtained by:
> 
> ```
> /mnt/c/Windows/System32/clip.exe < /etc/wsl.conf
> ```
> 
> Which should have failed.
> ### Diagnostic Logs
> 
> _No response_

Same error. Currently using lastest version
## version
> 
> WSL version: 2.2.4.0
>Kernel version: 5.15.153.1-2
>WSLg version: 1.0.61
>MSRDC version: 1.2.5326
>Direct3D version: 1.611.1-81528511
>DXCore version: 10.0.26091.1-240325-1447.ge-release
>Windows version: 10.0.19044.4651
>

**Comment by carkat** [comment]
Can not even edit WSLInterop file anymore. Attempting to echo to the file deleted the file and it no longer exists, and I cannot create a  new one either, even with sudo and full ownership of the machine. 

sudo su -
echo 0 > /proc/sys/fs/binfmt_misc/WSLInterop

or as normal user
sudo sh -c "sudo echo 0 > /proc/sys/fs/binfmt_misc/WSLInterop"

nothing works
