### ISSUE TITLE
snapd does not work inside WSL

### ISSUE THREAD

**Issue by elsaco** [microsoft/WSL#9026]
### Version

10.0.22621.674

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1

### Distro Version

Ubuntu 22.10

### Repro Steps

Run `systemctl --failed`

### Expected Behavior

Functional `snapd` service

### Actual Behavior

```
toor@XPS:~$ systemctl status snapd
● snapd.service - Snap Daemon
     Loaded: loaded (/lib/systemd/system/snapd.service; enabled; preset: enabled)
     Active: active (running) since Sun 2022-10-16 17:42:14 PDT; 3min 9s ago
TriggeredBy: ● snapd.socket
   Main PID: 181 (snapd)
      Tasks: 11 (limit: 4697)
     Memory: 44.6M
     CGroup: /system.slice/snapd.service
             └─181 /usr/lib/snapd/snapd

Oct 16 17:42:14 XPS systemd[1]: Starting Snap Daemon...
Oct 16 17:42:14 XPS snapd[181]: AppArmor status: apparmor not enabled
Oct 16 17:42:14 XPS snapd[181]: overlord.go:263: Acquiring state lock file
Oct 16 17:42:14 XPS snapd[181]: overlord.go:268: Acquired state lock file
Oct 16 17:42:14 XPS snapd[181]: daemon.go:247: started snapd/2.57.4+22.10ubuntu1 (series 16; classic; devmode; wsl) ubuntu/22.10 (amd64) linux/5.15.68.1-microsoft-stand.
Oct 16 17:42:14 XPS snapd[181]: main.go:129: system does not fully support snapd: snapd does not work inside WSL
Oct 16 17:42:14 XPS snapd[181]: daemon.go:340: adjusting startup timeout by 55s (pessimistic estimate of 30s plus 5s per snap)
Oct 16 17:42:14 XPS systemd[1]: Started Snap Daemon.
```

```
toor@XPS:~$ snap list
Interacting with snapd is not yet supported on Windows Subsystem for Linux.
This command has been left available for documentation purposes only.
```

**Comment by Biswa96** [comment]
Probably snapd was disabled for all WSL before this commit https://github.com/snapcore/snapd/commit/0582fcf5139ed87437505ecae02315267571877d

**Comment by cerebrate** [comment]
Yeah, it's kind of a long story. Way back when, _snapd_ implemented a test to see if it was running under WSL, but that test, it turned out, had a bug which meant that it only detected WSL 1, so for a very long time, you were able to get _snapd_ working under WSL 2 if you fixed the prerequisites that stopped it from doing so.

(I don't think any of us who got snapd working even noticed the test was there.)

Then along came snapcore/snapd#12135, which fixed the WSL detection bug so the test actually worked, and _snapd_ stopped working.

The good news is that WSL detection post that PR works by looking for `/proc/sys/fs/binfmt_misc/WSLInterop`, so you can enable snapd at the cost of disabling Windows interop. (Note: not using the `/etc/wsl.conf` method, because that leaves the binfmt in place; rather, as root, run `echo -1 >> /proc/sys/fs/binfmt_misc/WSLInterop`, which removes the binfmt handler. Then restart all snapd services.)

The **better** news is that there's a PR which acknowledges this stuff over at snapcore/snapd#12179, which has been merged, so we should be good once _snapd_ 2.57.5 hits.

**Comment by ishisaka** [comment]
I also suddenly couldn't use the snap command as well, it worked for a while after updating WSL2 to 0.7.0, but today it was not working anymore.

**Comment by kisialiou** [comment]
Experiencing the same thing. Just yesterday everything worked fine.

**Comment by haomingz** [comment]
> The good news is that WSL detection post that PR works by looking for /proc/sys/fs/binfmt_misc/WSLInterop, so you can enable snapd at the cost of disabling Windows interop. (Note: not using the /etc/wsl.conf method, because that leaves the binfmt in place; rather, as root, run echo -1 >> /proc/sys/fs/binfmt_misc/WSLInterop, which removes the binfmt handler. Then restart all snapd services.)

This can work 👍

**Comment by EduardGomezEscandell** [comment]
There is a fix for this in the beta channel of snapd. Problem being that you cannot update to beta because snap won't let you.

If you manage to make snap work temporarily (e.g. disabling interop or reverting to an older version via apt), you can use either command (try the first, if it fails try the second): 
```bash
sudo snap install snapd --beta 
```
```bash
sudo snap refresh snapd --beta
```

Then you can undo your temporary fix (e.g. enabling interop again or doing apt upgrade).

**Comment by martinnyborg** [comment]
Works great! Thanks @EduardGomezEscandell

**Comment by diddledani** [comment]
Workaround that keeps WSL Interop active:

Ensure you have `systemd-binfmt.service` installed in your distro (in Ubuntu that means having the `binfmt-support` package installed via apt), then execute the following:

```bash
echo ":windowsexe:M::\x4d\x5a::/init:PF" | sudo tee -a /etc/binfmt.d/windowsexe.conf
```

This will replace the `WSLInterop` binfmt support with an identical configuration under a different name. To activate this, leave WSL and run `wsl --shutdown` in a PowerShell or CMD window. Next time you restart your distro it should replace the `WSLInterop` binfmt configuration with this renamed copy so that `snapd` can't tell that it's on WSL.

**Comment by NotTheDr01ds** [comment]
@EduardGomezEscandell When the fix does make it into `jammy-updates`, will users who install via `--beta` need to revert anything to return to the "release" version, or will a basic `sudo apt update && sudo apt upgrade` take care of it?

**Comment by NotTheDr01ds** [comment]
Also tracking at this [Ask Ubuntu question](https://askubuntu.com/q/1436573/1165986).  I'm currently recommending @diddledani's workaround since it's a one-shot "masking" of the issue (unless someone sees an issue with that method).  It's also a easy to revert the workaround once the fix is released.

**Comment by EduardGomezEscandell** [comment]
Hey, the fix has been released for Ubuntu 22.04. It'll soon reach 20.04 and 22.10 as well. Here is the fix:

https://github.com/ubuntu/WSL/issues/299#issuecomment-1291650396

> will users who install via --beta need to revert anything to return to the "release" version, or will a basic sudo apt update && sudo apt upgrade take care of it?

Yes, they'll need to return to the stable channel. I added it to the linked comment.

**Comment by circleupx** [comment]
I've tried the permanent fix mentioned [WSL#299](https://github.com/ubuntu/WSL/issues/299#issuecomment-1291650396l) above but I still can't get it to work. At first, I was getting the message posted in this issue.

> Interacting with snapd is not yet supported on Windows Subsystem for Linux.
This command has been left available for documentation purposes only.

I decided to nuke the distro and start over, then it turned into this message. 

> error: cannot communicate with server: Post http://localhost/v2/snaps/microk8s: dial unix /run/snapd.socket: connect: no such file or directory

Snapd version
> snap version
snap                         2.57.5+20.04
snapd                        unavailable
series                       16
Windows Subsystem for Linux  -
kernel                       5.10.102.1-microsoft-standard-WSL2 (amd64)

Distro version
> Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

Windows Build 
Version	10.0.19045 Build 19045


Does anyone have any suggestions?
>

**Comment by EduardGomezEscandell** [comment]
> error: cannot communicate with server: Post http://localhost/v2/snaps/microk8s: dial unix /run/snapd.socket: connect: no such file or directory

This looks like the message you get when systemd is not enabled. Did you re-enable systemd after installing the distro anew?

**Comment by circleupx** [comment]
> > error: cannot communicate with server: Post http://localhost/v2/snaps/microk8s: dial unix /run/snapd.socket: connect: no such file or directory
> 
> This looks like the message you get when systemd is not enabled. Did you re-enable systemd after installing the distro anew?
> 
> Also, what command prompted this message? Does `snap list` work fine?

I had the systemd=true in the WSL, though snap list never yielded any results. I decide to take another route, I upgraded to Windows 11. Reinstalled everything following the guidelines listed here and on various posts by Microsoft and I am happy to say. 

It is working!!!!

Thank you.

**Comment by edurojasr** [comment]
Hi I don't know if this is related, but I have this problem

when install and run firefox from snap

`internal error, please report: running "firefox" failed: cannot find installed snap "firefox" at revision 2015: missing file /snap/firefox/2015/meta/snap.yaml`

**Comment by elsaco** [comment]
@edurojasr try running `sudo snap refresh` to update your snaps. It might fix your issue.

**Comment by NotTheDr01ds** [comment]
@circleupx 

> I decide to take another route, I upgraded to Windows 11

Ahh, then your original problem was simply because Systemd is not supported under Windows 10 anyway.  As the [announcement](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/) mentioned, Systemd support requires WSL 0.67.6 or later, which is only available for Windows 11! 😀

**Comment by linghengqian** [comment]
- The description of this issue is only for wsl2. Meanwhile I successfully installed and used gedit, gimp, vlc and chromium via Snap on Ubuntu 22.04. 
- I think this issue can be closed.

**Comment by EduardGomezEscandell** [comment]
> I think this issue can be closed.

The issue still affects users in WSL2 that use Ubuntu 22.10. (See [here](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1983035) to check out the status of the fix). I believe the issue should stay open until `snapd 2.57.5+22.10` is released.

**Comment by linghengqian** [comment]
- https://bugs.launchpad.net/snapd/+bug/1991826 has been closed, this issue has no meaning to continue to open.

**Comment by Dragon1573** [comment]
> The issue still affects users in WSL2 that use Ubuntu 22.10. I believe the issue should stay open until `snapd 2.57.5+22.10` is released.

I currently using **Ubuntu 22.10 Kinetic**. `snapd` with version `2.57.5+22.10ubuntu0.1` is currently available in `kinetic-updates,kinetic-security,now` channel.

```text
π lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic

π apt list snapd -a
正在列表... 完成
snapd/kinetic-updates,kinetic-security,now 2.57.5+22.10ubuntu0.1 amd64 [已安装]
snapd/kinetic 2.57.4+22.10ubuntu1 amd64

π snap version
snap                         2.57.6
snapd                        不可用
series                       16
Windows Subsystem for Linux  -
kernel                       5.15.74.2-microsoft-standard-WSL2 (amd64)

π snap list
名称      版本             修订版本   追踪             发布者         注记
core    16-2.57.6      14399  latest/stable  canonical✓  core
core20  20221027       1695   latest/stable  canonical✓  base
lxd     4.0.9-eb5e237  23991  4.0/stable/…   canonical✓  -
snapd   2.57.6         17883  latest/stable  canonical✓  snapd
```

Does it mean `snapd` with version `2.57.5+22.10ubuntu1` should be available in `kinetic` channel directly? What's the difference between 2 channels?

**Comment by EduardGomezEscandell** [comment]
> Does it mean snapd with version 2.57.5+22.10ubuntu1 should be available in kinetic channel directly? What's the difference between 2 channels?

No, it'll be on kinetic-updates. Form the `/etc/apt/sources.list` file:
```
## Major bug fix updates produced after the final release of the
## distribution.
deb http://archive.ubuntu.com/ubuntu/ kinetic-updates main restricted
```
kinetic-updates contains bug fixes (such as this one). Both ppa are enabled on your distro by default so simply do `apt update && apt upgrade` and this problem will be solved.

**Comment by EduardGomezEscandell** [comment]
This issue now considered solved from the Ubuntu team's point of view. `snapd 2.57.5+22.10` has been released on kinetic, you can fix it with:
```
sudo apt-get -y update
sudo apt-get -y upgrade snapd
```
