### ISSUE TITLE
Wrong CPU load reading?

### ISSUE THREAD

**Issue by iz0eyj** [Microsoft/WSL#945]
This is CPU load reading both WSL and Win side.
The machine is near idle (no browsers or other CPU-intensive software) so I thick that CPU-Z and Task Manager reading is correct, but WSL side I read abt 50% of CPU load on every core.
Using mpstat (taskmanager that shows 1% CPU load= I read this:

```
Federico@BESTIA:~$ mpstat -P ALL
Linux 3.4.0+ (BESTIA)   20/08/2016      _x86_64_        (8 CPU)

07:04:58     CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
07:04:58     all    3,02    0,00   26,59    0,00    0,03    0,00    0,00    0,00    0,00   70,36
07:04:58       0    2,87    0,00   26,72    0,00    0,19    0,00    0,00    0,00    0,00   70,22
07:04:58       1    2,88    0,00   26,67    0,00    0,01    0,00    0,00    0,00    0,00   70,45
07:04:58       2    3,31    0,00   26,76    0,00    0,01    0,00    0,00    0,00    0,00   69,91
07:04:58       3    4,24    0,00   26,38    0,00    0,01    0,00    0,00    0,00    0,00   69,37
07:04:58       4    2,58    0,00   26,80    0,00    0,01    0,00    0,00    0,00    0,00   70,61
07:04:58       5    2,39    0,00   26,57    0,00    0,01    0,00    0,00    0,00    0,00   71,03
07:04:58       6    3,21    0,00   26,14    0,00    0,01    0,00    0,00    0,00    0,00   70,65
07:04:58       7    2,73    0,00   26,71    0,00    0,01    0,00    0,00    0,00    0,00   70,55
Federico@BESTIA:~$

```

![cpu](https://cloud.githubusercontent.com/assets/6331284/17829128/e0bbd9f0-66a4-11e6-80f0-5c9377b49ac1.JPG)

**Comment by christian8246q** [comment]
I have the same problem. _htop_ shows about 50% usage on all my four cores.

**Comment by TiberiumPY** [comment]
I have this issue too

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, a fix for this should be out for insider builds soon.  The cpu usage reporting should be fixed in an insider build soon, but the load average will need some additional work to fix.

**Comment by vaibhav-y** [comment]
This issue still persists. Load average values are hard-coded to `0.52 0.58 0.59`

![image](https://user-images.githubusercontent.com/3663231/34538771-c743778a-f09b-11e7-9c06-60344c9aaf4f.png)

**Comment by Yardanico** [comment]
@vaibhav-y no, you don't have persistent 50% CPU usage, load average is a different thing. Maybe open another issue about it?

**Comment by vaibhav-y** [comment]
I see, I misread the title because it said "CPU load". I'll open a new issue if applicable for this.

**Comment by benhillis** [comment]
@vaibhav-y - The issue with CPU usage has been fixed, the "load average values" are currently hard coded.  I'm going to close this issue and if you would please create a new issue regarding load average it would be greatly appreciated.

**Comment by tlan16** [comment]
Still having this issue on wsl1 windows 10
![image](https://user-images.githubusercontent.com/6945696/71694241-aa49d880-2e02-11ea-88cb-4d9b004b98f3.png)

**Comment by Yardanico** [comment]
@tlan16 that's https://github.com/microsoft/WSL/issues/2814
