### ISSUE TITLE
Port forwarding repeated failure on WSL 1.1.0

### ISSUE THREAD

**Issue by rudyzeinoun** [microsoft/WSL#9508]
### Version

Microsoft Windows [Version 10.0.22623.1095]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.83.1

### Distro Version

Ubuntu 20.04

### Other Software

Apache/2.4.41
mysqld  Ver 10.3.37-MariaDB-0ubuntu0.20.04.1
PHP 8.1 + php8.1fpm
systemd enabled in /etc/wsl.conf 

### Repro Steps

With WSL 1.1.0 (recently pushed to Store although marked as pre-release), port forwarding fails repeatedly.
Start Apache on the Ubuntu distro, and from Command Prompt on Windows, try to:
telnet localhost 80
It will work.
A few seconds later, repeat the telnet command and it will fail.
Port forwarding no longer works to connect to WSL Ubuntu's running services.

### Expected Behavior

telnet command should keep working on the port.

### Actual Behavior

telnet command will timeout.

On first try:
netstat -an | findstr /c:"80" | findstr /c:"LISTENING"
Shows port 80 as Listening.

After a few seconds, repeat the netstat command, the port is no longer listed.
This applies to any service running on WSL, and not just Apache.
Port forwarding fails after a few seconds of the service going up.

Restart apache "service apache2 restart". The port will appear on netstat. Wait 10 seconds and check again. It disappears.

**Comment by rudyzeinoun** [comment]
Downgrading to 1.0.3 resolves the issue.

`$Package = Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers `
`Remove-AppxPackage $Package -AllUsers`
`Add-AppxPackage .\Microsoft.WSL_1.0.3.0_x64_ARM64.msixbundle`

**Comment by hensou** [comment]
Same issue for me with a nextjs 13 project.
Port Forwarding doesn't work.

Distro Version: Archlinux
Windows Build: Windows 11 Dev Preview Build 25281
WSL Version: 1.1.0.0

Downgrading it to 1.0.3, as suggested by @rudyzeinoun , did make it work again.

**Comment by pmartincic** [comment]
Thanks for reporting this. I need logs from someone because I can't reproduce. I installed apache2, default config.

**Comment by rudyzeinoun** [comment]
Here's my log. I removed 1.0.3 and reinstalled 1.1.0 from the Store. The problem is reproducible again.
During the log capture, the port forwarding was already gone. I restarted apache2. The port came back up. Did 1 connection to it, and then it died, as expected.

[WslLogs-2023-01-20_09-58-14.zip](https://github.com/microsoft/WSL/files/10464712/WslLogs-2023-01-20_09-58-14.zip)

**Comment by maicol07** [comment]
I confirm the same issue. 1 connection is successful and then I can't access it anymore. Here is my log if it can help:
[WslLogs-2023-01-20_14-20-05.zip](https://github.com/microsoft/WSL/files/10466640/WslLogs-2023-01-20_14-20-05.zip)

**Comment by john-henry** [comment]
I am getting similar problem I believe. My experience is with starting up DDEV with Docker.

`Error response from daemon: Ports are not available: exposing port TCP 127.0.0.1:443 -> 0.0.0.0:0: listen tcp 127.0.0.1:443: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.'`

**Comment by elsaco** [comment]
With WSL 1.1.0 it's connecting over IPv6 only. This is on Windows 10. The web server is running inside a WSL instance:

```
/usr/local/bin> ss -lt
State         Recv-Q        Send-Q               Local Address:Port               Peer Address:Port       Process
LISTEN        0             128                      127.0.0.1:ipp                     0.0.0.0:*
LISTEN        0             4096                             *:http                          *:*
LISTEN        0             128                          [::1]:ipp                        [::]:*
```

On Windows side `127.0.0.1` fails to connect:

```
PS C:\Windows\system32> .\curl.exe -4 -v localhost
*   Trying 127.0.0.1:80...
* connect to 127.0.0.1 port 80 failed: Connection refused
* Failed to connect to localhost port 80 after 2051 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 80 after 2051 ms: Connection refused
```

but `::1` works, and the connection is steady:

```
PS C:\Windows\system32> .\curl.exe -6 -v localhost
*   Trying ::1:80...
* Connected to localhost (::1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Date: Fri, 20 Jan 2023 17:59:08 GMT
< Server: Apache
```

More info:

```
PS C:\Windows\system32> Get-NetTCPConnection -localport 80 | ft -AutoSize

LocalAddress LocalPort RemoteAddress RemotePort State  AppliedSetting OwningProcess
------------ --------- ------------- ---------- -----  -------------- -------------
::1          80        ::            0          Listen                2972

PS C:\Windows\system32> Get-Process -id 2972

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    150      12     1604       7588       0.05   2972   1 wslhost
```

**Comment by pmartincic** [comment]
Ahhh, Thank-you! I was wondering. Is it bound to ::1 on the guest/wsl side?

**Comment by pmartincic** [comment]
From the logs I've looked at it appears the binds on the guest are port 80 ipv6 

This means that the relay is going to bind the host(windows side) at ::1 port 80.

**Comment by pmartincic** [comment]
@rudyzeinoun, I checked your logs and saw the relay bound ::1 80 on the host side, forwarded two connections, and then closed the listening socket 6 seconds later. Did you already verify that the port is still bound on the guest side inside WSL? Using something similar to `sudo netstat -lnpt`

**Comment by pmartincic** [comment]
Non deterministic repro instructions here: https://github.com/microsoft/WSL/issues/9516#issuecomment-1400557869 . If someone is experiencing failure to forward after a period other than exactly 1 minute then please say. Because in that case there may be a second issue. Thanks again for your patience.

**Comment by pmartincic** [comment]
Was able to reproduce the issue where the port tracker stops tracking immediately.

**Comment by rudyzeinoun** [comment]
> @rudyzeinoun, I checked your logs and saw the relay bound ::1 80 on the host side, forwarded two connections, and then closed the listening socket 6 seconds later. Did you already verify that the port is still bound on the guest side inside WSL? Using something similar to `sudo netstat -lnpt`

Yes, the port is still bound on the guest side. If I restart the service (unbind, bind again), it works for another 1 or 2 connections and disappears from host side again. 
I see you're able to reproduce it now. 👍

**Comment by cheynewallace** [comment]
Im having the same issue after updating (automatically via app store) to 1.1.0.   I didn't realize It had updated until I went digging around these issues and found this ticket. 

Wasted half a day on this yesterday disabling firewalls and resetting networks and ended up giving up and switching to my Macbook so I could actually work before I discovered this.  

The issue was as described here, I could usually boot my machine, open WSL, run docker and my dev API, it would work using localhost from the Windows host, in any browser for a about 30 seconds,  then it would just stop working.     Connection direct to the dynamic IP worked,  localhost did not.    

Performing `wsl --shutdown` did nothing and did not restore the localhost routing. 

Downgrading to 1.0.3 as suggested by @rudyzeinoun did solve the issue.

**Comment by CodeW0lf** [comment]
My experience with this is that having one port forwarded is fine, but as soon as another port attempts to be forwarded, the first port will get disconnected and no further forwarding can occur until `wsl --shutdown`.

My dev environment starts two servers, one on port 4200 and one on 4201. If I only start one of them and no other services that require a forwarded port, the connection and forwarded port is stable. Seconds after attempting to spawn another service that would require a forwarded port, all port forwarding stops working.

Services are still accessible from within the WSL distribution no matter what is going on with the forwarding.

**Comment by dylanirion** [comment]
I believe I am experiencing this issue via [aws-sam-cli](https://github.com/aws/aws-sam-cli) where when running a lambda function locally, docker hits an exception mapping ports `Ports are not available: exposing port TCP 127.0.0.1:5400 -> 0.0.0.0:0: listen tcp 127.0.0.1:5400: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.`

**Comment by xcellsoft** [comment]
Similar issues with running docker swarm stack, unable to bind ports. One of our dev machines got an update over the weekend, took us better part of the day to realize it was WSL 1.1.0 update. We downgraded and all is find.

Docker stack error snippet:
`skutok2kxqwb4sqhjy3cgnwza    \_ mysql_db.1               mysql:5.7.39@sha256:a85b8313feb7298ae240c4beb33a1b4d2e3a3867d3195bab9ed9346d332217c7                                           yoda      Shutdown        Failed less than a second ago     "starting container failed: container b5a3534fc47c51db1edd4a91b4b948b490768b98a25ab533f52121f0809e37b0: endpoint join on GW Network failed: driver failed programming external connectivity on endpoint gateway_e0c5563d9768 (13ddd6d5b49bc7228ed30f198fb44e549fc2e905f077bfbf84ed18b6ef8754f7): Error starting userland proxy: listen tcp4 0.0.0.0:3306: bind: address already in use"`

**Comment by yejiyang** [comment]
> Downgrading to 1.0.3 resolves the issue.
> 
> `$Package = Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers ` `Remove-AppxPackage $Package -AllUsers` `Add-AppxPackage .\Microsoft.WSL_1.0.3.0_x64_ARM64.msixbundle`

This works for me, great thanks!

**Comment by jayg-hive** [comment]
I tried to downgrade to 1.0.3 as well but I'm still not able to get the port forwarding to work. 😢 
![image](https://user-images.githubusercontent.com/94816631/214477492-0d756286-69ad-4e32-acd0-4e766d8a7714.png)

Pretty much did most of the stuff (i.e., firewall disable on vEthernet, disable Fast Startup) to no effect.
[WslLogs-2023-01-25_11-55-50.zip](https://github.com/microsoft/WSL/files/10496015/WslLogs-2023-01-25_11-55-50.zip)

**Comment by elsaco** [comment]
@jayg-hive open a debug console by adding `debugConsole = true` to your `.wslconfig` file. After a `wsl --shutdown` you'll see a console opened when launching a distro. If you see this kind of messages:

```
GnsPortTracker: Requested the host for port allocation on port (family 2, port 3000, protocol 6) - returned 0
GnsPortTracker: Tracking bind call: family (2) port (3000) protocol (6)
SecCompDispatcher: Responding to notification with id 6934181779582174820 for pid 928, result 0
GnsPortTracker: No longer tracking bind call: family (2) port (3000) protocol (6)
```

you're affected by the port proxy issue.

**Comment by jayg-hive** [comment]
> @jayg-hive open a debug console by adding `debugConsole = true` to your `.wslconfig` file. After a `wsl --shutdown` you'll see a console opened when launching a distro. If you see this kind of messages:
> 
> ```
> GnsPortTracker: Requested the host for port allocation on port (family 2, port 3000, protocol 6) - returned 0
> GnsPortTracker: Tracking bind call: family (2) port (3000) protocol (6)
> SecCompDispatcher: Responding to notification with id 6934181779582174820 for pid 928, result 0
> GnsPortTracker: No longer tracking bind call: family (2) port (3000) protocol (6)
> ```
> 
> you're affected by the port proxy issue.

Unfortunately I'm getting a different one:
[WSL-Debug-Logs-2023-01-25.txt](https://github.com/microsoft/WSL/files/10496565/WSL-Debug-Logs-2023-01-25.txt)

```
[    8.741519] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -2
[    8.742121] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -2
[    8.742747] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -2
[    8.743611] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -2
[    8.744353] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -2
[    8.744952] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -2
[    8.745537] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -2
[    9.140648] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -2
[   17.907860] TCP: eth0: Driver has suspect GRO implementation, TCP performance may be compromised.
[   49.891549] hv_balloon: Max. dynamic memory size: 7894 MB
```

Not even a blip on the last line after I tried another `curl` request. 😭

**Comment by jayg-hive** [comment]
For anyone developing on WSL and just want to see their `next dev` run, a workaround I've found is to follow the steps [here](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps) to run Google Chrome on WSL, then running `google-chrome`.  It's not as intuitive as having localhost access directly on Window though. 🤷

**Comment by pmartincic** [comment]
@jayg-hive, if you're experiencing problems with port forwarding on 1.0.3 it is not the same as the problem as this bug. 1.1.0 tracks ports via a different means.

**Comment by Dnouv** [comment]
Hello @pmartincic 

I can confirm this issue occurs with the latest 1.1.0.0. Here is the issue I faced:
1. Tried to start the development server of Rocket.Chat, starts two services, one on `3001` and the other on `3000`
2. After a minute, the port `3001` process is stopped in the "Resource Monitor> Listening Ports", following which port `3000` also stops. 
3. However, they are accessible on `wsl_ip:3000` and `wsl_ip:3001`.

I tried the following troubleshooting steps:
1. Restart WSL (`wsl --shutdown`)
2. Reset the WSL Ubuntu distribution, and installed a fresh one.
3. Added `localhostForwarding=true` in `.wslconfig`
4. Tried the `netsh portproxy`.

However, still no luck.

Any help would be really appreciated. Thank you!

**Comment by pmartincic** [comment]
@Dnouv, I'm sorry you're running into this. For the time being you should follow the instructions above and revert back to 1.0.3 I'm tracking the root cause of the bug and it will require a code change to fix.

**Comment by Tofandel** [comment]
Also had the same issue after trying the prerelease

Just adding a note that to run

> Downgrading to 1.0.3 resolves the issue.
> 
> `$Package = Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers ` `Remove-AppxPackage $Package -AllUsers` `Add-AppxPackage .\Microsoft.WSL_1.0.3.0_x64_ARM64.msixbundle`

You need to download the [1.0.3 release]( https://github.com/microsoft/WSL/releases/download/1.0.3/Microsoft.WSL_1.0.3.0_x64_ARM64.msixbundle)

**Comment by astroboylrx** [comment]
Also had this issue. I'm using `jupyter notebook` on WSL2 and have been accessing it via `localhost:8888` from Windows without issues until this update.

With this update, sometimes I can access the notebook from Windows browser, but it lost connection after a short while, exactly matching what has been described in many cases above. Sometimes I just cannot access from the very beginning (I guess the "short while" were too short). This behavior is consistent regardless of `python` version, port used (8888, 8999, etc.), etc. 

Also, sometimes `jupyter` reported that "address is already in use", but I cannot find any process in WSL2 occupying that address or port. I did notice that there are many `kubernetes` seemingly listening (?? not sure) to the same port every time when I start a Jupyter Notebook.
The following results are from `netstat -a` on Powershell, where only the first line was due to my jupyter and I have no idea about the other lines that show "ESTABLISHED" with local address on `8891`. If I kill jupyter, these lines would become "TIME_WAIT" in State, super confusing. 
```
  Proto  Local Address          Foreign Address        State
  TCP    127.0.0.1:8891         VectorPro:0            LISTENING
  TCP    127.0.0.1:8891         kubernetes:51023       ESTABLISHED
  TCP    127.0.0.1:8891         kubernetes:51035       ESTABLISHED
  TCP    127.0.0.1:8891         kubernetes:51036       ESTABLISHED
  TCP    127.0.0.1:8891         kubernetes:51037       ESTABLISHED
  TCP    127.0.0.1:8891         kubernetes:51038       ESTABLISHED
  TCP    127.0.0.1:8891         kubernetes:51039       ESTABLISHED
  TCP    127.0.0.1:8891         kubernetes:51086       ESTABLISHED
  TCP    127.0.0.1:9656         VectorPro:0            LISTENING
```

After downgrading to 1.0.3, I don't see `kubernetes` anymore under the port of my `jupyter notebook`.

**Comment by elsaco** [comment]
@astroboylrx when you kill jupyter your host keeps the TCP endpoint(s) for longer just in case some late packet(s) might arrive. They close after about 2 min or whatever the MSL is setup to. During this time they are in `TIME_WAIT` state. Run `netstat -a` after 4-5 min and those connections will be gone.

**Comment by pedrolamas** [comment]
Yesterday I manually removed WSL 1.1.0 and reinstalled 1.0.3 to fix this issue (which it did!), but this morning I turned on my machine and it is back to 1.1.0...

Is there a way I can stop Windows Store from updating WSL to 1.1.0?

**Comment by Tofandel** [comment]
Hmm I don't know what's up, but the downgrade to 1.0.3 made it worse, now I can't access WSL at all on localhost or 127.0.0.1 always get connection refused, in 1.1.0 I at least could connect for 1 minute

**Comment by Cremesis** [comment]
Yeah same problem here, I had to revert back to 1.0.3.

**Comment by pmartincic** [comment]
Fix is currently in testing.

**Comment by pmartincic** [comment]
@nickchomey , I completely get wanting to back up your distros. However, re-importing is unnecessary unless the packaging framework borks your distro.

**Comment by realmrv** [comment]
As a non-downgrading workaround, use IP address of `eth0` WSL virtual adapter instead of `localhost` address. To get it, run `iptable` inside WSL or run `wsl hostname -I` in a Windows terminal and select the first one in the resulting list.

**Comment by clmnin** [comment]
@rudyzeinoun @nickchomey Will removing WSL2 using `Remove-AppxPackage $Package -AllUsers` make me lose my data? I installed WSL2 using `wsl --install`.

I've previously lost my data when I ran `wsl --unregister DISTRO_NAME` - issue #9049

**Comment by clmnin** [comment]
I had installed WSL2 using `wsl --install` and I followed the steps shared by @rudyzeinoun 
```powershell
$Package = Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers 
Remove-AppxPackage $Package -AllUsers
Add-AppxPackage .\Microsoft.WSL_1.0.3.0_x64_ARM64.msixbundl
```

Downgrading to 1.0.3 works.

**Comment by bplasmeijer** [comment]
It also solved my problem, downgrading to 1.0.3

```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      22621  0
```
This issue should be solved soon, did spend hours debugging because thinking about VPN or network-related issues.

1.0.3  
[WslLogs-2023-01-30_08-57-55.zip](https://github.com/microsoft/WSL/files/10533705/WslLogs-2023-01-30_08-57-55.zip)
1.1.0
[WslLogs-2023-01-30_09-06-46.zip](https://github.com/microsoft/WSL/files/10533707/WslLogs-2023-01-30_09-06-46.zip)

A simple test with [kind](https://github.com/kubernetes-sigs/kind)

```kind create cluster --name test```
on 1.1.0 
```The connection to the server 127.0.0.1:40715 was refused - did you specify the right host or port?```
on 1.0.3
```
k get pods -A
NAMESPACE            NAME                                        READY   STATUS    RESTARTS      AGE
kube-system          coredns-565d847f94-hrcfs                    0/1     Running   5 (23s ago)   35m
kube-system          coredns-565d847f94-tfjwp                    0/1     Running   5 (23s ago)   35m
kube-system          etcd-abc-control-plane                      1/1     Running   5 (23s ago)   35m
kube-system          kindnet-txnq5                               1/1     Running   5 (23s ago)   35m
kube-system          kube-apiserver-abc-control-plane            1/1     Running   5 (23s ago)   35m
kube-system          kube-controller-manager-abc-control-plane   1/1     Running   5 (23s ago)   35m
kube-system          kube-proxy-ckkp2                            1/1     Running   5 (23s ago)   35m
kube-system          kube-scheduler-abc-control-plane            1/1     Running   5 (23s ago)   35m
local-path-storage   local-path-provisioner-684f458cdd-zzqfg     1/1     Running   7 (23s ago)   35m
```
cc: @craigloewen-msft @bitcrazed @benhillis

**Comment by bplasmeijer** [comment]
@craigloewen-msft @benhillis  can we please label this as a bug?

**Comment by pmartincic** [comment]
@bplasmeijer, it's actively being worked on and treated as a bug. Unfortunately we don't make religious use of the labels. Yesterday in testing, another issue was found with the release that was about to go out the door to address issue. That's been addressed.

**Comment by bplasmeijer** [comment]
> @bplasmeijer, it's actively being worked on and treated as a bug. Unfortunately we don't make religious use of the labels. Yesterday in testing, another issue was found with the release that was about to go out the door to fix this issue. That's been addressed.

Thanks 🙏 wsl team, and @pmartincic 
Labels can give visibility to the wsl consumers. 
Any insides on the bug would be appreciated. Many hours trying to find the issue.😬

Cc: @craigloewen-msft

**Comment by nuttakit** [comment]
was downgrading to 1.0.3 and work fine yesterday.
it broken again today.

wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1194

**Comment by pmartincic** [comment]
Sorry to hear that @nuttakit, If you're on anything on or before 1.0.3 you are experiencing a different issue.

**Comment by codebymikey** [comment]
Can someone please confirm if there's any potential for loss of data when attempting the downgrade back to 1.0.3 from a previous `wsl --update`?
```bash
$Package = Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers 
Remove-AppxPackage $Package -AllUsers
Add-AppxPackage .\Microsoft.WSL_1.0.3.0_x64_ARM64.msixbundle
```

The `Remove-AppxPackage` command looks particularly scary since I'm not sure if the WSL mount data of individual Distribution packages is somehow coupled with the WSL package (it doesn't appear so, but better safe than sorry!).

**Comment by hoanglan87** [comment]
@codebymikey your data is stored in .vhdx file (if you are using wsl 2) so this can't affect the data 
but better safe than sorry, backup first

**Comment by Cremesis** [comment]
I see a new release is available on the Microsoft Store (1.1.2) and it looks like the bug is fixed.

**Comment by realmrv** [comment]
> I see a new release is available on the Microsoft Store (1.1.2) and it looks like the bug is fixed.
I confirm. I don't see this problem after the update.

**Comment by Dnouv** [comment]
It is resolved in the new release 💯 . Just curious if it is ok to tell the community what the issue was, @pmartincic. 🤔

Thank you for the fix.

**Comment by stafyniaksacha** [comment]
1.1.2 seem to solve the issue!

**Comment by nidrissi** [comment]
There is an issue in LaTeX-Workshop (LW) that was believed to come from this bug: https://github.com/James-Yu/LaTeX-Workshop/issues/3670 However, even though I'm on 1.1.2, the bug remains.

LW launches a web server that listens on 127.0.0.1:PORT. Here's the output from the linux side:

```
$ ss -tlnp
State                Recv-Q                Send-Q                               Local Address:Port                                Peer Address:Port               Process
LISTEN               0                     511                                      127.0.0.1:39177                                    0.0.0.0:*                   users:(("node",pid=1677,fd=25))
```

And the webserver can be accessed from the linux side too:

```
$ curl --head 'http://127.0.0.1:39177/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyRmhvbWUlMkZuYWppYiUyRnRtcCUyRm1haW4ucGRm'
HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 25334
Cross-Origin-Resource-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
X-Content-Type-Options: nosniff
Date: Thu, 02 Feb 2023 13:09:48 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

However, the connection is refused from the Windows host:

```
> curl --head 'http://127.0.0.1:39177/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyRmhvbWUlMkZuYWppYiUyRnRtcCUyRm1haW4ucGRm'
curl: (7) Failed to connect to 127.0.0.1 port 39177 after 2043 ms: Connection refused
```

And `netstat -ano | findstr 39177` comes up empty.

**Comment by pmartincic** [comment]
@nidrissi, can you give me /logs? I'll try to reproduce this but might need some help from you.

So, I'm happy to hear that this seems to solve it for most people. That said, we're still working on resolving one more issue that I'm aware of. 1.1.2 Has preliminary fixes but you could still notice funny behavior if you're addressing via localhost:port on the host instead of 127.0.0.1:port or --1.ipv6-literal.net:port; That is still being worked on.

1.1.0 Contained an attempt at making bind calls synchronous across the guest and host. The old relay did not bind synchronously across the guest and host.

**Comment by bplasmeijer** [comment]
> Can someone please confirm if there's any potential for loss of data when attempting the downgrade back to 1.0.3 from a previous `wsl --update`?
> 
> ```shell
> $Package = Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers 
> Remove-AppxPackage $Package -AllUsers
> Add-AppxPackage .\Microsoft.WSL_1.0.3.0_x64_ARM64.msixbundle
> ```
> 
> The `Remove-AppxPackage` command looks particularly scary since I'm not sure if the WSL mount data of individual Distribution packages is somehow coupled with the WSL package (it doesn't appear so, but better safe than sorry!).

not on my revert

**Comment by ZedG2** [comment]
![image](https://user-images.githubusercontent.com/7886856/216491934-98b63801-78c7-4a46-844a-169c78b322bd.png)

kubernetes still not work on 1.1.2

**Comment by pmartincic** [comment]
@ZedG2, can you give me [logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) please? Logs starting from the time where you launch Kubernetes, to the time where you attempt to use it?

**Comment by elsaco** [comment]
@ZedG2 what is the output of `kubectl cluster-info`? Here's sample output on my test vm:

```
elsaco@RIPPER:~$ kubectl cluster-info
Kubernetes control plane is running at https://127.0.0.1:16443
CoreDNS is running at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.


```

and one nginx pod:

```
elsaco@RIPPER:~$ kubectl get pods
NAME                     READY   STATUS    RESTARTS   AGE
nginx-748c667d99-cpmf9   1/1     Running   0          9m10s
```

<details>
  <summary>nginx pod full info</summary>

```
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "v1",
            "kind": "Pod",
            "metadata": {
                "annotations": {
                    "cni.projectcalico.org/containerID": "2e926c65ce1480c0a696fcef22823a4a232d9a41538e89b8d0af1811f59b90b1",
                    "cni.projectcalico.org/podIP": "10.1.120.199/32",
                    "cni.projectcalico.org/podIPs": "10.1.120.199/32"
                },
                "creationTimestamp": "2023-02-03T03:06:57Z",
                "generateName": "nginx-748c667d99-",
                "labels": {
                    "app": "nginx",
                    "pod-template-hash": "748c667d99"
                },
                "name": "nginx-748c667d99-cpmf9",
                "namespace": "default",
                "ownerReferences": [
                    {
                        "apiVersion": "apps/v1",
                        "blockOwnerDeletion": true,
                        "controller": true,
                        "kind": "ReplicaSet",
                        "name": "nginx-748c667d99",
                        "uid": "4fa5cd3d-bed2-42fb-b619-df437541070f"
                    }
                ],
                "resourceVersion": "4539",
                "uid": "ee268cd8-ea68-4d01-b9a1-9c338edaf8ff"
            },
            "spec": {
                "containers": [
                    {
                        "image": "nginx",
                        "imagePullPolicy": "Always",
                        "name": "nginx",
                        "resources": {},
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File",
                        "volumeMounts": [
                            {
                                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                                "name": "kube-api-access-z96qv",
                                "readOnly": true
                            }
                        ]
                    }
                ],
                "dnsPolicy": "ClusterFirst",
                "enableServiceLinks": true,
                "nodeName": "ripper",
                "preemptionPolicy": "PreemptLowerPriority",
                "priority": 0,
                "restartPolicy": "Always",
                "schedulerName": "default-scheduler",
                "securityContext": {},
                "serviceAccount": "default",
                "serviceAccountName": "default",
                "terminationGracePeriodSeconds": 30,
                "tolerations": [
                    {
                        "effect": "NoExecute",
                        "key": "node.kubernetes.io/not-ready",
                        "operator": "Exists",
                        "tolerationSeconds": 300
                    },
                    {
                        "effect": "NoExecute",
                        "key": "node.kubernetes.io/unreachable",
                        "operator": "Exists",
                        "tolerationSeconds": 300
                    }
                ],
                "volumes": [
                    {
                        "name": "kube-api-access-z96qv",
                        "projected": {
                            "defaultMode": 420,
                            "sources": [
                                {
                                    "serviceAccountToken": {
                                        "expirationSeconds": 3607,
                                        "path": "token"
                                    }
                                },
                                {
                                    "configMap": {
                                        "items": [
                                            {
                                                "key": "ca.crt",
                                                "path": "ca.crt"
                                            }
                                        ],
                                        "name": "kube-root-ca.crt"
                                    }
                                },
                                {
                                    "downwardAPI": {
                                        "items": [
                                            {
                                                "fieldRef": {
                                                    "apiVersion": "v1",
                                                    "fieldPath": "metadata.namespace"
                                                },
                                                "path": "namespace"
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    }
                ]
            },
            "status": {
                "conditions": [
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2023-02-03T03:06:58Z",
                        "status": "True",
                        "type": "Initialized"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2023-02-03T03:07:04Z",
                        "status": "True",
                        "type": "Ready"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2023-02-03T03:07:04Z",
                        "status": "True",
                        "type": "ContainersReady"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2023-02-03T03:06:57Z",
                        "status": "True",
                        "type": "PodScheduled"
                    }
                ],
                "containerStatuses": [
                    {
                        "containerID": "containerd://e69718306e91cc7f6ab6c3738b2246239c94e8ce8d4ae4cb072f254da2997c96",
                        "image": "docker.io/library/nginx:latest",
                        "imageID": "docker.io/library/nginx@sha256:b8f2383a95879e1ae064940d9a200f67a6c79e710ed82ac42263397367e7cc4e",
                        "lastState": {},
                        "name": "nginx",
                        "ready": true,
                        "restartCount": 0,
                        "started": true,
                        "state": {
                            "running": {
                                "startedAt": "2023-02-03T03:07:03Z"
                            }
                        }
                    }
                ],
                "hostIP": "192.168.95.205",
                "phase": "Running",
                "podIP": "10.1.120.199",
                "podIPs": [
                    {
                        "ip": "10.1.120.199"
                    }
                ],
                "qosClass": "BestEffort",
                "startTime": "2023-02-03T03:06:58Z"
            }
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": ""
    }
}
```
</details>


Also, the dashboard is accessible from Windows side at `https://127.0.0.1:10443/`

```
WSL version: 1.1.2.0
Kernel version: 5.15.83.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2546
```

**Comment by nidrissi** [comment]
> @nidrissi, can you give me [logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method)? I'll try to reproduce this but might need some help from you.

Sure, there you go. Let me know if you need anything else. [WslLogs-2023-02-03_07-55-47.zip](https://github.com/microsoft/WSL/files/10576344/WslLogs-2023-02-03_07-55-47.zip)

**Comment by nidrissi** [comment]
@pmartincic Here are the logs from another machine, as well as the networking logs from WSL.

* [WslLogs-2023-02-03_11-11-15.zip](https://github.com/microsoft/WSL/files/10577885/WslLogs-2023-02-03_11-11-15.zip)
* [wsl.etl.zip](https://github.com/microsoft/WSL/files/10577890/wsl.etl.zip)

**Comment by ZedG2** [comment]
> @ZedG2, can you give me [logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) please? Logs starting from the time where you launch Kubernetes, to the time where you attempt to use it?

+ [1.1.2.zip](https://github.com/microsoft/WSL/files/10606703/1.1.2.zip)
+ [1.0.3.zip](https://github.com/microsoft/WSL/files/10606704/1.0.3.zip)

```
~
❯ kubectl cluster-info
Kubernetes control plane is running at https://kubernetes.docker.internal:6443
CoreDNS is running at https://kubernetes.docker.internal:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

**Comment by bplasmeijer** [comment]
Not fixed on my machine on 1.1.2 @craigloewen-msft @benhillis 
Same error, access denied on the local kind cluster 
```
Version                : 1.1.2.0
```
logs files, 1.1.2
[WslLogs-2023-02-06_15-50-04.zip](https://github.com/microsoft/WSL/files/10664366/WslLogs-2023-02-06_15-50-04.zip)
1.0.3
[WslLogs-2023-02-06_15-54-56.zip](https://github.com/microsoft/WSL/files/10664369/WslLogs-2023-02-06_15-54-56.zip)

**Comment by asampal** [comment]
Still having problems with 1.1.2. Easy to reproduce with the minikube (https://github.com/kubernetes/minikube) running in WSL2. Attempt to start the minikube dashboard (which will bind to 127.0.0.1:<some-port>). This will open up the page in your browser, but will not show the dashboard successfully, and instead just sit there doing nothing.

**Comment by elsaco** [comment]
@asampal if you run `minikube` inside a WSL instance, check `.minikube/logs/lastStart.txt` in your `$HOME` and get more insight of what's going on.

**Comment by asampal** [comment]
@elsaco , downgrading to 1.0.3 resolved the issue, so for now I think I'll stay at that version, unless I see something any suggestions specific to minikube either in this repo or minikube's.

**Comment by JshGrn** [comment]
How can I turn off the forced update? Every day I am having to downgrade unless I am missing a toggle somewhere? I have windows updates paused too and still doesn't stop it. This is a massively broken release because of this.

**Comment by pedrolamas** [comment]
@JshGrn disable it in the Microsoft Store app (click photo on top right, Settings, disable app updates)

Just do remember to come here ocasional to manually update the other apps...

**Comment by JshGrn** [comment]
@pedrolamas Yeah I saw in the end my bad, yeah I will come back in a month and hope its working again, is there any update on the timeline estimated for a fix on this?

**Comment by Jont828** [comment]
How would we downgrade the WSL program itself to 1.0.3?

**Comment by OneBlue** [comment]
Thanks everyone for the feedback. The fix for this issue is in [WSL 1.1.3](https://github.com/microsoft/WSL/releases/tag/1.1.3)

**Comment by pmartincic** [comment]
More specifically it is now back to the behavior that was part of 1.0.3

**Comment by svetoslavenchev** [comment]
> Thanks everyone for the feedback. The fix for this issue is in [WSL 1.1.3](https://github.com/microsoft/WSL/releases/tag/1.1.3)

Just tried it - my Docker Compose projects are happy :)

**Comment by OneBlue** [comment]
> Nice work!
> 
> How long does it typically take for a new version to arrive in the Windows Store? I just removed 1.0.3 that I installed manually and installed WSL2 from the Windows store, but I have 1.1.2.

It's in pre-release for now so only insiders will receive it through the store. It'll be available for everyone once we decide that it's stable enough to go for GA. 

In the meantime, non-insider users can download and install the package manually like you did.

**Comment by Cremesis** [comment]
I think that 1.1.3 reintroduced the problem in my machine, where the 1.1.2 fixed it :\

**Comment by pmartincic** [comment]
@Cremesis, can you open a new bug? 1.1.3 is supposed to be a revert to the behavior present in 1.0.3

**Comment by pmartincic** [comment]
@nickchomey, We don't push builds to everyone at once. This bug is a great example of why we have an insiders ring that we push to before going to GA.

**Comment by pmartincic** [comment]
I get where you're coming from. This is why I wasn't going to mark the bug as closed till I was sure it had rolled out. I can ask someone who knows more about the release process via the store, but I'm pretty sure it's not instantaneous like that.

**Comment by pmartincic** [comment]
@Cremesis, @rajshrimohanks: If you're still experiencing an issue on 1.1.3 I'd greatly appreciate it if you opened a new bug and posted logs.

**Comment by JshGrn** [comment]
Having to download manually as 1.1.2 still latest in Store on windows insider preview (19/02/2023), checking if fixed now.

**Comment by Cremesis** [comment]
> @Cremesis, @rajshrimohanks: If you're still experiencing an issue on 1.1.3 I'd greatly appreciate it if you opened a new bug and posted logs.

No issues, it was an error on my configuration: I had a `.wslconfig` file that disabled ipv6 because I had found that that helped my with the issues on 1.1.0 version, but in 1.1.3 it blocked the localhost access to my WSL from Windows... removing that file and restarting WSL solved the problem.

**Comment by androiddisk** [comment]
In normal use, execute docker ps or docker restart on the probability line. All forwarding ports fail. Restarting wsl doesn't work. You can only restart windows

**Comment by pmartincic** [comment]
Locking this thread because the functionality/feature in question was reverted to the old behavior. Any issues should be filed as new bugs or comments on other bugs.
