### ISSUE TITLE
sudo doesn't work when "-u" flag is assigned

### ISSUE THREAD

**Issue by kjelly** [Microsoft/WSL#962]
-  A brief description 

sudo command doesn't when '-u' flag is assigned.
For example, `sudo -u user  ls`
- Expected results

The command should be run 
- Actual results (with terminal output if applicable)

sudo: setresuid() [1000, 1000, 1000] -> [-1, 0, -1]: Operation not permitted
- Your Windows build number

windows 10 1607 x64
- Steps / commands required to reproduce the error
  
  sudo -u user  ls
- Strace of the failing command

```
execve("/usr/bin/sudo", ["sudo", "-u", "user", "ls"], [/* 16 vars */]) = -1 EPERM (Operation not permitted)
write(2, "strace: exec: Operation not perm"..., 38strace: exec: Operation not permitted
) = 38
exit_group(1)                           = ?
+++ exited with 1 +++
```
- Required packages and commands to install

None

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by russalex** [comment]
This should be resolved in the Insider build.  Looks like it was closed out with some of our other fixes.

Marking as fixed for insiders.

**Comment by russalex** [comment]
Marked as fixed for some time.  Closing it out.

**Comment by ya790206** [comment]
Which version is the bug fixed?
I try Windows 10 Insider Preview 14986 (rs_prerelease).
The bug still exist.
But the error message changed.
The new error message looks like

``
$ sudo -u user ls
sudo: unable to resolve host DESKTOP-K82BHUJ
sudo: setresuid() [1000, 1000, 1000] -> [-1, 0, -1]: Operation not permitted
sudo: unable to set runas group vector: Operation not permitted
sudo: PERM_ROOT: setresuid(0, -1, 0): Operation not permitted
user is not in the sudoers file.  This incident will be reported.
``

**Comment by GameKyuubi** [comment]
This is NOT fixed.  On build 15063 `sudo -u user ls` returns 

```
sudo: setresuid() [1000, 1000, 1000] -> [-1, 0, -1]: Operation not permitted
sudo: unable to set runas group vector: Operation not permitted
sudo: PERM_ROOT: setresuid(0, -1, 0): Operation not permitted
```

**Comment by benhillis** [comment]
Reopening because this is still broken.

**Comment by dingolfsson** [comment]
Having the same issue trying to access postgres.

`> $ sudo -u postgres psql
sudo: setresuid() [1000, 107, 1000] -> [-1, 0, -1]: Operation not permitted`

**Comment by ArsalanDotMe** [comment]
any workaround to configure postgres till this gets fixed?

**Comment by GameKyuubi** [comment]
It sounds stupid but try `sudo sudo -u`

**Comment by ArsalanDotMe** [comment]
That doesn't seem to work
```
$  sudo sudo -u postgres
[sudo] password for arsalan:
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-u user] file ...
```

**Comment by dingolfsson** [comment]
A workaround for me was to create the DB in the Windows environment, create the user and access it in Bash.

It ultimately defeats the purpose of using Bash, so obviously, this isn't a solution but while it's bugged, this should work.

**Comment by ArsalanDotMe** [comment]
Okay. Anyway, I've yet again wasted a couple of hours trying to get my RoR environment set up but looks like I still have to wait some more. Puma also fails with a weird `Read error: #<Errno::ENOPROTOOPT: Protocol not available - getsockopt(2)>` error. Bash for Windows is still not currently there yet for any dev work.
On 18-Apr-17 11:34:42 PM, Daniel Ingolfsson <notifications@github.com> wrote:
A workaround for me was to create the DB in the Windows environment, create the user and access it in Bash.
It ultimately defeats the purpose of using Bash, so obviously, this isn't a solution but while it's bugged, this should work.

**Comment by aseering** [comment]
@ArsalanDotMe -- in your previous comment, you want `sudo sudo -u postgres psql`.  (sudo is complaining that you didn't tell it what command to run :-) )

That said, it's definitely true that getting system services like PostgreSQL working within WSL is still a pain.  Fortunately, it sounds like it's being worked on.

**Comment by benhillis** [comment]
@aseering - you're correct I've filed a bug and will be looking into this.

**Comment by sunilmut** [comment]
@ArsalanDotMe - Thanks for your post and patience with WSL. WSL is still a beta feature and while we have covered some ground in Creators Update, there is still more to go. And, your input here actually helps us getting there meaningfully. So, I wouldn't consider your two hours a complete waste :). Would you be willing to open a new issue for the `RoR getsockopt` failure (a strace would be super useful, as it will be able to exactly pinpoint the issue here). See our [contributing.md](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for instructions.

We are trying to get "full" compatibility with Linux and as you can imagine, that's a huge surface area. Hopefully, that explains some of the time that we are taking here to cover the ground.

**Comment by sebaslogen** [comment]
A workaround that I used is ` sudo su postgres` to change to the postgres user in the console and then run the rest of the commands from there, this works on Insider build 15063

**Comment by JohnPostlethwait** [comment]
Just ran into this myself. Thanks for the workarounds!

Both `sudo sudo -u postgres` and `sudo su postgres` solutions were effective workarounds for me.

**Comment by benhillis** [comment]
Thanks to everyone for the help. I got some time to take a look at this and the issue was our driver not correctly setting the "saved-set" UID or GID on set-user-ID and set-group-ID bit binaries.  I have a fix for this and it will be available in a Windows Insider build soon.

**Comment by benhillis** [comment]
This is fixed in 16251.
