### ISSUE TITLE
WSL2 freezes/stutters my computer every X seconds

### ISSUE THREAD

**Issue by kevinmnm** [microsoft/WSL#9846]
### Windows Version

Microsoft Windows [Version 10.0.22621.1413]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04.x

### Repro Steps

1) Open Windows Features.
2) Check "Windows Subsystem for Linux.
3) Restart computer.

![image](https://user-images.githubusercontent.com/62520825/227731603-4817c286-67fa-471f-88a2-affcb8c2df6a.png)

### Expected Behavior

Smooth/normal Windows user experience.

### Actual Behavior

My desktop computer "stutters" every 3 - 10 seconds when WSL2 is enabled. The most prominent behavior I see is that my mouse sensitivity keeps on changing and goes back to normal. I have another laptop (Windows 11) with WSL2 enabled but same issue doesn't happen there.

**Comment by prescode** [comment]
@kevinmnm I am also experiencing this issue on Windows 10 (19044.2728), WSL version 1.1.6.0, and Ubuntu 22.04.x. I suspect this has to do with Docker Desktop and memory issues. Do you have Docker Desktop installed? What does your memory consumption for "Vmmem" look like when you are experiencing this problem?

**Comment by ReeyaDono** [comment]
I am also experiencing this issue but only when tmux server is running with my config file right here https://github.com/ReeyaDono/.dotfiles/blob/main/tmux/.tmux.conf. My whole system (mouse cursor lag, audio lag, everything) will start stuttering every few seconds and then return to normal after a few seconds and then the stuttering return after a few minutes (5-15 minutes) and the cycles continue. But, the cycles stop when i kill the tmux server. 

WSL version: 1.2.5.0
Kernel version: 5.15.90.1
Windows version: 10.0.19045.3086
Distro: Ubuntu 20 and ArchWSL both have the same issue in my system.

**Comment by dakka** [comment]
> I am also experiencing this issue but only when tmux server is running with my config file right here https://github.com/ReeyaDono/.dotfiles/blob/main/tmux/.tmux.conf. My whole system (mouse cursor lag, audio lag, everything) will start stuttering every few seconds and then return to normal after a few seconds and then the stuttering return after a few minutes (5-15 minutes) and the cycles continue. But, the cycles stop when i kill the tmux server.
Interesting temporary fix - detach tmux, issue a 'reset' at the terminal and reattach. Works until the 5-15 min cycle resumes.

**Comment by kevinmnm** [comment]
This issue was fixed by itself about a month or two ago. Prior to that random fix, I tried a lot of things and even upgraded from Windows 11 to Windows 11 Pro which wasn't the fix either. Anyways, this issue might be no longer relevant for me as I never had same issue since then. I'm assuming it was one of the Windows updates that did the trick but not sure which exact version it was.

### Current version info:
**Windows version (`cmd.exe /c ver`):**  Microsoft Windows [Version 10.0.22621.1992]
**Edition:** Windows 11 Pro
**Version:** 22H2
**OS build:** 22621.1992

### Current Windows features:
![image](https://github.com/microsoft/WSL/assets/62520825/32e404fc-a459-4358-8bb1-b85fe332563d)

**Comment by dakka** [comment]
No, still a problem for me, Windows Pro 11, `Version 10.0.22621.2070`

**Comment by Hifilo** [comment]
Confirming that I have had this issue. I currently have wsl window feature disabled since I'm not using it, but it would stutter & hijack focus periodically.

**Comment by suchcodewow** [comment]
SAME.  Latest Windows 11 as of December 11/2023.  WSL installed (for Docker Desktop) = Window drag stutter/lag.  Adobe AI mouse lags horribly.  Fusion 360 mouse lags horribly.

**Comment by mshumsky** [comment]
Same here after unregistering Ubuntu 22.04 distro and installing Ubuntu 24.04 from Microsoft Store.

**Comment by TatuMon** [comment]
Started happening to me not too long ago.
If I stop WSL, everything works normally.

I'm using NixOS-WSL

**Comment by alireza-karampour** [comment]
this is still happening to me anyone found a fix ?
