### ISSUE TITLE
`user@UID.service` works for first systemd enabled distro only

### ISSUE THREAD

**Issue by elsaco** [microsoft/WSL#9913]
### Windows Version

Microsoft Windows [Version 10.0.19045.2728]

### WSL Version

1.1.7.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

start a systemd enabled distro
start a 2nd systemd enable distro

### Expected Behavior

`user-UID.slice` to work for both distros

### Actual Behavior

The first distro does create `/run/usr/1000` with correct UID/GID ownership:

```
tux@focal:~$ ls -ln /run/user/1000/
total 0
srw-rw-rw- 1 1000 1000   0 Apr  4 14:07 bus
drwx------ 2 1000 1000 140 Apr  4 14:07 gnupg
d--------- 3 1000 1000 160 Apr  4 14:07 inaccessible
srw-rw-rw- 1 1000 1000   0 Apr  4 14:07 pk-debconf-socket
srw-rw-rw- 1 1000 1000   0 Apr  4 14:07 snapd-session-agent.socket
drwxr-xr-x 3 1000 1000 100 Apr  4 14:07 systemd
```

The 2nd distro creates `/run/user/1000` as root:

```
elsaco@lobster:~$ ls -ln /run/user/
total 0
drwx------ 2 0 0 40 Apr  4 14:07 1000
```

and  current user has no access to it:

```
elsaco@lobster:~$ ls -ln /run/user/1000
ls: cannot open directory '/run/user/1000': Permission denied
```

Latest release has `/run/uses/` as an overlay. However, when installing a distro a user is created with UID=1000 and GID=1000. Are the overlays suppose to work with same UID/GID? Didn't test with multiple users, yet.

**Comment by HenryGessau** [comment]
I have only one distro installed (Ubuntu).
Upgrading to WSL `1.2.0.0` broke this for me.
I was previously at `1.1.6.0` which worked fine.

It breaks all apps relying on dconf:
```
unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.
```

**Comment by benhillis** [comment]
Fixed in https://github.com/microsoft/WSL/releases/tag/1.2.1.

**Comment by HenryGessau** [comment]
@benhillis `1.2.1` did not fix it for me. Shall I open a new issue?
```                                                                                                                                     ─╯⠀
WSL version: 1.2.1.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1555
```

**Comment by benhillis** [comment]
Sorry I mistagged, 1.1.2 has the fix.
